### ISSUE TITLE
imagoVersions is undefined

### ISSUE THREAD

**Issue by wojiaoxiaomayun** [epam/Indigo#1017]
Hi,I used indigo-service images 1.8.2 and 1.9.0, but http://localhost/v2/info The obtained information does not contain imagoVersions，please help me
![image](https://user-images.githubusercontent.com/30283623/215932843-1abf3a35-03f4-41e9-839f-9369602132cb.png)

**Comment by AlexanderSavelyev** [comment]
Hi @wojiaoxiaomayun  thank you for your feedback. Yes, we are going to restore imago in the nearest release.

**Comment by wojiaoxiaomayun** [comment]
Thanks for you，Dear @AlexanderSavelyev .
