### ISSUE TITLE
Implement external fingerprints support for Bingo NoSQL

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/Indigo#104]
As user I expect to input a molecule with custom fingerprint calculated.
Create a function for bingo noslq

bingo.insert(IndigoMolecule mol, IndigoFingerprint sim_fp)

`bingo_db = Bingo.createDatabaseFile(..)`
`mol = indigo.loadMolecule('C1CCCCC1')`
`fp = mol.fingerprint("sim")
`bingo_db.insert(mol, fp)`

    # external api
fp_ext = indigo.loadFingerprint([d1,d2..dN]) # d1..dN array of doubles
bingo_db.insert(mol, fp)`

external fingerprint will be only for similarity!

internally bingo builds own fingerprint (sub,sim,tau,res)
and replace "sim" part by external fp

**Comment by IuriiPuzanov** [comment]
Added support of external fingerprints (similarity part) into NoSQL Bingo and corresponding API into wrappers (Python, Java, C#)
