### ISSUE TITLE
Bingo compile from source on Windows fails due to type conversion

### ISSUE THREAD

**Issue by dan2097** [epam/Indigo#106]
Using the latest code from GitHub (commit b9d835610883bbf88ba0b591c37b06851c5ddb89) + out of the box PostgreSQL 9.6 + Visual Studio 2015
Command-line invocation:
set BINGO_PG_DIR=C:\Program Files\PostgreSQL\9.6
set BINGO_PG_VERSION=9.6
bingo-release.py --preset=win64-2015 --dbms=postgres

Produces errors like:
 C:\Program Files\PostgreSQL\9.6\include\server\port/atomics/generic-msvc.h(85): error C2664: 'LONG64 _InterlockedCompareExchange64(volatile LONG64 *,LONG64,LONG64)': cannot convert argument 1 from 'volatile uint64 *' to 'volatile LONG64 *' [C:\documents\workspace\Indigo\build\pg_VS14Win64_Release\bingo-postgres\bingo-postgres-shared.vcxproj]

I attach the full output from running this:
[build.txt](https://github.com/epam/Indigo/files/1478829/build.txt)

**Comment by karnaukhovv** [comment]
Just to clarify - this seems to be an old PostgreSQL API issue: [1], [2]. Not sure about possible workaround, though...

[1] http://www.postgresql-archive.org/BUG-13788-compile-error-in-generic-msvc-h-td5875729.html
[2] https://www.postgresql.org/message-id/5176.1449005701@sss.pgh.pa.us

**Comment by IuriiPuzanov** [comment]
Hello Dan,

  Thank you very much for using Bingo and finding.
As about error this is know issue for the 64-bit Windows Postgres version.
For correct building you need to fix the header file in PostgreSQL installation generic-msvc.h
by including casting in accordance with recommendations in the next thread:

https://www.postgresql.org/message-id/20151201165457.2760.18019%40wrigleys.postgresql.org

Best Regards!
Yuriy

**Comment by dan2097** [comment]
Thanks! Adding the cast (volatile int64 *) to the appropriate place in the two failings lines fixed this and it has now built correctly.
