### ISSUE TITLE
[Bingo-Elastic] Cannot create custom index in python bingo-elastic

### ISSUE THREAD

**Issue by bodyangug** [epam/Indigo#1061]
**Description:**
I want to create a custom index for bingo-Elastic without using IndexName to implement library logic for reference API.
The problems I have faced include:
- In Python, we cannot enhance/extend Enum. Therefore, I used a workaround by using the aenum library to extend the IndexName enum with custom name logic;
- The next problem is located at line 147 in the elastic.py file. In that case, I want to index a molecule with a custom index name, but I cannot do so because the index value should be directly from the IndexName enum (see attachments).

**Indigo/Bingo version**  
bingo version: 1.9.0

**Expected behavior**
IndexName should be more flexible to have ability set custom value. 

**Actual behavior**
We should set up Index name only from IndexName enum.

**Attachments**
<img width="701" alt="image" src="https://user-images.githubusercontent.com/55767250/224302782-2f28b0fc-94a0-4903-acc0-efb9baa61d64.png">

**Comment by MysterionRise** [comment]
Thanks for reporting @bodyangug , will take a look into ti
