### ISSUE TITLE
How to "run" the reaction and get the resulting products in Indigo?

### ISSUE THREAD

**Issue by joeyissa** [epam/Indigo#1067]
Apologies for posting this here as this a question about functionality and not an actual feature/bug, but I wasnt able to find any community boards... I have spent a few hours reviewing the API documentation but it's not clear to how to actually "run" the reaction based on given reaction SMARTS . For example in the sample below for the hydrolysis of an ester. I have created a reaction using hydrolysis SMARTS. Which method do I need to call at this point to get the SMILES of the products of this hydrolysis reaction which will be CC(=O)O (acetic acid) and CCO (ethanol)?

```
            Indigo indigo = new Indigo();
            string smartsHydrolysis = "[#6:1][C:2](=[O:3])[O:4][#6:5].[O:6]>>[#6:1][C:2](=[O:3])[O:6].[O:4][#6:5]";
            IndigoObject? possibleEster = indigo.loadMolecule("CC(=O)OCC"); // ethyl acetate in this case
            IndigoObject? h2o = indigo.loadMolecule("O"); // water molecule
            IndigoObject? rxn = indigo.loadReactionSmarts(smartsHydrolysis);
```

**Comment by mkviatkovskii** [comment]
Hello @joeyissa,
This is the simple example. For now it requires to use a little bit low level API to create Indigo array with monomers:
```C#
// Initialize session
Indigo indigo = new Indigo();

// Load reaction template
IndigoObject? = reaction = indigo.loadReactionSmarts("[#6:1][C:2](=[O:3])[O:4][#6:5].[O:6]>>[#6:1][C:2](=[O:3])[O:6].[O:4][#6:5]");

// Create monomers table
IndigoObject? monomers_table = indigo.createArray();
monomers_table.arrayAdd(indigo.createArray());
monomers_table.arrayAdd(indigo.createArray());

// Add one monomer to first reactants list
monomers_table.at(0).arrayAdd(indigo.loadMolecule("CC(=O)OCC"));
// Add one monomer to second reactants list
monomers_table.at(1).arrayAdd(indigo.loadMolecule("O"));

// Run reaction product enumeration
IndigoObject? output_reactions = indigo.reactionProductEnumerate(reaction, monomers_table);

// Output result reactions.
// Not sure if Indigo properly supports foreach in this case.
// Please let me know if you need additional help here
foreach (IndigoObject? elem in output_reactions.iterateArray()) {
    System.Console.WriteLine(elem.canonicalSmiles());
}
```
More detailed information could be found here:
* API (see Reaction Products Enumeration section): https://lifescience.opensource.epam.com/indigo/api/index.html
* Options: https://lifescience.opensource.epam.com/indigo/options/reaction-product-enumeration.html
* Concepts: https://lifescience.opensource.epam.com/indigo/concepts/combichem.html

**Comment by joeyissa** [comment]
Thanks that worked! The only problem is I am not getting the products separated for elem.canonicalSmiles() I get the full reaction `O.CCOC(C)=O>>CCO.CC(O)=O |f:0.1,2.3|`. How can we get the actual products separated. Thanks again!

**Comment by mkviatkovskii** [comment]
> Thanks that worked! The only problem is I am not getting the products separated for elem.canonicalSmiles() I get the full reaction `O.CCOC(C)=O>>CCO.CC(O)=O |f:0.1,2.3|`. How can we get the actual products separated. Thanks again!

Each Reaction instance has method `iterateProducts`. And to iterate isolated components there is a method called `iterateComponents`. We need to use both of them:
```C#
foreach (IndigoObject? elem in output_reactions.iterateArray()) 
{
    foreach (IndigoObject? product in elem.iterateProducts())
    {
        foreach (IndigoObject? component in product.iterateComponents())
        {
            System.Console.WriteLine(component.clone().canonicalSmiles());
        }
    }
}
```

**Comment by joeyissa** [comment]
Thanks so much @mkviatkovskii  I got to the `iterateProducts` part but got stuck :). Appreciate the help!!
