### ISSUE TITLE
render structure image with S/R stereochemistry

### ISSUE THREAD

**Issue by Pandaaaa906** [epam/Indigo#1079]
is it possible to render structure image with S/R stereochemistry like this?
![image](https://user-images.githubusercontent.com/18494105/226858422-a687f83e-bc68-4a46-a105-15e298ece0a2.png)

**Comment by even1024** [comment]
Yes. It can be done using special S-groups. There are some examples: https://github.com/epam/Indigo/tree/master/api/tests/integration/tests/basic/molecules/CIP
