### ISSUE TITLE
Indigo canonicalSmiles() producing invalid SMILES

### ISSUE THREAD

**Issue by dan2097** [epam/Indigo#109]
Code to reproduce:

```
Indigo indigo = new Indigo();
IndigoObject mol = indigo.loadMolecule("C1([C@@]([C@]1(C(NC(C(OC2=C(C(F)(F)F)C=CC=C2)[H])C)=O)C)([H])[H])(Cl)Cl");
//Produces a valid SMILES C1(Cl)(Cl)[C@](C)(C(=O)NC(C)C([H])OC2C=CC=CC=2C(F)(F)F)[C@@]1([H])[H]
System.out.println(mol.smiles());
//Produces an invalid SMILES C[C@]1([C@@H2]C1(Cl)Cl)C(=O)NC(C)COC1C=CC=CC=1C(F)(F)F
System.out.println(mol.canonicalSmiles());
//[C@@H2] is clearly incorrect!
```

**Comment by IuriiPuzanov** [comment]
Hello Dan,

   Thank you very much for using Indigo library!
As about finding could you please clarify why atom description [C@@H2] is incorrect?

Best Regards!
Yuriy

**Comment by dan2097** [comment]
In the words of Indigo: "SMILES loader: chirality on atom 2 makes no sense" 
That's not entirely true as it is a tetrahedral center, but as two of the atoms are hydrogens both `@` and `@@ ` become degenerate unless the hydrogens are labelled. As there is no legitimate use for needing more than one hydrogen after `@/@@` most SMILES parsers, including Indigo's reject this. (If hypothetically one of the hydrogens was isotopically labelled it would have to be an explicit atom)
Essentially the issue is that the original SMILES input had superfluous/redundant stereochemistry specified, which at least at the point of writing canonical SMILES should be removed.
I note that if a user specifies cis bonds on benzene e.g. C1=C/C=C\C=C1 that Indigo ignores this information, so there is a precedence for dropping superfluous stereochemistry information.
The original SMILES came from a sketch where the hydrogens were explicit atoms for whatever reason.

**Comment by IuriiPuzanov** [comment]
Hello Dan,

   I've fixed this issue in accordance with your description.
The changes are on master branch now. Tell us please about any notes.

Thank you very much for your finding!

Best Regards!
Yuriy

**Comment by dan2097** [comment]
Just to note that these same structures (redundant two hydrogen tetrahedral stereocentres) also cause silent errors when encountered by Bingo No SQL 1.3.0beta.r16. It "succesfully" adds them to the index, but when the matcher encounters one no further results are returned (easiest to show by doing a similarity search that matches structures with similarities as low as 0, the last structure returned will be one before the problematic structure). I haven't checked whether this is fixed with the latest source code (I'm calling from Java). Fixing was a simple as searching for stereocentres with >2 hydrogen and calling resetStereo. It still might be worth investigating why the Bingo No SQL didn't produce an actual error (or at least not one visible from Java).
