### ISSUE TITLE
python binding memory leak from 1.8.0 (and still present in 1.10.0)

### ISSUE THREAD

**Issue by flc** [epam/Indigo#1093]
Given this simple Python script `indigo_memory_leak.py`:

```python
import os
import psutil
import indigo

process = psutil.Process(os.getpid())

def print_mem(i):
    mem_mb = process.memory_info().rss / 1024 ** 2
    print(f'{i} {mem_mb} MB')

def main():
    # ind = indigo.Indigo()
    for i in range(1, 100001):
        if i % 20000 == 0:
            print_mem(i)
        ind = indigo.Indigo()
        ind.loadMolecule('c1ccccc1')

main()
print_mem('end')
```

**indigo 1.7.4**
The memory usage remains constant.
`time python indigo_memory_leak.py` output:
```
20000 17.74609375 MB
40000 17.74609375 MB
60000 17.74609375 MB
80000 17.74609375 MB
100000 17.74609375 MB
end 17.74609375 MB

real    0m33.622s
user    0m33.612s
sys     0m0.010s
```

**indigo 1.8.0**
The memory usage keeps increasing.
`time python indigo_memory_leak.py` output:
```
20000 329.140625 MB
40000 634.81640625 MB
60000 940.94140625 MB
80000 1246.70703125 MB
100000 1552.92578125 MB
end 1552.92578125 MB

real    0m21.602s
user    0m20.691s
sys     0m0.911s
```

**indigo 1.10.0**
The memory usage keeps increasing.
`time python indigo_memory_leak.py` output:
```
20000 330.81640625 MB
40000 636.51171875 MB
60000 942.56640625 MB
80000 1248.07421875 MB
100000 1554.3828125 MB
end 1554.3828125 MB

real    0m25.900s
user    0m24.918s
sys     0m0.981s
```

**Expected behavior**
The memory usage remains constants.

**Actual behavior**
The memory usage keeps increasing.

Tested with Python versions:
Python 3.9.16
Python 3.10.10
Python 3.11.2
The memory leak is present with all tested Python versions.

**Comment by Wadym** [comment]
Running a loop of molecule loading through Python api confirms memory increase with iterations:

Running indigo-depict in a loop that encloses object creation and its deletition confirms memory increase:
`<pre>$ sudo ./indigo-depict sub_mar_q01.mol sub_mar_q01.ket

[sudo] password for vg: 

total program memory size 4419 

total program memory size 34294 

total program memory size 64107 

total program memory size 93939 

total program memory size 123738 

total program memory size 153623 

total program memory size 183391 

total program memory size 213195 

total program memory size 242998 

total program memory size 272939 </pre>`

But running two test cases, one through c-api and another through c++-api with sanitizers as well as running indigo-depict with valgind have not revealed any issues with memory leak:

**Comment by Wadym** [comment]
It was confirmed that memory increase was due to inefficient object usage but not becase of memory leak. The reason of memory increase has been fixed.
`$ python leak_load_molecule.py 
20000 26.73046875 MB
40000 26.73046875 MB
60000 26.73046875 MB
80000 26.73046875 MB
100000 26.73046875 MB
end 26.73046875 MB

`
