### ISSUE TITLE
Pathological performance when generating canonical Smiles for complex molecules

### ISSUE THREAD

**Issue by dan2097** [epam/Indigo#110]
Certain molecules have pathological performance when generating canonical SMILES. This can be reproduced through Indigo or Bingo.

I am aware that certain highly symmetrical molecules can be pathological for canonical SMILES generation (although this isn't actually an example of that). The acute issue I'm facing is trying to get the function to abort when called as a database function after a fixed timeout, so that such cases can be elegantly skipped. I see that Bingo actually has a timeout parameter which appears to default to 60,000ms... but also doesn't appears to be taken into account by the PostgreSQL CanSMILES function? [my use case is using the canonical SMILES as the primary key in the index to avoid indexing the same molecule twice, but still allow different tautomers to be indexed]

`select bingo.CanSMILES('C1[C@H]2C[C@H]3C([C@@H]1C[C@@H](C2)C3)(C)OC(C(C)(CC)CC(C(OC4([C@@H]5C[C@@H]6C[C@H]4C[C@H](C5)C6)C)=O)(C)CC(C(OC7([C@@H]8C[C@@H]9C[C@H]7C[C@H](C8)C9)C)=O)(C)CC(C(OC%10([C@@H]%11C[C@@H]%12C[C@H]%10C[C@H](C%11)C%12)C)=O)(C)CC(C(OC%13([C@@H]%14C[C@@H]%15C[C@H]%13C[C@H](C%14)C%15)C)=O)(C)CC(C(OC%16([C@@H]%17C[C@@H]%18C[C@H]%16C[C@H](C%17)C%18)C)=O)(C)CC(C(OC%19([C@@H]%20C[C@@H]%21C[C@H]%19C[C@H](C%20)C%21)C)=O)(C)CC(C(OC%22([C@@H]%23C[C@@H]%24C[C@H]%22C[C@H](C%23)C%24)C)=O)(C)CC(C(OC%25([C@@H]%26C[C@@H]%27C[C@H]%25C[C@H](C%26)C%27)C)=O)(C)CC(C(OC%28([C@@H]%29C[C@@H]%30C[C@H]%28C[C@H](C%29)C%30)C)=O)(C)CC(C(OC%31([C@@H]%32C[C@@H]%33C[C@H]%31C[C@H](C%32)C%33)C)=O)(C)CC(C(OC%34([C@@H]%35C[C@@H]%36C[C@H]%34C[C@H](C%35)C%36)C)=O)(C)CC(C(OC%37([C@@H]%38C[C@@H]%39C[C@H]%37C[C@H](C%38)C%39)C)=O)(C)CC(C(OC%40([C@@H]%41C[C@@H]%42C[C@H]%40C[C@H](C%41)C%42)C)=O)(C)CC(C(OC%43([C@@H]%44C[C@@H]%45C[C@H]%43C[C@H](C%44)C%45)C)=O)(C)CC(C(OC%46([C@@H]%47C[C@@H]%48C[C@H]%46C[C@H](C%47)C%48)C)=O)(C)CC(C(OC%49([C@@H]%50C[C@@H]%51C[C@H]%49C[C@H](C%50)C%51)C)=O)(C)CC(C(OC%52([C@@H]%53C[C@@H]%54C[C@H]%52C[C@H](C%53)C%54)C)=O)(C)CC(C(OC%55([C@@H]%56C[C@@H]%57C[C@H]%55C[C@H](C%56)C%57)C)=O)(C)CC(C(OC%58([C@@H]%59C[C@@H]%60C[C@H]%58C[C@H](C%59)C%60)C)=O)(C)CC(C(OC%61([C@@H]%62C[C@@H]%63C[C@H]%61C[C@H](C%62)C%63)C)=O)(C)CC(C(OC%64([C@@H]%65C[C@@H]%66C[C@H]%64C[C@H](C%65)C%66)C)=O)(C)CC(C(OC%67([C@@H]%68C[C@@H]%69C[C@H]%67C[C@H](C%68)C%69)C)=O)(C)CC(C(OC%70([C@@H]%71C[C@@H]%72C[C@H]%70C[C@H](C%71)C%72)C)=O)(C)CC(C(OC%73([C@@H]%74C[C@@H]%75C[C@H]%73C[C@H](C%74)C%75)C)=O)(C)CC(C(OC%76([C@@H]%77C[C@@H]%78C[C@H]%76C[C@H](C%77)C%78)C)=O)(C)CC(C(OC%79([C@@H]%80C[C@@H]%81C[C@H]%79C[C@H](C%80)C%81)C)=O)(C)CC(C(OC%82([C@@H]%83C[C@@H]%84C[C@H]%82C[C@H](C%83)C%84)C)=O)(C)CC(C(OC%85([C@@H]%86C[C@@H]%87C[C@H]%85C[C@H](C%86)C%87)C)=O)(C)CC(C(OC%88([C@@H]%89C[C@@H]%90C[C@H]%88C[C@H](C%89)C%90)C)=O)(C)CC(C(OC%91([C@@H]%92C[C@@H]%93C[C@H]%91C[C@H](C%92)C%93)C)=O)(C)CC(C(OC%94([C@@H]%95C[C@@H]%96C[C@H]%94C[C@H](C%95)C%96)C)=O)(C)CC(C(OC%97([C@@H]%98C[C@@H]%99C[C@H]%97C[C@H](C%98)C%99)C)=O)(C)CC(C(OC1([C@@H]2C[C@@H]3C[C@H]1C[C@H](C2)C3)C)=O)(C)CC(C)(C(OC4([C@@H]5C[C@@H]6C[C@H]4C[C@H](C5)C6)C)=O)C)=O')`

**Comment by dan2097** [comment]
Just to add, the timeout functionality in the underling Indigo toolkit **does** work correctly e.g.
Indigo indigo = new Indigo();
indigo.setOption("timeout", "60000");
IndigoObject mol = indigo.loadMolecule(smiles);
mol.canonicalSmiles();

will correctly abort with an exception "Molecule automorphism search timeout: The operation timed out: 60000 ms", so this is really just a Bingo issue.

**Comment by IuriiPuzanov** [comment]
Hello, Dan!

   Thank you very much for finding.
I've added support of the timeout parameter from Bingo config for calculation Canonical SMILES.
Fixed version is available on master branch now.
   Tell me please in case any issues or questions.

Best Regards!
Yuriy.
