### ISSUE TITLE
Check structure and Calculate values are not working for H+ atom

### ISSUE THREAD

**Issue by AleksandraSmolianinova** [epam/Indigo#1146]
**Steps to Reproduce**
1. Open the Extended table
2. Click the "H+" button in the 'Special Nodes' section click the Add button and click the canvas.
3. Click the 'Check Structure' button.
4. Close the window.
5. Click the 'Calculated Values' button.
6. Close the window.

**Expected behavior**
1. The H+ symbol is recognized as correct hydrogen atom with the Plus charge. The 'Structure Check' window contains the "No errors found" text.
2. The H+ symbol is recognized as correct hydrogen atom with the Plus charge. The fields in the  'Calculated Values' window are filled with info about the hydrogen atom:
Chemical Formula: H
Molecular Weight: 1.008
Exact Mass: 1.008
Elemental Analysis: H 100
**Actual behavior**
![image](https://github.com/epam/Indigo/assets/130548475/feea0814-493e-467b-afe7-24c8faea1ca2)
![image](https://github.com/epam/Indigo/assets/130548475/263c8660-f4e3-460e-8e3d-2f2ffa790362)

**Indigo/Bingo version**  
Version 1.12.0-rc.1.0-gc9f696226-x86_64-linux-gnu-11.2.1

**Comment by AleksandraSmolianinova** [comment]
This bug appears while testing those cases:
https://jiraeu.epam.com/browse/EPMLSOPKET-14085  https://jiraeu.epam.com/browse/EPMLSOPKET-14087  https://jiraeu.epam.com/browse/EPMLSOPKET-14089  https://jiraeu.epam.com/browse/EPMLSOPKET-14091  https://jiraeu.epam.com/browse/EPMLSOPKET-14093

As you can see ER is (for example, for 14087): a) The 'Structure Check' window contain s the "No errors found" text. b) the D symbol is recognized as correct Deuterium. The fields in the  'Calculated Values' window are filled with info about the deuterium hydrogen atom:
Chemical Formula: H
Molecular Weight: 2.014
Exact Mass: 2.014
Elemental Analysis: H 100

**Comment by even1024** [comment]
This issue should be solved on Ketcher's side.

**Comment by AliaksandrDziarkach** [comment]
Ketcher send proton as atom labeled 'H+' which is wrong. 
It shoud be 'H' atom with charge 1.

**Comment by AlexanderSavelyev** [comment]
@AleksandraSmolianinova please create a ticket in Ketcher
