### ISSUE TITLE
Bingo unable to index on SQL Server

### ISSUE THREAD

**Issue by boglet** [epam/Indigo#1161]
**Steps to Reproduce**
1. Use Indigo library (Bingo cartridge). Latest release on SQL Server 16.0.1000.6
2. exec bingo.CreateMoleculeIndex 'mycsdb', 'id', 'smiles';

**Expected behavior**
Index expected.

**Actual behavior**
Indexing fails with missing ".resources" manifest (see below)

**Attachments**
```
Msg 6522, Level 16, State 1, Procedure bingo.z_CreateMoleculeIndex, Line 0 [Batch Start Line 0]
A .NET Framework error occurred during execution of user-defined routine or aggregate "z_CreateMoleculeIndex": 
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "  .resources" was correctly embedded or linked into assembly "bingo-sqlserver" at compile time, or that all the satellite assemblies required are loadable and fully signed.
System.Resources.MissingManifestResourceException: 
   at indigo.Bingo._ExecuteBingoOperation(SqlString bingo_schema, bingoOperationDelegate operationDelegate, bingoGetIndexDataDelegate getBingoDataDelegate, BingoOp op_flags)
   at indigo.Bingo._ExecuteBingoOperationChangeIndex(SqlString bingo_schema, bingoOperationDelegate operationDelegate, bingoGetIndexDataDelegate getBingoDataDelegate, BingoOp flags)
   at indigo.Bingo.CreateIndex(SqlString table, SqlString id_column, SqlString data_column, SqlString bingo_schema, Boolean reaction)
```

**Indigo/Bingo version**  
Downloaded 26/06/2023

**Additional context**

**Comment by santiagomestrelab** [comment]
I have detected the same problem.
Using SQLServerDeveloper version 16.0.1000.6 and BingoDB version bingo-sqlserver-windows-x86_64-1.9.1.587,
and SQLServerExpress version 15.0.4316.3 and BingoDB version bingo-sqlserver-windows-x86_64-1.9.1.544

Regards
Santiago

**Comment by sapiosciences** [comment]
The old 1.9.1 version is working and the binaries released since then do not for MS-SQL.
I would also note the bingo-sqlserver.dll file size is 10MB in 1.9.1, which is twice as what we have in master.

I'm guessing it's missing some assemblies resources.

**Comment by AlexanderSavelyev** [comment]
Hi all

Thanks for the problem report. We will investigate the issue with compiling bingo-sqlserver dll

Thanks
Aleksandr

**Comment by santiagomestrelab** [comment]
Good afternoon
Do you know when will be available a release with this fix?
Regards

**Comment by santiagomestrelab** [comment]
Good morning
It seems that in the two latest Bingo versions released, 1.13.0 and 1.14.0, this problem has not been solved
Best regards

**Comment by santiagomestrelab** [comment]
Good morning
I have tested the new version 1.16.0 and the problem remains.
I am sorry, but it is difficult to understand the situation here.

**Comment by boglet** [comment]
I'm also wondering what is going on. It appears that the SQL Server dll is still not fixed and we have had several releases sine then. Please could someone fix this? It is a shame because it works well for Postgres but we need to use it with SQL Server...

**Comment by AlexeyGirin** [comment]
Almost impossible to check
Decided with @AlexanderSavelyev to skip

**Comment by AlexanderSavelyev** [comment]
Tested with SQL Server 2019. All index and search methods work
