### ISSUE TITLE
Error message when trying to save structure with Multiple Group type applied to entire structure

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1168]
**Steps to Reproduce**
1. Open Ketcher
2. Add Benzene on canvas
3. Select all structure
4. Press 'S-Group' button and select Type = Miltiple group, Repeat count = 1
5. Press 'Apply'
6. Press 'Save' button
**Note: the bug is not reproduced on the remote version of the Ketcher**

**Actual behavior**
Error message when trying to save structure with Multiple Group type applied to entire structure

**Expected behavior**
When you press save button, no error message appears and user can save the structure in selected format

**Screenshots**
![2023-07-03_10h50_45](https://github.com/epam/ketcher/assets/62464241/2edfab63-2118-4c43-a8b5-e2eda0933c49)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Indigo version** 
[Version 1.12.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)

**Comment by Wadym** [comment]
> 6\. Note: the bug is not reproduced on the remote version of the Ketcher

Remote (http) version using Python's tests reproduces the bug. Pull request related to this bug fixes it for both remote and local usages.

Ketcher's remote call should be checked on why the remote call did not rise the error message. Is there a try...catch in Ketcher around the call?
