### ISSUE TITLE
canonicalSmiles often flips stereochemistry

### ISSUE THREAD

**Issue by jstaker7** [epam/Indigo#117]
This may be a fairly serious issue.

In about ~15% of our tests SMILES are incorrect when we load a molecule from a mol file and output canonical smiles.

For example, using the attached mol file and running the following code:

    from indigo import Indigo
    indigo = Indigo()
    mol = indigo.loadMoleculeFromFile('test2.mol')
    print(str(mol.smiles()))
    print(str(mol.canonicalSmiles()))

The SMILES have different stereochemistry (canonicalSmiles being incorrect).

[test2.mol.zip](https://github.com/epam/Indigo/files/1617048/test2.mol.zip)

**Comment by IuriiPuzanov** [comment]
Hello Josh,

   Thank you very much for your interest to Indigo!
As about issue as I see your input molfile has no chiral flag and
as result the structure is loaded as "racemate" by default.
For change default behavior you can use Indigo option "ignore-no-chiral-flag", 
and if you set this option into "true" the stereo configuration will be treated "as drawn".
   Use the latest Indigo version, please.

Best Regards!
Yuriy

**Comment by jstaker7** [comment]
Thank you for the response, although I'm not quite satisfied with this answer.

In the bond specification table the line "4  6  1  6" indicates that this is a "down" configuration.

Not all sketching software defaults to setting the chiral flag when sketching molecules. For example, in epam's Ketcher it appears that this is this case (drawing a chiral molecule does not trigger the "1" chiral flag when saving out to mol). 

Although in a mol file no chiral means racemic, specifying "@" or "@@" in a SMILES means absolute chirality is specified. Even without setting "ignore-no-chiral-flag" I would expect that when going from mol to SMILES and assigning a particular configuration in the SMILES as part of the conversion, it's best to default to the bond configurations in the table (or no configuration at all) rather than potentially being incorrect.

Also, the fact that smiles() and canonicalSmiles() return different results and is not consistent either way is alarming.

Thoughts on these comments?

**Comment by IuriiPuzanov** [comment]
Hello Josh,

   Thank you very much for the comments.
But by default Indigo trusts the input molfile data, so if chiral flag is absent we treat the structure as
racemic. For handle described wrong cases the special flag should be used. As about Ketcher our latest 
includes  corresponding feature for setting chiral flag for drawn structure. Also as I see the output 
SMILES and canonical SMILES are consistent and correct in both cases

after loading as racemic (by default):

N1(C(CC)=O)C[C@H](C2=C3C=C(C)NC3=C(C(N)=O)C=C2)CC1 |&1:6,r|
CC1=CC2C(N1)=C(C=CC=2[C@@H]1CN(CC1)C(=O)CC)C(N)=O |&1:10,r|

and loading with "ignore-no-chiral-flag":

N1(C(CC)=O)C[C@H](C2=C3C=C(C)NC3=C(C(N)=O)C=C2)CC1
CC1=CC2C(N1)=C(C=CC=2[C@H]1CN(CC1)C(=O)CC)C(N)=O

Best Regards!
Yuriy
