### ISSUE TITLE
HELM ver 2.04 support multiple sequences and connection tables (import and export)

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1188]
**Background**
Indigo macromolecules support

**Solution**
Import and export of multiple RNA, PEPRIDE, CHEM in one string. Support connection tables.
Tests should include corresponding KET<>HELM<>MOL conversions.

HELM notation could be found here: https://www.pistoiaalliance.org/helm-notation/
Reference: [HELM Specification 2_04-1.pdf](https://github.com/user-attachments/files/15740988/HELM.Specification.2_04-1.pdf)
Decided to support only features that implemented in Ketcher already
That is
- 5.2 Simple Polymer section
	Implementation of two types of specific simple polymers: PEPTIDE, and RNA
	Implementation of non-specific simple polymer type: CHEM
	Implementation of unknown polymer type: BLOB
	Implementation of simple polymer notation (i.e. chains consists of polymers of supported types)
	Out of scope: 
		Monomer Lists (pp. 5.2.4.1 should not be implemented)
		Monomer repeating units (pp. 5.2.4.2 should not be implemented)
		Monomer annotation (pp. 5.2.5 should not be implemented)
- 5.3 Complex Polymer
	Implementation of list of connection between backbone chains
	Out of scope: 
		Unknown positions 
		Hydrogen pairings (pp. 5.2.5 should not be implemented)
 - 5.6 In-line HELM notation
         Implementation of SMILES and Extended SMILES formats support

**Comment by AlexeyGirin** [comment]
http://webeditor.openhelm.org/hwe/examples/App.htm

**Comment by AlexeyGirin** [comment]
[Test Set V1_0.xlsx](https://github.com/user-attachments/files/15741173/Test.Set.V1_0.xlsx)

**Comment by AlexeyGirin** [comment]
Verified.

Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
Indigo Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
Win 10
Chrome Version 126.0.6478.127 (Official Build) (64-bit)
