### ISSUE TITLE
Migrate indigo-knime nodes to KNIME Analytics Platform 5.1 

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/Indigo#1197]
**Background**
There is a new version of KNIME platform version. Indigo KNIME nodes should support it

**Solution**
Perform  migration from Buckminster->Maven project for indigo-knime in order to support the new platform

**Comment by steffen-fissler** [comment]
I prepared some [commits](https://github.com/steffen-fissler/Indigo/tree/test-5.1).

The remaining issue about Indigo failing on MacOS is already described in [this thread](https://github.com/epam/Indigo/issues/762).

Shall I squash mine with yours and open a PR? As the MacOS issue is an ongoing bug which existed before, I think we can publish in parallel while working at the issue.
