### ISSUE TITLE
Molecule loading is not working

### ISSUE THREAD

**Issue by Seva-Vaskin** [epam/Indigo#1213]
**Steps to Reproduce**
Run this c++ program: 
```
#include "IndigoSession.h"
#include "IndigoMolecule.h"
#include <string>

int main() {
    std::string smiles = "C";
    indigo_cpp::IndigoSessionPtr session = indigo_cpp::IndigoSession::create();
    auto molecule = session->loadMolecule(smiles);
    return 0;
}
```

**Expected behavior**
I expect the molecule to load without error

**Actual behavior**
An error occurs: basic_string::_S_construct null not valid

**Indigo/Bingo version**  
Indigo 1.12.0 (https://github.com/epam/Indigo/tree/0e3666ae76ee381254038ea3179b9d7cef2debcf)

**Comment by even1024** [comment]
typical approach is:

std::string smiles = "C";
auto session = IndigoSession::create();
session->loadMolecule(smiles.c_str());

loadMoleclue accepts null-terminated string

**Comment by even1024** [comment]
Will take a closer look

**Comment by Seva-Vaskin** [comment]
I must have messed around with the project configuration, because after simplifying CMake the error disappeared 
So I am not bothered by this error anymore, sorry for the inconvenience.

Nevertheless, here is a [project](https://github.com/Seva-Vaskin/indigo-test) to reproduce the error so you can figure it out. 

If you comment out line 7 of lib/CMakeLists.txt, the error will go away.
