### ISSUE TITLE
SMARTS Component-Level Grouping doesn't work

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#1242]
As an example, the following SMARTS query:
`([#8:1].[#6:2])>>([#8:1][#6:2])`
would mean that the LHS is talking about a single molecule and right hand side is on a single molecule.
That should have matched the reaction
[c:1]1([cH:10][cH:9][cH:8][cH:7][c:3]1[CH:4]([CH3:6])[OH:5])[OH:2]>>[c:1]12[cH:10][cH:9][cH:8][cH:7][c:3]1[CH:4]([CH2:6][O:2]2)[OH:5]
on atoms 2 and 6.

What we have noticed:
1) The reaction do not match using
```
query = indigo.loadReactionSmarts("([#8:1].[#6:2])>>([#8:1][#6:2])")

reaction = indigo.loadReaction("[c:1]1([cH:10][cH:9][cH:8][cH:7][c:3]1[CH:4]([CH3:6])[OH:5])[OH:2]>>[c:1]12[cH:10][cH:9][cH:8][cH:7][c:3]1[CH:4]([CH2:6][O:2]2)[OH:5]")


match = indigo.substructureMatcher(reaction).match(query) 
```
2) The SMARTS query had seem to automatically removed the parentheses
it is evident when we do (query.smarts()) that it returns
`[#8:1].[#6:2]>>[#8:1]-,:[#6:2]`

This issue consists at least of two issues:
- [x] #1252 
- [x] #1254

**Comment by AlexanderSavelyev** [comment]
need to check matcher

**Comment by AliaksandrDziarkach** [comment]
Already fixed
Verified indigo-1.15.0-rc1:

```python
from indigo import Indigo
indigo=Indigo()
query = indigo.loadReactionSmarts("([#8:1].[#6:2])>>([#8:1][#6:2])")
reaction = indigo.loadReaction("[c:1]1([cH:10][cH:9][cH:8][cH:7][c:3]1[CH:4]([CH3:6])[OH:5])[OH:2]>>[c:1]12[cH:10][cH:9][cH:8][cH:7][c:3]1[CH:4]([CH2:6][O:2]2)[OH:5]")
match = indigo.substructureMatcher(reaction).match(query)
print(match is not None)
``` 

Got 
```
True
```
So close as fixed
