### ISSUE TITLE
The structure with R-groups can't be saved in Daylight SMARTS format

### ISSUE THREAD

**Issue by chloechow** [epam/Indigo#1247]
**Steps to Reproduce**
Run next python code:
```
from indigo import *

indigo = Indigo()
mol = indigo.loadSmarts('c1c([*:2])c([*:3])ccn1')
mol.smarts()
```

**Expected behavior**
Got the SMARTS like the input, `c1c([*:2])c([*:3])ccn1`.

**Actual behavior**
Got `IndigoException: SMILES saver: Unknown atom attribute 6`.

**Indigo version**  
1.12.0

**Comment by AliaksandrDziarkach** [comment]
Already fixed.

Tested at with indigo-1.16.0-rc.2 - issue not reproduced.
