### ISSUE TITLE
Fails to build with glibc 2.26 and newer (due to removal of xlocale.h)

### ISSUE THREAD

**Issue by dleidert** [epam/Indigo#126]
Hi,

indigo [won't build with glibc 2.26][1] or newer, due to the [removal of xlocale.h][2]. It seems to me, that [locale_guard.h](../tree/master/common/base_cpp/locale_guard.h) in the master branch has not yet been fixed.

Regards, Daniel

[1]: https://bugs.debian.org/887777
[2]: https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27

**Comment by AlexanderSavelyev** [comment]
Our tests and build system targets old versions of glibc, due to old OS compatibility. But just removed the xlocale.h on [master ](https://github.com/epam/Indigo/commit/ca39ad280c180e9deaaedd6cf26714a5e7f253e7) and it seems that all tests are passed

**Comment by mbanck** [comment]
Would be good to release a 1.2.4 or so with this fix as people will start to compile indigo with current distributions shipping glibc 2.26+
