### ISSUE TITLE
After opening a saved Extended SMILES file Single Up Bond is changed to Single Down Bond

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1272]
**Steps to Reproduce**
1. Load the following molfile [atrop_enhanced_stereo.zip](https://github.com/epam/Indigo/files/12094011/atrop_enhanced_stereo.zip)
2. Save into Extended SMILES
3. Open saved file

![2023-09-13_16h35_44](https://github.com/epam/Indigo/assets/62464241/76e74c91-263a-403b-a7e5-9291ea275df8)

**Expected behavior**
Stereo information for bond and atom is kept. Single Up Bond is kept.

**Actual behavior**
Stereo information for bond and atom is kept. Single Up Bond is changed to Single Down Bond.

#185522135

**Comment by even1024** [comment]
Fixed in 1.15.0.rc.2
