### ISSUE TITLE
Can't compile based on instructions ...

### ISSUE THREAD

**Issue by dylan-jayatilaka** [epam/Indigo#131]
Hello,

I followed the instructions for Linux, but they failed because the python scripts were not executable.

Then I made those build scripts executable, adding a shebang comment at the start. Still no luck.

Here is the error message, from cmake:
Note python version is 2.7.15rc1

 cmake -G "Unix Makefiles" -DSUBSYSTEM_NAME=x64 /home/dylan/github/Indigo/build_scripts/indigo-all
-- System-specific folder name: Linux
-- Subsystem-specific folder name: x64
-- Set CMAKE_BUILD_TYPE to Release
-- Common output dir: /home/dylan/github/Indigo/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_x64/dist/Linux/x64
-- **** Indigo ****
-- Using local ZLib library
-- Indigo full version: 1.3.0beta.r371-g4df080cc
-- Indigo version is 1.3.0beta.r371
-- **** Indigo-inchi ****
-- **** Indigo-renderer ****
-- Using local LibPNG library
-- Using local Pixman library
-- Using local Cairo library
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)
  /home/dylan/github/Indigo/third_party/cairo-src/cairo/CMakeLists.txt:154 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/dylan/github/Indigo/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_x64/CMakeFiles/CMakeOutput.log".
CMake Error: Cannot open file for write: /home/dylan/github/Indigo/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_x64/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /home/dylan/github/Indigo/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_x64/CMakeCache.txt
CMake Error: : System Error: Permission denied
Traceback (most recent call last):
  File "./build_scripts/indigo-release-libs.py", line 215, in <module>
    build_libs(sys.argv[1:])
  File "./build_scripts/indigo-release-libs.py", line 165, in build_libs
    check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' cmake -G "Unix Makefiles" -DSUBSYSTEM_NAME=x64 /home/dylan/github/Indigo/build_scripts/indigo-all' returned non-zero exit status 1

**Comment by dylan-jayatilaka** [comment]
OK, after reading the error message, I found I needed cairo and freetype.
Both of these were npt so easy to install on ubutu, the ppa's being out of date.
For those interested I did:

sudo apt-get install cairo-dock cairo-dock-plug-ins
sudo apt install libcairo2-dev

But I am not sure if I did too much, or what ...

--dylan

**Comment by dylan-jayatilaka** [comment]
OK, more googling shows that the first part of the above error comes from Imagemagick.

To correct it you have to change the security policy. See here:

https://stackoverflow.com/questions/52861946/imagemagick-not-authorized-to-convert-pdf-to-an-image

Otherwise there are still these errors:

from: can't read /var/mail/optparse
./build_scripts/indigo-release-utils.py: 9: ./build_scripts/indigo-release-utils.py: version: not found
./build_scripts/indigo-release-utils.py: 10: ./build_scripts/indigo-release-utils.py: Syntax error: "(" unexpected

... with any luck I won't need this?

--dylan

**Comment by dylan-jayatilaka** [comment]
I am sorry, I mistyped the shebang.

Now mostly everything works, but I get this error after 
   sudo ./build_scripts/indigo-release-utils.py --preset=linux64

CC=gcc CXX=g++ cmake -G "Unix Makefiles" -DSUBSYSTEM_NAME=x64 -DCMAKE_BUILD_TYPE=Release /home/dylan/github/Indigo/build_scripts/indigo-utils
-- System-specific folder name: Linux
-- Subsystem-specific folder name: x64
-- Common output dir: /home/dylan/github/Indigo/build/indigo_utils_Unix_Makefiles__DSUBSYSTEM_NAME_x64__DCMAKE_BUILD_TYPE_Release/dist/Linux/x64
-- **** Indigo ****
-- Using local ZLib library
-- Indigo full version: 1.3.0beta.r371-g4df080cc
-- Indigo version is 1.3.0beta.r371
-- **** Indigo-renderer ****
-- Using local LibPNG library
-- Using local Pixman library
-- Using local Cairo library
-- **** Indigo-cano ****
-- **** Indigo-deco ****
-- **** Indigo-depict ****
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dylan/github/Indigo/build/indigo_utils_Unix_Makefiles__DSUBSYSTEM_NAME_x64__DCMAKE_BUILD_TYPE_Release
cmake --build . --config Release
[  4%] Built target z
[ 12%] Built target common
[ 13%] Built target tinyxml
[ 24%] Built target inchi
[ 30%] Built target graph
[ 45%] Built target molecule
[ 51%] Built target reaction
[ 55%] Built target layout
[ 60%] Built target indigoObj
[ 60%] Built target indigo-shared
[ 60%] Built target indigo-c-test-shared
[ 60%] Built target dlopen-test
[ 63%] Built target png
[ 70%] Built target pixman
[ 94%] Built target cairo
[ 97%] Built target render2d
[ 97%] Built target indigo-renderer-Obj
[ 98%] Built target indigo-renderer-shared
[ 98%] Built target indigo-renderer-c-test-shared
[ 98%] Linking C executable ../dist/Linux/x64/lib/indigo-cano
/usr/bin/ld: cannot find -lindigo
collect2: error: ld returned 1 exit status
indigo-cano/CMakeFiles/indigo-cano.dir/build.make:94: recipe for target 'dist/Linux/x64/lib/indigo-cano' failed
make[2]: *** [dist/Linux/x64/lib/indigo-cano] Error 1
CMakeFiles/Makefile2:2062: recipe for target 'indigo-cano/CMakeFiles/indigo-cano.dir/all' failed
make[1]: *** [indigo-cano/CMakeFiles/indigo-cano.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
[  4%] Built target z
[ 12%] Built target common
[ 13%] Built target tinyxml
[ 24%] Built target inchi
[ 30%] Built target graph
[ 45%] Built target molecule
[ 51%] Built target reaction
[ 55%] Built target layout
[ 60%] Built target indigoObj
[ 60%] Built target indigo-shared
[ 60%] Built target indigo-c-test-shared
[ 60%] Built target dlopen-test
[ 63%] Built target png
[ 70%] Built target pixman
[ 94%] Built target cairo
[ 97%] Built target render2d
[ 97%] Built target indigo-renderer-Obj
[ 98%] Built target indigo-renderer-shared
[ 98%] Built target indigo-renderer-c-test-shared
[ 98%] Linking C executable ../dist/Linux/x64/lib/indigo-cano
/usr/bin/ld: cannot find -lindigo
collect2: error: ld returned 1 exit status
indigo-cano/CMakeFiles/indigo-cano.dir/build.make:94: recipe for target 'dist/Linux/x64/lib/indigo-cano' failed
make[2]: *** [dist/Linux/x64/lib/indigo-cano] Error 1
CMakeFiles/Makefile2:2062: recipe for target 'indigo-cano/CMakeFiles/indigo-cano.dir/all' failed
make[1]: *** [indigo-cano/CMakeFiles/indigo-cano.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "./build_scripts/indigo-release-utils.py", line 99, in <module>
    subprocess.check_call("make package", shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make package' returned non-zero exit status 2

**Comment by IuriiPuzanov** [comment]
Hello Dylan,

  Thank you very much for using Indigo.
Unfortunately building scripts for utils are slightly outdated,
but actually they don't required for your purpose, I believe.
As I understand you successfully built Indigo library and then
you can build any corresponding wrapper (python, java, dotnet)
if it is required, or use library itself.

Tell us please about any question or issues.

Best Regards!
Yuriy

**Comment by ForceFaction** [comment]
I have the exact same problem. It seems CMake dose not add the correct -L directive in the corresponding link.txt files. Manually doing this makes the build succeed.

Does *slighlty outdated build scripts* include the CMake files ?

-- ForceFaction

**Comment by mkviatkovskii** [comment]
Closing this as outdated. Please, reopen if it is still actual.
