### ISSUE TITLE
An error appears when saving a structure with Atom Properties from the "Query specific" section

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/Indigo#1311]
**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Open the Console
3.	Draw any Template (like Benzene) on the canvas 
4.	Add all Atom Properties from the "Query specific" section to any atom
5.	Click on the "Save as" button

**Expected behavior**
There is no error on the screen and in the Console. The structure can be saved

**Actual behavior**
The error appears on the screen in Standalone mode. The error appears in the Console in Remote mode

**Attachments**

https://github.com/epam/Indigo/assets/139227567/b20068e2-d477-4170-b2b6-c101ebb6d919

https://github.com/epam/Indigo/assets/139227567/145d9181-4a01-44d3-b194-f3776d068f3c

**Indigo/Bingo version**  
1.14.0-rc.5.1

**Desktop (please complete the following information):**
•	OS: Windows 10 Pro (version 22H2) x64
•	Browser: Сhrome
•	Version: (114.0.5735.199) x64

**Comment by AliaksandrDziarkach** [comment]
Already fixed
