### ISSUE TITLE
When saving a structure with Atom Properties from the "Query specific" section in the "Daylight SMARTS" file format, properties are displayed incorrectly or an error appears

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/Indigo#1313]
**Case 1: when saving a structure, an error appears**

**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Open the Console
3.	Draw any Template (like Benzene) on the canvas 
4.	Add all Atom Properties from the "Query specific" section to any atom
5.	Click on the "Save as" button
6.	Select the "Daylight SMARTS" file format

**Expected behavior**
There is no error on the screen and in the Console. The structure can be saved in the "Daylight SMARTS" file format

**Actual behavior**
The error appears on the screen and in the Console 

**Case 2: after opening the saved file, properties are displayed incorrectly**

**Steps to Reproduce**
1.	Launch "Ketcher"
2.	Open the Console
3.	Draw any Template (like Benzene) on the canvas 
4.	Add Atom Properties (as in the video) from the "Query specific" section to any atom
5.	Click on the "Save as" button
6.	Select the "Daylight SMARTS" file format
7.	Click on the "Save" button
8.	Open the saved file
9.	Compare results 4 and 8 points

**Expected behavior**
All Atom Properties added initially should be displayed next to the Template after opening the saved file. Atom Properties are displayed near the atom, where these properties were originally added

**Actual behavior**
Only part (not all) of Atom Properties is displayed near the Template. These Atom Properties are not displayed near the atom, where these properties were originally added 

**Attachments**

https://github.com/epam/Indigo/assets/139227567/3025e2f2-7b99-4729-ade6-2af5c6a29b87

https://github.com/epam/Indigo/assets/139227567/d9d11f47-875f-4f54-9aa8-75f6d7ed6540

**Indigo/Bingo version**  
1.14.0-rc.5.1

**Desktop (please complete the following information):**
•	OS: Windows 10 Pro (version 22H2) x64
•	Browser: Сhrome
•	Version: (114.0.5735.199) x64

**Comment by AliaksandrDziarkach** [comment]
Already fixed
