### ISSUE TITLE
1.1.12 release

### ISSUE THREAD

**Issue by mbanck** [epam/Indigo#132]
The old ggasoftware repository had/has a 1.1.12 release (https://github.com/ggasoftware/indigo/releases/tag/indigo-1.1.12), is there a reason this one did not get carried over? Apparently the 1.1.11 release was imported "recently", it would be good to also add 1.1.12 in order to have a complete history.

**Comment by mkviatkovskii** [comment]
Closing this as outdated. Please, reopen if it is still actual.

**Comment by mbanck** [comment]
Outdated in what sense? The 1.1.12 tag hasn't been imported yet, AFAICT?

Maybe a different question would be: what's the actual current stable release of indigo? I see a lot of beta on the releases page.

**Comment by mkviatkovskii** [comment]
OK, I see. We are going to release a stable version in a couple of days, I'll let you know as soon as it's ready. Are you interested in source code or any binary packages?

**Comment by mbanck** [comment]
I'm interested in the source code, I'm doing the binary packages for the Debian and Ubuntu Linux distributions.
