### ISSUE TITLE
List of atoms from custom query is converted into SMARTS file without aliphatic attribute

### ISSUE THREAD

**Issue by urszula-gawlowska** [epam/Indigo#1337]
**Description**
When Indigo converts a custom query with a list of atoms in aliphatic format (uppercase atom symbols, e.g. "F,Cl,Br,I") into a SMARTS file then aliphatic attribute is left out.

**Expected behavior**
Custom query should be converted to: [#9,#17,#35,#53;A]

**Actual behavior**
Custom query is converted to: [#9,#17,#35,#53]

**Technical details**
Method: 
v2/indigo/convert

Payload options:
```
{
  "smart-layout": true,
  "ignore-stereochemistry-errors": true,
  "mass-skip-error-on-pseudoatoms": false,
  "gross-formula-add-rsites": true,
  "aromatize-skip-superatoms": true,
  "dearomatize-on-load": false,
  "ignore-no-chiral-flag": false,
  "gross-formula-add-isotopes": true
}
```

Payload struct:
[convert-struct-missing-aromacity.zip](https://github.com/epam/Indigo/files/12930456/convert-struct-missing-aromacity.zip)

**Indigo/Bingo version**  
1.15.0-dev.1.0-g5ee0dbc7d-x86_64-linux-gnu-11.2.1

**Additional context**

**Comment by AliaksandrDziarkach** [comment]
According to [daylight's documentation](https://www.daylight.com/dayhtml_tutorials/languages/smiles/index.html#AROM) 

> Only the following atoms may be interpreted as aromatic: C,  N,  P,  O,  S,  As,  Se,  and  *  (wildcard atom) 

As for me that means that other atoms always aliphatic.

So, I'm not sure that this is a bag.
