### ISSUE TITLE
Extended SMILES: Atropisomer is displayed incorrectly

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1346]
**Steps to Reproduce**
1. Paste 
` CC1=C(N2C=CC=C2[C@H](C)Cl)C(C)CCC1 |(2.679,0.4142,;1.3509,1.181,;0.0229,0.4141,;0.0229,-1.1195,;1.2645,-2.0302,;0.7901,-3.4813,;-0.7446,-3.4813,;-1.219,-2.0302,;-2.679,-1.5609,;-3.0039,-0.0556,;-3.8202,-2.595,;-1.3054,1.1809,;-2.6335,0.4141,;-1.3054,2.7145,;0.0229,3.4813,;1.3509,2.7146,),wD:2.11,wU:8.10,&1:8| `

**Expected behavior**
The atropisomer should be displayed correctly, in accordance with the provided coordinates
![2023-10-18_18h03_34](https://github.com/epam/Indigo/assets/62464241/5cc665bb-cc19-4c0f-b627-a61b090cb8e0)

**Actual behavior**
Atropisomer is displayed incorrectly
![2023-10-18_17h21_36](https://github.com/epam/Indigo/assets/62464241/fe1f01d8-c93d-49ca-8b93-9279b7da2edb)

**Indigo/Bingo version**  
Version 1.14.0-rc.6

#186288932

**Comment by even1024** [comment]
Fixed on ketcher side with https://github.com/epam/ketcher/issues/3462
