### ISSUE TITLE
Wrong bond types 

### ISSUE THREAD

**Issue by AKZhuk** [epam/Indigo#1369]
**Steps to Reproduce**
Launch "Ketcher"
Paste structure  `[#6]-[#6]-1=[#6]-[#6](-[#7])=[#6](-[#16])-[#6]=[#6]-1-[#8]>Cl>[#6]-[#6]-1=[#6]-[#6](I)=[#6](-[#8])-[#6]=[#6]-1Br`

**Expected behaviour**
Bonds type should be "single"
<img width="981" alt="image" src="https://github.com/epam/Indigo/assets/16281184/f195a42f-cf78-49e6-90a8-f0eace12f373">

**Actual behaviour**
Wrong bonds type "Single/aromatic"
<img width="981" alt="Screenshot 2023-10-24 at 11 18 54" src="https://github.com/epam/Indigo/assets/16281184/1988cea0-80df-4adb-aa7c-5522db0d3b61">

Indigo/Bingo version
1.15.0-rc.1

**Additional context**

**Comment by AlexanderSavelyev** [comment]
not a bug
Various bond symbols are available to match connections between atoms. A missing bond symbol is interpreted as "single or aromatic".
