### ISSUE TITLE
writing SDF file, the coordinates are all zero

### ISSUE THREAD

**Issue by 1398491991** [epam/Indigo#139]
writing SDF file, the coordinates are all zero. reference: https://lifescience.opensource.epam.com/indigo/api/index.html#reading-sdf-rdf-cml-multiline-smiles-files-cdx-binary.
platform information: Linux bide 4.15.0-54-generic #58~16.04.1-Ubuntu
python information: Python 3.6.4 :: Anaconda, Inc.

**Comment by IuriiPuzanov** [comment]
Hello!
  Thank you vary much for using Indigo toolkit.
Could you please describe your steps more detailed? Is it possible that coordinates are actually zero?
What is the source of your structure?

Best Regards!
Iurii

**Comment by 1398491991** [comment]
example coding:

from indigo import indigo
_indigo = indigo.Indigo()
saver = _indigo.writeFile("structures.sdf")
mol = _indigo.loadMolecule("[C@H]2(CC1=CC=CC=C1)NC(OC2)=O")
saver.sdfAppend(mol)
saver.close()

the coordinates are all zero.

**Comment by IuriiPuzanov** [comment]
Hello!

  This is correct result, because input SMILES structure has no atoms coordinates. If you need some coordinates for your structure, you can use layout functionality from the Indigo toolkit to generate some coordinates before writing it into SDF (https://lifescience.opensource.epam.com/indigo/api/index.html#layout-2d-coordinates)

Best Regards!
Iurii

**Comment by 1398491991** [comment]
hello!
How to construct 3d coordinates.




------------------ 原始邮件 ------------------
发件人: "IuriiPuzanov"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午2:50
收件人: "epam/Indigo"<Indigo@noreply.github.com>;
抄送: " "<1398491991@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [epam/Indigo] writing SDF file, the coordinates are all zero(#139)




Hello!
 
This is correct result, because input SMILES structure has no atoms coordinates. If you need some coordinates for your structure, you can use layout functionality from the Indigo toolkit to generate some coordinates before writing it into SDF (https://lifescience.opensource.epam.com/indigo/api/index.html#layout-2d-coordinates)
 
Best Regards!
 Iurii

**Comment by IuriiPuzanov** [comment]
Hello!
   Unfortunately, at the moment Indigo has no 3D modelling. So if something reasonable is required you need to use some specialised software for building correct 3D molecule structure.

Best Regards!
Iurii

**Comment by 1398491991** [comment]
ok! thinks.




------------------ 原始邮件 ------------------
发件人: "IuriiPuzanov"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午4:30
收件人: "epam/Indigo"<Indigo@noreply.github.com>;
抄送: " "<1398491991@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [epam/Indigo] writing SDF file, the coordinates are all zero(#139)




Hello!
 Unfortunately, at the moment Indigo has no 3D modelling. So if something reasonable is required you need to use some specialised software for building correct 3D molecule structure.
 
Best Regards!
 Iurii

**Comment by 1398491991** [comment]
sorry, thanks.




------------------ 原始邮件 ------------------
发件人: "IuriiPuzanov"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 下午4:30
收件人: "epam/Indigo"<Indigo@noreply.github.com>;
抄送: " "<1398491991@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [epam/Indigo] writing SDF file, the coordinates are all zero(#139)




Hello!
 Unfortunately, at the moment Indigo has no 3D modelling. So if something reasonable is required you need to use some specialised software for building correct 3D molecule structure.
 
Best Regards!
 Iurii

**Comment by IuriiPuzanov** [comment]
You are welcome!
