### ISSUE TITLE
Templates with space in templateId lost after conversion from ket to molv3000

### ISSUE THREAD

**Issue by rrodionov91** [epam/Indigo#1414]
**Steps to Reproduce**
1. Convert ket file with template which contains space in templateId, f.e. "monomerTemplate-Met_O___(2S)-2-amino-4-methanesulfinylbutanoic acid" to molv3000 and backwards.

**Expected behavior**
Template still exist in ket file after conversion.

**Actual behavior**
Template lost.

**Attachments**
[Test-files.zip](https://github.com/epam/Indigo/files/13439065/Test-files.zip)

**Comment by even1024** [comment]
This task is done as a side task of https://github.com/epam/Indigo/issues/1412
