### ISSUE TITLE
bingo.getWeight seems not as exact as as other tool like chemdraw, rdkit

### ISSUE THREAD

**Issue by lloydz** [epam/Indigo#144]
bingo version: 1.8.0beta.r0-gfe6a41c linux64
sql:
```
SELECT
	bingo.getmass ( 'C1=CC=CC=C1' ),
	bingo.getweight ( 'C1=CC=CC=C1', '' ),
	bingo.getweight ( 'C1=CC=CC=C1', 'molecular-weight' );
```
sql result:
78.1118416786194, 78.1118416786194, 78.1118416786194

I calculated the same smiles with ChemDraw and Rdkit, and both got 78.1140

Is there any way to solve this problem?
Thanks.

**Comment by mkviatkovskii** [comment]
Dear @lloydz,

It seems like ChemDraw and RDKit calculate molecular weight quite inprecisely.  For example, here is the periodic table atom data from RDKit sources: https://github.com/rdkit/rdkit/blob/master/Code/GraphMol/atomic_data.cpp
It seems like they round atomic mass up to 3 decimal points, so atomic mass for hydrogen is 1.008 and atomic mass for carbon is 12.011. So `6 * (1.008 + 12.011) = 78.114.

In fact, atomic mass of hydrogene is closer to 1.00794, and for carbon to 12.0107, so more accurate value of molecular mass for C6H6 is `6 * (1.00794+12.0107) = 78.11184`. It is much closer to Bingo results than to ChemDraw or RDKit.

So Bingo results is more correct.
