### ISSUE TITLE
Macro: Can't open mol file with modified DNA

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1454]
**Steps to Reproduce**
1. Switch to Macro mode
2. Open attached file 
[DNA_mod_base_sugar_phosphate_example.zip](https://github.com/epam/Indigo/files/13726642/DNA_mod_base_sugar_phosphate_example.zip)

**Expected behavior**
File opens without errors

**Actual behavior**
Convert error

**Attachments**
![2023-12-20_14h19_40](https://github.com/epam/Indigo/assets/62464241/0108b5cc-1494-45e8-8390-c7670fa251f7)

**Indigo/Bingo version**  
Version 1.17.0-rc.3
**Also after switch to Micro mode and back to Macro application completely crashes and becomes inactive(see related Ketcher issue)
Related Ketcher issue:** https://github.com/epam/ketcher/issues/3747

**Comment by even1024** [comment]
Not an Indigo issue
