### ISSUE TITLE
ImplicitH set to zero casue error loading query molecule from ket

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#1460]
Trying to load query molecule from ket while ImplicitH set to 0 cuase error "Wrong value for implicitHCount: 0" which is wrong.

**Comment by AlexeyGirin** [comment]
Fixed.
[ZeroImplicitH.zip](https://github.com/epam/Indigo/files/14083788/ZeroImplicitH.zip)
