### ISSUE TITLE
Export as sequence string for RNA, DNA and PEPTIDEs

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1466]
**Background**
Export previously loaded monomer's sequence into RNA/DNA/PEPTIDE string.
The following symbols should be supported:

for peptides:
A - Alanine
C - Cysteine
D - Aspartic Acid
E - Glutamic Acid
F - Phenylalanine
G - Glycine
H - Histidine
I - Isoleucine
K - Lysine
L - Leucine
M - Methionine
N - Asparagine
P - Proline
Q - Glutamine
R - Arginine
S - Serine
T - Threonine
V - Valine
W - Tryptophan
Y - Tyrosine

for RNA nucleotides:
A - AMP (Adenosine monophosphate)
C - CMP (Cytidine monophosphate)
G - GMP (Guanosine monophosphate)
U - UMP (Uridine monophosphate)
T - rTMP (Ribothymidine monophosphate)

for DNA nucleotides:
A - dAMP (Deoxyadenosine monophosphate)
C - dCMP (Deoxycytidine monophosphate)
G - dGMP (Deoxyguanosine monophosphate)
U - dUMP (Deoxyuridine monophosphate)
T - TMP (Thymidine monophosphate)

**Solution**
1. Implement C++ class SequenceSaver in addition to the existing Indigo savers for molecular formats.
2. Implement following functions for C API, where type can be one of "RNA", "DNA" or "PEPTIDE":

```
int indigoSaveSequence(int molecule, int output, const char* type);
int indigoSaveSequenceToFile(int molecule, const char* filename, const char* type);
const char* indigoSequence(int molecule, const char* type);

```
3. Add language bindings for Python, Java, C#
python binding functions:

```
def sequence(self, sequence_type: string):
def saveSequence(self, output_file: string, sequence_type: string)

```
4. Add the following output content types to WASM  and Indigo service "convert" API:

chemical/x-rna-sequence, chemical/x-dna-sequence, chemical/x-peptide-sequence

**Comment by AlexeyGirin** [comment]
Verified.

**Versions:**
Windows 10
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0
