### ISSUE TITLE
Aromatizing custom query fails with error

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1474]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.2.0-g369c82f8c-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.15.0-rc.4 Build at 2023-10-25; 14:15:43
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1446
 
**Describe the bug**
Aromatizing custom query fails with error

https://github.com/epam/Indigo/assets/26869421/9b772a3f-6ee4-4a0d-be1b-ad2623edb378

**Steps to Reproduce**
1. Load molecule from file: [CustomQuery.zip](https://github.com/epam/Indigo/files/13822238/CustomQuery.zip) (unzip first)
2. Press Aromatize button (Alt+A)

**Actual behavior**
System throws an error:
Error Message
struct data not recognized as molecule, query, reaction or reaction query
![image](https://github.com/epam/Indigo/assets/26869421/69b029aa-2944-461d-abab-3c6204f6c21a)

**Expected behavior**
Works as intended

**Comment by AliaksandrDziarkach** [comment]
Custom query should contain valid smarts sequence.

**Comment by AliaksandrDziarkach** [comment]
Dublicate of #1510

**Comment by AlexeyGirin** [comment]
Should not throw exception
