### ISSUE TITLE
SMARTS components are not displayed for Single up and Single down bonds

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1480]
**Steps to Reproduce**
1. Open structures from file [Bonds.zip](https://github.com/epam/Indigo/files/13841499/Bonds.2.zip)
2. Save as Daylight SMARTS

**Expected behavior**
SMARTS components are displayed for Single up and Single down bonds

**Actual behavior**
SMARTS components are not displayed for Single up and Single down bonds

**Attachments**
![2024-01-05_13h22_13](https://github.com/epam/Indigo/assets/62464241/a316783e-1c98-4018-a8f5-912832ab515c)
![2024-01-05_13h22_25](https://github.com/epam/Indigo/assets/62464241/a28897bd-9a6b-447e-8206-d7281e5df88c)

**Indigo/Bingo version**  
Version 1.16.0-rc.3

**Comment by AliaksandrDziarkach** [comment]
Single up '/' and single down '\' bonds present.
I see chirality ( '@' and '@@' ) in expected string. Have no idea why it is expected. Molecule "C(-C)(-C)C" cannot contain chirality. 

btw. Looks like wrong chirality warning generated at check for this molecule:
![image](https://github.com/epam/Indigo/assets/18146690/23a7b4db-74d0-48b8-a754-d4f1696c38db)

**Comment by Zhirnoff** [comment]
We found that actual result obtained in tests is correct.
