### ISSUE TITLE
SMARTS components are not displayed for S-Groups ( round brackets )

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1481]
**Steps to Reproduce**
1. Open structures from file [s-group structure.zip](https://github.com/epam/Indigo/files/13857806/s-group.structure.zip)
2. Add Query component (left toolbar S-Group button -> Type = Query component)
3. Save as Daylight SMARTS

**Expected behavior**
SMARTS components are displayed for S-Groups

**Actual behavior**
SMARTS components are not displayed for S-Groups ( round brackets )

**Attachments**
![2024-01-05_13h24_24](https://github.com/epam/Indigo/assets/62464241/137dad8b-8987-4aec-9703-0086a30ae5d9)
![2024-01-05_13h25_17](https://github.com/epam/Indigo/assets/62464241/1c391930-6dbd-462e-ac94-4828a24038df)
![2024-01-05_13h30_42](https://github.com/epam/Indigo/assets/62464241/54bf32e8-1f42-417a-b924-7a763e19cc5f)

**Indigo/Bingo version**  
Version 1.16.0-rc.3

**Comment by AliaksandrDziarkach** [comment]
Open provided ket file - see no S-group.
Investigated ket file content - see no S-group definition.
Looks like this is ketcher(frontend) issue

**Comment by AliaksandrDziarkach** [comment]
As per previous comment close issue.

**Comment by Zhirnoff** [comment]
The bug was registered on Ketcher side https://github.com/epam/ketcher/issues/3931

**Comment by AlexeyGirin** [comment]
Moved to Ketcher
