### ISSUE TITLE
Unable to past empty reaction (arrow only) from clipboard to canvas

### ISSUE THREAD

**Issue by captain2b** [epam/Indigo#1483]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-rc.3.0-ge65b5cde3-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.18.0-rc.2 Build at 2024-01-17; 16:42:55
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10

**Steps to Reproduce**
1. Open that file [arrow.txt](https://github.com/epam/Indigo/files/13862754/arrow.txt) in notepad
2. Copy content to clipboard
3. Paste it from clipboard to Ketcher canvas

**Actual behavior**
Error appears: Convert error! struct data not recognized as molecule, query, reaction or reaction query
![EF6C9BC5-566B-4577-8579-EE923DE46E6A](https://github.com/epam/Indigo/assets/9428000/fa654804-33db-4c32-9e33-3da03212e935)

**Expected behavior**
Arrow appears
![image](https://github.com/epam/Indigo/assets/26869421/9ce0f1fe-456b-497e-b88b-9610083a3092)

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.18.0-rc.3 Build at 2024-01-31; 11:55:42
Indigo Toolkit Version 1.18.0-dev.5.0-g0ce216135-x86_64-linux-gnu-11.2.1
![image](https://github.com/epam/Indigo/assets/26869421/4f45dcc8-9219-4bb0-8677-deafa49f6edb)
