### ISSUE TITLE
Query molecule convert implicit/explicit hydrogens cause error

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#1484]
Try to convert from implicit to explicit hydrogen molecule with query features and got error:
"IndigoException: core: <query molecule> is not a molecule"

Same error when try to convert from explicit to implicit hydrogen.

**Comment by AlexeyGirin** [comment]
Fixed.
Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
