### ISSUE TITLE
Atom Query feature export: System replace "Ring membership" values with "Ring Bond Count" ones for value 0, corrupts layout - export to RXN V2000 file

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1501]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.2.0-g369c82f8c-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.17.0-rc.2 Build at 2024-01-03; 17:17:22
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1440

**Describe the bug**
System replace "Ring membership" values with "Ring Bond Count" ones for value 0

**Steps to Reproduce**
1. Open from file: [Ring membership2.zip](https://github.com/epam/Indigo/files/13884833/Ring.membership2.zip)
2. Save it to RXN V2000 file format
3. Clear canvas
4. Load from RXN V2000 file format

**Actual behavior**
System replace "Ring membership" values with "Ring Bond Count" ones for value 0, corrupts layout
![image](https://github.com/epam/Indigo/assets/26869421/489347c2-981a-4475-83c0-bfc7fdc963ef)

**Expected behavior**
Works as intended. (system doesn't show some values because of https://github.com/epam/ketcher/issues/3529 issue)
![image](https://github.com/epam/Indigo/assets/26869421/ac6d451c-f126-4549-9bf6-59f0e38f3f19)

**Comment by AliaksandrDziarkach** [comment]
Smiles loader treat "R0" as "x0" starting from initial commit from 2010-11-04.
Have no idea why.

**Comment by AliaksandrDziarkach** [comment]
Dublicate of 1500

**Comment by AlexeyGirin** [comment]
Have to be fixed

**Comment by AlexeyGirin** [comment]
Fixed.
Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
![image](https://github.com/epam/Indigo/assets/26869421/a345d3d9-32b5-40c9-a3c8-73f22f6ca90e)
