### ISSUE TITLE
Molfile MRV extension generated for "H count"

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#1504]
Set property "H count" and generate molfile:
```python
from indigo import Indigo
indigo=Indigo()
mol = indigo.loadQueryMolecule("[#6H2]")
print(mol.molfile())
```

Got next molfile:
```
  -INDIGO-01102414142D

  1  0  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  3  0  0  0  0  0  0  0  0
M  MRV SMA   1 [#6;H2]
M  END

```
H count saved in CTab - "3" and in "MRV SMA" extension which is bug - it should be saved only in CTab

**Comment by AlexeyGirin** [comment]
Fixed.
Version 1.18.0-rc.5.0-gb21ab5ad5-x86_64-linux-gnu-11.2.1
![image](https://github.com/epam/Indigo/assets/26869421/431f5fd1-acf0-45aa-bf46-3a02a674f785)
