### ISSUE TITLE
Atom Query feature export: System lost all "Chirality" values - export to mol file

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1506]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.2.0-g369c82f8c-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.17.0-rc.2 Build at 2024-01-03; 17:17:22
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1440

**Describe the bug**
System lost all "Chirality" values

**Steps to Reproduce**
1. Open from file: [Chirality.zip](https://github.com/epam/Indigo/files/13887013/Chirality.zip)
2. Save it to mol file format
3. Clear canvas
4. Load from mol file format

**Actual behavior**
System lost all "Chirality" values
![image](https://github.com/epam/Indigo/assets/26869421/7c8ba481-67a8-4230-b25c-2ba42959dcea)

**Expected behavior**
Works as intended
![image](https://github.com/epam/Indigo/assets/26869421/3c775ed5-addc-45d0-98a3-8def3e6180c6)

**Comment by AliaksandrDziarkach** [comment]
Looks like no chirality support in MOL files

**Comment by AlexeyGirin** [comment]
Not a bug - mol format doesn't support it
