### ISSUE TITLE
SMARTS components are not displayed for Single/aromatic bonds

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1515]
**Steps to Reproduce**
1. Open structures from file 
2. Save as Daylight SMARTS [structure.zip](https://github.com/epam/Indigo/files/13905702/structure.zip)

**Expected behavior**
SMARTS components are displayed for Single/aromatic bonds

**Actual behavior**
SMARTS components are not displayed for Single/aromatic bonds

**Attachments**

![2024-01-11_19h09_40](https://github.com/epam/Indigo/assets/62464241/5d37c87a-580a-46cf-a6d1-0626fac9e4ab)

**Indigo/Bingo version**  
Version 1.18.0-dev.4

**Comment by AliaksandrDziarkach** [comment]
It is not a bug. It is intentional behaviour.
According to SMARTS specification:
> A missing bond symbol is interpreted as "single or aromatic".

**Comment by Zhirnoff** [comment]
Confirm.
