### ISSUE TITLE
Non-mapped product atoms

### ISSUE THREAD

**Issue by chaoyan1037** [epam/Indigo#152]
`[NH2:1][CH:6]([CH2:5][CH2:4][S-])[C:7]([OH:2])=[O:3]>>[NH2:1][CH:6]([CH2:5][CH2:4][S])[C:7]([OH:2])=[O:3]`

The 'S' atom is without a mapping number. Does anyone have a clue how to fix it?

**Comment by IuriiPuzanov** [comment]
Hello,
   Thank you very much for using Indigo toolkit!
Could you please describe more detailed the wrong situation? Which API was used, what is the source of the input structure?
Best Regards!
Iurii

**Comment by autodataming** [comment]
try add the parameters **ignore_charges** in automap

```py
from indigo import *
indigo = Indigo()
def  addmapbyINDIGO(rxnsmi):
    smi = rxnsmi
    rxn = indigo.loadReaction(smi)
    rxn.automap('discard ignore_charges ignore_isotopes ignore_valence ignore_radicals')
#     rxn.automap('discard')

    rxnsmi_map_indigo = rxn.smiles() 
    return rxnsmi_map_indigo
rxnsmi='[NH2:1][CH:6]([CH2:5][CH2:4][S-])[C:7]([OH:2])=[O:3]>>[NH2:1][CH:6]([CH2:5][CH2:4][S])[C:7]([OH:2])=[O:3]'
tem=addmapbyINDIGO(rxnsmi).split()[0]
rxn=AllChem.ReactionFromSmarts(tem,useSmiles=True)
display(rxn)
print(tem)
```

**Comment by autodataming** [comment]
#160
