### ISSUE TITLE
Aromatize/Dearomatize doesn't work if user manually added any atom with custom query feature

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1527]
**IMPORTANT NOTE:** Bug described below couldn't be reproduced if you load the same molecule from file/clipboard

**Steps to Reproduce**
1. Put Carbon on the canvas
2. Open its properties and add Custom query: `[$([#1]),$([#17])]`
![image](https://github.com/epam/Indigo/assets/26869421/ec5a5a55-28cf-4d6e-a8a7-22cea1a1decb)
3. Press Aromatize button (Alt+A) **or** Dearomatize button (Ctrl+Alt+A)

https://github.com/epam/Indigo/assets/26869421/2bdf589d-c28e-47f1-ba7a-bf6274ce14e3

**Actual behavior**
System throws exception:
![image](https://github.com/epam/Indigo/assets/26869421/ea94a84b-5621-4bb2-b248-05f0a6b714a4)

**Expected behavior**
No exception happens

Issue found while testing https://github.com/epam/Indigo/issues/1446

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome Version 120.0.6099.130 (Official Build) (64-bit)

**Ketcher version** [e.g. v2.4.2]. 
Ketcher Version 2.18.0+dev.1 Build at 2024-01-11; 13:21:50
Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0

**Comment by AliaksandrDziarkach** [comment]
Dublicate of #1567

**Comment by AlexeyGirin** [comment]
S
