### ISSUE TITLE
ionize call causes segfault for deuterated molecule (if pKa-model-level >= 1)

### ISSUE THREAD

**Issue by flc** [epam/Indigo#153]
The segmentation fault can be reproduced with the following code:

```
from indigo import Indigo
smiles = '[2H]C1=C([2H])C([2H])=C(C2N=C(N3CCCCCC3)SC=2C(=O)C2=CC=CC=C2)C([2H])=C1[2H]'
ind = Indigo()
ind.setOption("pKa-model", "advanced")
ind.setOption("pKa-model-level", 1)
imol = ind.loadMolecule(smiles)
imol.ionize(7.4, 0)
```
-> Segmentation fault

It's OK if the `pKa-model-level` option is 0 (the default).
For a similar structure it is OK even with higher `pKa-model-level`:
`N1(CC2=C([2H])C([2H])=C([2H])C([2H])=C2[2H])CCN(C2C=CC=C(C)C=2)CC1`

Indigo version:
```
In [3]: ind.version()
Out[3]: '1.4.0-beta.r10-gbfcd6505 linux64'
```

Thanks in advance if you look into it!

**Comment by IuriiPuzanov** [comment]
Hi Zoltan,
    Thank you very much for using Indigo toolkit and discovered issue. We'll try to investigate this issue and resolve it.
    By the way I have a question about using pka-model-level: what is the reason of using level 1? Are the results from level 0 have not enough accuracy?
Best Regards!
Iurii

**Comment by flc** [comment]
Hi Iurii,

A long time ago we compared it with some other tools, examined some options and we decided to go with these settings for best accuracy. I don't remember the exact details unfortunately.

Thanks

**Comment by flc** [comment]
Also, this page doesn't say too much about what these options actually do:
https://lifescience.opensource.epam.com/indigo/options/pka.html
If it is better documented somewhere else, then please share it.

This code also uses a higher "pKa-model-level" value, we actually use 5 as well.
https://lifescience.opensource.epam.com/indigo/api/index.html#ionize-of-molecule

Bests

**Comment by mkviatkovskii** [comment]
Fixed in https://github.com/epam/Indigo/pull/332
