### ISSUE TITLE
Dearomatize doesn't work for aromatized molecules

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1532]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.1 Build at 2024-01-11; 13:21:50
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1446
 
**Describe the bug**
Dearomatize doesn't work for aromatized molecules

**Steps to Reproduce**
1. Load from file: [CantDearomatize.zip](https://github.com/epam/Indigo/files/13929462/CantDearomatize.zip) (unzip first)
2. Press Dearomatize button (Ctrl+Alt+A)

**Actual behavior**
Nothing happens
![image](https://github.com/epam/Indigo/assets/26869421/dcb0f63f-7151-48ab-b7ef-651624ef1f95)

**Expected behavior**
Dearomatization works (discuss with @AlexanderSavelyev how)

**Comment by AliaksandrDziarkach** [comment]
It is not a query-specific issue

**Comment by AlexeyGirin** [comment]
No a bug
