### ISSUE TITLE
Add/Remove explicit hydrogens feature doesn't work for Aromatic Either bond ([#6]:[#6])

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1544]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.1 Build at 2024-01-11; 13:21:50
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436
 
**Describe the bug**
Add/Remove explicit hydrogens feature doesn't work for Aromatic Either bond (`[#6]:[#6]`)

**Steps to Reproduce**
1. Load from file: [AromaticEitherBond.zip](https://github.com/epam/Indigo/files/13933043/AromaticEitherBond.zip) (unzip first)
2. Press Add/Remove explicit hydrogens button
![image](https://github.com/epam/Indigo/assets/26869421/5b9ba4f5-fc5d-422a-983e-0598fc82c4fc)

**Actual behavior**
System throws exception:
IndigoException: element: can not calculate implicit hydrogens on aromatic C, charge 0, degree 1, 0 radical electrons
[uat.test.lifescience.opensource.epam.com-1705264293466.log](https://github.com/epam/Indigo/files/13933046/uat.test.lifescience.opensource.epam.com-1705264293466.log)
![image](https://github.com/epam/Indigo/assets/26869421/a898a9f2-5baa-4651-91f7-72ef0307ab3b)
![image](https://github.com/epam/Indigo/assets/26869421/59a58556-490b-4ea2-a8d4-079cb8c7bc78)

**Expected behavior**
No exception

**Comment by AlexeyGirin** [comment]
Should be fixed.
Decided to fix in Query Features - Phase II

**Comment by AlexeyGirin** [comment]
Not fully fixed.
It doesn't throw exception but it doesn't add hydrogens as well (is should!)

Actual behavior:
![image](https://github.com/epam/Indigo/assets/26869421/3ff17bdb-83fb-4626-b1f8-4acb0d12acf4)


Expected behavior:
![image](https://github.com/epam/Indigo/assets/26869421/85863aa4-03ef-42ea-8fce-a4b9ea413024)

**Comment by AlexeyGirin** [comment]
MOved to RC7 as per @vanoprenko decision

**Comment by AliaksandrDziarkach** [comment]
> **Expected behavior**
No exception

Exception issue fixed.
Please fill separate bugs for other issues.

**Comment by AlexeyGirin** [comment]
MOved to https://github.com/epam/Indigo/issues/1667
