### ISSUE TITLE
what is meaning of the second field(|^1:3|) in the reaction map?

### ISSUE THREAD

**Issue by autodataming** [epam/Indigo#155]
I try to add map id for the reaction, code as the following,
```py
from indigo import *
indigo = Indigo()
def  addmapbyINDIGO(rxnsmi):
    smi = rxnsmi
    rxn = indigo.loadReaction(smi)
    rxn.automap('discard ignore_charges ignore_isotopes ignore_valence ignore_radicals')
#     rxn.automap('discard')

    rxnsmi_map_indigo = rxn.smiles() 
    return rxnsmi_map_indigo
rxnsmi='CC1(C)CCCC(C)(C)N1[O]>>CC(=O)c1cccnc1Cl'
output=addmapbyINDIGO(rxnsmi)
```

output:
```
output: C[C:2]1([N:10]([O])[C:7]([CH3:9])(C)[CH2:6][CH2:5][CH2:4]1)C>>[CH3:9][C:7]([c:4]1[c:2](Cl)[n:10][cH:7][cH:6][cH:5]1)=O |^1:3|

```
what is meaning of the second field(|^1:3|) in the reaction map?

**Comment by dan2097** [comment]
The second field uses the format of ChemAxon Extended SMILES. In this case ^1:3 explicitly specifies that there is a monovalent radical center at atom index 3 (i.e. the Oxygen which is the 4th atom in the SMILES as the index is zero-based)

https://docs.chemaxon.com/display/docs/ChemAxon_Extended_SMILES_and_SMARTS_-_CXSMILES_and_CXSMARTS.html#src-1806633_ChemAxonExtendedSMILESandSMARTS-CXSMILESandCXSMARTS-Radicalnumbers

Indigo also makes use of the "Fragment grouping" functionality in Extended SMILES e.g. a hydrochloride salt of a compound (1 reactant) can be distinguished from a compound + hydrochloric acid (2 reactants).

**Comment by autodataming** [comment]
> Indigo also makes use of the "Fragment grouping" functionality in Extended SMILES e.g. a hydrochloride salt of a compound (1 reactant) can be distinguished from a compound + hydrochloric acid (2 reactants).

Thank you very much!   I try the RDT tools and indigo TK to add atom map, these tools did well for the clean reaction. But for the raw reaction in the USPTO,  they didn't do well. Could you recommend some other tools for me.

**Comment by dan2097** [comment]
I am aware of quite a few other tools that have decent atom-atom mapping algorithms, but all the ones that come to mind are commercial e.g. InfoChem's ICMAP, ChemAxon's Marvin toolkit (might be free for academics), Pipeline Pilot

I'll just add that the I got better results from Indigo's atom mapping by calling
```
for (IndigoObject m: reaction.iterateMolecules()){
	for (IndigoObject b: m.iterateBonds()){
		reaction.setReactingCenter(b, Indigo.RC_UNCHANGED | Indigo.RC_ORDER_CHANGED | Indigo.RC_MADE_OR_BROKEN);
	}
}
```
prior to calling 
`reaction.automap`
I think without doing this the Indigo atom mapping won't map a double bond in a reactant to a single bond in the product or vice versa.

**Comment by autodataming** [comment]
Thank you.

```py
for m in rxn.iterateMolecules():
    for b in m.iterateBonds():
        rxn.setReactingCenter(b, Indigo.RC_UNCHANGED | Indigo.RC_ORDER_CHANGED | Indigo.RC_MADE_OR_BROKEN)
```

**Comment by autodataming** [comment]
> 
> 
> The second field uses the format of ChemAxon Extended SMILES. In this case ^1:3 explicitly specifies that there is a monovalent radical center at atom index 3 (i.e. the Oxygen which is the 4th atom in the SMILES as the index is zero-based)
> 
> [docs.chemaxon.com/display/docs/ChemAxon_Extended_SMILES_and_SMARTS_-_CXSMILES_and_CXSMARTS.html#src-1806633_ChemAxonExtendedSMILESandSMARTS-CXSMILESandCXSMARTS-Radicalnumbers](https://docs.chemaxon.com/display/docs/ChemAxon_Extended_SMILES_and_SMARTS_-_CXSMILES_and_CXSMARTS.html#src-1806633_ChemAxonExtendedSMILESandSMARTS-CXSMILESandCXSMARTS-Radicalnumbers)
> 
> Indigo also makes use of the "Fragment grouping" functionality in Extended SMILES e.g. a hydrochloride salt of a compound (1 reactant) can be distinguished from a compound + hydrochloric acid (2 reactants).

```
Fragment grouping

Fragment level grouping of reactant, agent and product fragments Grouped fragment indexes are written after "f:" in the following format:

    Connected groups are separated by ",".

    A connected group is a "." separated list of fragment indexes.

```

I was confused by |f:3.4| in the following reaction .
```

[N+:1]([C:4]1[CH:13]=[CH:12][CH:11]=[C:10]2[C:5]=1[CH:6]=[CH:7][N:8]=[CH:9]2)([O-:3])=[O:2].[BrH:14]>C(O)C>[BrH:14].[N+:1]([C:4]1[CH:13]=[CH:12][CH:11]=[C:10]2[C:5]=1[CH:6]=[CH:7][N:8]=[CH:9]2)([O-:3])=[O:2] |f:3.4| US03930837              1976

```
the first group is  [C:4]1[CH:13]=[CH:12][CH:11]=[C:10]2[C:5]=1[CH:6]=[CH:7][N:8]=[CH:9]2 ?
the second group is [O-:3] ?
the third group is [C:4]1[CH:13]=[CH:12][CH:11]=[C:10]2[C:5]=1[CH:6]=[CH:7][N:8]=[CH:9]2 ?
the forth group is [O-:3] ?
what's meaning of f:3.4?

**Comment by dan2097** [comment]
The groups are numbered from 0, hence:
0:[N+:1]([C:4]1[CH:13]=[CH:12][CH:11]=[C:10]2[C:5]=1[CH:6]=[CH:7][N:8]=[CH:9]2)([O-:3])=[O:2]
1:[BrH:14]
2:C(O)C
3:[BrH:14]
4:[N+:1]([C:4]1[CH:13]=[CH:12][CH:11]=[C:10]2[C:5]=1[CH:6]=[CH:7][N:8]=[CH:9]2)([O-:3])=[O:2]

i.e. the product is a single compound

**Comment by autodataming** [comment]
> BrH:14]

Thank you, I got it. The group is seprated by the dot in the rxnsmi. 

product is composed of group3 and group4.
