### ISSUE TITLE
Add/Remove explicit hydrogens doesn't work if Charge values set for atom

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1552]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.1 Build at 2024-01-11; 13:21:50
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436
 
**Describe the bug**
Add/Remove explicit hydrogens doesn't work if Charge values set for atom

**Steps to Reproduce**
1. Load from file: [Can't add hydrogens if charge value set.zip](https://github.com/epam/Indigo/files/13942987/Can.t.add.hydrogens.if.charge.value.set.zip) (unzip first)
2. Press Add/Remove explicit hydrogens button
![image](https://github.com/epam/Indigo/assets/26869421/7a3e4259-fe9a-4834-aa5b-96be3f54d521)

**Actual behavior**
System throws exception: IndigoException: element: bad valence on He having 0 drawn bonds, charge 2, and 0 radical electrons
[uat.test.lifescience.opensource.epam.com-1705352322061.log](https://github.com/epam/Indigo/files/13942994/uat.test.lifescience.opensource.epam.com-1705352322061.log)
![image](https://github.com/epam/Indigo/assets/26869421/527a1c64-c112-42a8-ae85-0e34abfc86d1)
![image](https://github.com/epam/Indigo/assets/26869421/be0d4fe6-4afd-4a3c-803d-aa732a90b17f)

**Expected behavior**
No exception

**Comment by AliaksandrDziarkach** [comment]
It is not a query-specific issue

**Comment by AlexeyGirin** [comment]
Should not throw exception.
Decided to fix in Query Features - Phase II

**Comment by AlexeyGirin** [comment]
Fixed.
Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
