### ISSUE TITLE
Add/Remove explicit hydrogens wanishes "Chirality" value

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1564]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.1 Build at 2024-01-11; 13:21:50
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436
 
**Describe the bug**
Add/Remove explicit hydrogens wanishes "Chirality" value

**Steps to Reproduce**
1. Load from file: [Add-Remove explicit hydrogens wanishes 'Chirality' value.zip](https://github.com/epam/Indigo/files/13950056/Add-Remove.explicit.hydrogens.wanishes.Chirality.value.zip) (unzip first)
2. Press Add/Remove explicit hydrogens button
![image](https://github.com/epam/Indigo/assets/26869421/dff6a844-be23-47fd-8f10-e35576ee32fb)

**Actual behavior**
"Chirality" value is absent
![image](https://github.com/epam/Indigo/assets/26869421/e7ac7b3a-20b4-4484-b2be-27212b9bde44)

**Expected behavior**
"Chirality" value remains in place
![image](https://github.com/epam/Indigo/assets/26869421/7c2846ad-5f10-437d-82b0-ca99479c4446)

**Comment by AliaksandrDziarkach** [comment]
Same behavior for "Aromatize"/"Dearomatize" and "Clean Up"

**Comment by AlexeyGirin** [comment]
Fixed.
Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
![image](https://github.com/epam/Indigo/assets/26869421/65318cd7-b39d-4825-b303-59efdc75ef1e)
