### ISSUE TITLE
Basic hydrogen layout problem - angles of hydrogens are not perfect

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1575]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.2 Build at 2024-01-12; 11:50:06
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Describe the bug**
Basic hydrogen layout problem - angles of hydrogens are not perfect

**Steps to Reproduce**
1. Make simple molecular on the canvas
![image](https://github.com/epam/Indigo/assets/26869421/b3a53670-b397-4c9e-982c-57cbbe73f633)
2. Press Add/Remove explicit hydrogens button

**Actual behavior**
![image](https://github.com/epam/Indigo/assets/26869421/5dd5f4f7-c6c2-4fa2-9cf5-b69f8c49bc13)

**Expected behavior**
![image](https://github.com/epam/Indigo/assets/26869421/fa8de55b-893f-43f9-a551-ab662feb95aa)

**Comment by AliaksandrDziarkach** [comment]
It is not a query-specific issue

**Comment by Zhirnoff** [comment]
Tested. Fixed.
![2024-03-18_17h52_31](https://github.com/epam/Indigo/assets/62464241/6c926eb2-b41f-4bb9-9046-2ab8097938ab)

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/4c9b2404-a49a-4430-a7bf-ff722701fcb5)
 - Indigo Toolkit Version 1.19.0-rc.1.0-g8cd9f1e27-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc1 Build at 2024-03-15; 15:42:19
 - Chrome Version 122.0.6261.129 (Official Build) (64-bit)
 - Win10
