### ISSUE TITLE
Bad molecule layout after adding hydrogens (Chlorophyll A)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1576]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.2 Build at 2024-01-12; 11:50:06
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Describe the bug**
Bad molecule layout after adding hydrogens

**Steps to Reproduce**
1. Put Chlorophyll A molecule on the canvas (from Structure Library)
![image](https://github.com/epam/Indigo/assets/26869421/2e768466-25c9-4070-a3b6-dd8ebbf9bb8c)
2. Press Add/Remove explicit hydrogens button
3. Press Add/Remove explicit hydrogens button one more time

**Actual behavior**
![image](https://github.com/epam/Indigo/assets/26869421/a3b3619f-0ccd-4651-b14b-46b14060f986)

**Expected behavior**
![image](https://github.com/epam/Indigo/assets/26869421/a3adfe4a-8a84-494b-8659-e4af4c85ae23)

**Comment by AliaksandrDziarkach** [comment]
It is not a query-specific issue

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.18.0-rc.8 Build at 2024-02-22; 17:29:02
Indigo Toolkit Version 1.18.0-rc.8.0-g85a393c7c-wasm32-wasm-clang-12.0.0

![image](https://github.com/epam/Indigo/assets/26869421/26e07607-e351-4e52-bef8-65e3338e7a64)
