### ISSUE TITLE
Layout problem for 2 molecules (max simplified case)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1578]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.4+1452.0-gaf1efce67-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.18.0+dev.2 Build at 2024-01-12; 11:50:06
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Describe the bug**
Layout problem for 2 molecules (max simplified case) 
It is may be a duplicate for https://github.com/epam/Indigo/issues/1576 but example is less complicated

![image](https://github.com/epam/Indigo/assets/26869421/64f3f0a0-3f95-4642-86cf-8e9ee03109f6)

**Steps to Reproduce**
1. Load from file: [Layout problem for 2 molecules (max simplified case).zip](https://github.com/epam/Indigo/files/13964118/Layout.problem.for.2.molecules.max.simplified.case.zip) (unzip first)
2. Press Add/Remove explicit hydrogens button

**Actual behavior**
![image](https://github.com/epam/Indigo/assets/26869421/c86074b2-8780-4822-9193-ae7fe28974ac)

**Expected behavior**
![image](https://github.com/epam/Indigo/assets/26869421/69cb79c5-f59a-48f4-b3d9-b922d5645b9e)

ADDITINAL CASE:
Load this SMILES: `CC[C@@H]1[C@@]([C@@H]([C@H](C(=O)[C@@H](C[C@@]([C@@H]([C@H]([C@@H]([C@H](C(=O)O1)C)O[C@H]2C[C@@]([C@H]([C@@H](O2)C)O)(C)OC)C)O[C@H]3[C@@H]([C@H](C[C@H](O3)C)N(C)C)O)(C)O)C)C)O)(C)O`
![image](https://github.com/epam/Indigo/assets/26869421/002e81b6-430a-4c09-ab2a-0a26c93d302b)

Click the "Add/Remove explicit hydrogens" button

Actual behavior:
![image](https://github.com/epam/Indigo/assets/26869421/70d57b05-6592-4ac0-81e6-9c96f5593ca2)

Expected:
![image](https://github.com/epam/Indigo/assets/26869421/9ac762f1-4a1b-473f-882c-74804c702e73)

**Comment by AlexeyGirin** [comment]
Check on RC - if not fixed - 1.19

**Comment by AlexeyGirin** [comment]
Same at https://rc.test.lifescience.opensource.epam.com/KetcherDemo/index.html
Indigo Toolkit Version 1.18.0-rc.4.0-g84a1f903f-x86_64-linux-gnu-11.2.1

![image](https://github.com/epam/Indigo/assets/26869421/2fc12651-1303-457e-8967-8978ce60550e)

**Comment by AlexeyGirin** [comment]
Priority changed to High since cx found similar problem

**Comment by AliaksandrDziarkach** [comment]
Dublicate of #1576
