### ISSUE TITLE
Unable to add hydrogens for aromatic bonds outside the ring - system throws exception

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1579]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-rc.3.0-ge65b5cde3-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.18.0-rc.2 Build at 2024-01-17; 16:42:55
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Describe the bug**
Unable to add hydrogens for aromatic bonds outside the ring - system throws exception

**Steps to Reproduce**
1. Load from file: [Unable to add hydrogens for aromatic bonds outside the ring - system throws exception.zip](https://github.com/epam/Indigo/files/13968715/Unable.to.add.hydrogens.for.aromatic.bonds.outside.the.ring.-.system.throws.exception.zip) (unzip first)
2. Press Add/Remove explicit hydrogens button
![image](https://github.com/epam/Indigo/assets/26869421/5d4f119f-b7dc-4b0a-aff8-3ad7444097dd)

**Actual behavior**
System throws exception: IndigoException: element: can not calculate implicit hydrogens on aromatic C, charge 0, degree 1, 0 radical electrons
![image](https://github.com/epam/Indigo/assets/26869421/b7258bba-bb7d-4ee6-b2fd-b2c0f2131d0c)
![image](https://github.com/epam/Indigo/assets/26869421/161f2b15-cbc4-4ec4-b382-f04839b35c9d)
[uat.test.lifescience.opensource.epam.com-1705525259112.log](https://github.com/epam/Indigo/files/13968728/uat.test.lifescience.opensource.epam.com-1705525259112.log)

**Expected behavior**
![image](https://github.com/epam/Indigo/assets/26869421/1aeabf66-9211-40ee-a41f-ffc4822eaf4a)

**Comment by AliaksandrDziarkach** [comment]
This is not query related issue.
If you add 'aromatic' for any atom to use query molecule mode you can see that it will work

**Comment by AliaksandrDziarkach** [comment]
I have no idea why "aromatic" bond placed in query bonds in ketcher.
This is just a normal bond like single/double/triple.
For example: if you add cyclohexane and change all bonds to aromatic - after change last bond to aromatic it will be re-drawn as aromatic benzene.

**Comment by AlexeyGirin** [comment]
Should not throw exceptopn

**Comment by AlexeyGirin** [comment]
No exception now - good, but works wrong (Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0)
Actual behavior:
![image](https://github.com/epam/Indigo/assets/26869421/3401fd60-41f2-4e7a-a1b2-f7270395f768)

Expected behavior:
![image](https://github.com/epam/Indigo/assets/26869421/1aeabf66-9211-40ee-a41f-ffc4822eaf4a)

**Comment by AlexeyGirin** [comment]
MOved to RC7 as per @vanoprenko decision

**Comment by AlexeyGirin** [comment]
MOved to 1.19 as per @vanoprenko decision

**Comment by AlexeyGirin** [comment]
MOved to https://github.com/epam/Indigo/issues/1915
