### ISSUE TITLE
Adding hydrogens works wrong for Single Down and Single Up types of bond

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1581]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-rc.3.0-ge65b5cde3-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.18.0-rc.2 Build at 2024-01-17; 16:42:55
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Describe the bug**
Adding hydrogens works wrong for Single Down and Single Up types of bond

**Steps to Reproduce**
1. Load from file: [Adding hydrogens works wrong for Single Down and Single Up types of bond.zip](https://github.com/epam/Indigo/files/13968845/Adding.hydrogens.works.wrong.for.Single.Down.and.Single.Up.types.of.bond.zip) (unzip first)
2. Press Add/Remove explicit hydrogens button
![image](https://github.com/epam/Indigo/assets/26869421/ceafeb13-08c9-436e-9b45-33b69f878bae)

**Actual behavior**
![image](https://github.com/epam/Indigo/assets/26869421/d9395912-34df-4250-972b-7031d804a42d)

**Expected behavior**
![image](https://github.com/epam/Indigo/assets/26869421/8feab8cb-f02b-4bce-9839-fbe66264246f)

NOTE that system should add Single Down or Single Up to Single Up or Single Down accordingly (talk with @AlexanderSavelyev for explanation)
IMPORTANT NOTE:
Combinations that doesn't have minimum 5 atoms connected from one side - are INCORRECT and should be processed
Example of incorrect molecules:
![image](https://github.com/epam/Indigo/assets/26869421/f9c007d1-a88f-44a2-8637-7adce2765925)
Please talk with @AlexanderSavelyev for explanation

**Comment by AliaksandrDziarkach** [comment]
It son a query-specific issue

**Comment by AlexeyGirin** [comment]
Not a bug
