### ISSUE TITLE
Import of standard IDT monomers

### ISSUE THREAD

**Issue by olganaz** [epam/Indigo#1588]
**Background**
In IDT notation modified sequences represented as a plain strings with a combination of standard and modified monomers. 
Standard monomer  `[s]<Base>[*]` is nucleotides with the same configurations as supported in Ketcher.  
Modified monomer `/<pos><Identifier>/[*]` could be nucleotide or CHEM or their combination. 
This task  covers only import of standard IDT monomers.

**Requirements**

 The system should interpret standard monomers  `[s]<Base>[*]`  as **nucleotides** with a structure (defined by the name components):

`Base` - standard unmodified nucleotide base symbol (see table below)
 `s` - optional symbol of the sugar that makes the nucleotide (see table below). If not specified, standard sugar deoxy-ribose (dR) is implied. 
`*` - optional indicator of modified phosphate. If specified, indicates that Phosphorothioate (sP) is included into nucleotide, otherwise standard phosphate (P) is implied.
The last monomer in the chain is considered to be nucleoside (nucleotide, which lacks phosphate), so` *` couldn't be the last symbol in the sequence.

<img width="350" src="https://github.com/epam/Indigo/assets/143799055/c831cd09-d1a8-4419-adae-6989070a0edb">
<img width="350" src="https://github.com/epam/Indigo/assets/143799055/ad3b18c0-cbbc-478f-9fab-9d4988f826f8">

**Solution**

**Alternatives**
For base symbols R , Y, M, K, S, W, H, B, V, D, N and Modified IDT monomers Error message should be displayed. 
Modified IDT monomers `/<pos><Identifier>/[*]`  will be supported as described in  [#1899](https://github.com/epam/Indigo/issues/1899)

**Additional context**
Examples: 
`ACG`
<img width="300" src="https://github.com/epam/Indigo/assets/143799055/dfc20248-05b9-4a73-8f33-317bf6536b73">

`rArC*rG`
<img width="300" src="https://github.com/epam/Indigo/assets/143799055/db9bb50c-252f-4920-b194-216200667dd0">

`A*C*G`
<img width="300" src="https://github.com/epam/Indigo/assets/143799055/daebecab-5a14-40d7-8b41-62946d2f2362">

`+C*+G*A`
<img width="300" src="https://github.com/epam/Indigo/assets/143799055/b5d5f225-8beb-42f0-9f17-fc9cddc10389">

`mA*mGC`
<img width="300" src="https://github.com/epam/Indigo/assets/143799055/b25dbebe-32ea-4afe-a706-edb7a9beebae">

**Comment by AlexeyGirin** [comment]
Will be tested in the context of https://github.com/epam/ketcher/issues/4495
