### ISSUE TITLE
Apply hydrogens folding/unfolding with respect to selected atoms 

### ISSUE THREAD

**Issue by vanoprenko** [epam/Indigo#1589]
Hydrogens folding/unfolding implemented in scope of https://github.com/epam/Indigo/issues/1436 is currently applied to all atoms in the destination structure. Enhance this functionality, so that folding/unfolding is applied to selected atoms only. If no atoms are selected, the whole structure should be affected.
KET format should be enhanced in scope of this task, so that selection flag is specified for each selectable entity (atom, bond, static drawing, etc).

**Comment by AliaksandrDziarkach** [comment]
Backmerge https://github.com/epam/Indigo/pull/1655
