### ISSUE TITLE
System lost Any Atom label while saving to RXN, SDF and mol formats (query feature case)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1591]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-dev.2.0-g369c82f8c-x86_64-linux-gnu-11.4.0
 - Ketcher Version 2.17.0-rc.2 Build at 2024-01-03; 17:17:22
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1440

**Describe the bug**
System lost Any Atom label while saving to RXN, SDF and mol formats (query feature case)

**Steps to Reproduce**
1. Open from file: [Custom.zip](https://github.com/epam/Indigo/files/13986340/Custom.zip) (unzip first)
2. Save it to mol file format (or RXN or SDF)
3. Clear canvas
4. Load from mol file format back
![image](https://github.com/epam/Indigo/assets/26869421/6a452fb1-b4c7-4389-acf3-fc375a6beddd)

**Actual behavior**
System lost all Any Atom labels
![image](https://github.com/epam/Indigo/assets/26869421/20227359-863a-4ca0-8f9e-2bb4147ecc10)

**Expected behavior**
Works as intended
![image](https://github.com/epam/Indigo/assets/26869421/86ebab2f-b55c-4c09-a103-17112e9e097f)

**Comment by AlexeyGirin** [comment]
Have to be fixed

**Comment by AliaksandrDziarkach** [comment]
Will be fix by https://github.com/epam/Indigo/pull/1596

**Comment by AlexeyGirin** [comment]
Well. Atom labels are remain in place - this is good.
But at the same time all Custom Query features are lost.
[Exports to MOL, SDF, RXN.zip](https://github.com/epam/Indigo/files/14084138/Exports.to.MOL.SDF.RXN.zip)

**Comment by AlexeyGirin** [comment]
MOved to RC7 as per @vanoprenko decision
