### ISSUE TITLE
Macro: V3000 Export: Complex structure (modified RNA-peptide-disulfide bridge) saved to mol V3000 is displayed improperly in other sketcher (part of the structure left)

### ISSUE THREAD

**Issue by olganaz** [epam/Indigo#1592]
**Environment details  (please complete the following information):**
 - Indigo Version 1.18.0-rc.3.0-ge65b5cde3-wasm32-wasm-clang-12.0.0
 - Ketcher [Version 2.18.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
 - [Optional] Chrome version 120.0.6099.130 (Official Build) (64-bit)
 - [Optional] OS version Windows 10 Pro

**Describe the bug**
The structure created in Ketcher and exported to  mol V3000 file looks different in other sketcher (part of the structure is lost)

**Steps to Reproduce**
1. Create structure in Ketcher using elements from the library (or open file from attachments)
![image](https://github.com/epam/Indigo/assets/143799055/77e0debe-34c0-4bab-94c1-3da09afed4f7)
2. Save to mol file 
3. Open mol file in different sketcher.

**Additional information**
1. BIOVIA expects the following template name format for molv3000: TEMPLATE 1 AA/Ala/A/
2. For NATREPLACE=AA/X the following form is expected TEMPLATE 1 AA/Ac/
3. All CHEMs should be converted to LINKERs - otherwise it will not be displayed in BIOVIA
4. All SEQIDs should be calculated. Sugar, Base and right Phosphate should have the same SEQID otherwise BIOVIA will not detect the nucleotides.

**Expected behavior**
(The symbols in upper row should be red)
![image](https://github.com/epam/Indigo/assets/143799055/6644c953-607f-47be-aa7e-94a0cc858118)

**Actual behavior**
![image](https://github.com/epam/Indigo/assets/143799055/b1f1fc77-2896-4d38-923d-da95437f9c53)

**Attachments**
[ketcher_example.zip](https://github.com/epam/Indigo/files/13990046/ketcher_example.zip)

**Indigo/Bingo version**  
1.18.0-rc.3.0-ge65b5cde3-wasm32-wasm-clang-12.0.0

**Additional context**

**Comment by AlexeyGirin** [comment]
MOved to RC7 since we decided to release RC6 today because it has all features for Query Features Phase II done and remained tasks (Macromolecules) definitely out of scope

**Comment by AlexeyGirin** [comment]
MOved to 1.19 as per @vanoprenko decision

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/5e76de94-d4c4-425c-ae8e-d390def65c71)
[ketcher - 2024-03-18T221649.577.zip](https://github.com/epam/Indigo/files/14641370/ketcher.-.2024-03-18T221649.577.zip)

 - Indigo Toolkit Version 1.19.0-rc.1.0-g8cd9f1e27-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc1 Build at 2024-03-15; 15:42:19
 - Chrome Version 122.0.6261.129 (Official Build) (64-bit)
 - Win10
