### ISSUE TITLE
Unable to load large base64 CDX content to canvas if remote indigo used

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1607]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-rc.4.0-g84a1f903f-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.18.0-rc.2 Build at 2024-01-17; 16:42:55
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Describe the bug**
Unable to load large base64 CDX content to canvas if remote indigo used

**Steps to Reproduce**
1. Load from file: [LargeContent.zip](https://github.com/epam/Indigo/files/14051125/LargeContent.zip) (unzip first)

**Actual behavior**
System throws exception: Convert error! Unexpected token '<', "<!DOCTYPE "... is not valid JSON
![image](https://github.com/epam/Indigo/assets/26869421/50616568-3dbc-4fc2-9240-b82b8b77ef5c)

**Expected behavior**
![image](https://github.com/epam/Indigo/assets/26869421/3e73f14f-995f-4410-90be-52d006392fb9)

Context:
This issues come together with https://github.com/epam/ketcher/issues/3961
Payload taken from PPT file: [PPT with chemdraw (1) 1.pptx](https://github.com/epam/Indigo/files/14051166/PPT.with.chemdraw.1.1.pptx)

**Comment by AliaksandrDziarkach** [comment]
Backmerge https://github.com/epam/Indigo/pull/1647
