### ISSUE TITLE
convert_explicit_hydrogens response doesn't comply with the ket schema 

### ISSUE THREAD

**Issue by captain2b** [epam/Indigo#1608]
**Environment details  (please complete the following information):**
 - Back-end version 
Version 1.18.0-rc.4.0-g84a1f903f-x86_64-linux-gnu-11.2.1

**Describe the bug**
Redundant data passed in response of "convert_explicit_hydrogens"

**Steps to Reproduce**
1. Create request for convert_explicit_hydrogens with "selected" field present in  atoms/bonds fields.

**Expected behavior**
'hilight' field consists of 2 string items
**Actual behavior**
'hilight' field consists of 3 items 
**Attachments**
<img width="1432" alt="Screenshot 2024-01-25 at 18 26 08" src="https://github.com/epam/Indigo/assets/9428000/c2a68073-e114-4ed2-8d7e-45bd2f0c5a46">

**Comment by AlexeyGirin** [comment]
Fixed.
Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
