### ISSUE TITLE
Copy to clipboard doesn't work (throws exception) for very simple custom query bond

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1623]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-rc.4.0-g84a1f903f-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.18.0-rc.2 Build at 2024-01-17; 16:42:55
 - Chrome Version 120.0.6099.130 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1436

**Describe the bug**
Copy to clipboard doesn't work (throws exception) for very simple custom query bond
![image](https://github.com/epam/Indigo/assets/26869421/a67cbc4c-cc75-4379-ba10-1e7343c8a1e4)

**Steps to Reproduce**
1. Load from file: [Copy to clipboard doesn't work (throws exception) for very simple custom query bond.zip](https://github.com/epam/Indigo/files/14065613/Copy.to.clipboard.doesn.t.work.throws.exception.for.very.simple.custom.query.bond.zip) (unzip first)
2. Press Ctrl+A keys
3. Press Ctrl+C keys

**Actual behavior**
System throws exception: Convert error! IndigoException: molfile saver: unrepresentable query bond: (order = 3 | order = 4)
![image](https://github.com/epam/Indigo/assets/26869421/91386d51-6a7b-4825-a861-375230c3a9a6)

**Expected behavior**
No exception. Works as intended

**Comment by AliaksandrDziarkach** [comment]
This is molfile restriction.

**Comment by AlexeyGirin** [comment]
Should work. Result should not contain unsupported features in mol format

**Comment by AlexeyGirin** [comment]
Moved to Refined Backlog since not fixed over 2 releases
