### ISSUE TITLE
Add/Remove Explicit Hydrogens works incorrectly with selection

### ISSUE THREAD

**Issue by captain2b** [epam/Indigo#1632]
**Environment details  (please complete the following information):**
 - Back-end version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
 - Issue found while testing https://github.com/epam/Indigo/issues/1589
 
**Steps to Reproduce**
1. Create a structure with some explicit hydrogens
<img width="1440" alt="Screenshot 2024-01-29 at 14 21 38" src="https://github.com/epam/Indigo/assets/9428000/4745ff4e-a07c-4afa-82e3-13f76540ef34">

2. Select a bond without explicit hydrogens
3. Press 'Add/Remove Explicit Hydrogens'

**Expected behavior**
More hydrogens are added

**Actual behavior**
Nothing happens

**Comment by AlexeyGirin** [comment]
Fixed.
 - Ketcher Version 2.18.0-rc.4 Build at 2024-02-06; 13:45:28
 - Indigo Toolkit Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1
 
![image](https://github.com/epam/Indigo/assets/26869421/30d763db-8c23-4112-99c4-9e219899d451)
