### ISSUE TITLE
Running Bingo in Elasticsearch

### ISSUE THREAD

**Issue by pshenichnov** [epam/Indigo#164]
It's not really an issue, but I would like to check if it's even possible to run Bingo in Elasticsearch?

We use Elasticsearch as our general search engine and would like to move the structure search there as well. I know you have Lucine cartridge, but not sure if it compatible with Elasticsearch. If you could give any hints if it's possible and easy to do that would be very much appreciated!

**Comment by pshenichnov** [comment]
hello! anyone?

**Comment by AlexanderSavelyev** [comment]
yes, it is possible to run Bingo in Elasticsearch. Actually, it is Indigo built in into the client. Please see this pull request with elastic
https://github.com/epam/Indigo/pull/116
The only hint would be that it is not necessary to install server plug-in. One can just use elastic to keep and search by fingerprints and then on client do verification (because fingerprints is just a "hash" for given structures)

**Comment by pshenichnov** [comment]
Great! Thanks a lot, @AlexanderSavelyev. I'll review the PR

**Comment by MysterionRise** [comment]
@pshenichnov there are plans to revive this problem and come up with Elasticsearch plugin that will be able to achieve similarity search based on the compounds, so stay in touch!

**Comment by yeskela** [comment]
Wow! this is cool, @MysterionRise! Do you have any estimation when we should expect to play with it?

**Comment by pshenichnov** [comment]
Wow! this is cool, @MysterionRise! Do you have any estimation when we should expect to play with it?

**Comment by MysterionRise** [comment]
@pshenichnov hard to tell, to be honest, but watch out this space

**Comment by MysterionRise** [comment]
@pshenichnov we have merged first version of the Java API that is able to index molecules from different file formats, add custom metadadata and search molecules by exact match, similarity match and substructure match.
Some of the functionality isn't available yet, and we started to work on Python API as well. You're welcome to try it out

Readme is available by link - https://github.com/epam/Indigo/blob/master/api/plugins/bingo-elastic/java/README.md 
Your feedback of usage and future improvements is highly appreciated
