### ISSUE TITLE
Add/Remove hydrogens doesn't work for bonds if separate atoms and bonds selected together

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1650]
**Environment details  (please complete the following information):**
 - Indigo Toolkit Version 1.18.0-rc.5.0-gb21ab5ad5-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.18.0-rc.2 Build at 2024-01-26; 15:56:57
 - Chrome Version 120.0.6099.225 (Official Build) (64-bit)
 - Win10
 - Issue found while testing https://github.com/epam/Indigo/issues/1589
 
**Describe the bug**
Add/Remove hydrogens doesn't work for bonds if separate atoms and bonds selected together

**Steps to Reproduce**
1. Load from file: [Atom and Bonds.zip](https://github.com/epam/Indigo/files/14109991/Atom.and.Bonds.zip) (unzip first)
2. Select few atoms and few bonds
3. Press Add/Remove explicit hydrogens button
![image](https://github.com/epam/Indigo/assets/26869421/65266ca1-63fc-44a2-ae95-4f67aba78afa)

**Actual behavior**
System adds hydrogens to atoms only
![image](https://github.com/epam/Indigo/assets/26869421/2945a686-4b90-4e67-930c-ca00d7c64c26)

**Expected behavior**
Hydrogens added for all selected atoms and bonds
![image](https://github.com/epam/Indigo/assets/26869421/9fa6b566-6748-44ce-94f8-c1c60dc6e79e)

**Comment by AliaksandrDziarkach** [comment]
Works as designed

**Comment by AlexeyGirin** [comment]
DECISION: For selected bonds - we don't have to add hydrogens, but IF only bonds selected - should happen nothing

**Comment by AlexeyGirin** [comment]
Closed.

**Comment by AlexeyGirin** [comment]
Particular case has works as intended. Followed up bug created: https://github.com/epam/Indigo/issues/1728
 - Indigo Toolkit Version 1.18.0-rc.7.0-g8a5c36802-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.19.0-rc.1 Build at 2024-02-19; 15:33:56
 - Chrome Version 120.0.6099.225 (Official Build) (64-bit)
 - Win10
 
 ![image](https://github.com/epam/Indigo/assets/26869421/794bdd66-4fa6-4006-8386-9e349482c547)
