### ISSUE TITLE
bingo_install.sql and version 10.13 of PostgreSQL

### ISSUE THREAD

**Issue by AliZainoul** [epam/Indigo#169]
Hello, I am working on a Linux kernel : Linux XXXXX 4.15.0-107-generic #108~16.04.1-Ubuntu SMP Fri Jun 12 02:57:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux; 

I followed the procedure for pre configuration, configuration, compilation and installation of the Cartridge on the 10.13 version of Postgres, all worked fine, until I launch the command psql -p 5434 -d testdb -f bingo/bingo_install.sql  (p = 5434 is just the port for the 10.13 version of Postgresql, and bingo is just a directory hosting the file bingo_install.sql), so I get: 

BEGIN
CREATE SCHEMA
SET
psql:bingo/bingo_install.sql:7: ERROR: can not upload the library « /usr/lib/postgresql/10/lib/bingo_postgres.so » : /usr/lib/postgresql/10/lib/bingo_postgres.so: undefined symbol: DatumGetFloat8; 

It appears that there is a problem somewhere in the linkage between the library postgres.h and bingo. 

Can you please consider this issue, trying to reproduce it in order to know where the bug is?! (It works fine on 9.5 & 9.6 versions)

Thank you in advance!

**Comment by AlexanderSavelyev** [comment]
Hi
Latest supported PostgreSQL is 10.1
But we are going to include support for more recent versions of Postgre in the nearest future

Thanks
Aleksandr

**Comment by AliZainoul** [comment]
Thank you for giving me an answer as fastest as possible, however, I try to adapt Bingo to be " version-independant " from Postgres, so I have just to test for the latest version (10.1) and then have to adapt the source code for further versions of Postgres. May you please specify technically speaking, the dependancies who cause the issue discussed above ?
( in a simple form ) 
Thank you in advance; :) 

By the way: the source code where you are including postgres librairies cause some bugs while compilation: 
I had to readapt the order of the called libraries (postgres.h then fmgr.h etc.) so the compilation pass smooth. 

Ali

**Comment by AliZainoul** [comment]
EDIT: even on version 10.13 it works (No bigger differences between version 9.6 and >= 10, may you please confirm that?) 

I am adapting right now the src code for versions above 11.8;

**Comment by targetgenenotebook** [comment]
Hi,
Have you had any success to your efforts adapting Bingo for PostgreSQL 11?
Thanks for any information.
Best,
Andrew

**Comment by AliZainoul** [comment]
Hello, yes I have adapted it, and it was successful (until proven otherwise), but I can not share the source code... (it is due to the confidentiality contract that I signed with my company), but feel free to ask any question.

Best regards, Ali

**Comment by AlexanderSavelyev** [comment]
Hello. right now we are working on creating Bingo cartridge for PostgreSQL 11 and 12. Also at the same time there is a plan to create an extension (#133 ) so it can take some time

**Comment by targetgenenotebook** [comment]
Thank you both for the quick responses.

That is great news, Ali.  It is understandable regarding confidentiality.  Thank you for the offer .. you may hear from me if we take on the compilation ourselves .. smile

Alexander, do you have a rough timeframe for PostgreSQL 11 support?  Do you plan to wait for the extension development to be completed until you release PostgreSQL support?

Thanks again, Andrew

**Comment by targetgenenotebook** [comment]
Apologies, the last question should have included "11":

Do you plan to wait for the extension development to be completed until you release PostgreSQL 11 support?

**Comment by AliZainoul** [comment]
> That is great news, Ali. It is understandable regarding confidentiality. Thank you for the offer .. you may hear from me if we take on the compilation ourselves .. smile

A hint that I can give to you:
For version 11.8, the corresponding three files MUST be adapted:
- bingo_pg_buffer.cpp
- bingo_pg_cursor.cpp
- pg_bingo_build.cpp

We will keep in touch if I was effectively right. Keep the great work. 

Regards;





> Hello. right now we are working on creating Bingo cartridge for PostgreSQL 11 and 12. Also at the same time there is a plan to create an extension (#133 ) so it can take some time

I have noticed the fact that effectively, after version 9.6, one can create an extension of Bingo so we can adapt it to further versions of PostgreSQL smoothly.

Have a nice day.

**Comment by targetgenenotebook** [comment]
Thanks!

**Comment by AlexanderSavelyev** [comment]
I have added support for 11 and 12 version. The regression testing passed smoothly but there are some errors while unit testing though for very specific cases. Will check this issues later and deploy binaries for Linux

**Comment by targetgenenotebook** [comment]
That sounds like great progress .. thank you for the update, Alexander!

**Comment by AliZainoul** [comment]
> I have added support for 11 and 12 version. The regression testing passed smoothly but there are some errors while unit testing though for very specific cases. Will check this issues later and deploy binaries for Linux

All works fine, I have made exactly same changes, with some bug fixes a priori.. And It was successful.

Btw: the source code does not compile on 9.5 version; one have to adapt the conditional clause for pg_bingo_costestimate.c if >=12.3 versions use bingo_costestimate120 else <12.3 versions take the old source code. It worked for me.

**Comment by AlexanderSavelyev** [comment]
Version 1.9.1 was released with 11 and 12 PostgreSQL support
One can find binaries here
https://lifescience.opensource.epam.com/download/bingo.html
Currently the supported and tested PostgreSQL versions
9.6,
10 (tested with 10.14)
11 (tested with 11.8)
12 (tested with 12.3)
