### ISSUE TITLE
CDX loader failed if object with zero id follow by reaction

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#1695]
Steps to reproduce:

1) download attached file
[test_zero_id.zip](https://github.com/epam/Indigo/files/14250043/test_zero_id.zip)
2) Try to open in ketcher
3) Error occured:
![image](https://github.com/epam/Indigo/assets/18146690/960ff34a-2bbd-4ca8-94ef-9ce0593ab9e6)

Expected behavior: file should be successfully opened.

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.18.0-rc.5 Build at 2024-02-13; 10:27:16
Indigo Toolkit Version 1.18.0-rc.6.3-gdb6a7f5e-wasm32-wasm-clang-12.0.0
