### ISSUE TITLE
Can not install Indigo's API python utilities 

### ISSUE THREAD

**Issue by AliZainoul** [epam/Indigo#170]
Hello all,

It is me again haha;

So, I have one question and one issue concerning Indigo:

I will start with the question: 
- Is there any dependency between a DBMS (Postgres as instance) and the Indigo API ?

Then the issue:
- After installing the prerequisite tools, launching the building script for indigo lib: 
 `python build_scripts/indigo-release-libs.py --preset=linux64` ; 
I wanted to generate the utility tools as well, but in the near end of compilation (98%), I had the following error:

`[ 98%] Linking C executable ../dist/Linux/x64/lib/indigo-cano`
`/usr/bin/ld : ne peut trouver -lindigo`
`collect2: error: ld returned 1 exit status`
`indigo-cano/CMakeFiles/indigo-cano.dir/build.make:94 : la recette pour la cible « dist/Linux/x64/lib/indigo-cano » a échouée`
`make[2]: *** [dist/Linux/x64/lib/indigo-cano] Erreur 1`
`CMakeFiles/Makefile2:2065 : la recette pour la cible « indigo-cano/CMakeFiles/indigo-cano.dir/all » a échouée`
`make[1]: *** [indigo-cano/CMakeFiles/indigo-cano.dir/all] Erreur 2`
`Makefile:160 : la recette pour la cible « all » a échouée`
`make: *** [all] Erreur 2`

All works fine (generating the libraries for Indigo and the python Wrappers as well) until launching the utilities python command; the thing is it became so much difficult and complicated to keep track of all files, dependencies and to understand the exact operation between the different makefiles, so I have some trouble to debug this part, may you please give me the precise path to follow please? :+1: 

Btw, system info:

 Linux XXXXXXXX 4.15.0-112-generic 113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by AliZainoul** [comment]
Please ignore the mentioned issue, it was a mistake.
@AliZainoul  mentioned this issue 23 minutes ago
Certain concurrent queries crash Bingo #113

**Comment by mkviatkovskii** [comment]
Hello @AliZainoul 
Thanks for your bug report, I was able to reproduce it and going to release the fix soon.

**Comment by mkviatkovskii** [comment]
As for your question,

> Is there any dependency between a DBMS (Postgres as instance) and the Indigo API ?

We have a set of core C++ libraries (could be found in folders `common`, `graph`, `molecule`, `reaction`, `layout`). Indigo API is built on top of them.
Our Bingo cartridges for various DBMS (Oracle, Postgres, SQL Server) are also built on top of core libraries, but do not use Indigo API itself.
So Indigo API and Bingo they are kind of siblings with same parent.

**Comment by mkviatkovskii** [comment]
@AliZainoul could you please try latest revision in `master` branch?

**Comment by AliZainoul** [comment]
Hello @mkviatkovskii, first thing first, thanks for your answers, it is now clear.

Concerning the issue, because of the fact that it was my last day as a trainee, I can not retest if it works or not; However I asked my internship tutor to try to reproduce the issue and as soon as I get an answer, I'll deliver it here.

Thanks again ;)

**Comment by mkviatkovskii** [comment]
Closing the issue as it is fixed.
