### ISSUE TITLE
Unable to load molecule from CDX - Unsupported node connectivity for bond

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1702]
**Steps to Reproduce**
1. Click Open... button (Ctrl+O)
2. Select open from file
3. Select file: [Unsupported node connectivity for bond.pptx](https://github.com/epam/Indigo/files/14271762/Unsupported.node.connectivity.for.bond.pptx)
4. Click Open

**Actual behavior**
System throws exception: Error: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'CDXML loader: Unsupported node connectivity for bond id: 19851', 'CDXML loader: Unsupported node connectivity for bond id: 19851', 'CDXML loader: Unsupported node connectivity for bond id: 19851', 'CDXML loader: Unsupported node connectivity for bond id: 19851'
![image](https://github.com/epam/Indigo/assets/26869421/7b6027d5-ca2d-4770-936c-65010c034c99)

**Expected behavior**
No exception.
![image](https://github.com/epam/Indigo/assets/26869421/31810b3b-e0c4-46d5-8c07-2bc5e7093e68)

**Environment details:**
- Ketcher Version 2.18.0-rc.5 Build at 2024-02-09; 17:07:18
- Indigo Toolkit Version 1.18.0-rc.6.3-gdb6a7f5e-wasm32-wasm-clang-12.0.0
- Chrome Version Version 121.0.6167.161 (Official Build) (64-bit)
- Win10
- Issue found while testing https://github.com/epam/ketcher/issues/3914

**Comment by AliaksandrDziarkach** [comment]
Dublicate of [#1695](https://github.com/epam/Indigo/issues/1695)

**Comment by AlexeyGirin** [comment]
Duplicate https://github.com/epam/Indigo/issues/1697 ?

**Comment by AlexeyGirin** [comment]
Reopened. It was not a duplicate of https://github.com/epam/Indigo/issues/1697

**Comment by AlexeyGirin** [comment]
Fixed.
Ketcher Version 2.18.0-rc.8 Build at 2024-02-22; 17:29:02
Indigo Toolkit Version 1.18.0-rc.8.0-g85a393c7c-wasm32-wasm-clang-12.0.0
![image](https://github.com/epam/Indigo/assets/26869421/d96b45db-bc3f-4723-a77d-2189c54eb73e)
