### ISSUE TITLE
Add support for Windows in Travis CI

### ISSUE THREAD

**Issue by MysterionRise** [epam/Indigo#174]
Let's add support for windows platform during CI run

**Comment by mkviatkovskii** [comment]
Currently we consider using Github Actions instead of Travis/AppVeyor, there is a ticket for that: https://github.com/epam/Indigo/issues/175
First of all we need to investigate the situation with artifacts, since they are required for proper package building.

**Comment by MysterionRise** [comment]
@mkviatkovskii agreed, Github actions should be good

**Comment by mkviatkovskii** [comment]
Closing since we moved to GitHub actions
