### ISSUE TITLE
Can't export sequence with 1 monomer to molv3000

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1761]
**Describe the bug**
Invalid index message during the export to molv3000

**Steps to Reproduce**
1. Load hundred-monomers.ket from attached zip
[files.zip](https://github.com/epam/Indigo/files/14444614/files.zip)
 
2. Export to molv3000

**Expected behavior**
Sequence successfully converted

**Actual behavior**
Invalid index exception appears

**Comment by Zhirnoff** [comment]
Tested. Fixed.

**Comment by AlexeyGirin** [comment]
Fixed.

![image](https://github.com/epam/Indigo/assets/26869421/0b4144e2-b0e5-4bb5-9a24-b4fb74b30458)

 - Indigo Toolkit Version 1.19.0-rc.1.0-g8cd9f1e27-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc1 Build at 2024-03-15; 15:42:19
 - Chrome Version 122.0.6261.129 (Official Build) (64-bit)
 - Win10
