### ISSUE TITLE
Some bonds don't display correctly in ChemDraw when opening a saved Ketcher CDX file.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1777]
**Steps to Reproduce**
1. Use Indigo library (Bingo cartridge). Describe environment
2. Open Ket file with Bonds >> Add to Canvas
3. Save  >> select CDX 
4. Open this CDX file in the ChemDraw

**Expected behavior**
We should be able to open saved in the Ketcher CDX file in the ChemDraw and all structures should be visible as well as saved.

**Actual behavior**
Some bonds don't display correctly in ChemDraw when opening a saved Ketcher CDX file.
Kindly see pictures and wrong CDX file and Ket file in the attachment files.

 https://github.com/epam/Indigo/issues/1775
https://github.com/epam/Indigo/issues/1776

**Attachments**
[1 CDX and ket Bonds ketcher.zip](https://github.com/epam/Indigo/files/14493716/1.CDX.and.ket.Bonds.ketcher.zip)
![1 CDX Bonds Screenshot Error-ChemDraw2](https://github.com/epam/Indigo/assets/161723514/056f896b-be1b-449d-99f4-ce36cf4a5cf4)

**Environment details:**
• OS: Windows 10 Pro (version 22H2) x64
• Browser: Сhrome
• Version: (122.0.6261.95) x64
- Ketcher version 2.19.0 – rc.1
- Indigo Toolkit
- Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/95800b9c-7aae-4428-b239-29906058986a)

In Chem Draw it seems that it doesn't support Hydrogen Bond, so - it shows Single one instead. But in terms of CDX - we save it correct and able to load from CDX in Ketcher

 - Indigo Toolkit Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc2 Build at 2024-03-27; 08:30:51
 - Chrome Version 122.0.6261.70 (Official Build) (64-bit)
 - Win10
