### ISSUE TITLE
Some Bonds from ChemDraw don't open in the Ketcher

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1787]
**Steps to Reproduce**
1. Use Indigo library (Bingo cartridge). Describe environment
2. Open ChemDraw CDX file with additional Bonds [01 Bonds ChemDraw - full.zip] >> **_Error_** 

**Expected behavior**
We should be able to open all bonds from ChemDraw in the Ketcher app. 

**Actual behavior**
**_Error_** Some Bonds don't open in the Ketcher
Also see https://github.com/epam/Indigo/issues/1796
Kindly see attachment file
 https://github.com/epam/Indigo/issues/1775

**Attachments**
[01 Bonds ChemDraw - full.zip](https://github.com/epam/Indigo/files/14528613/01.Bonds.ChemDraw.-.full.zip)

**_Error_** 
<img width="963" alt="cannot open cdx from ChemDarw - Bonds2" src="https://github.com/epam/Indigo/assets/161723514/0e6760e6-aeab-4864-84ac-5defa985959a">

**Versions**
• OS: Windows 10 Pro (version 22H2) x64
• Browser: Сhrome
• Version: (122.0.6261.95) x64
Ketcher version 2.19.0 – rc.1
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/1654058f-a4c4-46b3-8cf4-98e41a23b1c5)

 - Windows 10
 - Сhrome Version: (122.0.6261.95) x64
 - Ketcher version 2.19.0-rc.1
 - Indigo Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1
