### ISSUE TITLE
Aromatic is lost from Benzene while save to CDX/base64 CDX formats

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1791]
**Steps to Reproduce**
1. Use Indigo library (Bingo cartridge). Describe environment
2. Open Ket file different Rings:  [4 Rounds-hydro ket.zip](https://github.com/epam/Indigo/files/14537135/4.Rounds-hydro.ket.zip)
3. Add to Canvas
4. Save >> select CDX >> Save
5. Open CDX files in the Ketcher
6. Open CDX file in the ChemDraw

**Expected behavior**
We should be able to open saved in the Ketcher CDX file in the ChemDraw and all structures should be visible as well as saved.

**Actual behavior**
Aromatic is lost from Benzene while save to CDX/base64 CDX formats.
Aromatic is saved successful for CDX XML fomat
Kindly see pictures.

 https://github.com/epam/Indigo/issues/1775
https://github.com/epam/Indigo/issues/1776

**Attachments**

[4 Rounds-hydro CDX.zip](https://github.com/epam/Indigo/files/14537136/4.Rounds-hydro.CDX.zip)

ChemDraw
<img width="995" alt="CDX - in ChemDraw no Aromatize" src="https://github.com/epam/Indigo/assets/161723514/e983bfa2-fbee-406c-a907-47f9240b7fb3">

Ketcher
<img width="959" alt="CDX and 64 cdx - no Aromatize" src="https://github.com/epam/Indigo/assets/161723514/87d4e90d-3ab3-4c19-855e-2417e15ef72b">

**Environment details:**
• OS: Windows 10 Pro (version 22H2) x64
• Browser: Сhrome
• Version: (122.0.6261.95) x64
- Ketcher version 2.19.0 – rc.1
- Indigo Toolkit
- Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1

**Comment by AlexeyGirin** [comment]
Considered as High since we have similar issues same priority:
 - https://github.com/epam/Indigo/issues/1777
 - https://github.com/epam/Indigo/issues/1786

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/faa2f1eb-b9a3-49f2-891a-1454b2576bef)

 - Indigo Toolkit Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc2 Build at 2024-03-27; 08:30:51
 - Chrome Version 122.0.6261.70 (Official Build) (64-bit)
 - Win10
