### ISSUE TITLE
 Some bonds from ChemDraw don't display correctly in the Ketcher.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1796]
**Steps to Reproduce**
1. Use Indigo library (Bingo cartridge). Describe environment
2. Open ChemDraw CDX file with default Bonds [02 Bonds ChemDraw - part.zip] >> **_Error1_** not all bonds are correct

**Expected behavior**
We should be able to open all bonds from ChemDraw in the Ketcher app. 

**Actual behavior**
**_Error1_** Some bonds from ChemDraw don't display correctly in the Ketcher
Also, see https://github.com/epam/Indigo/issues/1787
Kindly see attachment file
 https://github.com/epam/Indigo/issues/1775

**Attachments**
[02 Bonds ChemDraw - part.zip](https://github.com/epam/Indigo/files/14528612/02.Bonds.ChemDraw.-.part.zip)

**_Error1_**
<img width="964" alt="cdx from ChemDarw - Bonds incorrect" src="https://github.com/epam/Indigo/assets/161723514/9ead9d70-ffa3-49dc-adb3-30f2c0e80703">

**Versions**
• OS: Windows 10 Pro (version 22H2) x64
• Browser: Сhrome
• Version: (122.0.6261.95) x64
Ketcher version 2.19.0 – rc.1
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.18.0-rc.6.0-g98bf384e0-x86_64-linux-gnu-11.2.1

**Comment by AlexeyGirin** [comment]
Not fully fixed.
Some bonds such as "Double tautomeric" and "Double bold" are not shown correct in Ketcher
1. "Double tautomeric" - shown as Aromatic
![image](https://github.com/epam/Indigo/assets/26869421/2cb320a7-66e6-459a-b1bf-4fbc25db4c31)

2. "Double bold" - shown as "blank" or empty type
![image](https://github.com/epam/Indigo/assets/26869421/97458d99-4388-408f-a80b-1dd6e7c2408d)

As per reference: [ChemDraw_17_manual.pdf](https://github.com/epam/Indigo/files/14773484/ChemDraw_17_manual.pdf)


Use following CDX to reproduce: [Not fully fixed.zip](https://github.com/epam/Indigo/files/14773461/Not.fully.fixed.zip)
Open it in Ketcher.

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/e8875cec-6a14-4df8-b4d2-f4d8c22e3d2a)

 - Indigo Version 1.19.0-rc.3.0-gf2d7689b-wasm32-wasm-clang-12.0.0
 - Ketcher Version 2.20.0-rc2 Build at 2024-03-27; 08:30:51
 - Chrome Version 122.0.6261.70 (Official Build) (64-bit)
 - Win10
