### ISSUE TITLE
No monomer full name when import from a sequence

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1801]
**Steps to Reproduce**
1. Import RNA, DNA or PEPTIDE sequence
2. Save as KET file

**Actual behavior**
No fullName field appears in monomer template description

**Expected behavior**
corresponding fullName should appear in the template description

**Comment by Zhirnoff** [comment]
Tested on build 2.20.0-rc.2 and Indigo 1.19.0-rc.2 Bug is fixed.
![2024-03-27_20h44_39](https://github.com/epam/Indigo/assets/62464241/30120c7a-0f2d-426a-9a11-8a8b0526b1f9)
