### ISSUE TITLE
Fasta: All Peptides should be saved to FASTA format and (use N/X symbol as well).

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1822]
**Steps to Reproduce**
1. Macromolecules mode
2. Add one Peptide from Peptides tab
3. Try to Save to FASTA format
<img width="957" alt="Not all Peptides Saved to FASTA" src="https://github.com/epam/Indigo/assets/161723514/9adc3bc6-86ca-4d7d-9550-3e6d386c613e">

**Current implementation for non-standard monomers**
save natural analog if present
if no natural analog:

PEPTIDE: X
RNA: N
all other cases: monomer breaks the sequence

**Expected behavior**
all Peptides should be saved to FASTA format.
Expected result from comment:
Sequences are expected to be represented in the standard nucleic acid codes, with these exceptions:
N or n as unknown nucleic acid residue will be translated into X for unknown amino acid residue.
The nucleic acid codes supported are:
A --> adenosine
C --> cytidine
G --> guanine
T --> thymidine
**N --> A G C T U (any)**

Symbols for translated amino acids:
A alanine P proline
B aspartate or asparagine Q glutamine
C cystine R arginine
D aspartate S serine
E glutamate T threonine
F phenylalanine U selenocysteine
G glycine V valine
H histidine W tryptophan
I isoleucine Y tyrosine
K lysine Z glutamate or glutamine
L leucine **X any**
M methionine * translation stop
N asparagine

**Actual behavior**
 Not all Peptides can be saved to FASTA format.
- https://github.com/epam/Indigo/issues/1755
- https://github.com/epam/ketcher/issues/4146
- https://github.com/epam/ketcher/issues/4280

**Environment details:**
• [Version 2.19.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-03-13; 13:51:33

[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.19.0-dev.1.0-g9fa8cfe30-wasm32-wasm-clang-12.0.0

Win10
Chrome Version 122.0.6261.129 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
@even1024 says it is fixed.

**Comment by NadezhdaPeskun** [comment]
[Yesterday 1:23 PM] Olga Nazarenko

У нас библиотека сгруппирована по натурал аналогу. То есть все сложные буквы в группе А, должны експортироваться как А
