### ISSUE TITLE
Impossible open Fasta file with few Peptides or RNA or DNA sequences.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1828]
**Steps to Reproduce**

1. Switch to Macro
2. Click Open...->Paste from Clipboard >> Select 'FASTA' and 'Peptides'
3. Paste Peptides
```
>seq1
KYRTWEEFTRAAEKLYQADPMKVRVVLKYRHCDGNLCIKVTDDVVCLLYRTDQAQDVKKIEKFHSQLMRLMELKVTDNKECLKFKTDQAQEAKKMEKLNNIFFTLM

```
4. Add this Peptides again 
5. Save FASTA file with two sequences.
6. Try to Open this FASTA file selected 'FASTA' and 'Peptides' from drop-down menu

**Actual behavior**
We cannot open Fasta file with few Peptides or RNA or DNA sequences.
Error appears.
![image](https://github.com/epam/Indigo/assets/161723514/e900dab6-f8e4-4c3b-a722-4dfff0b33729)

- https://github.com/epam/ketcher/issues/4146

**Expected behavior**
We should be able to open Faste file with any Peptides or RNA or DNA sequences.

**Attachments**
[FASTA 2 Peptides.zip]
(https://github.com/epam/Indigo/files/14618565/FASTA.2.Peptides.zip)

**Version:**
OS: Windows 10
Browser Chrome
Version 112.0.5615.138 (Official Build) (64-bit)

[Version 2.20.0-rc.1](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-03-15; 15:36:45
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.19.0-rc.1.0-g8cd9f1e27-wasm32-wasm-clang-12.0.0

**Comment by AlexeyGirin** [comment]
Moved to next release after discussion with @vanoprenko (considered low priority and can be shifted)

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/e7d81369-58cb-4e96-9842-899ac269daca)

 - Indigo Toolkit Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc2 Build at 2024-03-27; 08:30:51
 - Chrome Version 122.0.6261.70 (Official Build) (64-bit)
 - Win10
