### ISSUE TITLE
How to get molecule from Inchikey

### ISSUE THREAD

**Issue by Surajpatil07** [epam/Indigo#1831]
**Background**
How to get molecule from Inchikey. 
Currently we have the option to get the molecule from "SMILES" using indigo.loadmolecule(smilestring). Similarly, do we have any function to get the molecule from InchIKey.

**Solution**

**Alternatives**

**Additional context**

**Comment by even1024** [comment]
SMILES contains a structural description of the molecule, whereas InChIKey does not. It's like a hash code for the molecule, and you can only use the InChIKey to search for the molecule in the database.

**Comment by Surajpatil07** [comment]
Thanks for the clarification.
Is there any way to get the SMIILES from the Inchikey so that I can print
the molecular structure.

**Comment by even1024** [comment]
I already mention that InchiKey just doesn't have an information about the molecule atoms and structure so there is no way to extract if from there.
Did you notice that InchiKey has a fixed size (27 characters) but SMILES can be as complex as desired?
For instance you can calculate a fixed size hash code of any string, but you can't restore that string from the hash code.

**Comment by Surajpatil07** [comment]
Thanks for the clarification!
