### ISSUE TITLE
FASTA export: 80 chars limit

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1843]
**Background**
FASTA specification recommends to make sequence strings shorter than 80 characters

**Solution**
Implement 80 chars limit formatting for exported sequences.

Example:

```
>MCHU - Calmodulin - Human, rabbit, bovine, rat, and chicken
MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID
FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREAD
IDGDGQVNYEEFVQMMTAK*
```

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/Indigo/assets/26869421/b38b0ece-5354-42d4-aad6-9e82a2ab542b)


 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
