### ISSUE TITLE
Implement GenBank/GenPept sequences import

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1844]
**Background**
In addition to the traditional representation of a sequence, there is a GenBank/GenPept representation:

simple sequence:
ACCLCAACCLC

GenBank/GenPept:

1 gatcctccat atacaacggt atctccacct caggtttaga tctcaacaac ggaaccattg
61 ccgacatgag acagttaggt atcgtcgaga gttacaagct aaaacgagca gtagtcagct
121 ctgcatctga agccgctgaa gttctactaa gggtggataa catcatccgt gcaagaccaa

**Solution**
Implement GenBank/GenPept automatic detection so both simple sequence and GenBank/GenPept should be supported for the import.

**Comment by AlexeyGirin** [comment]
Verified.
![Image](https://github.com/user-attachments/assets/c73e07fa-224b-4a3a-88eb-ea4335c13b36)
- Ketcher Version 3.1.0-rc.8 Build at 2025-03-10; 20:00:16
- Indigo Version 1.29.0-rc.2.0-g6d2650d9c-wasm32-wasm-clang-19.0.0
- Chrome Version 134.0.6998.36 (Official Build) (64-bit)
- Win10
