### ISSUE TITLE
Macro(Import FASTA): The ';' symbol is not recognized as a comment

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1851]
**Steps to Reproduce**
1. Switch to Macro mode
2. Paste FASTA sequence with ';' 
```
>M18404.1 Human IgG2 lambda antibody (1B8.env reactive) gp41 coding region DNA
GCAGTGGGAAGAGGAGCTTTGTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTATGGGCGCAGCCTCAA
;This is simple comment for this sequence > as it is
>M18404.1 Human IgG2 lambda antibody (1B8.env reactive) gp41 coding region DNA
GCAGTGGGAAGAGGAGCTTTGTTCCTTGGGTTCTTGGGAGCAGCAGGAAGCACTATGGGCGCAGCCTCAA
```

**Actual behavior**
The ';' symbol is not recognized as a comment

**Expected behavior**
The ';' symbol is recognized as a comment. The comments line starts with the semicolon ";" symbol and ends with newline. May contain any symbol (including ">")
 https://github.com/epam/Indigo/issues/1755

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Indigo version** 
[Version 1.19.0-rc.1]

**Attachments**

![2024-03-19_16h47_38](https://github.com/epam/Indigo/assets/62464241/44554507-15e5-4a6b-9100-338db7ffc1be)
![2024-03-19_16h47_47](https://github.com/epam/Indigo/assets/62464241/d0eb8d07-94d1-4dea-89ca-cf788515f941)

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/90ac97dd-21e5-4bbe-9bf6-df533c44bde6)

 - Indigo Toolkit Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1
 - Ketcher Version 2.20.0-rc2 Build at 2024-03-27; 08:30:51
 - Chrome Version 122.0.6261.70 (Official Build) (64-bit)
 - Win10
