### ISSUE TITLE
Macro: V3000 export causes two sequences pile one above other if opened in another sketcher

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1877]
**Steps to Reproduce**
1. Go to 'Macromolecules'
2. Load from file using open as New way: [Macro_ V3000 export causes two sequences pile one above other if opened in another sketcher.zip](https://github.com/epam/Indigo/files/14746252/Macro_.V3000.export.causes.two.sequences.pile.one.above.other.if.opened.in.another.sketcher.zip)
![image](https://github.com/epam/Indigo/assets/26869421/940b631c-eae3-42b6-a7f6-2b2c5260cb22)
3. Export to MDL Molfile V3000
4. Open resulted file in another sketcher

**Actual behavior**
Two sequences pile one above other if opened in another sketcher
![image](https://github.com/epam/Indigo/assets/26869421/616a79ce-9633-493d-b18c-b35adc478407)

**Expected behavior**
Two sequences NOT pile one above other if opened in another sketcher
![image](https://github.com/epam/Indigo/assets/26869421/63636a85-2c67-4cc5-a2ab-4d8a352c5ab4)

**Versions**
- Ketcher Version 2.20.0-rc.1 Build at 2024-03-15; 15:36:45
- Indigo Toolkit Version 1.19.0-rc.1.0-g8cd9f1e27-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 122.0.6261.131 (Official Build) (64-bit)

**Comment by AliaksandrDziarkach** [comment]
I add phosphates at left and save in molv3000 - it opened correctly:
![image](https://github.com/epam/Indigo/assets/18146690/2d268594-36c8-411c-9ee8-e6b173737c10)
opened as 
![image](https://github.com/epam/Indigo/assets/18146690/bdabc4bf-93bd-4c19-b1c7-67a821baf712)
After removing one phosphate and save in molv3000 modified molecule moved to the top-left:
![image](https://github.com/epam/Indigo/assets/18146690/d94f2ad3-c045-47f4-899f-abacf8eb9378)
opened as 
![image](https://github.com/epam/Indigo/assets/18146690/7f37e218-14d1-4ede-a193-ddd06b7224bc)
So this is not a indigo/ketcher problem.

**Comment by even1024** [comment]
duplicate to #1910
