### ISSUE TITLE
indigo dotNet can not load version V3000 molfile which contains cis/trans double bond

### ISSUE THREAD

**Issue by jank9201** [epam/Indigo#1879]
Indigo dotnet version 1.20.0-dev.1

when I use the function of indigo.loadMolecule (  ) to load the following V3000 molfile, which was generated from the ketcher-standalone:
"
  -INDIGO-03262416322D

  0  0  0  0  0  0  0  0  0  0  0 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 6 5 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 11.3636 -3.71364 0.0 0 CFG=1
M  V30 2 C 11.3636 -4.71364 0.0 0
M  V30 3 C 10.6565 -3.00653 0.0 0
M  V30 4 C 10.4976 -5.21364 0.0 0
M  V30 5 N 12.2297 -3.21364 0.0 0
M  V30 6 N 12.2297 -5.21364 0.0 0
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 2 1 2
M  V30 2 1 1 3
M  V30 3 1 2 4
M  V30 4 1 1 5
M  V30 5 1 2 6
M  V30 END BOND
M  V30 BEGIN COLLECTION
M  V30 MDLV30/STEABS ATOMS=(1 1)
M  V30 END COLLECTION
M  V30 END CTAB
M  END"
I got the following error message: "molfile loader: stereo type specified for atom #0, but the bond directions does not say that it is a stereocenter"

the following attachment is the screenshot of the above-mentioned molfile
![cisortransbond](https://github.com/epam/Indigo/assets/38416247/9dcc0c83-8f18-406c-835f-bf2dbaf1bdad)

**Comment by even1024** [comment]
Use ignore-stereochemistry-errors option.

**Comment by jank9201** [comment]
> Use ignore-stereochemistry-errors option
Hi, even1024, thanks for your reply, but I still have a question
"does current Indigo dotnet not support the above-mentioned double cis/trans stereo feature?"
