### ISSUE TITLE
Macro: When opening a seq file with peptides via RNA or DNA, an error appears in the Console DevTool           

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/Indigo#1883]
**Steps to Reproduce**
1.	Switch to the Macro mode
2.	Open this file as Sequence - RNA or DNA [Peptides.zip](https://github.com/epam/Indigo/files/14823728/Peptides.zip)

**Actual behavior**
The error appears on the canvas (Convert error! IndigoException: SEQUENCE loader: Invalid symbols in the sequence: E,D) and in the Console DevTool (POST https://rc.test.lifescience.opensource.epam.com/v2/indigo/convert 400 (Bad Request))

<img width="396" alt="image" src="https://github.com/epam/Indigo/assets/139227567/53f7afa2-0cc2-4be2-91d3-1f1d65bad541">

<img width="284" alt="image" src="https://github.com/epam/Indigo/assets/139227567/f00f434d-2c57-4c86-b465-0f2d5eee682f">

[rc.test.lifescience.opensource.epam.com-1711977506620.log](https://github.com/epam/Indigo/files/14823797/rc.test.lifescience.opensource.epam.com-1711977506620.log)

**Expected behavior**
The error is displayed on the canvas, but there are no errors in the Console DevTool

**Environment details:**
 - OS: Windows 10 Pro (version 22H2) x64
 - Browser: Сhrome
 - Version: (122.0.6261.112) x64

Indigo version  1.19.0-rc.2.0

Issue found while testing https://github.com/epam/ketcher/issues/4109

**Screenshots**

https://github.com/epam/Indigo/assets/139227567/3cffad7e-f8c8-45d2-aae0-0aa74a5d0a48

**Comment by AlexeyGirin** [comment]
Not a bug - if client sends bad request - server honestly report about that

**Comment by AlexeyGirin** [comment]
Not a bug - we send wrong request to server - server returns error (you have an error on client side - 4xx)
