### ISSUE TITLE
CDX: Dashed bonds type from ChemDraw are changed to Single Down bonds

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1886]
**Steps to Reproduce**
1. Micro
2. Open ChemDraw CDX file 
[Super1.zip](https://github.com/epam/Indigo/files/14803233/Super1.zip)

![image](https://github.com/epam/Indigo/assets/161723514/4e9d863a-f0f9-45ca-bc8a-70dc99df8961)

**Actual behavior**
Dashed Bonds are changed to Single Down bonds
![image](https://github.com/epam/Indigo/assets/161723514/ca3d0de0-2118-4fe1-b174-406f0b1f6387)

**Expected behavior**
Dashed Bonds from ChemDraw can be visible as Hydrogen bond (?).
![image](https://github.com/epam/Indigo/assets/161723514/d699cfa5-0574-4b86-a421-ed7647aaf67e))

**Environment details:**
• OS: Windows 10 Pro (version 22H2) x64
• Browser: Сhrome
• Version: (122.0.6261.95) x64

[Version 2.20.0-rc.2](https://lifescience.opensource.epam.com/ketcher/index.html)
Build at 2024-03-27; 08:30:51
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.19.0-rc.2.0-g6c0e3fecf-x86_64-linux-gnu-11.2.1

**Comment by AliaksandrDziarkach** [comment]
This is not a bug.
This is according to documentation:
![image](https://github.com/epam/Indigo/assets/18146690/e83dd2c4-c1b8-45ab-b89b-0dbc7f49dd11)
