### ISSUE TITLE
Import of modified IDT monomers

### ISSUE THREAD

**Issue by olganaz** [epam/Indigo#1899]
**Background**
In IDT notation modified sequences represented as a plain strings with a combination of standard and modified monomers.
Standard monomer `[s]<Base>[*]` is nucleotides with the same configurations as supported in Ketcher.
Modified monomer `/<pos><Identifier>/[*]` could be recognized as one of the following: 
 - Known nucleotide with defined submonomers (RNA preset) from Ketcher library
 - Known nucleotide with defined structure, but with undefined submonomers (unsplit nucleotide) or CHEM.
 - CHEM with unknown structure (unresolved monomer)
 
This task covers only import of modified IDT monomers.

**Requirements**
1. The system should interpret the following `/<pos><Identifier>/[*]` as the IDT alias of monomer from Ketcher library and import corresponding monomer.
 2. If there is no monomer with corresponding alias in a library, then system should Import IDT monomer as monomer with IDT alias only (no structure)

3. The system should check the position of the monomer in a chain according to `pos`  in IDT alias:
      -  ` 5 `- at the 5' end (the first monomer in a chain)
      -  ` i `- inside the chain 
      -  `3` - at the 3' end (the last monomer in a chain)
      
      In case if position indicator in IDT code contradicts real position of the monomer in the chain, this should be treated as format error and import should fail with appropriate error message: 
_Position of monomer \<IDT id\> in sequence contradicts its code_
4. When `*` is implied to modified IDT monomer, system should check also whether RNA preset with IDT alias `/<pos><Identifier>/`  exists in a library
       - if there is an RNA preset with IDT alias `/<pos><Identifier>/` then `/<pos><Identifier>/*` should be imported as RNA preset, in which phosphate (P) is  changed to Phosphorothioate (sP)
![Import IDT_modified phosphate](https://github.com/epam/Indigo/assets/143799055/9f93d621-032a-45e7-80f4-22e0b2c720af)

5. The bonds between monomers should be established from R2 attachment point of the first monomer to R1 attachment point of the second monomer. 
      
**Examples**

- `/52MOErA/*/i2MOErC/*/32MOErT/`
<img width="350" src="https://github.com/epam/Indigo/assets/143799055/230a198a-a778-4463-b3ba-a5c2d3cd9eed">

- `/5Phos/ACG/3Phos/`
<img width="500" src="https://github.com/epam/Indigo/assets/143799055/c0f06c2e-0919-4595-978e-ff5863ec904c">

**Comment by AlexeyGirin** [comment]
Verified.

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

**Comment by AlexeyGirin** [comment]
Updated logic approved by @ljubica-milovic 

<img width="421" height="568" alt="Image" src="https://github.com/user-attachments/assets/24db2b86-ae68-4bbf-aec4-0e2aaf685401" />
