### ISSUE TITLE
Receive monomer library from Ketcher upon import/export IDT notation

### ISSUE THREAD

**Issue by olganaz** [epam/Indigo#1901]
**Background**
Indigo should receive monomer library from Ketcher to be able to look for IDT aliases of monomers. 

**Solution**

**Alternatives**

**Additional context**

**Comment by AlexeyGirin** [comment]
Verified.

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
