### ISSUE TITLE
Introduce IDT alias for monomers and RNA presets in Ket format

### ISSUE THREAD

**Issue by olganaz** [epam/Indigo#1903]
**Background**
To support IDT format import/export it needs to add some relations between monomers in Ketcher library and IDT library.

**Solution**
It needs to introduce IDT alias field to monomer and rna templates in ketcher library according to ket specification.
IDT alias should be also stored in monomer model to have an access to it during the export/import in future.
One monomer or RNA preset could have multiple IDT aliases.
IDT alias should contain the name of IDT monomer without '/' symbols. 

**Alternatives**

**Additional context**

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/Indigo/assets/26869421/4ddf60c6-7c20-4cac-996a-5a6679317551)

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
