### ISSUE TITLE
Support unresolved IDT monomers (no structure, IDT only)

### ISSUE THREAD

**Issue by olganaz** [epam/Indigo#1912]
**Background**
If user imports modified RNA in IDT notation which contains monomers not found in Monomer library, this should not be interpreted as an error. There should be possible to load such monomers from IDT and KET formats and save to these formats.

**Requirements**
1. If there is no monomer with corresponding alias in a library, then system should Import IDT monomer as monomer with IDT alias only (no structure)
2. Attachment points
4 attachment points should be available for this type of monomers: R1/R2 - backbone (default connection), R3/R4 - sidechain
3. Attempt to save macromolecules with unknown monomers to file formats other than IDT and KET should result in error.

**Comment by AlexeyGirin** [comment]
Verified.

![image](https://github.com/epam/Indigo/assets/26869421/9977963b-4b51-421b-b6ce-ad56fb50520e)

Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
Indigo Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
Win 10
Chrome Version 126.0.6478.127 (Official Build) (64-bit)
