### ISSUE TITLE
Red-black tree key not found

### ISSUE THREAD

**Issue by DongElkan** [epam/Indigo#193]
Hi,

I’m using Indigo on Windows 10 with Python 3.7.2
I created two classes: one is `Matcher` to build match methods based on Indigo’s `substructureMatcher` and `exactMatch` methods; the other is a general class `general` inherites `Matcher` class for processing the matched groups.

When I pass the target molecular IndigoObject `mol` from child `general` class to parent `Matcher` class, `IndigoException` raised when I call `matcher = idg.substructureMatcher(mol)`as 
`core: can not access object #1477: red-black tree: at (): key not found`. It’s surprising that when I run different times, the code number (#1477 here) changed.

When I directly call `matcher = idg.substructureMatcher(mol)` in class `general`, or create molecular object in `Matcher` class by `idg.loadMolecule` using SMILES passed to the class instead of IndigoObject, it works.

I tested this code at different part of my codes, seems the error raised was because I passed the `mol` object to the parent class, and something changed in this argument pass.

Interestingly, when I create the two classes directly in Python’s IDE, passing the object between classes then calling `matcher = idg.substructureMatcher(mol)` still works. The exception raised when I save the two classes to different Python files and use `import` to import `Matcher` to the module where class `general` located.

Any clue?

**Comment by khyurri** [comment]
@DongElkan
Could you please share code example to reproduce the bug? 

Usually exception `can not access object #1477: red-black tree: at (): key not found` raises when developer works with different `Indigo` instances.

**Comment by mkviatkovskii** [comment]
Dear @DongElkan,
We reworked internal objects handling in Indigo, and most probably fixed this issue. I'm closing it, please feel free to reopen it if the problem still exists in new versions of Indigo.
