### ISSUE TITLE
Fix error message in the SequenceLoader for an invalid sequence

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1960]
**Expected behavior**
error message for all sequence format:
"SEQUENCE loader: Invalid symbols in the sequence:"

**Actual behavior**
"SEQUENCE loader: SequenceLoader::loadSequence(), Invalid symbols in the sequence:"
"SEQUENCE loader: SequenceLoader::loadIdt(), Invalid symbols in the sequence:"
"SEQUENCE loader: SequenceLoader::loadFasta(), Invalid symbols in the sequence:"

**Comment by AlexeyGirin** [comment]
Verified.
Windows 10
Chrome Version 125.0.6422.113 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.2 Build at 2024-05-31; 10:48:44
Indigo Toolkit Version 1.21.0-dev.5.2-g994bdab98-x86_64-linux-gnu-11.2.1

![image](https://github.com/epam/Indigo/assets/26869421/7ad3623a-7fcb-4466-a87c-c749b4f0b6e1)
