### ISSUE TITLE
Can't save KET with nameless superatom

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#1972]
**Steps to Reproduce**
1. Convert attached KET-files to KET
 [kets.zip](https://github.com/epam/Indigo/files/15462146/kets.zip)

**Expected behavior**
Files converted

**Actual behavior**
Exception appears

**Comment by AlexeyGirin** [comment]
Verified.
Windows 10
Chrome Version 125.0.6422.113 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.2 Build at 2024-05-31; 10:48:44
Indigo Toolkit Version 1.21.0-dev.5.2-g994bdab98-x86_64-linux-gnu-11.2.1
![image](https://github.com/epam/Indigo/assets/26869421/7fe6e1f1-46fe-4a66-a0b2-c6c037eda9f4)
