### ISSUE TITLE
Preview: User can save IDT with 5' phosphate but cannot open this file again.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1974]
**Steps to Reproduce**

1. Switch to Macro 
2. Open ket file
[ketcher (50).zip](https://github.com/epam/Indigo/files/15468640/ketcher.50.zip)

![image](https://github.com/epam/Indigo/assets/161723514/6de789dd-91d3-46d3-acbc-fce09e987f21)

3.Save to IDT format
![image](https://github.com/epam/Indigo/assets/161723514/841f279d-3fc6-4781-8b1c-c106632c6f0d)

4. Try to open this file
[ketcher (2).zip](https://github.com/epam/Indigo/files/15468724/ketcher.2.zip)

**Actual behavior**
Cannot open IDT with /5Phos/, _but can open with /3Phos/ ( rUrA*rUrA/3Phos/)_

![image](https://github.com/epam/Indigo/assets/161723514/31972a22-98be-4391-99d9-d65f622c1199)

**Expected behavior**
User should be able to open from clipboard or from file the IDT with /5Phos/ as with /3Phos/,
for example /5Phos/rUrA*rUrA/3Phos/

<img width="630" alt="5-3 phosphates2" src="https://github.com/epam/Indigo/assets/161723514/e1bf6104-8c7a-426b-b47f-839c71edd1de">

Tasks:
- https://github.com/epam/ketcher/issues/4310
- https://github.com/epam/Indigo/issues/1899
- https://github.com/epam/Indigo/issues/1900
- https://github.com/epam/Indigo/issues/1588
- https://github.com/epam/Indigo/issues/1654

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)

CI version:
Ketcher Version 2.22.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.21.0-dev4

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/Indigo/assets/26869421/d818e362-01e3-4c3d-84b8-130265f994d5)

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10
