### ISSUE TITLE
Preview: Open an IDT file with a "*" character if the "*" is only between nucleotides (RNA presets or unsplit nucleotides)

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1978]
**Steps to Reproduce**

1. Switch to Macro 
2. Open from Clipboard
3.  Add IDT sequence 
`/52MOErG/*/i2MOErG/*/3Phos/`

4.Select IDT >> Open 
 
![Can MOE OPen](https://github.com/epam/Indigo/assets/161723514/a41ac9cd-fbec-453a-9c38-eb00e694e4fa)

5. Save >> Select IDT >> Try to Save structure to IDT format

**Actual behavior**
User **cannot Save** the next sequences to IDT - **it's OK**
User **can** **Open** the next IDT sequences - **it's error**;
`/52MOErG/*/i2MOErG/*/3Phos/ `
OR 
`/5Phos/*/i2MOErG/*/3Phos/`

**Expected behavior**
The user should be able to open an IDT file with a `"*"` character if the `"*"` is 
only between **nucleotides or nucleosides** (RNA presets or unsplit nucleotides).

And Error message should appear while user try to **Open** the next examples:
`/52MOErG/*/i2MOErG/*/3Phos/ `
OR 
`/5Phos/*/i2MOErG/*/3Phos/`

![Cannot MOE Save](https://github.com/epam/Indigo/assets/161723514/525e47d0-c6b4-444c-8840-9b492577af4a)

Tasks:
- https://github.com/epam/ketcher/issues/4310
- https://github.com/epam/Indigo/issues/1899
- https://github.com/epam/Indigo/issues/1900
- https://github.com/epam/Indigo/issues/1588
- https://github.com/epam/Indigo/issues/1654
Issue
- https://github.com/epam/Indigo/issues/1974

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)

CI version:
Ketcher Version 2.22.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.21.0-dev4

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/Indigo/assets/26869421/59ce0fab-de0b-4e60-9912-d78616fc6b95)

 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

**Comment by AlexeyGirin** [comment]
Test case added to automation table
