### ISSUE TITLE
Preview: IDT sequence with leading or trailing spaces will not open.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1979]
**Steps to Reproduce**

1. Switch to Macro 
2. Open from Clipboard
3.  Add IDT sequence 
`/52MOErA/*/i2MOErC/*/i2MOErG/*G*+A*mT*A*T*rA*G*/i2MOErG/*/32MOErT/`

4.Select IDT
5. Add break-spaces to start or end of sequences
6. try to Add to Canvas
 

**Actual behavior**
IDT sequence with leading or trailing spaces will not open.
![image](https://github.com/epam/Indigo/assets/161723514/2ce139c6-b4a9-4c61-a40c-98b7174c0078)

**Expected behavior**
IDT sequence with leading or trailing spaces will not open.
leading or trailing spaces should be removed

Tasks:
- https://github.com/epam/ketcher/issues/4310
- https://github.com/epam/Indigo/issues/1899
Issue
- https://github.com/epam/Indigo/issues/1974
- https://github.com/epam/Indigo/issues/1978

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)

CI version:
Ketcher Version 2.22.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.21.0-dev4

**Comment by AlexeyGirin** [comment]
Test cases added to autotests table
