### ISSUE TITLE
Cannot open some expected IDT.

### ISSUE THREAD

**Issue by NadezhdaPeskun** [epam/Indigo#1982]
**Steps to Reproduce**

1. Switch to Macro 
2. Open >> Try to Open from clipboard the next IDTs
```
/52MOErA/
/i2MOErA/
/52MOErA//i2MOErA/
/52MOErA/*/i2MOErA/
/i2MOErA//32MOErA/
/i2MOErA/*/32MOErA/

```

**Actual result:**
Cannot open some IDTs
**Errors >>
1) `/52MOErA/`
<img width="518" alt="image" src="https://github.com/epam/Indigo/assets/161723514/4d3f2040-3740-4d4d-a2c0-4e24e3e14900">

2)` /i2MOErA/`
<img width="496" alt="image" src="https://github.com/epam/Indigo/assets/161723514/8549483e-0bf3-49ef-b4cd-22db55f67bd6">

3) `/52MOErA//i2MOErA/ and for /52MOErA/*/i2MOErA/`
<img width="511" alt="image" src="https://github.com/epam/Indigo/assets/161723514/33ce7ef6-e596-461e-92f4-9d18638f6a21">

4) `/i2MOErA/*/32MOErA/`
<img width="500" alt="image" src="https://github.com/epam/Indigo/assets/161723514/6b0a1a02-781c-4070-87c0-ec481560fb42">

**Expected behavior**
<img width="350" src="https://github.com/epam/Indigo/assets/143799055/0b860764-266e-49a4-887f-31e75dd9d5c0">
<img width="350" src="https://github.com/epam/Indigo/assets/143799055/eee14f7f-3f02-4b65-8e4f-c1e5170004fc">
<img width="500" src="https://github.com/epam/Indigo/assets/143799055/f6d9a667-0f5e-4eb9-a38d-0d32f4021e2f">

<img width="350" src="https://github.com/epam/Indigo/assets/143799055/ac6c0324-4719-46bc-a2eb-59df410a99a0">

**Opened as expected:**
```
/32MOErA/
/52MOErA/*/32MOErC/
/52MOErA//32MOErC/
/52MOErA//i2MOErC//32MOErT/ 
/52MOErA/*/i2MOErC/*/32MOErT/ 
/52MOErA/*/i2MOErC/*/i2MOErG/*G*+A*mT*A*T*rA*G*/i2MOErG/*/32MOErT/ 
```

Related with:
- https://github.com/epam/Indigo/issues/1966

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)

CI version:
Ketcher Version 2.22.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.21.0-dev4

**Comment by AlexeyGirin** [comment]
Not fixed.
All errors are in place.
![image](https://github.com/epam/Indigo/assets/26869421/76acc417-8aca-450b-bbe0-2b2631b4386f)

 - Indigo Toolkit 1.21.0-rc.2.0-g1eba70228-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.7 Build at 2024-06-20; 18:42:41
 - Chrome Version 126.0.6478.62 (Official Build) (64-bit)
 - Windows 10

**Comment by AlexeyGirin** [comment]
Not fixed.
![image](https://github.com/epam/Indigo/assets/26869421/cda70ab2-17d3-4a4f-bae6-5135c0aba4df)

**Comment by Zhirnoff** [comment]
![2024-07-03_14h45_22](https://github.com/epam/Indigo/assets/62464241/dbafedcb-6af1-4629-9799-0cbaea6a99b1)
![2024-07-03_14h45_48](https://github.com/epam/Indigo/assets/62464241/dedd46ea-e957-4b6c-87cc-298f07f882fd)
Tested. Bug fixed.
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]

**Comment by AlexeyGirin** [comment]
1.21.0-rc.3

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-04_19h18_56](https://github.com/epam/Indigo/assets/62464241/571b18f5-df5a-46db-ab1c-0d6107369fe6)
![2024-07-04_19h19_23](https://github.com/epam/Indigo/assets/62464241/c21a039c-abc0-40c8-bd72-3c9b8a938e1b)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.8]
**Indigo version** 
[Version 1.21.0-rc.3]
