### ISSUE TITLE
Error message is wrong if in case if position indicator in IDT code contradicts real position of the monomer in the chain

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1984]
**Steps to Reproduce**
1. Load following IDT string using Paste from Clipboard way: `/32MOErC/*/32MOErT/`
![image](https://github.com/epam/Indigo/assets/26869421/27b46cb8-5da0-4c91-86da-fefd921491b5)

**Actual behavior**
System throws an error: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: IDT alias 32MOErC not found at five-prime end position.'
![image](https://github.com/epam/Indigo/assets/26869421/414014c3-0aa2-4ccf-afee-f00442eb4c75)

**Expected behavior**
System throws an error: Position of monomer 1 in sequence contradicts its code
![image](https://github.com/epam/Indigo/assets/26869421/761ada87-8148-47e5-9beb-a981372c40a1)

As per requirement:

>   In case if position indicator in IDT code contradicts real position of the monomer in the chain, 
>   this should be treated as format error and import should fail with appropriate error message: 
> _Position of monomer \<IDT id\> in sequence contradicts its code_

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/Indigo/issues/1899

**Comment by AnnaKosol** [comment]
The problem is still reproduced (the code is missing in the release branch for version 2.23.0-rc.1)
<img width="1010" alt="Снимок экрана 2024-07-03 в 14 45 41" src="https://github.com/epam/Indigo/assets/174325443/cc720926-a4d9-48c7-aee8-c671bd0a2af2">
**Expected result:**
System throws an error: Position of monomer 1 in sequence contradicts its code

**Comment by AlexeyGirin** [comment]
Verified.
Agreed with @olganaz and @ljubica-milovic that currect implementation (i.e. error message) is acceptable
![image](https://github.com/epam/Indigo/assets/26869421/59c7bc5a-478d-480b-842e-cd910055ce17)
