### ISSUE TITLE
Error message in case of no IDT name for monomer is wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1985]
**Steps to Reproduce**
1. Switch to Macro
2. Load from file: [Error message in case of no IDT name for monomer is wrong.zip](https://github.com/user-attachments/files/15592500/Error.message.in.case.of.no.IDT.name.for.monomer.is.wrong.zip)
OR create on the canvas followng configuration:
![image](https://github.com/epam/Indigo/assets/26869421/4c50e8e5-46b7-4457-92fc-1c5f48f9208d)
3. Try to export canvas to IDT

**Actual behavior**
System throws an error: Convert error! Sequence saver: IDT alias for group sugar:5formD base:form5C phosphate:cm not found.
![image](https://github.com/epam/Indigo/assets/26869421/1e19d576-f20c-43d7-8e45-c46fabc7d4c5)

**Expected behavior**
System throws an error: This molecule has unsupported monomer and couldn't be exported to IDT notation
![image](https://github.com/epam/Indigo/assets/26869421/6c871fa7-6ed2-4131-b84d-0909008b5070)

As per [requirement](https://github.com/epam/Indigo/issues/1900):

>   If there is no IDT name for monomer, system should display Error message 
>  "This molecule has unsupported monomer and couldn't be exported to IDT notation".

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/Indigo/issues/1900

**Comment by Zhirnoff** [comment]
Automated.

**Comment by AliaksandrDziarkach** [comment]
Discussed with @olganaz and decided that current error message is more specific and it is ok.

**Comment by AlexeyGirin** [comment]
Ok.
