### ISSUE TITLE
Convert api does not recognise format during autodetection

### ISSUE THREAD

**Issue by rrodionov91** [epam/Indigo#1989]
**Steps to Reproduce**
1. Send IDT string (f.e. `/52MOErA/*/i2MOErC/*/32MOErT/`) to convert api without `"input_format": "chemical/x-idt"` parameter

**Expected behavior**
Indigo converts string in any macromolecules format supported on ketcher side(MolV3000, Sequence, Fasta, IDT, HELM) to KET format. In case if it is not possible to identify format (f.e. ACGT could be interpreted as IDT as well as Sequence or Fasta) - use the simplest one.

**Actual behavior**
Indigo returns error:
<img width="696" alt="image" src="https://github.com/epam/Indigo/assets/14859362/568deccb-bc03-4374-a3e5-b44e4c4ccbc0">

**Environment details:**
 - Back-end version - Indigo 1.21.0-rc.1
 - [Optional] Ketcher 2.22.0-rc.3

**Comment by AlexeyGirin** [comment]
Verified.

**Versions**
- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)
- Win10
