### ISSUE TITLE
Micro and macro structures connected through attachment points cannot be saved in CML format in micro mode

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1990]
**Summary**
Micro and macro structures connected through attachment points cannot be saved in CML format in micro mode

**Steps to Reproduce**
1. Open Ketcher.
2. Draw a benzene ring
3. Add an attachment point to the benzene ring via right click menu
4. Switch to Macro mode and connect attachment point to a macro structure
5. Switch to Micro mode
6. Save structure in CML format

If it is not possible to draw the structure, then you can open the prepared file (you just need to open it in macro mode and then switch to micro mode): 
[ketcher (53).zip](https://github.com/user-attachments/files/15620336/ketcher.53.zip)

**Expected behavior**
Micro and macro structures connected through attachment points can be saved in CML format in micro mode

**Actual behavior**
Micro and macro structures connected through attachment points cannot be saved in CML format in micro mode
![2024-06-06_15h28_47](https://github.com/epam/Indigo/assets/62464241/ca955193-4722-499a-bda4-f73813f74bde)
![2024-06-06_15h29_25](https://github.com/epam/Indigo/assets/62464241/ae67c575-18fc-4446-b48f-8896869ef93c)
![2024-06-06_15h29_33](https://github.com/epam/Indigo/assets/62464241/3744db1f-c7f7-4f1d-b445-28a33bc5367d)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
**Indigo version** 
[Version 1.21.0-rc.1]

**Refers to feature:** https://github.com/epam/ketcher/issues/4530

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. Micro and macro structures can be saved in CML format but cannot be opened. Registered bug: https://github.com/epam/Indigo/issues/2084
![2024-07-04_15h59_51](https://github.com/epam/Indigo/assets/62464241/a39f4afd-561c-4a60-9f21-b31da5e2f8a8)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]

**Comment by AlexeyGirin** [comment]
1.21.0-rc.3

**Comment by Zhirnoff** [comment]
Tested. Bug for saving is fixed but when we loadind it a mess. We have bug for it for Indigo 1.22.0-rc.1 but with another behaviour https://github.com/epam/Indigo/issues/2084
![2024-07-04_19h05_08](https://github.com/epam/Indigo/assets/62464241/fd0fffba-2273-4cd2-bb99-30bc78df727a)
**Saved CML file:** [ketcher (5).zip](https://github.com/user-attachments/files/16101092/ketcher.5.zip)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.8]
**Indigo version** 
[Version 1.21.0-rc.3]
