### ISSUE TITLE
Micro and macro structures connected through attachment points cannot be saved in Extended SMILES format in micro mode

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1992]
**Summary**
Micro and macro structures connected through attachment points cannot be saved in Extended SMILES format in micro mode

**Steps to Reproduce**
1. Open Ketcher.
2. Draw a benzene ring
3. Add an attachment point to the benzene ring via right click menu
4. Switch to Macro mode and connect attachment point to a macro structure
5. Switch to Micro mode
6. Save structure in Extended SMILES format

If it is not possible to draw the structure, then you can open the prepared file (you just need to open it in macro mode and then switch to micro mode): 
[ketcher (53).zip](https://github.com/user-attachments/files/15620336/ketcher.53.zip)

**Expected behavior**
Micro and macro structures connected through attachment points can be saved in Extended SMILES format in micro mode

**Actual behavior**
Micro and macro structures connected through attachment points cannot be saved in Extended SMILES format in micro mode
![2024-06-06_16h05_39](https://github.com/epam/Indigo/assets/62464241/f3170031-05aa-4224-8e55-d4b4d1404f96)
![2024-06-06_16h06_55](https://github.com/epam/Indigo/assets/62464241/c1df2176-a382-4d11-8c0b-a5593de11f16)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
**Indigo version** 
[Version 1.21.0-rc.1]

**Refers to feature:** https://github.com/epam/ketcher/issues/4530

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-07-03_14h54_19](https://github.com/epam/Indigo/assets/62464241/91d208cb-998d-4a4b-aba6-a75d778614de)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]

**Comment by AlexeyGirin** [comment]
Have to be checked in version 1.21.0-rc.3

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. File saves in Extended SMILES and open from it.
![2024-07-04_19h27_24](https://github.com/epam/Indigo/assets/62464241/9433dfc5-1562-4f34-b7be-57494af91588)
![2024-07-04_19h27_42](https://github.com/epam/Indigo/assets/62464241/526726df-d9f5-4c87-824f-0b2ced9b78db)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.8]
**Indigo version** 
[Version 1.21.0-rc.3]
