### ISSUE TITLE
Micro and macro structures connected through attachment points cannot be opened after save in CDX and Base 64CDX format in micro mode

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#1994]
**Summary**
Micro and macro structures connected through attachment points cannot be opened after save in CDX and Base 64CDX format in micro mode

**Steps to Reproduce**
1. Open Ketcher.
2. Draw a benzene ring
3. Add an attachment point to the benzene ring via right click menu
4. Switch to Macro mode and connect attachment point to a macro structure
5. Switch to Micro mode
6. Save structure in CDXML format
7. Open saved file

If it is not possible to draw the structure, then you can open the prepared file (you just need to open it in macro mode and then switch to micro mode): 
[ketcher (53).zip](https://github.com/user-attachments/files/15620336/ketcher.53.zip)

**Actual behavior**
Micro and macro structures connected through attachment points cannot be opened after save in CDX and Base 64CDX format in micro mode

![2024-06-06_16h24_23](https://github.com/epam/Indigo/assets/62464241/d8311b90-5ea5-44d7-b78a-a5174c522744)
![2024-06-06_16h24_33](https://github.com/epam/Indigo/assets/62464241/2266bb67-40f0-494c-b800-b05e59b41003)
![2024-06-06_16h24_41](https://github.com/epam/Indigo/assets/62464241/55921312-a6bc-40d5-90e9-2e3c18481ba4)

**Expected behavior**
Micro and macro structures connected through attachment points can be opened after save in CDX and Base 64CDX format in micro mode
![2024-06-06_14h02_50](https://github.com/epam/Indigo/assets/62464241/eb38e10e-1ea3-42ed-bd56-a1a9bddf4d14)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.2]
**Indigo version** 
[Version 1.21.0-rc.1]

**Refers to feature:** https://github.com/epam/ketcher/issues/4530

**Attached saved files:**
[ketcherCDX (1).zip](https://github.com/user-attachments/files/15628319/ketcherCDX.1.zip)

**Comment by AnnaKosol** [comment]
When opening a file with a cdxml format, a modal window with an error is displayed
<img width="1042" alt="Снимок экрана 2024-07-03 в 16 11 13" src="https://github.com/epam/Indigo/assets/174325443/4770d5e0-33b8-4cde-bbb7-1927e6dee87a">
When opening a file with a b64cdx format, a modal window with an error is displayed
<img width="928" alt="Снимок экрана 2024-07-03 в 16 14 26" src="https://github.com/epam/Indigo/assets/174325443/f90515ff-b69c-458f-b9d0-ced039e63a6d">

**Versions:**
Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 09:03:38
Indigo Version 1.21.0-rc.1.0-g9194599b2-x86_64-linux-gnu-11.2.1
MacOs Sonoma version 14.5
Chrome Version 126.0.6478.127 (Официальная сборка), (arm64)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/epam/Indigo/assets/26869421/64e3db04-fde2-4272-ace0-7de7a2f48857)

- Ketcher Version 2.22.0-rc.9 Build at 2024-07-04; 15:58:14
- Indigo Toolkit Version 1.21.0-rc.3.0-g1570d3f9f-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
