### ISSUE TITLE
Export to IDT doesn't work at all for remote indigo

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#1997]
**Steps to Reproduce**
1. Load from file: [Export to IDT doesn't work at all for remote indigo.zip](https://github.com/user-attachments/files/15738539/Export.to.IDT.doesn.t.work.at.all.for.remote.indigo.zip)
Or create manually following configuration:
![image](https://github.com/epam/Indigo/assets/26869421/30c9ad18-383a-43b1-9884-c3baf99a0a11)
2. Press Save button and choose IDT format

**Actual behavior**
System throws an error: Convert error! Unexpected token '<', "<html><h"... is not valid JSON
![image](https://github.com/epam/Indigo/assets/26869421/bd067cf6-3757-40e6-b053-360791f65e3d)
![image](https://github.com/epam/Indigo/assets/26869421/4fd410a6-dcff-4b3f-a647-eb5a7ba724b3)
[rc.test.lifescience.opensource.epam.com-1717760901110.log](https://github.com/user-attachments/files/15738565/rc.test.lifescience.opensource.epam.com-1717760901110.log)

**Expected behavior**
No exceptions. 

**Versions:**
 - Indigo Toolkit Version 1.21.0-rc.1.0-g9194599b2-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.2 Build at 2024-06-03; 18:43:00
 - Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 - Windows 10

Issue found while testing https://github.com/epam/Indigo/issues/1900

**Comment by AliaksandrDziarkach** [comment]
This is the nginx config issue.

**Comment by AlexeyGirin** [comment]
Waiting for Alex fix.

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/173075d9-693f-4f05-94d0-3a2ecd7c979a)

 - Indigo Toolkit 1.21.0-rc.2.0-g1eba70228-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.7 Build at 2024-06-20; 18:42:41
 - Chrome Version 126.0.6478.62 (Official Build) (64-bit)
 - Windows 10
