### ISSUE TITLE
Exporting a CDX file to ChemDraw loses information about charge on atoms

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2000]
**Summary**
Exporting a CDX file to ChemDraw loses information about charge on atoms

**Steps to Reproduce**
1. Put on the canvas following SMILE: `N#Cc1ccccc1.O=C([O-])O.[Na+]>>C#Cc1ccccc1`
2. Save to CDX format file
3. Open it in ChemDraw

**Expected behavior**
Exporting a CDX file to ChemDraw does not lose information about charge on atoms
![2024-06-12_14h37_38](https://github.com/epam/Indigo/assets/62464241/268e66d1-083e-4d2f-9f47-7087bacda8a8)

**Actual behavior**
Exporting a CDX file to ChemDraw loses information about charge on atoms
![2024-06-12_14h37_13](https://github.com/epam/Indigo/assets/62464241/73959f21-1f4a-4325-890a-1783a4a7c748)

**Attached saved in Ketcher CDX file:**
[ketcher (21).zip](https://github.com/user-attachments/files/15804135/ketcher.21.zip)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.4]
**Indigo version** 
[Version 1.21.0-rc.1]

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/epam/Indigo/assets/26869421/56b335d2-9ad1-4d1c-adf3-e21b0053f712)

 - Indigo Toolkit 1.21.0-rc.2.0-g1eba70228-wasm32-wasm-clang-19.0.0
 - Ketcher Version 2.22.0-rc.7 Build at 2024-06-20; 18:42:41
 - Chrome Version 126.0.6478.62 (Official Build) (64-bit)
 - Windows 10
