### ISSUE TITLE
Errors occur when trying to save a macro structure connected to a micro structure to MOL V3000

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2004]
**Steps to Reproduce**
1. Open prepared test file [file-for-test.zip](https://github.com/user-attachments/files/15826249/file-for-test.zip)
2. Switch to Macro mode and connect macro structure to micro

**Case1**
Save in Macro mode to MOL V3000 
![2024-06-13_20h40_06](https://github.com/epam/ketcher/assets/62464241/e3a78f8b-4505-4020-9391-af749bf3a068)

**Case2**
Save in Micro mode to MOL V3000 

![2024-06-13_20h43_37](https://github.com/epam/ketcher/assets/62464241/b7a5d6b3-fbe5-4329-8c4d-8a24d1aeb57f)

**Actual behavior**
Errors occur when trying to save a macro structure connected to a micro structure

**Expected behavior**
Errors do not appear when saving in these formats

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.5]
**Indigo version** 
[Version 1.21.0-rc.1]

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-03_15h01_42](https://github.com/epam/Indigo/assets/62464241/7d899753-6214-4cae-a2d0-a4e2e13adc0d)
![2024-07-03_15h01_54](https://github.com/epam/Indigo/assets/62464241/ac25bf42-3dc2-4243-95d9-0c5f73e92030)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.1]
**Indigo version** 
[Version 1.22.0-rc.1]

**Comment by AlexeyGirin** [comment]
1.21.0-rc.3

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-03_15h01_42](https://github.com/epam/Indigo/assets/62464241/7d899753-6214-4cae-a2d0-a4e2e13adc0d)
![2024-07-03_15h01_54](https://github.com/epam/Indigo/assets/62464241/ac25bf42-3dc2-4243-95d9-0c5f73e92030)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.22.0-rc.8]
**Indigo version** 
[Version 1.21.0-rc.3]
