### ISSUE TITLE
Import/Export of variant monomers from Fasta/Sequence

### ISSUE THREAD

**Issue by olganaz** [epam/Indigo#2015]
**Background**
Sometimes users need to register oligonucleotides containing randomized or "mixed" bases. It means that on the defined position a variant monomer could occur.
Variant monomer is a monomer which can be used instead of another monomer within listed variants.

**Requirements**
In addition to the requirements for import/export  Sequences [#1426](https://github.com/epam/Indigo/issues/1426) and Fasta [#1755](https://github.com/epam/Indigo/issues/1755) the following symbols should be supported for:

-  RNA and DNA
      <img width="200" src="https://github.com/epam/Indigo/assets/143799055/a6c77901-9804-4a1c-b719-c035c3459cb0">

  If one of the following base symbols is entered (first column), this means that the base in the nucleotide can be represented by any of the bases indicated in the second column (in equimolar ratio)

- Peptide monomers
When importing `X` should be interpreted as variant monomer which could be any of unmodified peptide monomer X={A, C, D, E, F, G, H, I, K, L, M, N, P, Q, R, S, T, V, W, Y}
When exporting symbol 'X' could be used  both for variant monomers and for peptide monomers with natural analogue 'X'

**Comment by ljubica-milovic** [comment]
In addition to X as a symbol that represents "any amino acid", following symbols for Peptides should be supported:

| Symbol | Symbols of amino acid represented by it|
|---|---|
| B | D, N |
| J | L, I |
| Z | E, Q |

**Comment by ljubica-milovic** [comment]
By `X` (any amino acid), in addition to the 20 amino acids listed above two more are to be added to the list. 
X = 
[ A, C, D, E, F, G, H, I, K, L, M, N, P, Q, R, S, T, V, W, Y
and
O, U]

**Comment by AlexeyGirin** [comment]
Verified with issues.

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10
