### ISSUE TITLE
PNG image support in CDX/CDXML

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2028]
As a **User**, I want the ability **to save and load images in the CDX/CDXML format** so that I can utilize and share my work with other applications or users that use these formats.

**Acceptance Criteria:**
There should be possible to save chemical structure with embedded PNG images to CDX/CDXML files and load such structures from these formats.

**Comment by Zhirnoff** [comment]
Tested. We have identified some bugs attached to this issue.


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
