### ISSUE TITLE
PNG Image rendering in Indigo for SVG and PNG export

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2029]
As a **User**, I want the ability **to save images in the supported graphical formats** (SVG and PNG) so that I can utilize and share my work with other applications or users.

**Acceptance Criteria:**

1. A user should be able to save the current state of the canvas, including any inserted images, the supported graphical formats. This can be achieved through a 'Save Structure' function. Currently we support SVG and PNG formats.
2. The saved image should accurately represent the state of the canvas at the time of saving, including the placement, size, and orientation of all elements and images.

![Image](https://github.com/epam/Indigo/assets/173041434/8c859434-c8b1-453c-9bab-fcf8fa0443f7)

3. We support image formats PNG and SVG.

**Comment by ivanmaslow** [comment]
Confirmed with DM that recognition of PNG and SVG images (open from image) which contain images (PNG, SVG) with elements is out of scope

**Comment by ivanmaslow** [comment]
SVG Image rendering in Indigo for PNG and SVG are in the scope of other tasks:
- https://github.com/epam/Indigo/issues/2161
- https://github.com/epam/Indigo/issues/2162

**Comment by ivanmaslow** [comment]
Exploratory testing is finished on the Remote environment:
- **Ketcher**: [Version 2.24.0-rc.1] Build at 2024-08-06; 19:25:43
- **Indigo**: Version 1.23.0-rc.1.0-g85f89b8f5-x86_64-linux-gnu-11.2.1
- **OS**: Windows 11 Enterprise
- **Browser**: Chrome Version 124.0.6367.79 (Official Build) (64-bit)

Points below are covered during testing, tests are updated: 
- Verify that PNG images with elements are displayed on preview and can be saved separately/together to PNG/SVG file with the correct positions and layers including cases after moving, scaling, deleting, copying of images

High priority defects related to this feature are fixed:
- https://github.com/epam/Indigo/issues/2173
- https://github.com/epam/Indigo/issues/2183

Defects related to the existing behavior of indigo functions and not related to image changes:
- https://github.com/epam/Indigo/issues/2196
