### ISSUE TITLE
.net core NuGet warnings

### ISSUE THREAD

**Issue by Doidel** [epam/Indigo#203]
As mentioned once before at #140 when using the .net core NuGet package I get the following warning for each DLL:

    Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'bingo.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

(Besides bingo.dll, also for concrt140.dll, indigo-inchi.dll, etc.)
I'm using it on Windows with .NET 5.

I found a possibly related description of why these occur at [this StackOverflow post](https://stackoverflow.com/questions/48122173/warning-when-using-nuget-package-that-contains-native-dll).

The NuGet package still works and I can code with it, it's annoying not to be able to deal with the warnings and according to the linked StackOverflow post it's possibly easy to fix.

Thanks for looking into this!

**Comment by mkviatkovskii** [comment]
Dear @Doidel, thanks for reporting this. I'll take a look at the StackOverflow solution, hopefully it works. .NET core native libs packaging is confusing.

**Comment by mkviatkovskii** [comment]
@Doidel I used this approach and it worked successfully on Windows and Linux, thank you for suggestion.
I am currently preparing the new version for Nuget repository and will notify you when it's ready.

**Comment by mkviatkovskii** [comment]
Dear @Doidel,
New version of Indigo.Net (1.4.1) is already in Nuget. Please let me know if the problem still exists in it.

**Comment by Doidel** [comment]
@mkviatkovskii Warnings are gone, thanks! Much appreciated 👍
