### ISSUE TITLE
Load RDF Format as simple list of reaction

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2030]
As a **User**, I want to have the ability to load my data in RDF format and save it to KET, So that I can easily exchange data with other users that use the same application.

**Acceptance Criteria:**

1. When I choose to load data, the application should provide an option to load RDF files.
2. The application should be able to load RDF files from a specified location.
3. Upon loading an RDF file, the application should convert the RDF data back into the application's native format.
4. The application should properly handle any errors during the load process and display an appropriate error message.
5. We understand reactions from RDF file as plain list of reactions (not hierarchical).

**Comment by yauhen-karmyzau** [comment]
For AC 3: As we discuss, it will be great to have convert reactions from RDF file as plain list of reactions to KET file, however, it's not mandatory, if it will be complex to implement. Assumption, that this operation will be used in any case to save the reaction tree and will bring the value.

**Comment by yauhen-karmyzau** [comment]
Team Agreement: To have product increment, we need to convert **reaction(s) to KET**. We are not expect to properly place all reactions on a canvas, items can be placed one on other or we can draw the first/last reaction.

**Comment by yauhen-karmyzau** [comment]
Team Agreement: We place reactants and reaction products on the canvas within "table" view: X: 0, 200px, 400px, ...; Y: 0, 200px, 400px, ...; reaction arrows are out of scope.

**Comment by yauhen-karmyzau** [comment]
Decision lock: RXN load shouldn’t be affected - stays as it is.

**Comment by ivanmaslow** [comment]
Exploratory testing is completed on the environment in Remote mode:
- **Ketcher** [Version 2.24.0-rc.1] Build at 2024-08-06; 19:25:43
- **Indigo** Version 1.23.0-rc.1.0-g85f89b8f5-x86_64-linux-gnu-11.2.1
 - OS: Windows 11 Enterprise
 - Browser: Chrome, Version 127.0.6533.100 (Official Build) (64-bit)

Points below are covered, tests are updated:
- RDF file is recognized by $RDFILE sign at the first line of doc:
![image](https://github.com/user-attachments/assets/8db90749-8053-4f44-85e1-2020d81a3660)
![image](https://github.com/user-attachments/assets/4be10594-cef5-4429-8348-1b5c8b7ef146)
- RDF file with RXN V2000/V3000 reactions (different reactions 1:0, 0:1, 1:1, 2:2...) can be loaded with correct positions and saved to KET/MOL V2000/V3000 formats as molecules
- RDF file with RXN V2000/V3000 reactions (different reactions 1:0, 0:1, 1:1, 2:2...) can be loaded with correct positions and saved to KET/RXN V2000/V3000 formats after adding of reactions
- Reagents are placed on the left side together and products are on the right side together, an example for 2x2 is below, reactions elements (pluses and arrow) are out of scope:
![image](https://github.com/user-attachments/assets/8b55beeb-8b14-4888-8af3-4df44b48bb72)
- Also, several reactions can be loaded from RDF RXN V2000/V3000 and can be displayed on Canvas as molecules:
![image](https://github.com/user-attachments/assets/51753da1-e9ca-4f2c-9bdc-2f7e7baffea1)
- RDF file with MOL V2000/V3000 cannot be loaded to Canvas, error is displayed (look at defects for more details)

Detected issues are not related to the current implementation but to the existing behavior of recognition of mol and rxn files:
 - https://github.com/epam/Indigo/issues/2194
 - https://github.com/epam/Indigo/issues/2211
 - https://github.com/epam/ketcher/issues/5273

**Comment by ivanmaslow** [comment]
Tests are updated in scope of https://github.com/epam/Indigo/issues/2102, because logic is rewritten
