### ISSUE TITLE
Preview: Unable to save unsplit nucleotides to IDT

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2033]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Open RNA tab - Nucleotides section
3. Put any monomers from that section to the canvas (it was 5AmdA in my case)
4. Save canvas to IDT

**Actual behavior**
System throws an error: Convert error! Sequence saver: Nucleotide '5AmdA' has no IDT alias.
![image](https://github.com/epam/Indigo/assets/26869421/1d54ac9d-c91b-42b6-9cc3-6cd8c2155fe9)

**Expected behavior**
Save should work. Save result should be `/5AmdA/`

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AliaksandrDziarkach** [comment]
Fixed

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/5a028b01-538d-41df-b1bc-090769bf9feb)
- Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
- Indigo Toolkit Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
