### ISSUE TITLE
Preview: We shouldn't allow to export canvas with nucleotides with no natural analog to Sequence format (and FASTA)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2035]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Open RNA tab - Nucleotides section
3. Put `55NitInd` nucleotide from the library on the canvas
![image](https://github.com/epam/Indigo/assets/26869421/3ad5f0ca-77ac-416c-83d0-4fe1276e7c72)

5. Save canvas to Sequence format (or FASTA)

**Actual behavior**
System let user to do that
Sequence:
![image](https://github.com/epam/Indigo/assets/26869421/58843555-1010-435d-ac45-322ce6cd9e92)
FASTA:
![image](https://github.com/epam/Indigo/assets/26869421/a27c44a8-df07-44bb-b84f-966e634ad4b4)

**Expected behavior**
Since we don't support import of monomers with no natural analog (as per https://github.com/epam/Indigo/issues/1466 and https://github.com/epam/Indigo/issues/1755) - we should not allow to export it.
System should throw proper error in that case

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by AlexeyGirin** [comment]
We decide to return Error in such case
(by @AlexanderSavelyev and @vanoprenko )

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-16_14h04_05](https://github.com/user-attachments/assets/7b749795-e4af-4a8d-bb64-831a3acb5811)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.3]
**Indigo version** 
[Version 1.22.0-rc.3]

**Comment by AlexeyGirin** [comment]
Fixed.
![image](https://github.com/user-attachments/assets/2d3bd0c2-8768-4563-9fba-ce4baa7fad26)
- Ketcher Version 2.23.0-rc.3 Build at 2024-07-14; 20:34:10
- Indigo Toolkit Version 1.22.0-rc.3.0-gbb5c51fc2-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)
