### ISSUE TITLE
Preview: Unsplit monomer couldn't be saved to SMILES

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2036]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Open RNA tab - Nucleotides section
3. Put any monomers from that section to the canvas (it was 5AmdA in my case)
![image](https://github.com/epam/Indigo/assets/26869421/36f67fd1-a3d8-403f-b359-db7b7b82f43d)
4. Switch to Micro mode
5. Save canvas to SMARTS

**Actual behavior**
System throws an error: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'RXN loader: bad header {', 'molecule: casting to molecule is invalid'
![image](https://github.com/epam/Indigo/assets/26869421/0546dbc1-57f3-49e1-a6be-f68b660140a5)

**Expected behavior**
`[H]-[#8]-[#6]/[#6]1-[#6](\[#8]-[#15](-[H])(-[#8])=[#8])-[#6]-[#6](/[#7]2-[#6]=[#7]-[#6]3-[#6](-[#7])=[#7]-[#6](-[#7])=[#7]-[#6]=3-2)-[#8]-1`

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-16_13h38_51](https://github.com/user-attachments/assets/f21ae1f9-f31d-4d97-9bc1-31eafeb67f31)
![2024-07-16_13h48_17](https://github.com/user-attachments/assets/b7e67892-419a-485a-bf17-64b26fa666bc)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.21.0-rc.3]
**Indigo version** 
[Version 1.20.0-rc.3]
