### ISSUE TITLE
Preview: Reaction with unsplit monomer couldn't be saved to RXN V2000 format

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2038]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Open RNA tab - Nucleotides section
3. Put any monomers from that section to the canvas (it was 5AmdA in my case)
![image](https://github.com/epam/Indigo/assets/26869421/36f67fd1-a3d8-403f-b359-db7b7b82f43d)
4. Switch to Micro mode
5. Add Arrow to make a reaction
![image](https://github.com/epam/Indigo/assets/26869421/d1b5c268-a1b1-4a96-b97c-c849ab1dbab7)
6. Press Save button (to save to RXN V2000)

**Actual behavior**
System throws an error: Convert error! molfile saver: internal: template atom is not supported in V2000 format
![image](https://github.com/epam/Indigo/assets/26869421/3b1c2e54-4d8b-42be-b9d2-ce4c0952aae4)

**Expected behavior**
No exception. Save works as intended

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4382

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. The file can be saved in RXN V2000 format and loaded.
![2024-07-16_13h56_02](https://github.com/user-attachments/assets/a4f48ef3-f092-4c93-a089-248d43bd8f6e)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.3]
**Indigo version** 
[Version 1.22.0-rc.3]
