### ISSUE TITLE
Wrong sequence if sequence with cycle is saved to FASTA or Sequence file

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2042]
**Steps to Reproduce**
1. Switch to Macro 
2. Open file
[ketcher (modify (1)).zip](https://github.com/epam/ketcher/files/15413934/ketcher.modify.1.zip)

3. Try to save to FASTA of Sequence file

**Actual behavior**
Wrong sequence (GCG) is saved to FASTA or Sequence file  instead of GGC.
![wrong sequence](https://github.com/epam/ketcher/assets/161723514/74b33a78-f5a8-4ce9-bf47-890d9a135182)

![wrong sequence2](https://github.com/epam/ketcher/assets/161723514/c56187b1-8dea-4075-ba09-e5f54c787d19)

**Expected behavior**
Sequence should be GGC as on the Canvas

please see
- https://github.com/epam/ketcher/issues/4575
- https://github.com/epam/ketcher/issues/4690

**Versions:**
Windows 11
Chrome Version Version 123.0.6312.106 (Official Build) (64-bit)
Ketcher Version 2.21.0-rc.1 Build at 2024-04-15; 20:00:15
Indigo Toolkit Version 1.20.0-rc.1.0-g8e8ffc3c3-wasm32-wasm-clang-12.0.0

**Comment by even1024** [comment]
Most left coordinate = first monomer

**Comment by split-ends** [comment]
Successfully verified:

![2024-09-05_17h14_55](https://github.com/user-attachments/assets/b2e9f936-d802-4918-a886-45d0735ff27a)

**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-03; 15:37:29
Indigo Version: 1.24.0-rc.1.0-gb8f099851-x86_64-linux-gnu-11.2.1
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
Windows 11 Enterprise
