### ISSUE TITLE
Position pathway reaction on canvas

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2052]
As a **User**, I want to **open a reaction tree from an RDF file and display it in Ketcher's canvas**, So that I can have a visual representation of the reaction data contained in the RDF file.

**Acceptance Criteria:**
1. When I upload an RDF file, the application should parse the file and build a reaction tree based on the data.
2. The reaction tree should be displayed in Ketcher's canvas in a clear and understandable manner.
3. The reaction tree should accurately represent the data in the RDF file, with each node corresponding to a reaction and each edge representing the relationship between reactions.
4. If a user uploads RXN file, a single reaction with “+” and a single arrow should be displayed (as it is).
5. The application should handle errors in the RDF file gracefully, displaying an appropriate error message if the file cannot be parsed or the reaction tree cannot be built.
6. The multi-tail arrow connection of reactions in the tree is not required in this feature;
7. We should use a sequence as in file, as soon as matching is done it's applied
8. Here is an implementation for recognition only of one pathway reaction as in the use case
9. Reagents should be ignored
10. (Out of scope) - Single arrow will be presented instead of multi-arrow.

**Here is an implementation for recognition of only one first pathway reaction as in the use case, edge cases are out of scope, **
1. If there are reactions or elements in the RDF file that are not included in the reaction tree, these should be placed below the reaction tree in the canvas.
2. Currently we are ignoring reagents for loading from RDF
3. Meta data rendering will implemented in scope of other story.

**Comment by ivanmaslow** [comment]
This task will be tested in scope of https://github.com/epam/Indigo/issues/2128
