### ISSUE TITLE
Save pathway reaction as an image

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2053]
As a **User**, I want the ability **to save my reaction tree as a PNG image** _(or SVG Document)_ so that I can easily share, present, or publish my work in a widely accepted and viewable format.

**Acceptance Criteria:**

1. A user should be able to save a reaction tree as a PNG image _(or SVG Document)_ using a dedicated 'Save Structure' function.
2. The rendered PNG image should accurately represent the reaction tree as it appears on the canvas, including all elements, colors, and labels.
3. The resolution and quality of the rendered PNG image should be high enough to clearly display all details of the reaction tree.
4. The application should provide a mechanism to download or directly save the rendered PNG image to a location specified by the user.
5. If there are any issues or errors during the rendering process, the application should display an appropriate error message and guide the user to resolve the issue.
6. The application should handle the rendering process efficiently to minimize waiting time for the user.

**Comment by ivanmaslow** [comment]
Testing isn't required for this task, it will be covered in scope of https://github.com/epam/Indigo/issues/2129
