### ISSUE TITLE
Consider no ending token as empty case in order to let polymers to load

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2058]
**NOTE:** Export works fine.

**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `RNA1{R(A)P}`
![image](https://github.com/epam/Indigo/assets/26869421/60d05d3b-a2bd-46f4-ad6f-45e0d70c1a26)

**Actual behavior**
System throws exception: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: emsc'
![image](https://github.com/epam/Indigo/assets/26869421/75d306bf-eded-4df4-bf86-52883db36636)

**Expected behavior**
System loads RNA 

Argument: Now we allow user to load HELMs with no version at the end - i.e. `RNA1{R(A)P}$$$$` instead of `RNA1{R(A)P}$$$$V2.0`
Why can we consider absence if mandatory sections (that ends with $-sign) as empty ones?

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AliaksandrDziarkach** [comment]
Not a bug
