### ISSUE TITLE
Label for unknown monomer is wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2060]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `/5i2AmPr/`
![image](https://github.com/epam/Indigo/assets/26869421/091f94a3-dc0a-4894-91e6-c7521326fed3)

**Actual behavior**
System adds monomer to the canvas with label: `unknown_monomer_with_idt_alias_i2AmPr`
![image](https://github.com/epam/ketcher/assets/26869421/0eb1cba1-9f38-44e0-b3a6-6a8c76b45711)

**Expected behavior**
System adds monomer to the canvas with label: `i2AmPr`
![image](https://github.com/epam/ketcher/assets/26869421/39e81c52-0899-4954-b173-9f06ddb7a743)

As per [requirements](https://github.com/epam/ketcher/issues/4431):
```
1. Display on canvas:
    - in flex/snake modes - as a "black box" (see mockups)
```
![image](https://github.com/epam/ketcher/assets/141816460/fe0ee1b2-19a4-4384-a380-a6a3bf4bbc30)

**Versions**
- Ketcher Version 2.22.0-rc.2 Build at 2024-06-28; 05:30:15
- Indigo Toolkit Version 1.22.0-dev.2.1-gd5637f75-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/ketcher/issues/4431

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-11_18h08_25](https://github.com/epam/Indigo/assets/62464241/f05ffcf2-a00e-4f12-b3c9-26c88a13cda0)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.2]
**Indigo version** 
[Version 1.22.0-rc.2]
