### ISSUE TITLE
HELM loader ignores repeating token

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2062]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `RNA1{[Sm5moe]([m2nprn])[mepo2]'5'}$$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/e63433aa-3ea7-4202-bbf1-f8363e991985)

**Actual behavior**
Loads RNA (but without repeating)
![image](https://github.com/epam/Indigo/assets/26869421/aa2a4a6a-693b-441a-a60a-b613a62d9513)

**Expected behavior**
System throws exception: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: Repeating do not supported for now.'
![image](https://github.com/epam/Indigo/assets/26869421/2b4fc02e-4927-4c58-a316-c1da5e2f89b9)

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AliaksandrDziarkach** [comment]
Fixed

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/aea1783c-3c24-4b20-9033-ff032c9a8777)
- Ketcher Version 3.20.0-rc.1 Build at 2024-12-31; 12:50:08
- Indigo Toolkit Version 1.28.0-rc.1.0-gc167e6266-wasm32-wasm-clang-19.0.0
- Chrome Version Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
