### ISSUE TITLE
System ignores invalid connection point and load canvas instead of throwing an error 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2066]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `CHEM1{[A6OH]}|PEPTIDE1{A}$CHEM1,PEPTIDE1,1:R4-1:R1$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/d21f72bd-8017-4304-b503-7b48a926e654)

**Actual behavior**
System loads two monomers not connected to each other
![image](https://github.com/epam/Indigo/assets/26869421/f1be4d31-18d6-4dd4-921e-7ec0a06bea28)

**Expected behavior**
System throws exception: Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'Attachment point (R4) is not found for given monomer ([A6OH]) in given polymer (CHEM1)'
![image](https://github.com/epam/Indigo/assets/26869421/a7f1987d-c893-44c9-a336-42aa49a6eb05)

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AlexeyGirin** [comment]
Not fixed.
No error message appear
![image](https://github.com/user-attachments/assets/2ace3206-ab6b-45c7-abc1-b7007f8cbcdd)

- Ketcher Version 2.23.0-rc.3 Build at 2024-07-25; 05:30:25
- Indigo Toolkit Version 1.23.0-dev.1.14-g284c33a1-wasm32-wasm-clang-12.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.73 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
Re-CHECK

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-09-05_15h09_58](https://github.com/user-attachments/assets/2a62247a-b928-4e0f-8106-497165328fd2)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
