### ISSUE TITLE
HELM export for cycled polymer is wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2068]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from file: [HELM Export for cycled polymer is wrong.zip](https://github.com/user-attachments/files/16085762/HELM.Export.for.cycled.polymer.is.wrong.zip)
![image](https://github.com/epam/Indigo/assets/26869421/9273a14b-7167-4902-a7ca-686886e13e10)
3. Save canvas to HELM

**Actual behavior**
Export result contains non-cycled polymer chain: `PEPTIDE1{C.D.E.F.A}$$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/c6c91560-8dcb-46d6-b0ec-718a93f7e177)

**Expected behavior**
Export result contains cycled polymer chain: `PEPTIDE1{C.D.E.F.A}$PEPTIDE1,PEPTIDE1,1:R1-5:R2$$$V2.0`

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-07-16_13h52_59](https://github.com/user-attachments/assets/75013d79-7f72-4733-bd82-8ba044b000a8)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.23.0-rc.3]
**Indigo version** 
[Version 1.22.0-rc.3]
