### ISSUE TITLE
Support retrosynthetic arrows

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/Indigo#2071]
**Background**
Currently Indigo processes reactions based on positions of molecules, reaction arrow and plus sign on canvas. In horizontal orientation it recognizes molecules on the left from arrow as **reactants** and molecules on the right as **products** of the reaction.  

**Solution**
Introduce a new 'retrosynthetic' type of reaction arrow that will be processed based on the opposite logic: components to the right from arrow should be treated as reactants, components on the left -- as products.
The retrosynthesis reaction will look like `Z => X + Y` or `B => A` where X, Y and A are reactants, Z and B are products. 

Similarly. the logic should be adjusted for vertically oriented reactions, so that direction of retrosynthetic reactions is opposite to regular ones.

Import/Export into formats:
* KET
  * Add new mode "retrosynthetic" for type "arrow" into KET specification and save/load the reaction without changes
* RXN (2000/3000), SMILES, SMARTS, CML
  * Reaction should be saved with opposite order of components (reactants becomes products as described above)
  * Warning should appear that some information can be lost
  * Reaction load works as before (as this formats do not support the retrosynthesis arrows)
* Molfile/SDF/Inchi 
  * Works as before (no support for reactions)  

Acceptance criteria:
* Code written with respect of current architecture
* Python integration tests updated for at least (but not limited to) the following cases:
   * read from KET write to KET
   * read from KET write to RXN
   * read from KET write to SMILES
   * read from KET write to SMARTS
   * read from KET write to CML
given the following reactions
   * R1 => R2
   * R1 + R2 => R3
   * => R1
   * R1 =>
   * R1 => R2 -> R3
   * R1=>R2=>R3
   * R1->R2=>R3 + R4 

Where 
R* - reagent molecules (any molecules can be used, e.g.  "C", "O", "N", "P", "CN", "ON", etc ).
=> retrosyntheticarrow 
-> single arrow

Related tickets:

* PNG/SVG
  moved to a separate ticket - [#2096 PNG/SVG rendering](https://github.com/epam/Indigo/issues/2096) 
* CDXML/CDX
  moved to a separate ticket - [#2097 CDXML/CDX formats](https://github.com/epam/Indigo/issues/2097) 

Related Ketcher task - [#4985](https://github.com/epam/ketcher/issues/4985)

**Comment by AnnaKosol** [comment]
Verified by autotests + manually
![Image](https://github.com/user-attachments/assets/512434fe-cbb6-4415-9fd7-17d94ef844be)


**Environment details:**
Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.6
