### ISSUE TITLE
Unable to save micro-molecule connected to CHEM to HELM

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2073]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from file: [Unable to save micro-molecule connected to CHEM to HELM.zip](https://github.com/user-attachments/files/16086669/Unable.to.save.micro-molecule.connected.to.CHEM.to.HELM.zip)
![image](https://github.com/epam/Indigo/assets/26869421/544b4aaf-e68f-427d-9eac-125945416b1c)
3. Save canvas to HELM

**Actual behavior**
System throws exception: Convert error! map::at:  key not found
![image](https://github.com/epam/Indigo/assets/26869421/660dfdfe-9314-4d95-bcb0-bd317679530c)

**Expected behavior**
Export result: `CHEM1{[A6OH]}|CHEM2{[C1C=CC=C%91C%92=1.[*:1]%92.[*:2]%91 |$;;;;;;_R1;_R2$|]}$CHEM1,CHEM2,1:R1-1:R2$$$V2.0`

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AlexeyGirin** [comment]
RE-CHECK

**Comment by Zhirnoff** [comment]
Tested. Able to save micro-molecule connected to CHEM to HELM. But we have another bug https://github.com/epam/Indigo/issues/2316


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
