### ISSUE TITLE
HELM export of RNA polymer is wrong

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2074]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load from file: [HELM export of RNA polymer is wrong.zip](https://github.com/user-attachments/files/16087175/HELM.export.of.RNA.polymer.is.wrong.zip)
![image](https://github.com/epam/Indigo/assets/26869421/cdfe61a7-cba3-456f-95e2-8eb3d8c33b80)
3. Save canvas to HELM

**Actual behavior**
Export result contains RNA that broken: `RNA1{P.R(C)P.R(G)P.R(A)}$$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/8314d214-59d4-4740-8b9f-3eea725ae19f)

**Expected behavior**
Export result is correct: `RNA1{R(A)P.R(C)P.R(G)P}$RNA1,RNA1,9:R2-1:R1$$$V2.0`

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AliaksandrDziarkach** [comment]
This is dublicate of #2068

**Comment by AlexeyGirin** [comment]
Ok
