### ISSUE TITLE
Sysmem should throw an error if we try to connect monomer to already occopied attachment point

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2078]
**Steps to Reproduce**
1. Go to Macromolecules mode - Flex mode
2. Load using paste from clipboard IDT type: `CHEM1{[MCC]}|RNA1{R(U)P}$CHEM1,RNA1,1:R1-1:R2$$$V2.0`
![image](https://github.com/epam/Indigo/assets/26869421/0e755786-7047-407a-97a0-04497bd7b48e)

**Actual behavior**
System load something
![image](https://github.com/epam/Indigo/assets/26869421/d3987b1c-c784-4e5e-9848-9b00eb1469f5)

**Expected behavior**
Error should occur - Can't connect to R2 attachment point of monomer index 1 of RNA1 - it is already occupied

**Versions**
- Ketcher Version 2.23.0-rc.1 Build at 2024-07-02; 08:57:41
- Indigo Toolkit Version 1.22.0-rc.1.0-g2bef0ce6c-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 126.0.6478.127 (Official Build) (64-bit)

Issue found while testing - https://github.com/epam/Indigo/issues/1188

**Comment by AliaksandrDziarkach** [comment]
Planed to fix with variant monomers helm support.

**Comment by split-ends** [comment]
Successfully verified: an error appears with the corresponding message:
![image](https://github.com/user-attachments/assets/da390aef-050f-49f3-bf2d-3a0a0f41c147)

**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
Windows 11 Enterprise
