### ISSUE TITLE
Support retrosynthetic arrows - PNG/SVG rendering

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/Indigo#2096]
The parent ticket about retrosynthetic arrows - [#2017 Support retrosynthetic arrows](https://github.com/epam/Indigo/issues/2071)

How the arrow should look can be found in the task [#4985](https://github.com/epam/ketcher/issues/4985)

Add rendering for the new type of the reaction arrow into Export to PNG/SVG formats.

**Comment by AlexeyGirin** [comment]
Part of #2071

**Comment by AnnaKosol** [comment]
Verified
![Image](https://github.com/user-attachments/assets/b650c2e9-9d00-4fb0-8942-94607228f538)

![Image](https://github.com/user-attachments/assets/f1cdeb77-c8be-43ed-8ca8-f268571962f3)



**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-04; 09:15:28
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
MacOs 14.6
