### ISSUE TITLE
Support retrosynthetic arrows - CDXML/CDX formats

### ISSUE THREAD

**Issue by AlekseiKhariukov** [epam/Indigo#2097]
The parent ticket about retrosynthetic arrows - [#2017 Support retrosynthetic arrows](https://github.com/epam/Indigo/issues/2071)

Implement Import/Export retrosynthetic arrows into CDXML/CDX formats:
  * Add support for exiting type "Retrosynthesis (small)"
  * Reaction should be saved/loaded without changing order of components 
![Image](https://github.com/epam/Indigo/assets/7427808/cc71d99c-da7c-449c-9f77-0c67d3bf085b)

**Comment by AnnaKosol** [comment]
Verified
![Image](https://github.com/user-attachments/assets/a5ade332-5ee2-407a-993b-6a5a9039cf90)
[ketcher (23).cdxml.zip](https://github.com/user-attachments/files/16908756/ketcher.23.cdxml.zip)



**Environment details:**
Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.6
