### ISSUE TITLE
Libraries download for indigo-service: Where do I get these from?

### ISSUE THREAD

**Issue by Doidel** [epam/Indigo#210]
In order to build the docker file for the indigo service, a few libs are required: [/utils/indigo-service/lib](https://github.com/epam/Indigo/tree/master/utils/indigo-service/lib)
I am trying to build on Windows. When I download e.g. the Bingo files from [here](https://lifescience.opensource.epam.com/download/bingo.html), I receive a **ZIP** file. However, when I execute docker-compose, it searches for **7z** files:

> Step 5/9 : COPY ./lib/bingo-postgres*.7z /opt/
> ERROR: Service 'db' failed to build : COPY failed: no source files were specified

So my question is: What are those library files, and where do I get them from?
(Please note that I don't want to build those libraries from scratch, if in any way possible...)

Thanks for your assistance!

**Comment by mkviatkovskii** [comment]
Dear @Doidel 
We plan to automate indigo_service Dccker image building and deployment. Right now the most easy way is to use our image: https://hub.docker.com/r/epmlsop/indigo_service

It uses a bit outdated version of Indigo API (should be enough for Ketcher server side functionality though). But if you want to update Indigo, you can use this image as a base and update `/srv/indigo-python/` with new version of Indigo built manually:
```
python build_scripts/indigo-release-libs.py --preset=linux64
python build_scripts/indigo-make-by-libs.py --type=python
```
Target version of indigo-python should be in `dist/indigo-python-*.zip`.

**Comment by Doidel** [comment]
Using your image is fine for me, thanks for the reply!
Maybe the image can be linked somewhere in the download sections of the webpage? Because I wasn't able to find this image coming from there and therefore tried to build the docker container with the source files here on GitHub.

The issue of "finding the service files" is closed for me, Please reopen if you wish to keep it open for the Indigo ToDo.
