### ISSUE TITLE
Indigo API has Bingo queries..?

### ISSUE THREAD

**Issue by Doidel** [epam/Indigo#212]
In my project, I use the Indigo framework for calculations and just working in memory. Then I have my custom ORM which maps to the database with Bingo and its Stored Procedures. However, by accident (and not by reading the online API docs) I discovered that the Indigo library also has a Bingo namespace with functions that seem to match the Bingo backend, e.g.
`new Bingo().searchSub()`
Care to explain? What is the concept behind this? Does the Indigo library contain a Bingo mapping with which you can query?

Thanks for some clarification!

**Comment by mkviatkovskii** [comment]
Hi @Doidel

This is called Bingo-NoSQL, our plugin to Indigo that implements a file-based molecules and reactions database storage. It allows to add compounds to index and performs fast searches (substructure, exact, similarity, molecule formula) without any DMBS like Postgres, Oracle of ElasticSearch. It is useful if you only need to search for molecules (or reactions), not some related data.

**Comment by Doidel** [comment]
Oh I see, thanks for the elaborate response.

Hmm I wouldn't have asked the question if there was anything mentioned anywhere, except of course on the Bingo NoSQL page itself. Maybe in [the Indigo API](https://lifescience.opensource.epam.com/indigo/api/index.html) a link at the bottom of the page clarifying that Indigo has no direct connection to the Bingo cartridge, except in the NoSQL case. This fact was not clear to me until you told me here.

**Comment by AlexanderSavelyev** [comment]
created a new ticket for the portal
https://github.com/epam/lifescience/issues/66
