### ISSUE TITLE
An error occurred while saving the nucleotide and arrow in the RXN2000 format

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2126]
**Steps to Reproduce**
1. Open Macromolecules mode - Flex mode
2. Add any nucleotide
3. Open Molecules mode
4. Add an arrow
5. Click on save

**Expected behavior**
You can save file in the RXN2000 format

**Actual behavior**
An error occurred
![Снимок экрана 2024-07-16 в 12 45 55](https://github.com/user-attachments/assets/3bfea768-70e6-47ad-8570-5b7b20ee2b43)

**Environment details:**
Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
Issue found for https://github.com/epam/ketcher/issues/4382

**Comment by AliaksandrDziarkach** [comment]
Expected fixed

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. However, after loading the file, the monomer appears expanded. A separate bug will be created to address this issue.

https://github.com/user-attachments/assets/e84f97cd-530e-4533-93b8-ddef2c64f25f



**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
