### ISSUE TITLE
Add Multi-tail Arrows to Pathway Reactions Loaded from RDF

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2128]
As a **User**, I want **to see multi-tail arrows in pathway reactions** when I load them from RDF files, so that I can accurately understand and analyze complex reactions involving multiple reactants.

**Acceptance Criteria:**

1. When a user loads pathway reactions from an RDF file, any multi-tail arrows in the reactions should be accurately displayed on the canvas.
2. The multi-tail arrows should correctly connect multiple reactants to a single product, accurately representing the structure of the reaction.
3. If a pathway reaction contains a reaction with a single reactant, a simple arrow should be displayed.
4. Reagents should be ignored
5. If a user will upload RXN file, single reaction with “+” and single arrow should be displayed (as it is).
6. When we loading RDF with pathway reaction, Multi-tail default width is 3 (0,5 + 2,5).

**Comment by ivanmaslow** [comment]
Smoke testing is performed on RC Remote environment:
- Structures can be loaded from RDF files and it's displayed with Multi-Tailed Arrows:
![image](https://github.com/user-attachments/assets/de291191-8f46-41a2-a16b-df0bbde51c2e)
- The algorithm of recognition from RDF will be rewritten in scope of this task https://github.com/epam/Indigo/issues/2102, so the exploratory testing will be performed in scope of this task later, acceptance Criteria from tasks below will be considered during testing of #2102:
    - https://github.com/epam/Indigo/issues/2031
    - https://github.com/epam/Indigo/issues/2052
    - https://github.com/epam/Indigo/issues/2128
