### ISSUE TITLE
indigo-service: Running, but all answers are empty

### ISSUE THREAD

**Issue by Doidel** [epam/Indigo#213]
I could successfully run the image you provided in #210, however the service doesn't answer, I always get empty responses no matter that I query, e.g.

- http://localhost:{myport}
- http://localhost:{myport}/info
- http://localhost:{myport}/v2/indigo
- http://localhost:{myport}/swagger

etc. (Please notice that empty response = Server is responding, but returns nothing. No status code, no nothing, but it means I have the right address).
So since the docker logs show nothing, I thought it's probably something with the python process running inside docker. However, I wasn't able to find a log file. I checked /var/logs and the usual culprits, and I actually found the uwsgi log folder, yet it is empty.
So I'd be grateful for some guidance, e.g.:

- What is an URL I can test and actually expect something? E.g. like the swagger yaml/json?
- Where can I find your logs inside the docker image?

Thank you for your answer!

**Comment by mkviatkovskii** [comment]
Dear @Doidel,
Not sure how you started the container, I tried this approach
```bash
 docker run --rm -p 8080:80 epmlsop/indigo_service python3 app.py -s 0.0.0.0 -p 80
```
And then tried to get the Swagger spec at http://localhost:8080/spec/ and Indigo libraries versions at http://localhost:8080/v2/info. Both worked, last showed this result:
```
{
  "imago_versions": [
    "v10.1-dev1-1-ge78b2cb-linux64", 
    "v2.1-dev1-0-ge78b2cb-linux64"
  ], 
  "indigo_version": "1.3.0beta.r355-g4846731c linux64", 
  "service_version": "0.2-334-g0c1d67f"
}
```
As for the Swagger, as far as I remember, the swagger itself is not included in this image, we used some static files in the standalone container that used the JSON spec from http://localhost:8080/spec. I tried to manually copy it to the https://editor.swagger.io/, and despite some error messages, it worked.

Please let me know if you want to run the indigo_service in some specific way and need my assistance on that.

**Comment by Doidel** [comment]
Yep, that was it!
I tried to salvage a docker command from [the Indigo Service Readme](https://github.com/epam/Indigo/tree/master/utils/indigo-service) but didn't see there that I had to particularly run `app.py`.

Thank you again for your help!
