### ISSUE TITLE
Create Indigo WASM bundle with removed rendering part

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#2131]
**Background**
Whole WASM Indigo bundle is quite large and major part of the code is on behalf of renderer and its 3rd party libraries like
png support, cairo graphics, etc.  Indigo renderer is not used very often so it make sense to create a bundle version without the render code (Only Indigo core).

**Solution**
All render-related code should be put under the conditional compilation blocks.
The following files have to be added to Indigo bundle:

1) indigo-ketcher-norender.js
2) indigo-ketcher-separate-wasm-norender.wasm

**Comment by AlexeyGirin** [comment]
Verified verbally
