### ISSUE TITLE
An error occurred while saving the unresolved nucleotides and arrow in the RXN3000 format

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2137]
**Steps to Reproduce**
1. Open in micro mode
2. Add file with nucleotides and other monomers
[Schema nucleotide with sugar with different connections.ket.zip](https://github.com/user-attachments/files/16308860/Schema.nucleotide.with.sugar.with.different.connections.ket.zip)
3. Add a row (Open Angle tool)
4. Save to file in RXN3000 format
5. Open file in RXN3000 format on Canvas

**Expected behavior**
File is opened without errors

**Actual behavior**
An error occurred
![Снимок экрана 2024-07-19 в 09 41 45](https://github.com/user-attachments/assets/bf3bf82e-80c9-4f53-8840-273c29343016)

With other connections is the same situation
[Schema nucleotide with nucleotide with different connections.ket.zip](https://github.com/user-attachments/files/16308945/Schema.nucleotide.with.nucleotide.with.different.connections.ket.zip)
[Schema nucleotide with base with different connections.ket.zip](https://github.com/user-attachments/files/16308946/Schema.nucleotide.with.base.with.different.connections.ket.zip)
[Schema nucleotide with peptide with different connections.ket.zip](https://github.com/user-attachments/files/16308947/Schema.nucleotide.with.peptide.with.different.connections.ket.zip)
[Schema nucleotides with phosphate with different connections.ket.zip](https://github.com/user-attachments/files/16308948/Schema.nucleotides.with.phosphate.with.different.connections.ket.zip)
[Schema nucleotide with chem with different connections.ket.zip](https://github.com/user-attachments/files/16308949/Schema.nucleotide.with.chem.with.different.connections.ket.zip)

**Environment details:**
 Ketcher Version 2.23.0-rc.2 Build at 2024-07-10; 19:39:22
Indigo Version 1.22.0-rc.2.0-ga21fb5d8f-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
Issue found for https://github.com/epam/ketcher/issues/4382

**Comment by AliaksandrDziarkach** [comment]
Expected fixed

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/8430d651-d518-414c-987d-7556804b54ad)
- Ketcher Version 3.20.0-rc.1 Build at 2024-12-31; 12:50:08
- Indigo Toolkit Version 1.28.0-rc.1.0-gc167e6266-wasm32-wasm-clang-19.0.0
- Chrome Version Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
