### ISSUE TITLE
Replace common/base_c/os_dir* with <filesystem>

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#2139]
**Background**
Currently own-written C functions using Windows and POSIX API are used for manipulating with directories. It's outdated approach, since C++17 has <filesystem> for that.

**Solution**
Use standard C++17 filesystem library to manipulate with files and folders.

**Alternatives**

**Additional context**

**Comment by AlexeyGirin** [comment]
Verbally verified.
