### ISSUE TITLE
Import/export images in KET

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2144]
Indigo should understand and support images in KET file.
In case, if layout processing or any other operations will be called from Ketcher - images should be presented at the same (X,Y) position.

**Comment by ivanmaslow** [comment]
An example of .ket file with png and SVG images:
[images-png-svg-demo.zip](https://github.com/user-attachments/files/16330650/images-png-svg-demo.zip)

**Comment by ivanmaslow** [comment]
AC: Images don't disappear after actions with indigo tools:
![image](https://github.com/user-attachments/assets/20a1c64e-98c4-4828-a512-7bd1eac96709)
![image](https://github.com/user-attachments/assets/db9d93e7-da2e-4a42-badd-f26908d80475)

**Comment by ivanmaslow** [comment]
Exploratory testing is finished on the Remote environment:
- **Ketcher**: [Version 2.24.0-rc.1] Build at 2024-08-06; 19:25:43
- **Indigo**: Version 1.23.0-rc.1.0-g85f89b8f5-x86_64-linux-gnu-11.2.1
- **OS**: Windows 11 Enterprise
- **Browser**: Chrome Version 124.0.6367.79 (Official Build) (64-bit)

Points below are covered during testing, tests are updated: 
- Tests were completed for PNG/SVG images with/without corrupted/non-corrupted Benzene rings and reaction elements after different Indigo actions
- After the following actions, images don't change position and layer: Aromatize/Dearomatize, Clean Up, Auto-Mapping, Calculate CIP, Calculate Values, Check Structure, Hydrogens, 3D View
- After Layout action images and reactions are centered on Canvas;

High priority defects related to this feature are fixed:
- https://github.com/epam/Indigo/issues/2172
- https://github.com/epam/Indigo/issues/2182

Defects related to the existing behavior of indigo functions and not related to image changes, they have Medium priority:
- https://github.com/epam/Indigo/issues/2184
- https://github.com/epam/Indigo/issues/2191
- https://github.com/epam/Indigo/issues/2192
- https://github.com/epam/Indigo/issues/2193
