### ISSUE TITLE
Property "render-output-format" not defined

### ISSUE THREAD

**Issue by Doidel** [epam/Indigo#215]
I'm trying to use the IndigoRenderer (.NET from NuGet) and according to the docs ([1](https://lifescience.opensource.epam.com/indigo/api/index.html, [2](https://lifescience.opensource.epam.com/indigo/options/rendering-options.html)) I should set the `render-output-format`. However, when I execute the following code...

```csharp
var indigo = new Indigo();
indigo.setOption("smart-layout", "false");
indigo.setOption("render-output-format", "png");
var renderer = new IndigoRenderer(indigo);
...
```
... I get the Exception `Property "render-output-format" not defined`.

My guess is that it was renamed at some point. I tried to search the GitHub repository but couldn't find a rename. Would you mind pointing me into the right direction?

Thanks!

**Comment by mkviatkovskii** [comment]
Dear @Doidel,
Render options are loaded when the Renderer plugins is loaded (when you create an IndigoRenderer instance). So your code should look like:
```csharp
var indigo = new Indigo();
var renderer = new IndigoRenderer(indigo);
indigo.setOption("smart-layout", "false");
indigo.setOption("render-output-format", "png");
...
```

**Comment by Doidel** [comment]
That was it, thank you. I wasn't aware of the required order.
