### ISSUE TITLE
Add support for including embedded SVGs while exporting as SVG

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#2161]
**Background**
Indigo library supports rendering of KET files into SVG-file. Currently KET-files are extended with embedded SVG-images which should also be included into result SVG-file 

**Solution**
Embedded SVG-files should be added using `<image> tag`:

```
<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
  <image href="path_to_external_svg_file.svg" width="200" height="200"/>
</svg>
```

**Comment by yauhen-karmyzau** [comment]
Issue was closed as part of SVG export to PNG.

**Comment by Zhirnoff** [comment]
Pre-tested.
![2024-09-30_11h20_44](https://github.com/user-attachments/assets/df56d0dd-1dd7-4165-96ab-3c1def56da34)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.4]
**Indigo version** 
[Version 1.25.0-dev.2]

**Comment by Zhirnoff** [comment]
Tested. Embedded SVG-file saved using <image> tag as png:
![2024-10-09_15h11_25](https://github.com/user-attachments/assets/9ff30831-b170-4a28-aa96-4bc8fe4a5139)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]
