### ISSUE TITLE
Add support for rendering embedded SVGs while exporting to PNG

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#2162]
**Background**
Indigo library supports rendering of KET files into PNG-file. Currently KET-files are extended with embedded SVG-images which should also be included into result PNG-file 

**Solution**
SVG parser should be implemented to translate SVG-tags into cairo calls.
Possible 3rd party solutions are:

1) librsvg
2) nanosvg
3) LunaSVG

**Comment by Zhirnoff** [comment]
Pre-tested.
![2024-09-30_11h20_44](https://github.com/user-attachments/assets/df56d0dd-1dd7-4165-96ab-3c1def56da34)
![2024-10-01_10h39_00](https://github.com/user-attachments/assets/ea46f174-ea88-4ad7-8f99-875ffc81ab6c)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.4]
**Indigo version** 
[Version 1.25.0-dev.2]

**Comment by Zhirnoff** [comment]
Tested. SVG image renders in the preview when saving as PNG.

![2024-10-09_15h07_16](https://github.com/user-attachments/assets/417be2b4-311a-4b04-a608-a0b7c31551c1)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]
