### ISSUE TITLE
Update embedded images format in KET-files

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#2168]
**Solution**
Embedded images representation inside KET-format should be implemented according to this example:

```
{
    "root": {
        "nodes": [
            {
                "type": "image",
                "format": "image/svg+xml",
                "boundingBox": {
                    "x": 12.55,
                    "y": -7.375,
                    "z": 0,
                    "width": 0.4,
                    "height": 0.4
                },
                "data": "<encoded base64 string>"
            }
        ]
    }
}
```

**Comment by ivanmaslow** [comment]
Preview exploratory testing is completed on env with 5172-update-ket-image branch in the scope of https://github.com/epam/ketcher/issues/5172 (Json structure for images in .ket file was changed):
All scope of checks from previous tasks were retested successfully:
https://github.com/epam/ketcher/issues/4911
https://github.com/epam/ketcher/issues/4897

**Comment by Zhirnoff** [comment]
Tested.
![2024-08-09_11h46_19](https://github.com/user-attachments/assets/b8a46a03-00a4-4671-bb70-4d0aaa153c07)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
