### ISSUE TITLE
Create Python Bingo API for Elasticsearch

### ISSUE THREAD

**Issue by MysterionRise** [epam/Indigo#217]
Same as #198 but in Python :)

**Comment by khyurri** [comment]
Branch: https://github.com/epam/Indigo/tree/bingo-elastic-python

**Comment by MichelML** [comment]
+1

**Comment by MysterionRise** [comment]
@MichelML we already working on this by porting Java API into Pythonic way. In the meantime, you could check out our Java API Readme - contribution and questions are always welcome.

https://github.com/epam/Indigo/blob/master/api/plugins/bingo-elastic/java/README.md

**Comment by MysterionRise** [comment]
@MichelML we have first version of it completed into master and it should be available in pypi soon
Resolved via #223
