### ISSUE TITLE
Preview: Image disappear after layout function when images are on canvas with reaction

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2172]
**Steps to Reproduce**
1. Open .ket file: 
[test1.zip](https://github.com/user-attachments/files/16457129/test1.zip)
![image](https://github.com/user-attachments/assets/799773a8-f446-47aa-be80-9fccf3623e32)
2. Click on the Layout button

**Expected behavior**
Images are on the same place, the reaction is aligned

**Actual behavior**
Images disappear, reaction is aligned
![image](https://github.com/user-attachments/assets/dfd26904-d329-4d4c-a7e9-f519b38ada16)

**Environment details:**
 - Indigo: Version 1.23.0-dev.4.0-gb71e441d7-wasm32-wasm-clang-19.0.0
 - Ketcher: [Version 2.23.0-rc.3] Build at 2024-08-01; 08:58:34
 - Chrome: Version 127.0.6533.88 (Official Build) (64-bit)
 - Windows 11 Enterprise

**Additional context**
Issue is detected during testing of https://github.com/epam/Indigo/issues/2144

**Comment by ivanmaslow** [comment]
The fix is verified on CI-CD env with the master branch:
- Indigo version: Version 1.23.0-dev.3.5-g24c4f29f-wasm32-wasm-clang-12.0.0
- Ketcher Version: [Version 2.23.0-rc.3] Build at 2024-08-05; 09:52:36
Images don't disappear, but change positions after Indigo actions, new defect is reported - https://github.com/epam/Indigo/issues/2182

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

https://github.com/user-attachments/assets/57699bd8-0774-4f26-826c-a22f6e8bbc91

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.79 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.23.0-rc.1]
