### ISSUE TITLE
Preview: PNG image and elements can't be saved to PNG or SVG formats with correct position of image

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2173]
**Steps to Reproduce**
1. Open .ket file:
[test1png.zip](https://github.com/user-attachments/files/16457402/test1png.zip)
2. Add elements and image to Canvas
![image](https://github.com/user-attachments/assets/47305982-83f4-48ee-b819-dc9574bffd38)
3. Click Save as
4. Select PNG Image or SVG Document

**Expected behavior**
- The preview is as it was on Canvas, image is on the same position regardless SVG and PNG saving format
- After clicking to save, It is saved as on preview with correct position of image

**Actual behavior**
- The preview isn't correct, image is on top regardless SVG or PNG format to save
![image](https://github.com/user-attachments/assets/b2bf0040-7d44-4af2-bb2d-50f6693faf79)
- After clicking to save, It will be saved as on preview with not correct position of image

**Environment details:**
- Indigo: Version 1.23.0-dev.4.0-gb71e441d7-wasm32-wasm-clang-19.0.0
- Ketcher: [Version 2.23.0-rc.3] Build at 2024-08-01; 08:58:34
- Chrome: Version 127.0.6533.88 (Official Build) (64-bit)
- Windows 11 Enterprise

**Additional context**
- Issue is detected during testing of https://github.com/epam/Indigo/issues/2029
- It works the same in case of multiple reactions and images

**Comment by ivanmaslow** [comment]
The fix is verified on CI-CD env with the master branch:
- Indigo version: Version 1.23.0-dev.3.5-g24c4f29f-wasm32-wasm-clang-12.0.0
- Ketcher Version: [Version 2.23.0-rc.3] Build at 2024-08-05; 09:52:36
Image is displayed at the correct position in preview, but one more issue is reported - https://github.com/epam/Indigo/issues/2183

**Comment by AnnaKosol** [comment]
Verified
PNG
<img width="534" alt="Снимок экрана 2024-08-07 в 15 00 06" src="https://github.com/user-attachments/assets/60b91a42-001c-4c1d-ad0e-095a1e218e7d">
SVG
<img width="533" alt="Снимок экрана 2024-08-07 в 15 00 16" src="https://github.com/user-attachments/assets/455028d4-98e3-474e-a40a-425c7db478c3">

**Environments details**
Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
Indigo Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
