### ISSUE TITLE
Add new settings for ACS style for convert and layout functions

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2176]
**Background**
Related issue: https://github.com/epam/ketcher/issues/5152 need to add new settings. 

**Solution**
When calling indigo's functions such as layout, convert on the Canvas, new settings parameters should be processed.
List of the new settings in the JSON of the Settings:
`bond-length-unit: "px"` 
`bond-length: 2.2` 
> If possible, the size of an arrow should be the same as the size of a bond. Exceptions are when catalysts/reaction conditions/other additional context placed bellow or above the arrow. The logic is described in Ketcher issue: [#5155](https://github.com/epam/Indigo/issues/2243)
Default arrow size is equal to 2 default sizes of bonds (in angstrom)
(images for better understanding)
![image](https://github.com/user-attachments/assets/d68ae0d0-9761-4f1f-81b5-3c64c7063841)
![image](https://github.com/user-attachments/assets/5b65e74c-4fe1-4cef-9964-141dc4294943)

Reaction margin size should be applied both for distance between plus and component and between arrow and component `structure bounding box` (should be equal distance)

![image](https://github.com/user-attachments/assets/8a514558-68c6-4655-87d5-6a2b721236c4)

`Structure bounding box` should be calculated as `atoms bounding box` + default `atom label margin`=0.5 `Default bond length`

![image](https://github.com/user-attachments/assets/fc6455ed-ef66-4d1c-9606-4c0a204e25a2)

For simple atoms `atoms bounding box` is a dot in center of the atom
![Image](https://github.com/user-attachments/assets/8ade3be5-dc4e-444d-b8db-36c38301237e)

Default size of the `plus` element by default equals 0.5 `bond-length`

![image](https://github.com/user-attachments/assets/4a9f3f9e-2994-4095-bf38-3e77e96da998)

`reaction-component-margin-size-unit: "px"` 
`reaction-component-margin-size: default value = 2.3 pt`
`image-resolution`

`bond-length-unit` values can be in cm/pt/px/in
`bond-length` number with 1 decimal places
`reaction-component-margin-size-unit` values can be in cm/pt/px/in
`reaction-component-margin-size` number with 1 decimal places
`image-resolution` should be a number; 
Regardless of the resolution, the size of the image should be such that one bond is ~0,5cm (0,2in/14,4pt) long when printed/100% zoom.

**Additional information**
1 inch = 72 pt
1 inch = 2.54 cm
1 angstrom = 1e-8 cm
PPI  = pixels per inch = sqrt(w^2 + h^2) /d 
where w - width in px, h - height in px,  d - diagonal in inches
if PPI = 100 then 1px = 0.01 in
reactionComponentMarginSize - horizontal & vertical margins

SMILES for testing
`OC(=O)C.OCCC>>CC(=O)OCCCC.O`

**Comment by AlexeyGirin** [comment]
[ACS-StyleGuide.pdf](https://github.com/user-attachments/files/16849103/ACS-StyleGuide.pdf)
