### ISSUE TITLE
Preview: Images change their positions after Indigo actions

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2182]
**Steps to Reproduce**
1. Open the KET file with images and reaction: 
[defect1.zip](https://github.com/user-attachments/files/16495157/defect1.zip)
![image](https://github.com/user-attachments/assets/76b783ff-72dd-4e58-bbb9-b09d690c3492)

2. Click on Indigo actions (Aromatize, Dearomatize, Layout, Clean Up, Calculate CIP, Add/Remove Explicit Hydrogens, Reaction Auto-Mapping Tool)

**Expected behavior**
- Images are in the same positions, elements are affected if changes can be applied.

**Actual behavior**
- Images change position on Canvas, elements are affected if changes can be applied (example after Aromatize/Dearomatize actions):
![image](https://github.com/user-attachments/assets/d1456fca-8b93-4a59-914c-d7cfa0282539) 

**Environment details**
 - Indigo version: Version 1.23.0-dev.3.5-g24c4f29f-wasm32-wasm-clang-12.0.0
 - Ketcher Version: [Version 2.23.0-rc.3] Build at 2024-08-05; 09:52:36
 - Chrome version: Version 127.0.6533.89 (Official Build) (64-bit)
 - OS version: Windows 11 Enterprise

**Additional context**
- Issue is found during retesting of defect https://github.com/epam/Indigo/issues/2172 in scope of this task https://github.com/epam/Indigo/issues/2144

**Comment by AnnaKosol** [comment]
Verified
<img width="987" alt="Снимок экрана 2024-08-07 в 15 53 54" src="https://github.com/user-attachments/assets/815afba7-282d-4e9a-9901-4206da18c757">

**Environments details**
Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
Indigo Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
