### ISSUE TITLE
Preview: PNG images aren't on the bottom layer on preview and after save to PNG and SVG formats

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2183]
**Steps to Reproduce**
1. Open the KET file with PNG image and different types of elements:
[defect2.zip](https://github.com/user-attachments/files/16495368/defect2.zip)
![image](https://github.com/user-attachments/assets/3f81ff76-d074-48dd-97b1-c75d906ee7c9)
2. Click on Save as...
3. Select PNG Image or SVG Document

**Expected behavior**
- The preview is as it was on Canvas, image is on the same position regardless SVG and PNG saving format
- After clicking to save, It is saved as on preview with correct position of image

**Actual behavior**
- The preview isn't correct, simple objects are under image:
![image](https://github.com/user-attachments/assets/582268a5-8e74-432b-be92-d735d6e302da)

**Environment details:**
- Indigo version: Version 1.23.0-dev.3.5-g24c4f29f-wasm32-wasm-clang-12.0.0
- Ketcher Version: [Version 2.23.0-rc.3] Build at 2024-08-05; 09:52:36
- Chrome version: Version 127.0.6533.89 (Official Build) (64-bit)
- OS version: Windows 11 Enterprise

**Additional context**
- Issue is found during retesting of defect https://github.com/epam/Indigo/issues/2173 in scope of this task https://github.com/epam/Indigo/issues/2144

**Comment by ivanmaslow** [comment]
The fix is verified on CI-CD env with the master branch:
- Indigo version: Version 1.23.0-dev.3.8-g4927ba55-wasm32-wasm-clang-12.0.0
- Ketcher Version: [Version 2.23.0-rc.3] Build at 2024-08-06; 12:00:21
All elements are displayed correctly in the preview of PNG, SVG and can be saved with correct positions:
![image](https://github.com/user-attachments/assets/021e0ba1-5d69-4fdb-92fd-15c2347a308f)

**Comment by AnnaKosol** [comment]
Tested.
Regarding absence of the R-group, a bug created  https://github.com/epam/Indigo/issues/2196
<img width="767" alt="Снимок экрана 2024-08-07 в 16 10 34" src="https://github.com/user-attachments/assets/6e36a68f-1b22-4c1c-bffb-68b5d0cfbffe">

**Environment details:**
Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
Indigo Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5
