### ISSUE TITLE
HELM 2 support: variant monomers

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/Indigo#2188]
Import/export variant monomers to HELM 2

**Comment by AlexeyGirin** [comment]
Verified with issues
**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10
