### ISSUE TITLE
next() always returns true when using enumerateId from Java bindings

### ISSUE THREAD

**Issue by dan2097** [epam/Indigo#220]
Tested with bingo-nosql 1.4.0-beta.r0, as this is still the latest on Maven Central.

```
Indigo indigo = new Indigo();
Bingo bingo = Bingo.createDatabaseFile(indigo, "C:/temp/bingodb", "molecule");
bingo.insert(indigo.loadMolecule("C"));
bingo.insert(indigo.loadMolecule("CC"));

BingoObject enumerator = bingo.enumerateId();
do {
  System.out.println("id: " + enumerator.getCurrentId());
}
while (enumerator.next());
```

Outputs:
```
id: 0
id: 1
Exception in thread "main" com.epam.indigo.BingoException: BingoArray: incorrect idx 2 (size=2)
	at com.epam.indigo.Bingo.checkResult(Bingo.java:91)
	at com.epam.indigo.BingoObject.getCurrentId(BingoObject.java:53)
```

I think it would actually be more consistent with APIs like searchSub if you had to call next initially before a value is populated, I wonder whether this is whether that's what the bug actually is. One would then write:
```
while (enumerator.next()) {
  System.out.println("id: " + enumerator.getCurrentId());
}
```

-----
Unrelatedly to this issue, are there any performance differences between having sequential Bingo Ids (as occurs if you don't specify an id) and non-sequential ids?
I also noticed that Bingo is an optimize method, assuming this is intended for public use it would be useful for this to be documented e.g. when is it safe to call, what effect does it have?

**Comment by yuriiq** [comment]
I suppose it would be more consistent to implement java.util.Enumeration interface. One would then write:
```
while (enumerator.hasMoreElements()) {
  System.out.println("id: " + enumerator.nextElement().id());
}
```

**Comment by yuriiq** [comment]
Perhaps it would be better to implement java.util.Enumeration interface?
