### ISSUE TITLE
System wipe out half of molecules on the canvas if Layout feature applied

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2200]
**Steps to Reproduce**
1. Go to Micro mode
2. Load from file (unzip first): [System wipe out half of molecules on the canvas if Layout feature applied.zip](https://github.com/user-attachments/files/16540090/System.wipe.out.half.of.molecules.on.the.canvas.if.Layout.feature.applied.zip)
![image](https://github.com/user-attachments/assets/9ee8fb1a-f50e-4599-90bc-b747dd7e3298)
3. Click on Layout button

**Actual behavior**
One molecule and arrow disappears
![image](https://github.com/user-attachments/assets/a88364c0-f546-4dc0-ba2c-79dddbc2ef30)

**Expected behavior**
All elements on the canvas remain on the canvas
![image](https://github.com/user-attachments/assets/e7e90ff9-4e15-4be0-b738-c2821261cfe4)

**Versions**
- Ketcher Version 2.24.0-rc.1 Build at 2024-08-06; 19:17:47
- Indigo Toolkit Version 1.23.0-rc.1.0-g85f89b8f5-wasm32-wasm-clang-19.0.0
- Windows 10 Pro
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)

KUDOS to @AleksandrParamonoff

**Comment by split-ends** [comment]
Successfully verified:
![2024-09-06_16h27_02](https://github.com/user-attachments/assets/4b0bdfb9-4ec5-4cb6-9664-6b397841bfe1)

**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
Windows 11 Enterprise
