### ISSUE TITLE
SVG image support in CDX/CDXML

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#2209]
**Pre-requirement** #2162

**Background**
As SVG-file can be embedded to KET-format it should be possible to export and import it from/into embedded CDX/CDXML graphics.

**Solution**
Implement WMF-EMF<->SVG conversion

**Comment by yauhen-karmyzau** [comment]
SVG is not supported by CDX/CDXML format.

If user saves canvas with SVG images to CDX/CDXML, than the images should be replaced by "Image is not supported" icon keeping original image sizing.
![Image](https://github.com/user-attachments/assets/c57a2952-17bb-4c5a-a6f4-f53b9c52d2cd)

**Comment by Zhirnoff** [comment]
Pre-tested.
![2024-09-30_11h20_44](https://github.com/user-attachments/assets/df56d0dd-1dd7-4165-96ab-3c1def56da34)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.4]
**Indigo version** 
[Version 1.25.0-dev.2]

**Comment by Zhirnoff** [comment]
Tested.
Before save to CDX/CDXML
![2024-10-08_16h43_12](https://github.com/user-attachments/assets/0fa4132d-c48a-4aba-ba99-43073acc1d41)
After load CDX/CDXML
![2024-10-08_16h42_25](https://github.com/user-attachments/assets/9fa3b961-4ef8-463d-a3b1-eebde896d17a)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]
