### ISSUE TITLE
Layout for 1-step reactions is broken

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#2213]
**Steps to Reproduce**
1. Draw any reaction:

![image](https://github.com/user-attachments/assets/5b78ed2c-706e-4acc-bbd6-72bd361b9fbe)

2. Apply layout

**Expected behavior**
![image](https://github.com/user-attachments/assets/f1fae713-49fb-462b-a52d-47ab0bc170c3)

**Actual behavior**
![image](https://github.com/user-attachments/assets/5b927093-674a-4c6c-a388-3006e874255d)

**Comment by AlexeyGirin** [comment]
Fixed.
Smart layout OFF
![image](https://github.com/user-attachments/assets/7b542321-ad50-42c8-9538-462a29d2b106)

Smart layout ON
![image](https://github.com/user-attachments/assets/51f002e5-b0b3-4eb5-a07b-e54d0685b843)
- Ketcher Version 2.24.0-rc.2 Build at 2024-08-14; 19:00:14
- Indigo Toolkit Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0
- Chrome Version 127.0.6533.100 (Official Build) (64-bit)
- Win10

**Comment by ivanmaslow** [comment]
Also, in scope of this issue these two defects were fixed, structures are just centered after layout:
- https://github.com/epam/Indigo/issues/2231:
![image](https://github.com/user-attachments/assets/182009bb-fa15-418f-9c5d-482eb6067cea)
- https://github.com/epam/Indigo/issues/2230:
![image](https://github.com/user-attachments/assets/f57cd004-1533-4037-a719-e31cdd886f68)

Env details:
- Ketcher [Version 2.24.0-rc.2] Build at 2024-08-14; 19:00:14
- Indigo Version 1.23.0-rc.2.0-g6a2a7526a-wasm32-wasm-clang-19.0.0
- OS: Windows 11 Enterprise
- Browser: Crhome, Version 127.0.6533.119 (Official Build) (64-bit)
