### ISSUE TITLE
The wrong direction of the arrows when exporting from CDXML (or CDX, base64 cdx) format and two retrosynthetic arrows

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2217]
**Steps to Reproduce**
1. Open Ketcher
2. Add file 
[4 mol.ket.zip](https://github.com/user-attachments/files/16561201/4.mol.ket.zip)
or create manually
<img width="1301" alt="Снимок экрана 2024-08-09 в 14 34 37" src="https://github.com/user-attachments/assets/f7e6bb45-30c5-47f9-8ae7-c1ebdc827990">

3. save to CDX (or CDXML, base64 cdx) format
4. open saving file on the canvas

**Expected behavior**
Reaction should be loaded without changing order of components

**Actual behavior**
The retrosynthetic arrows are pointing in the other direction.
<img width="1292" alt="Снимок экрана 2024-08-12 в 13 17 43" src="https://github.com/user-attachments/assets/a539507d-43e7-43e6-a62c-3edefbe93c95">

**Environment details:**
Ketcher Version 2.23.0-rc.3 Build at 2024-08-08; 13:17:49
Indigo Version 1.24.0-dev.1.0-g5561a82a1-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

Issue found while testing https://github.com/epam/Indigo/issues/2071

**Comment by AlexeyGirin** [comment]
Verified. Follow up bug created: https://github.com/epam/Indigo/issues/2558
![image](https://github.com/user-attachments/assets/c44d60bc-ad2f-4935-aaa6-5ac9024d88db)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
