### ISSUE TITLE
The retrosynthetic arrow is not displayed when export file in CDXML, CDX, base64 CDX formats and arrow is vertical

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2219]
**Steps to Reproduce**
1. Open Ketcher
2. Add file 
[arr vert.ket.zip](https://github.com/user-attachments/files/16582011/arr.vert.ket.zip)
or create manually
<img width="506" alt="Снимок экрана 2024-08-12 в 15 03 56" src="https://github.com/user-attachments/assets/7adfa4fa-3716-44bb-8d5e-9ec4d00f8d17">

3. save to CDXML format (or CDX, base64 cdx)
4. open saving file on the canvas

**Expected behavior**
Reaction should be saved/loaded without changing order of components

**Actual behavior**
The retrosynthetic arrow is displayed gorisontal
<img width="621" alt="Снимок экрана 2024-09-17 в 16 45 03" src="https://github.com/user-attachments/assets/74eb210c-ca93-431c-be97-70390e1e3e04">

**Environment details:**
Ketcher Version 2.25.0-rc.2 Build at 2024-09-14; 10:47:47
Indigo Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.6

Issue found while testing https://github.com/epam/Indigo/issues/2071

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/cb9e548f-f3cd-4829-b5d5-3bb8e0c971aa)
- Ketcher Version 2.26.0-rc.4 Build at 2024-10-18; 17:00:39
- Indigo Toolkit Version 1.25.0-rc.3.0-g795119115-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.59 (Official Build) (64-bit)
- Win10
