### ISSUE TITLE
The diagonally retrosynthetic arrow becomes horizontal after export from the CDXML file (or CDX, base64 cdx)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2221]
**Steps to Reproduce**
1. Open Ketcher
2. Add file 
[arr diagonally.ket.zip](https://github.com/user-attachments/files/16588766/arr.diagonally.ket.zip)

or create manually
![Снимок экрана 2024-08-12 в 17 11 16](https://github.com/user-attachments/assets/2ebaba33-7266-4ec4-9224-62f64496a65a)

3. save to CDXML (or CDX, base64 cdx) format
4. open saving file on the canvas

**Expected behavior**
Reaction should be saved/loaded without changing order of components

**Actual behavior**
The arrow has become horizontal
![Снимок экрана 2024-08-12 в 17 12 44](https://github.com/user-attachments/assets/9d0dd3aa-1eb0-4b8f-bcd8-53ed474f0ecf)

**Environment details:**
Ketcher Version 2.23.0-rc.3 Build at 2024-08-08; 13:17:49
Indigo Version 1.24.0-dev.1.0-g5561a82a1-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

Issue found while testing https://github.com/epam/Indigo/issues/2071

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/6421fe77-6282-4765-ac70-de0a2e39484b)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
