### ISSUE TITLE
Save single pathway reaction to RDF Format

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2235]
As a **User**, I want to have the ability to save my pathway reaction in RDF format, So that I can easily exchange data with other applications that use the same format.

**Acceptance Criteria:**
- Saved single pathway reaction in RDF (with multi-tail arrow) can be loaded in Ketcher with appropriate positions and layers 
- If user saves empty multi-tail to RDF it should work like in case when user saves empty arrow to RXN (can be saved, but the error on load), the same approach when we have only products or reactants (can be saved with reactants products 0 1, 1 0)
- We consider that RDF works only with multi-tails, so if we save single reaction with pathway reaction to RDF, after loading from RDF both of them will be presented on Canvas with multi-tails
- In this phase we are ignoring reagents for save to RDF

**Comment by yauhen-karmyzau** [comment]
Implemented in scope #2237
