### ISSUE TITLE
Pathway reactions and multi-tail support in CDX/CDXML/Base 64 CDX

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2238]
Saved pathway in CDX can be loaded in Ketcher with appropriate positions.
Multi-tailed arrows should be ignored as CDX is not support such items.

**Comment by AlexeyGirin** [comment]
No development needed. Need to test and create bugs if any

**Comment by Zhirnoff** [comment]
Tested. Reopened.
Currently, when saving cascade reactions in CDXML, some elements are lost when opening the saved file (see screenshots). When saving in CDX, the file cannot be opened, and it's impossible to save in Base64CDX. I checked, and we already have a bug for this: https://github.com/epam/Indigo/issues/2433. A fix is planned to be reviewed in 1.25.0-rc.2

**Original structure:**
![2024-10-09_15h57_31](https://github.com/user-attachments/assets/bd08784d-469c-4c61-a8ee-2de26e7601c5)

**After opening from CDXML:**
![2024-10-09_15h58_04](https://github.com/user-attachments/assets/532bfd35-8539-461e-9c82-34c0f3c553bd)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-10-15_16h05_04](https://github.com/user-attachments/assets/8ad5756c-85ed-4634-b1e8-e30daa34bea6)
![2024-10-15_16h05_58](https://github.com/user-attachments/assets/e5f41a27-fb9c-4fa8-a7c0-07fd064d16ad)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.2]
**Indigo version** 
[Version 1.25.0-rc.2]
