### ISSUE TITLE
Add ACS style rendering options to customize molecule elements 

### ISSUE THREAD

**Issue by AleksandrParamonoff** [epam/Indigo#2246]
**Background**
Currently, the ACS style settings are not supported by Indigo rendering module(PNG and SVG output formats).

**Requirements**
The following parameters should be processed for rendering:
`render-bond-spacing` (default = 0.18 i.e. bondLength * 0.18)
`render-stereo-bond-width`
`render-stereo-bond-width-unit`
`render-hash-spacing`
`render-hash-spacing-unit`

**Additional context**
related issues: 
https://github.com/epam/Indigo/issues/2175
https://github.com/epam/Indigo/issues/2176

**Comment by AlexeyGirin** [comment]
[ACS-StyleGuide.pdf](https://github.com/user-attachments/files/16849103/ACS-StyleGuide.pdf)

**Comment by AnnaKosol** [comment]
Verified

**Environment**
https://rc.test.lifescience.opensource.epam.com/KetcherDemoSA/index.html
Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
MacOs
Chrome 129.0.6668.71 (Official Build) (arm64)
