### ISSUE TITLE
Unable to save CHEM SS3 to IDT format 

### ISSUE THREAD

**Issue by ViktoriaTkacheva** [epam/Indigo#2257]
**Steps to Reproduce**
1.	Switch to the Macro mode – the Flex mode
2.	Open the tab “CHEM” and click on SS3
3.	Add SS3 on the canvas
4.	Save canvas to IDT file format
5.	In the Error message click on the “Close” button

**Expected behavior**
There is no error on the canvas and in the Console. CHEM SS3 is saved to IDT file format

**Actual behavior**
There is an error on the canvas and an error in the Console: 
Blocked aria-hidden on a <div element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. <div tabindex=​"0" role=​"combobox" aria-controls=​":​r3:​" aria-expanded=​"false" aria-haspopup=​"listbox" class=​"MuiSelect-select MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-qiwgdb">​…​</div>​

<img width="768" alt="image" src="https://github.com/user-attachments/assets/d610578e-258f-47ba-83e4-cba22f7d1c9b">

<img width="247" alt="image" src="https://github.com/user-attachments/assets/e7657a8f-8983-451a-a511-5a3599ee096d">

[localhost-1724756865888.log](https://github.com/user-attachments/files/16761643/localhost-1724756865888.log)

Can be related to https://github.com/epam/Indigo/issues/2033

**Environment details:**
 - OS: Windows 11 Pro (version 22H2) 
 - Browser: Сhrome
 - Version: (127.0.6533.122) x64

**Ketcher version**  2.24.0-rc.1, Build at 2024-08-23; 12:23:08

**Indigo version**  1.24.0-dev.4.0

Issue found while testing https://github.com/epam/ketcher/issues/4926

**Attachments**

https://github.com/user-attachments/assets/024932cb-c04a-4200-bab6-d147095d8283

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-10-15_17h18_02](https://github.com/user-attachments/assets/aa5d1409-ac52-4287-be50-34efa97fb5c8)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.2]
**Indigo version** 
[Version 1.25.0-rc.2]
