### ISSUE TITLE
Error message is wrong for wrong probability number that is greater than 100 (PEPTIDE1{(A:10,C:1000)}$$$$V2.0)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2272]
**Steps to Reproduce**
1. Toggle to Macromolecules mode
2. Load using Paste from clipboard way: `PEPTIDE1{(A:10,C:1000)}$$$$V2.0`
![image](https://github.com/user-attachments/assets/9d56d86a-060d-47f6-80b0-847674316125)

**Actual behavior**
Error message is wrong: `Convert error! {}`
![image](https://github.com/user-attachments/assets/92231ccf-732e-4c56-8da0-04f2f17dcbe6)

**Expected behavior**
Error message should report that probability number is invalid (and optionally - greater than 100)

**Versions**
- Version 2.24.0-rc.1 Build at 2024-08-28; 15:19:12
- Indigo Toolkit Version 1.24.0-dev.5.0-g382df81fd-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/Indigo/issues/2188

**Comment by AliaksandrDziarkach** [comment]
This is ketcher issue. It already fixed.

**Comment by AlexeyGirin** [comment]
Alternative issue created - https://github.com/epam/Indigo/issues/2322
