### ISSUE TITLE
Error message is wrong for invalid range (PEPTIDE1{([Aad]+[Abu]+[Aca]+[Aib]+[Apm])'5-i'}$$$$V2.0)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2278]
**Steps to Reproduce**
1. Toggle to Macromolecules mode
2. Load using Paste from clipboard way: `PEPTIDE1{([Aad]+[Abu]+[Aca]+[Aib]+[Apm])'5-i'}$$$$V2.0`
![image](https://github.com/user-attachments/assets/4694457a-17c3-4d5a-9505-785e6b76c732)

**Actual behavior**
Error message is wrong: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: Repeating not supported now.'`
![image](https://github.com/user-attachments/assets/6c9aca9a-201e-42fb-9531-dd65c7cf7b39)

**Expected behavior**
Error message should report that range is not supported now (in any case - message about repeating is irrelevant)

**Versions**
- Version 2.24.0-rc.1 Build at 2024-08-28; 15:19:12
- Indigo Toolkit Version 1.24.0-dev.5.0-g382df81fd-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/Indigo/issues/2188

**Comment by AliaksandrDziarkach** [comment]
According to documentation:

> 5.2.4.2 Monomer repeating units
A single monomer or a group of monomers can be repeated multiple times. The repeating unit is marked as the repeat unit count enclosed in single quote characters immediately after the monomer or a group of monomers that are enclosed in round brackets. The repeat unit count can be a single value or a range of repeats. The range is defined with a “-“ between the two numbers.

So message is correct.

**Comment by AlexeyGirin** [comment]
Verified.
