### ISSUE TITLE
Regress: R1-R2 connected unsplit nucleotides saved in FASTA as separate squences 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2280]
**Steps to Reproduce**
1. Toggle to Macromolecules mode
2. Load from file: [Regress_ R1-R2 connected unsplit nucleotides saved in FASTA as separate squences.zip](https://github.com/user-attachments/files/16800249/Regress_.R1-R2.connected.unsplit.nucleotides.saved.in.FASTA.as.separate.squences.zip)
![image](https://github.com/user-attachments/assets/5589e2d1-caeb-4609-91b1-9d5d31c8f571)
3. Try to save to FASTA

**Actual behavior**
System saves two monomers apart:
```
>Sequence1
A
>Sequence2
A
```

**Expected behavior**
System saves two monomers in one sequence:
```
>Sequence1
AA
```

**Versions**
- Version 2.24.0-rc.1 Build at 2024-08-28; 15:19:12
- Indigo Toolkit Version 1.24.0-dev.5.0-g382df81fd-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/Indigo/issues/1755

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-09-05_14h59_22](https://github.com/user-attachments/assets/826e48e5-d3df-4dcb-b1ea-d42e17666f96)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.24.0-rc.1]
