### ISSUE TITLE
Wrong smiles in HELM

### ISSUE THREAD

**Issue by AliaksandrDziarkach** [epam/Indigo#2287]
Molecules saved to HELM generate SMILES with non-existing cycles:
`PEPTIDE1{A}|CHEM1{[C(N%91)=C%92.[*:1]%92.[*:2]%91 |$;;;_R1;_R2$|}$CHEM1,PEPTIDE1,1:R2-1:R1$$$V2.0`
Also all molecules repited for each polymer.

**Comment by AlexeyGirin** [comment]
Verified.

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10
