### ISSUE TITLE
Preview: Margin between catalyst and arrow isn't changed and displayed not correct 

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2291]
**Summary**
Regarding task https://github.com/epam/Indigo/issues/2176 implemented margins and layout

**Steps to Reproduce**
1. Change Reaction component margin size in the Settings to 80 px
2. Bond length in the Settings is 20 px
3. add schema or create manually
[Margin between catalyst and arrow doesn't change.ket.zip](https://github.com/user-attachments/files/16849231/Margin.between.catalyst.and.arrow.doesn.t.change.ket.zip)

<img width="1138" alt="Снимок экрана 2024-09-03 в 14 49 47" src="https://github.com/user-attachments/assets/3cea0b82-6eb7-4b12-8051-618ec880e57c">

4. click on layout

**Expected behavior**
all margins are correct and correspond to settings margin

**Actual behavior**
<img width="1268" alt="Снимок экрана 2024-09-03 в 14 52 30" src="https://github.com/user-attachments/assets/f71d6297-3857-43e0-a2de-71683c2b9c3f">

If change Reaction component margin size in the Settings to 50 px and click on the layout again, margin is not changed
<img width="1133" alt="Снимок экрана 2024-09-03 в 15 19 40" src="https://github.com/user-attachments/assets/1fd59cd5-f6d5-49d0-a22c-54bf6ace97e0">

**Environment details:**
https://nightly.test.lifescience.opensource.epam.com/KetcherDemo/5365-send-acs-parameters-for-layout-and-convert-backend-functions/index.html
Branches:
Ketcher: 5365-send-acs-parameters-for-layout-and-convert-backend-functions
Indigo: feature/2176-add-acs-style-reaction-layout
MacOs 14.6.1
Chrome Версия 127.0.6533.120 (Официальная сборка), (arm64)

**Comment by AnnaKosol** [comment]
Verified on https://ci.test.lifescience.opensource.epam.com/5365-send-acs-parameters-for-layout-and-convert-backend-functions/feature/2176-add-acs-style-reaction-layout/20240913-071121/micro/KetcherDemoSA/index.html
![Image](https://github.com/user-attachments/assets/8fae5993-36cc-4b50-a021-2299eef5e3ad)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/e801400f-ec79-4a6d-bfbe-e35058f8e834)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
