### ISSUE TITLE
Preview: Margin is not correct for reaction which located after arrow

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2292]
**Summary**
Regarding task https://github.com/epam/Indigo/issues/2176 implemented margins and layout

**Steps to Reproduce**
1. Change Reaction component margin size in the Settings to 40 px
2. Bond length in the Settings is 20 px
3. Add to Canvas 
[Margin is not correct for reaction which located after arrow.ket.zip](https://github.com/user-attachments/files/16849675/Margin.is.not.correct.for.reaction.which.located.after.arrow.ket.zip)

4. Click on layout

**Expected behavior**
Margins from right side and left side of arrow are the same

**Actual behavior**
![Снимок экрана 2024-09-03 в 15 36 47](https://github.com/user-attachments/assets/38cf5a35-2c56-4cd7-afda-859872c48cd2)

**Environment details:**
 https://nightly.test.lifescience.opensource.epam.com/KetcherDemo/5365-send-acs-parameters-for-layout-and-convert-backend-functions/index.html
Branches:
Ketcher: 5365-send-acs-parameters-for-layout-and-convert-backend-functions
Indigo: feature/2176-add-acs-style-reaction-layout
MacOs 14.6.1
Chrome Версия 127.0.6533.120 (Официальная сборка), (arm64)

**Comment by AnnaKosol** [comment]
Verified on https://ci.test.lifescience.opensource.epam.com/5365-send-acs-parameters-for-layout-and-convert-backend-functions/feature/2176-add-acs-style-reaction-layout/20240913-071121/micro/KetcherDemoSA/index.html

**Comment by AnnaKosol** [comment]
Verified on https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
![Image](https://github.com/user-attachments/assets/5fc1020b-c53d-43ba-b30f-37322f858f7f)

with new parameters from frontend

**Environment**
Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
Indigo branch 2175-acs-style-rendering
Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/2e53116b-10d0-4bd0-a89e-28c472fa4bb8)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
