### ISSUE TITLE
Import of variant monomers from Sequence doesn't work for RNA and FASTA for RNA/DNA

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2303]
**Steps to Reproduce**
1. Toggle to Macro - Flex
2. Load using paste from clipboard way RNA sequence (or FASTA): `RYMKSWHBVDN`
![image](https://github.com/user-attachments/assets/83a5dc4a-4aef-4bc7-8411-ba949cdefe8f)

**Actual behavior**
System throws exception: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages`
![image](https://github.com/user-attachments/assets/750698b2-1c6e-4e82-9804-cd4ba577f2b0)

**Expected behavior**
No exception. Loading works as intended
![image](https://github.com/user-attachments/assets/1695da85-90f9-43c6-a8d8-2fbab8c35827)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2015

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-09-19_12h22_12](https://github.com/user-attachments/assets/4aac24c2-0da6-432b-88e1-6c9d11aa717b)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.3]
**Indigo version** 
[Version 1.24.0-rc.3]
