### ISSUE TITLE
Update layout for pathway reaction on canvas

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2309]
Building pathway reactions, we align arrow's starting points vertically:
![Image](https://github.com/user-attachments/assets/86d0ef7e-8abb-42dc-85dd-d6cccc795e4e)

**Pathway reaction layout should be updated to meet the following requirements:**
1. Single arrow type should be changed to have the same style head arrow, as we use for multi-tailed arrows.
2. Pathway reaction should be divided into sections and each element should be centred in the section.
3. Margin between sections must be equal to _reaction-component-margin-size_ (distance between an arrow's right/left point and closest bond of the widest molecule in right/left columns). 
4. Section width must be equal to the widest molecule in the section.
5. Multi-tailed arrows' and single arrows' start and and points must be aligned vertically in a section as well.
6. Default size of arrows in a pathway reaction must be changed:
    1. Head arrow's line must be 6.5 default sizes of the bond
![Image](https://github.com/user-attachments/assets/6a4b5e6a-3cf6-4cfe-b175-795f1993217e)

![Image](https://github.com/user-attachments/assets/7b0a08f8-ec7a-4418-a34e-45afdcf85599)

**Comment by ivanmaslow** [comment]
Tested in scope of Load RDF task, for more details check comments here - https://github.com/epam/Indigo/issues/2102, cascade reactions are displayed with correct alignment and filled arrow style.
Two defects are detected, they should be retested after fixes:
- https://github.com/epam/Indigo/issues/2453
- https://github.com/epam/Indigo/issues/2498

**Comment by ivanmaslow** [comment]
New defects related to length are detected:
- https://github.com/epam/Indigo/issues/2555
- https://github.com/epam/Indigo/issues/2583
