### ISSUE TITLE
Result string of indigoData is not properly terminated

### ISSUE THREAD

**Issue by achher** [epam/Indigo#231]
Add data to a DataSGroup:
m.addDataSGroup([0, 1, 2, 3], [], "color", "0.155, 0.55, 0.955")
When reading the data:
nId:= indigoGetDataSGroup(index);
aString:= indigoData(nId)

the resulting string is not terminated properly by 0-character:
'0.155, 0.55, 0.955'#$00AD'º'#$D'ð'#$00AD'º'#$D'ð'#$00AD'º'#$D'ð'#$00AD'º'#$D'ð'#$00AD'ºîþ««««««««îþ'

**Comment by mkviatkovskii** [comment]
Dear @achher,
This issue should be fixed in latest version of Indigo (1.4.3). Could you please take a look and let us know if you are still facing the problem?

**Comment by achher** [comment]
I can confirm the issue is fixed in Indigo (1.4.3). Many thanks.
