### ISSUE TITLE
The schema with retrosynthetic arrow is changed the direction after exporting from CDXML (CDX, base64cdx)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2311]
**Steps to Reproduce**
1. Add to Ketcher schema
[retrosynt arr reverse.ket.zip](https://github.com/user-attachments/files/16885848/retrosynt.arr.reverse.ket.zip)
or create manually
<img width="774" alt="Снимок экрана 2024-09-05 в 09 52 24" src="https://github.com/user-attachments/assets/6214c23d-4857-4b88-8714-924704ff987b">

2. Save to CDXML format (CDX, base64cdx)
3. Open saving file on the Canvas

**Expected behavior**
The schema is displayed as it was created
<img width="774" alt="Снимок экрана 2024-09-05 в 09 52 24" src="https://github.com/user-attachments/assets/6214c23d-4857-4b88-8714-924704ff987b">

**Actual behavior**
The schema  is changed the direction
<img width="667" alt="Снимок экрана 2024-09-05 в 09 54 18" src="https://github.com/user-attachments/assets/952726b1-2382-4a18-9ad6-8fb9c6c26cdf">

**Environment details:**
Ketcher Version: 2.25.0-rc.1 Build at 2024-09-04; 09:15:28
Indigo Version: 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Version: Version 128.0.6613.113 (Official Build) (64-bit)
MacOs 14.6

Issue found while testing https://github.com/epam/Indigo/issues/2071

**Comment by AlexeyGirin** [comment]
Seems to be fixed.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/f82f3f61-34b2-4fac-9a84-e2418fa828fa)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
