### ISSUE TITLE
The reaction with retrosynthetic arrow is displayed not correct after clicking on Aromatize, Dearomatize, Calculate CIP, Add explicit hydrogens

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2318]
**Steps to Reproduce**
1. Open file on the Canvas
[error with aromatize.ket.zip](https://github.com/user-attachments/files/16891996/error.with.aromatize.ket.zip)

or create manually
![Снимок экрана 2024-09-05 в 13 33 37](https://github.com/user-attachments/assets/c7d4b0c8-c938-4988-8e07-5d025c4605b5)

2.1 Click on Aromatize
**Actual behavior**
the reaction is changed the direction and location
![Снимок экрана 2024-09-05 в 13 34 44](https://github.com/user-attachments/assets/81df215c-d2ec-44d1-b8b5-96f66325a8a8)

2.2 Click on Dearomatize
 **Actual behavior**
the reaction is changed the direction and location
![Снимок экрана 2024-09-05 в 13 36 59](https://github.com/user-attachments/assets/de60e7c2-cdb3-4de0-ac1a-d2150b45c16f)

2.3 Click on Calculate CIP
 **Actual behavior**
the reaction is changed the direction and location
![Снимок экрана 2024-09-05 в 13 37 56](https://github.com/user-attachments/assets/bc94f7c7-e897-44a4-8ad7-97cb1151a071)

2.4 Click on Add explicit hydrogens
**Actual behavior**
the reaction is changed the direction and location
![Снимок экрана 2024-09-05 в 13 39 38](https://github.com/user-attachments/assets/8514755b-80cc-404f-9328-e4d92e00d041)

**Expected behavior**
the reaction is not changed the direction and location and Aromatize, Dearonatize, Calculate CIP, Add explicit hydrogens are applied correctly

**Environment details:**
Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

Issue found while testing https://github.com/epam/Indigo/issues/2071

**Comment by AnnaKosol** [comment]
<img width="830" alt="Снимок экрана 2024-09-19 в 12 19 23" src="https://github.com/user-attachments/assets/57f9b19e-13af-405a-8bc2-02faac879d43">

For reaction the behavior is the same

After clicking on aromatize
<img width="957" alt="Снимок экрана 2024-09-19 в 12 21 09" src="https://github.com/user-attachments/assets/9b3d102f-c466-4661-a9fd-604fdf360df8">

After clicking on explicit hydrogens
<img width="1210" alt="Снимок экрана 2024-09-19 в 12 22 16" src="https://github.com/user-attachments/assets/420f2b6e-4b81-46d0-ad9c-a176394c436b">

**Environment**
Ketcher Version 2.25.0-rc.3 Build at 2024-09-18; 16:24:03
Indigo Version 1.24.0-rc.3.0-g692080c62-wasm32-wasm-clang-19.0.0
MacOs 14.6

**Comment by AliaksandrDziarkach** [comment]
Now behavior same as other arrows.

**Comment by AnnaKosol** [comment]
verified
<img width="844" alt="Снимок экрана 2024-09-19 в 18 39 48" src="https://github.com/user-attachments/assets/776bb8d5-ee27-44bc-8418-228327f41130">

**Environment**
Ketcher Version 2.25.0-rc.3 Build at 2024-09-18; 16:24:03
Indigo Version 1.24.0-rc.3.0-g692080c62-wasm32-wasm-clang-19.0.0
Chrome Версия 128.0.6613.138
MacOs 14.6
