### ISSUE TITLE
Export of  multi-character monomer IDs  inside ambiguous monomer works wrong (RNA1{R([5eU],[Xan],[psiU])P}$$$$V2.0)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2321]
**Steps to Reproduce**
1. Toggle to Macro - Sequence mode
2. Load from clipboard way: `RNA1{R([5eU],[Xan],[psiU])P}$$$$V2.0`
![image](https://github.com/user-attachments/assets/d43fe759-4456-45a9-8cd4-097c59297a47)
3. Save canvas to HELM

**Actual behavior**
Export result has no square brackets for multi-character monomer IDs
![image](https://github.com/user-attachments/assets/1846ce44-3488-4e0d-a450-7c4e62523091)

**Expected behavior**
Monomers with multi-character IDs must be enclosed in square brackets “[]” - `RNA1{R(5eU,Xan,psiU)P}$$$$V2.0`

As per requirement: 
![image](https://github.com/user-attachments/assets/030fab81-5735-4a95-99b9-a511bb2e8568)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2188

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-09-19_12h42_16](https://github.com/user-attachments/assets/a220dddf-181a-4135-9008-ccfa9e7cb9d9)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.3]
**Indigo version** 
[Version 1.24.0-rc.3]
