### ISSUE TITLE
Percent values for alternative groups should be verified before load

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2322]
**Steps to Reproduce**
1. Toggle to Macro - Sequence mode
2. Load from clipboard way: `PEPTIDE1{(D:10,N:90,I)}$$$$V2.0`
![image](https://github.com/user-attachments/assets/499fc1cf-e833-4ae0-b3aa-46444bc00023)

**Actual behavior**
System puts on the canvas ambiguous monomer
![image](https://github.com/user-attachments/assets/d4c7ba3f-92f2-4bc7-819e-8cdd31ed6c38)

**Expected behavior**
System should throw exceptions:
1. If at least one percent value defined for one of many monomers inside ambiguous monomer - percentage values for other monomers must be defined as well (this is mandatory)
2. Sum of all percent values must be equal 100
3. Every value should be greater than 0 and less than 100

as per @AlexanderSavelyev decision

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2188

**Comment by AliaksandrDziarkach** [comment]
According to documentation sum of probabilities could be not equal to 100:
![image](https://github.com/user-attachments/assets/1cb0f55e-c711-46a4-ba94-baa8900c8ef4)
