### ISSUE TITLE
System loads DNA bases instead of RNA ones during IDT import

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2324]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load IDT from paste from clipboard way: `rYrKrHrBrDrN`
![image](https://github.com/user-attachments/assets/d5d7d3e8-670b-45ff-aa5d-d73c4c31f517)
3. Hover mouse over every base

**Actual behavior**
System shows that every ambiguous base contains Thymine
![image](https://github.com/user-attachments/assets/965ab090-4e16-4968-b8d8-71e5e7e95e9a)

**Expected behavior**
System shows that every ambiguous base contains Uracil
![image](https://github.com/user-attachments/assets/ad06de41-00a9-4843-9ea6-f94ebd3256dd)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/1619

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/user-attachments/assets/f963567e-95c1-4b36-9165-43a64b935bf3


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
