### ISSUE TITLE
Error diagnostic is not clear in case of wrong percent value type

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2330]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load IDT from paste from clipboard way: `(Y:003300a6)`
![image](https://github.com/user-attachments/assets/669a6307-05ab-4caa-8839-59991f9574b0)

**Actual behavior**
System throws an error: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'stof: no conversion'`
![image](https://github.com/user-attachments/assets/aee4468b-4eb0-4afb-98a5-8c6bd8ec25d8)

**Expected behavior**
I would prefer to have it more exact - something like - digit expected but got letter

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/1619

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2025-01-06_17h48_56](https://github.com/user-attachments/assets/c322a61a-4a72-42ad-94e7-9dad62c07afc)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
