### ISSUE TITLE
Error message should use "ambiguous monomer" instead of "variant monomer"

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2332]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load IDT from paste from clipboard way: `(Y:)`
![image](https://github.com/user-attachments/assets/68b1e83e-756e-4036-9a4b-ace842e57a9e)

**Actual behavior**
System throws an error: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'Invalid IDT variant monomer (Y:)'`
![image](https://github.com/user-attachments/assets/0512383c-61f2-4d6e-b29d-dfdb5b7135b9)

**Expected behavior**
System throws an error: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'Invalid IDT ambiguous monomer (Y:)'`

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/1619

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2025-01-02_11h41_49](https://github.com/user-attachments/assets/a0488784-d81c-4cb2-b62e-768652cb2dc5)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
