### ISSUE TITLE
Export of HELM of micromolecules with R-group and same number AP doesn't work

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2347]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load from file: [Export of HELM of micromolecules with inline SMILES doesn't work.zip](https://github.com/user-attachments/files/16945548/Export.of.HELM.of.micromolecules.with.inline.SMILES.doesn.t.work.zip)
![image](https://github.com/user-attachments/assets/32ee29f3-dca9-4bed-a6e9-3cae6c62af78)
3. Save canvas to HELM
`CHEM1{[O[C@H]1[C@H](C[*:1])[C@H](O)[C@H](O)[C@@H](C[*:1][*:2])O1 |$;;;;_R1;;;;;;;_R1;_R2;$|]}|CHEM2{[OCC1([H])O[C@]([*:2][*:1])(O)[C@](C(O)([H])[C@@]1(O)C[*:2])([H])O |$;;;;;;_R2;_R1;;;;;;;;;_R2;;$|]}$CHEM2,CHEM1,1:R2-1:R1$$$V2.0`
4. Load it back as HELM

**Actual behavior**
System throws exception: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: Attachment point should be connected to single atom'`
![image](https://github.com/user-attachments/assets/0adcf524-53a4-4344-abe9-96f61a6a7977)

**Expected behavior**
System loads monomer correct
![image](https://github.com/user-attachments/assets/32ee29f3-dca9-4bed-a6e9-3cae6c62af78)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2189

**Comment by AliaksandrDziarkach** [comment]
As per discussion with @AlexanderSavelyev should be clossed as not planned.
