### ISSUE TITLE
Wrong error message if SMILES phosphate has lack of attachemt point

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2361]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load HELM from paste from clipboard way: `RNA1{R[P(O)(O)(=O)O]}$$$$V2.0`
![image](https://github.com/user-attachments/assets/6d2e23af-2053-41b9-8e23-7ae81bcf8745)

**Actual behavior**
System throws an error: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: Monomer template with class 'Phosphate' and alias 'P(O)(O)(=O)O' not found in monomer librarys'`
![image](https://github.com/user-attachments/assets/864cbd97-efee-4c10-8dca-a996d6455fbf)

**Expected behavior**
System throws an error: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'Ket Base Monomer: Unknown attachment point 'R1' in monomer Mod0'`
![image](https://github.com/user-attachments/assets/1302236a-f57f-479d-ad97-9ac35544f6d3)

**Versions**
- Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
- Indigo Toolkit Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.114 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2189

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2025-01-03_11h50_00](https://github.com/user-attachments/assets/234fdaa1-8ae3-453e-aab3-fe3478dcce02)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
