### ISSUE TITLE
Bingo PostgreSQL Cartridge Substructure Match query not working with generic groups

### ISSUE THREAD

**Issue by Simone99** [epam/Indigo#2378]
**Summary**
Using generic groups seems to be tricky to use for substructure match queries.
In the majority of cases, I wasn't able to get a match out of simple molecules and query molecules with generic groups such as AEL.

**Steps to Reproduce**
1. Install Bingo PostgreSQL cartridge in your database.
2. Run "select bingo.matchsub('CC(=O)CC=C', ('CC(=O)C* |$;;;;AEL$|', '')::bingo.sub);" query in psql.

**Expected behavior**
The result of the query above should be true.

**Actual behavior**
The result of the query above is false.

**Environment details:**
 - Bingo 1.23
 - PostgreSQL 15

**Attachments**
Molecule I'm trying to match: 
![Screenshot from 2024-09-14 11-42-29](https://github.com/user-attachments/assets/67af19ef-c7f1-4aa3-b40c-36f3f8375d6f)
Query molecule: 
![Screenshot from 2024-09-14 11-42-36](https://github.com/user-attachments/assets/a55200e6-ac33-4619-a1f8-658089fcdcaa)

**Additional questions**
I was wondering if all generic groups are described in details alongside an example of sub match anywhere on the website.
I took a look but I was not able to find what I was looking for.

**Comment by AlexanderSavelyev** [comment]
Hi @Simone99  . Unfortunately Indigo and Bingo does not support generic groups.

**Comment by Simone99** [comment]
Thanks for the reply!
