### ISSUE TITLE
After opening a saved HELM file, microstructure name F1 turns into Mod0

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2387]
**Summary**
After opening a saved HELM file, microstructure name F1 turns into Mod0

**Steps to Reproduce**
1. Open file in Macro [Unable.to.save.micro-molecule.connected.to.CHEM.to.HELM.zip](https://github.com/user-attachments/files/16887687/Unable.to.save.micro-molecule.connected.to.CHEM.to.HELM.zip)
2. Save as HELM
3. Open saved file

**Expected behavior**
The structure name look same as before saving.
![2024-09-16_16h20_33](https://github.com/user-attachments/assets/25b8f7ae-8088-4664-a139-861fea954234)

**Actual behavior**
After opening a saved HELM file, microstructure name F1 turns into Mod0
![2024-09-16_16h21_11](https://github.com/user-attachments/assets/a173a3f0-cbd3-4fd6-b1a8-ed478ab6f484)

Saved HELM file [ketcher (2).zip](https://github.com/user-attachments/files/16887696/ketcher.2.zip)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.2]
**Indigo version** 
[Version 1.24.0-rc.2]

**Additional context**
Bug found during testing: 
https://github.com/epam/ketcher/issues/5513

**Comment by AliaksandrDziarkach** [comment]
Not a bug.
HELM can store microstructures only as a CHEM.
