### ISSUE TITLE
IDT mixed base declaration does't work proprtly if used with sugar modifier (r)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2388]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load IDT from paste from clipboard way: `r(B1:00503020)(B1)`
![image](https://github.com/user-attachments/assets/e98a58c1-2200-457e-a87f-b4faa1a1de18)

**Actual behavior**
System throws an error: `Convert error! Given string could not be loaded as (query or plain) molecule or reaction, see the error messages: 'SEQUENCE loader: Unknown mixed base 'B1''`
![image](https://github.com/user-attachments/assets/a00e2053-9f2d-452e-9a67-bd80c4136066)

**Expected behavior**
System loads IDT sequence correct
![image](https://github.com/user-attachments/assets/5098601a-4db6-48ac-9299-307f3f5d8e2a)

As per @ljubica-milovic finding:
![image](https://github.com/user-attachments/assets/abe50952-ddc7-4ae9-a532-ac8f11ea247a)

**Versions**
- Ketcher Version 2.25.0-rc.2 Build at 2024-09-14; 10:47:47
- Indigo Toolkit Version 1.24.0-rc.2.0-g5f2751d70-wasm32-wasm-clang-19.0.0
- Chrome Version 128.0.6613.138 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/1619

**Comment by AliaksandrDziarkach** [comment]
According to IDT site mixed RNA-DNA oligos cannot be specified:
![image](https://github.com/user-attachments/assets/d9cac70d-f23d-486b-addf-a517bc4b58e3)
