### ISSUE TITLE
Preview: Corrupted Multi-Tailed Arrows when saving to SVG/PNG

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2400]
**Summary**
Corrupted Multi-Tail Arrows When Saving to SVG/PNG in Ketcher

**Steps to Reproduce**
1. Create a structure in Ketcher that includes multi-tail arrows.
2. Save the structure as an SVG or PNG file.
3. Observe preview for multi-tail arrows

**Expected behavior**
The multi-tail arrows should be rendered correctly in the saved SVG/PNG file, maintaining their original appearance.

**Actual behavior**
When saving as SVG/PNG, the multi-tail arrows appear distorted, resulting in the visual corruption seen in the attached screenshot (with unusual shapes and misaligned elements replacing the arrows).
![2024-09-18_12h01_50](https://github.com/user-attachments/assets/dbc3c69c-0ace-4d32-8b72-a7eec228a9e2)

**Note:** When a plus sign is present on canvas, multi-tail arrows display correctly in preview window.
![2024-09-18_12h23_29](https://github.com/user-attachments/assets/223fbb3f-a97d-4bae-abc5-fdd06957b7b6)

![2024-09-18_12h26_47](https://github.com/user-attachments/assets/e1b0c95e-2334-4fe8-90ad-ca867f4e8fd1)

**Environment details:**

 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.1]
**Indigo version** 
[Version 1.25.0-dev.1]

Bug found during pre-testing: https://github.com/epam/Indigo/issues/2129

**Comment by yauhen-karmyzau** [comment]
Implemented in scope #2237

**Comment by Zhirnoff** [comment]
Pre-tested. Multi-tailed Arrows are saved without distortion. SVG is saved as PNG.

![2024-10-01_10h34_27](https://github.com/user-attachments/assets/dca14025-e1da-4215-9c33-aa65e3e0e193)
![2024-10-01_10h34_34](https://github.com/user-attachments/assets/62e1a7a2-8a49-4693-a8ff-1275ffc854ab)
![2024-10-01_10h39_00](https://github.com/user-attachments/assets/feaff393-11df-4aee-8ba8-74df6f2404a8)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.25.0-rc.4]
**Indigo version** 
[Version 1.25.0-dev.2]

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. But Multi-Tailed Arrows looks faded. Added bug to 1.25.0-rc.2
![2024-10-08_17h10_25](https://github.com/user-attachments/assets/9c92dfd8-7863-44de-b175-3c5c201e09d5)
![2024-10-08_17h08_41](https://github.com/user-attachments/assets/efe1f35d-24c4-41f1-96b3-e84425392336)
![2024-10-08_17h08_36](https://github.com/user-attachments/assets/f3ce6b46-60d5-44cb-a916-f9cd46308c20)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.1]
**Indigo version** 
[Version 1.25.0-rc.1]
