### ISSUE TITLE
Save Name and Reaction Conditions to RDF Metadata

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2404]
**Background**
Currently, the system lacks the capability to automatically detect and incorporate text annotations (Name and Reaction Conditions) located above reaction arrows into the RDF metadata. Implementing this feature will allow for a more comprehensive representation of reaction diagrams, including textual annotations directly associated with specific reactions and opening them in other applications with RDF support.

**Solution**

1. Text Detection:
    **Objective:** Develop an automated feature in the system that detects text placed above reaction arrows and associates this text with the corresponding reaction.
    **Details:** Utilize text recognition algorithms to identify text blocks positioned strategically above reaction arrows on the canvas.
    If a KET text block will be within TEXTBLOCK_WIDTH/2 x TEXTBLOCK_HEIGHT/2, than this text must be understand as reaction's text.
    Multi-tailed arrow:
    Bottom left point of the text must be positioned inside the box. The box must be stick to spain.
    ![Image](https://github.com/user-attachments/assets/f6b82345-d170-4774-af1d-68ea0c3a14df)

    Simple arrow:
    Bottom center point of the text must be positioned inside the box. The box must be centred.
    ![Image](https://github.com/user-attachments/assets/69c5cf45-a571-481f-891b-42506bfa24ba)

    If there are several text objects in the rectangle, than we should take the closest one: bottom-left point to head arrow x spine and bottom-center point to center of a simple arrow.

2. Text parsing:
    **Objective:** Develop text parsing to recognise reaction's Name and Reaction Conditions.
    **Details:** We should read KET text object and understand text before **the first empty line** as Name and after, as Reaction Conditions.
    If there is no empty line, than we should understand this text as Name only.
    If there is an empty line at the very beginning, than we should understand text as Reaction Conditions.
    If there are several empty lines in the text block, that we should understand all empty lines after the first one as a part of Reaction Conditions.
    ![Image](https://github.com/user-attachments/assets/dba585f2-0115-4e8d-a18b-f34d4e15099f)

3. Insert Name and Reaction Conditions to RDF's metadata
    **Objective:** Name and Reaction Conditions should be added to reaction's metadata while saving to RDF format.
    **Details:** When user saves reactions to RDF, reaction's Name and Reaction Conditions should be added to reaction's metadata as a plain text. Metadata fields should be added after each reaction (RXN) inside RDF in $DTYPE - $DATUM pairs, where $DTYPE is a name of a field and $DATUM is a plain text information.

    If there is no Name or Reaction Condition, than $DATUM field should be "Not available"

    ```
    ...
    11 12  1  0
    11  4  4  0
    M  END
    $DTYPE Name
    $DATUM Reaction name is here
    $DTYPE Reaction Conditions
    $DATUM Reaction Conditions text
    ...
    ```

**Comment by ivanmaslow** [comment]
AC were confirmed with @yauhen-karmyzau:
- In the case of Multi-Tailed Arrow if a KET text block will be within SPINE LENGTH/2 x HEAD ARROW LENGTH, than this text must be understood as reaction's text.
- In the case of Simple Arrow if a KET text block will be within ARROW LENGTH/2 x ARROW LENGTH, than this text must be understood as reaction's text.
Example of approximate area of bounding box:
![image](https://github.com/user-attachments/assets/12f5b363-28fb-4b8e-a737-48eb4f79fdf1)

**Comment by Zhirnoff** [comment]
Tested.
![2024-12-05_10h58_31](https://github.com/user-attachments/assets/204470b3-e6d9-4e67-9949-6d80e28004ae)
![2024-12-05_10h59_22](https://github.com/user-attachments/assets/ca347fd5-dc48-43d5-9caa-73efc9bb5caa)
![2024-12-05_10h59_59](https://github.com/user-attachments/assets/576497ff-bf1b-4a82-a03e-fe316988548b)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
