### ISSUE TITLE
The ordering of branches of cascade reactions and reactions themselves should be the same on Load/Save from/to RDF 

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2407]
**Expected pathway reaction ordering**
Idea is to follow reactant’s order: first reactant in a reaction must be "at the top" position of a multi-tailed arrow, as upper molecule in a reaction (reactant near multi-tailed arrow) must be the first reactant in RXN format.

![Image](https://github.com/user-attachments/assets/bf5cb4d7-1e11-4231-a7a8-e5ff2922393f)

**Steps to Reproduce 1**
1. Load from RDF file with the single cascade reaction with several branches:
[!Synthia_path_5_tails.zip](https://github.com/user-attachments/files/17058376/Synthia_path_5_tails.zip)

**Actual Result**
- The first branch of cascade reactions in RDF file is the second on Canvas:
![image](https://github.com/user-attachments/assets/052b516b-7ed2-4e59-9ce5-038d9a41ad40)

**Expected Result**
- The first branch of cascade reactions in the RDF file is the first on Canvas

2. Save to RDF and Load again

**Actual Result**
- Positioning of elements is changed after Save/Load, but it should like after the first load:
![image](https://github.com/user-attachments/assets/5862ef38-30b3-405a-b2e7-4068727dccb9)

**Expected Result**
- Positioning of elements isn't changed after Save/Load, it's displayed like after the first load

**Steps to Reproduce 2**
1. Load from RDF file with several single reactions:
[rdf-rxn-v2000-reactions-1x1-2x2-3x3.zip](https://github.com/user-attachments/files/17058595/rdf-rxn-v2000-reactions-1x1-2x2-3x3.zip)

**Actual Result**
- The first reaction in RDF file is the third on Canvas, the third reaction in RDF is the first on Canvas:
![image](https://github.com/user-attachments/assets/4721e11a-d4a4-4683-8258-994e22358b2b)

**Expected Result**
- Reactions should be displayed on Canvas as in RDF file 1:1, 2:2, 3:3

2. Save to RDF

**Actual Result**
- It can't be saved as separate reactions:
![image](https://github.com/user-attachments/assets/59ef829e-6262-479b-ac09-538fc2297c00)

**Expected Result**
- It can be saved as separate reactions 1:1, 2:2, 3:3
- It will be fixed in scope of https://github.com/epam/Indigo/issues/2412

**Steps to Reproduce 3 - Ordering of elements**
1. Load from KET reaction:[ket-cascade-reaction-3-1-2-1-1.zip](https://github.com/user-attachments/files/17258780/ket-cascade-reaction-3-1-2-1-1.zip)
![image](https://github.com/user-attachments/assets/c20a77f2-2e50-425d-85d4-2f30ad101825)
2. Click on Layout or make Save/Load to/from RDF:

**Actual result:**
- Arrow is changed according to indigo default sizes, elements are aligned, cyclopropane changes the position:
![image](https://github.com/user-attachments/assets/120bee83-3c23-4fe7-821b-c7982c7c81ee)

**Expected result:**
- Arrow is changed according to indigo default sizes, elements are aligned, cyclopropane doesn't change the position:
![image](https://github.com/user-attachments/assets/f375abfb-a753-4c03-b929-eae972704181)

**Environment details:**
- Tested on CI CD master SA environment
- Ketcher [Version 2.25.0-rc.1] Build at 2024-09-18; 05:59:24
- Indigo Version 1.25.0-dev.1.38-gdbf49deb-wasm32-wasm-clang-12.0.0
- Windows 11 Enterprise
- Chrome Version 128.0.6613.138 (Official Build) (64-bit)

**Notes**
- Tests are added to xls and have to be automated after fixing
- Also, position of branches shouldn't be changed on Layout action
- Issue is detected during exploratory testing of Save RDF feature for cascade reactions - https://github.com/epam/Indigo/issues/2237

**Comment by ivanmaslow** [comment]
Tested on CI CD env with 2309-update-layout:

- Ketcher [Version 2.25.0-rc.2] Build at 2024-09-30; 06:32:00
- Version 1.25.0-dev.2.6-g0e1cfa10-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise 
- Chrome Version 129.0.6668.71 (Official Build) (64-bit)

The second part of the defect isn't fixed:
Reactions are still not in order as in RDF, also the displaying for reactions with several products is broken:
![image](https://github.com/user-attachments/assets/97142ce0-805f-4177-b126-2f33c9794028)

**Comment by yauhen-karmyzau** [comment]
Cases are not fixed.

**Comment by ivanmaslow** [comment]
Pre-tested on aws_ci environment with Ketcher master and Indigo 2407-branch-ordering branches:
- Ketcher [Version 2.26.0-rc.1] Build at 2024-10-24; 12:25:38;
- Indigo Version 1.25.0-rc.3.18-gcdee98d4-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 130.0.6723.70 (Official Build) (64-bit)

In the first case, the ordering of branches isn't changed after layout actions on save/load to/from RDF:
![image](https://github.com/user-attachments/assets/9d81150b-fc3e-4b4d-9678-f0e6db57e337)
But still the first branch in the file not the first branch on Canvas, you can see below screenshot how RXN reactions are positioned in RDF file:
![image](https://github.com/user-attachments/assets/a8bcb012-7883-4815-8b53-ef6e1f654bf4)

The second case is fixed partially, so it can be loaded with correct ordering for this specific case:
![image](https://github.com/user-attachments/assets/81d224a7-6400-4d23-abb6-7f5b0371fcdf)
But it still can be reproduced for other cases - mentioned in https://github.com/epam/Indigo/issues/2452 - ordering is changed after layout or save/load to/from RDF actions:
![image](https://github.com/user-attachments/assets/866b1754-bdf5-4c64-897e-80a2345d456d)
![image](https://github.com/user-attachments/assets/0690522f-3d6a-4dc7-a4c5-f95a90b2b54f)
[ketcher-2452.zip](https://github.com/user-attachments/files/17509445/ketcher-2452.zip)

The third case is fixed:
![image](https://github.com/user-attachments/assets/22c5fa33-d118-4134-b81d-399ce93a4874)
![image](https://github.com/user-attachments/assets/84dfca13-61b6-4e58-9251-21f2ef9a3946)

**Comment by ivanmaslow** [comment]
The fix is successfully verified on RC SA env:
- Ketcher [Version 2.26.0-rc.6] Build at 2024-10-25; 09:57:12
- Indigo Version 1.25.0-rc.4.0-g8862ccb7e-wasm32-wasm-clang-19.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 130.0.6723.70 (Official Build) (64-bit)

As mentioned above the first case is fixed, branches doesn't change ordering after save/load to/from RDF or layout actions as mentioned above.
The second case is fixed too, another one is reported - https://github.com/epam/Indigo/issues/2584.
The third case is fixed as mentioned above.
One more issue detected that's related to ordering - https://github.com/epam/Indigo/issues/2585.
