### ISSUE TITLE
The reaction with reverse retrosynthetic arrow is displayed not correct after clicking on Aromatize, Dearomatize, Calculate CIP, Add explicit hydrogens

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2409]
**Steps to Reproduce**
1. Open file on the Canvas
[error with aromatize v2 (1).ket.zip](https://github.com/user-attachments/files/17063163/error.with.aromatize.v2.1.ket.zip)

<img width="885" alt="Снимок экрана 2024-09-19 в 18 51 07" src="https://github.com/user-attachments/assets/44f099a6-f864-42ac-bffe-2df4e15168b1">

2.1 Click on Aromatize
**Actual behavior**
the reaction is changed the direction and location
<img width="1007" alt="Снимок экрана 2024-09-19 в 18 52 29" src="https://github.com/user-attachments/assets/c164fb52-aea8-405f-b8fb-e3dccd04fe7f">

2.2 Click on Dearomatize
 **Actual behavior**
the reaction is changed the direction and location
<img width="990" alt="Снимок экрана 2024-09-19 в 18 52 55" src="https://github.com/user-attachments/assets/4eea2d2a-d4ef-4c58-b0d0-1518d799b0c9">

2.3 Click on Calculate CIP
 **Actual behavior**
the reaction is changed the direction and location
<img width="990" alt="Снимок экрана 2024-09-19 в 18 52 55" src="https://github.com/user-attachments/assets/4eea2d2a-d4ef-4c58-b0d0-1518d799b0c9">

2.4 Click on Add explicit hydrogens
**Actual behavior**
the reaction is changed the direction and location
<img width="1280" alt="Снимок экрана 2024-09-19 в 18 53 35" src="https://github.com/user-attachments/assets/65eb400f-128c-4a4f-9f9c-630886c00b0b">

**Expected behavior**
the reaction is not changed the direction and location and Aromatize, Dearonatize, Calculate CIP, Add explicit hydrogens are applied correctly

**Environment details:**
Ketcher Version 2.25.0-rc.1 Build at 2024-09-03; 15:31:03
Version 1.24.0-rc.1.0-gb8f099851-wasm32-wasm-clang-19.0.0
Chrome Версия 126.0.6478.127 (Официальная сборка), (arm64)
MacOs Sonoma 14.5

Issue found while testing https://github.com/epam/Indigo/issues/2318

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/d879281d-706f-4123-80a7-00a15a6b7c0d)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.


https://github.com/user-attachments/assets/0d69c8a6-9c70-432c-a86c-1ff851d23c74


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.5]
**Indigo version** 
[Version 1.25.0-rc.3]
