### ISSUE TITLE
Export of ambiguous monomers to Sequence/FASTA doesn't work for mixed ambiguous monomers

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2435]
**Steps to Reproduce**
1. Toggle to Macro - Flex
2. Load following HELM using copy from clipboard way: `PEPTIDE1{(A+C+D+E+F+G+H+I+K+L+M+N+O+P+Q+R+S+T+U+V+W+Y)}$$$$V2.0`
![image](https://github.com/user-attachments/assets/9d9bb6dd-321b-4284-823d-3571e6dcc558)
3. Try to export canvas to Sequence (or FASTA - result is the same)

**Actual behavior**
System throws exception: `Convert error! map::at:  key not found`
![image](https://github.com/user-attachments/assets/f17e75ac-e2cc-4639-80f2-cb189a72eb91)

**Expected behavior**
No exception. Correct error message should be shown

**Versions**
- Ketcher Version 2.25.0-rc.5 Build at 2024-09-24; 18:17:25
- Indigo Toolkit Version 1.24.0-rc.4.0-gdf51dc428-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.71 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2015

**Comment by AliaksandrDziarkach** [comment]
Already fixed

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/b87427a8-c9d8-455a-9907-2cfd0e5b6cb4)
- Ketcher Version 3.20.0-rc.1 Build at 2024-12-31; 12:50:08
- Indigo Toolkit Version 1.28.0-rc.1.0-gc167e6266-wasm32-wasm-clang-19.0.0
- Chrome Version Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
