### ISSUE TITLE
System should report an error if we have one or more monomers on the canvas don't have mapping for them in case of export to Sequence/FASTA

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2436]
**Steps to Reproduce**
1. Toggle to Macro - Flex
2. Load following HELM using copy from clipboard way: `PEPTIDE1{(G,H,I,K,L,M,N,O)}$$$$V2.0`
![image](https://github.com/user-attachments/assets/8aeff147-e461-4309-80a2-3d9a2e89a7b1)
3. Try to export canvas to Sequence (or FASTA - result is the same)

**Actual behavior**
System throws exception: `Convert error! map::at:  key not found`
![image](https://github.com/user-attachments/assets/877a71aa-f64a-4570-bc5f-1b1c58f99cbb)

**Expected behavior**
No exception. System should report an error that one or more monomers couldn't be exported to Sequence/FASTA since we don't have mapping for them

**Versions**
- Ketcher Version 2.25.0-rc.5 Build at 2024-09-24; 18:17:25
- Indigo Toolkit Version 1.24.0-rc.4.0-gdf51dc428-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.71 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/2015

**Comment by AlexeyGirin** [comment]
Moved to 1.26 as per @AlexanderSavelyev decision

**Comment by AliaksandrDziarkach** [comment]
Expected fixed

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/a9e0095d-26a8-4870-977a-3c683acfe3a7)
- Ketcher Version 3.20.0-rc.1 Build at 2024-12-31; 12:50:08
- Indigo Toolkit Version 1.28.0-rc.1.0-gc167e6266-wasm32-wasm-clang-19.0.0
- Chrome Version Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
