### ISSUE TITLE
System shouldn't allow user to export alternatives ambiguous monomers to IDT (since only mixtures are supported)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2440]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load from file: [Ambiguous DNA Bases (alternatives).zip](https://github.com/user-attachments/files/17188611/Ambiguous.DNA.Bases.alternatives.zip)
![image](https://github.com/user-attachments/assets/c8bbad8a-dc5b-483b-a452-3c70a44f0972)
3. Export canvas to IDT

**Actual behavior**
System provide the result: `NBDHKWY/3Phos/`
![image](https://github.com/user-attachments/assets/3065e3f4-7b46-4eb0-8496-7b60ec5cba26)

**Expected behavior**
System throws an error: `Alternatives ambiguous monomers on the canvas souldn't be saved to IDT, only mixtures allowed`

As per [requirement](https://github.com/epam/Indigo/issues/1619):

> For <base> variant monomers ([mixed bases](https://www.idtdna.com/pages/products/custom-dna-rna/mixed-bases)) are also supported in IDT notation.

**Versions**
- Ketcher Version 2.25.0-rc.5 Build at 2024-09-24; 18:17:25
- Indigo Toolkit Version 1.24.0-rc.4.0-gdf51dc428-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.71 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/1619

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-10-21_19h21_24](https://github.com/user-attachments/assets/2aed9b15-59c1-48ed-9134-411d1230fbb6)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.5]
**Indigo version** 
[Version 1.25.0-rc.3]
