### ISSUE TITLE
Preview: the thickness of the arrow is incorrect when saving to png(svg)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2444]
**Steps to Reproduce**
1. add to the Canvas reaction with arrow
<img width="387" alt="Снимок экрана 2024-09-30 в 13 22 00" src="https://github.com/user-attachments/assets/04761622-7ae3-4198-b9be-bde2a0d24c51">

2. save to PNG (svg)

**Expected behavior**
the thickness of the arrow should be the same as the thickness of bonds

**Actual behavior**
The thickness of the arrow is not the same as bond
<img width="493" alt="Снимок экрана 2024-09-30 в 13 21 48" src="https://github.com/user-attachments/assets/78bbfe13-ad8a-4f34-b264-2fcc77d4b03e">

**Environment details:**
 - https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
 - Indigo branch 2175-acs-style-rendering
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AliaksandrDziarkach** [comment]
Indigo render should be fixed.
Need to discuss expected behavior.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/280d4e71-c0c8-44b0-b26e-0a2881d9444f)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
