### ISSUE TITLE
Preview: Font size is incorrect when save to png (svg)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2445]
**Steps to Reproduce**
1. add chain to the Canvas
<img width="298" alt="Снимок экрана 2024-09-30 в 14 01 35" src="https://github.com/user-attachments/assets/94a60cc4-9a72-44fc-bc3e-5381e60e522b">

2. set 5 px to the Font size in the Settings
3. click on the Apply button
4. save to PNG (svg)

**Expected behavior**
<img width="289" alt="Снимок экрана 2024-09-30 в 14 00 11" src="https://github.com/user-attachments/assets/7105274c-7f65-45a6-9265-bb90f81def96">

**Actual behavior**
atoms are displayed without settings
<img width="461" alt="Снимок экрана 2024-09-30 в 14 03 20" src="https://github.com/user-attachments/assets/b1fbb35d-7d83-4d33-823f-ce1de9908dd0">

**Environment details:**
 - https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
 - Indigo branch 2175-acs-style-rendering
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AliaksandrDziarkach** [comment]
Looks like indigo render use same font size for  all parts of atom label.
