### ISSUE TITLE
Sub font size is incorrect when save to png (svg)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2446]
**Steps to Reproduce**
1. add chain to the Canvas
<img width="298" alt="Снимок экрана 2024-09-30 в 14 01 35" src="https://github.com/user-attachments/assets/94a60cc4-9a72-44fc-bc3e-5381e60e522b">

2. set 30 pt to the Sub Font size in the Settings
3. click on the Apply button
4. save to PNG (svg)

**Expected behavior**
<img width="335" alt="Снимок экрана 2024-09-30 в 14 41 58" src="https://github.com/user-attachments/assets/66a452cf-4631-492f-951c-8abea6e947f9">

**Actual behavior**
atoms are displayed without settings
<img width="473" alt="Снимок экрана 2024-09-30 в 14 42 18" src="https://github.com/user-attachments/assets/45de9fbe-2f3e-417c-a507-136ce5a927ec">

**Environment details:**
 - https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
 - Indigo branch 2175-acs-style-rendering
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AliaksandrDziarkach** [comment]
Looks like indigo render use same font size for all parts of atom label.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/2fde0ba3-2501-483d-837c-172816f10b37)
- Ketcher Version 2.26.0-rc.6 Build at 2024-10-25; 09:57:12
- Indigo Toolkit Version 1.25.0-rc.4.0-g8862ccb7e-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.59 (Official Build) (64-bit)
- Win10
