### ISSUE TITLE
Preview: single up and single down bonds are displayed incorrect when save to PNG(svg)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2447]
**Steps to Reproduce**
1. add to the canvas 
<img width="328" alt="Снимок экрана 2024-09-30 в 15 15 31" src="https://github.com/user-attachments/assets/06a63973-ba77-4669-91e3-6166c6d17695">

[ring with single up and single down bonds.ket.zip](https://github.com/user-attachments/files/17190470/ring.with.single.up.and.single.down.bonds.ket.zip)

2. save to png (svg)

**Expected behavior**
<img width="328" alt="Снимок экрана 2024-09-30 в 15 15 31" src="https://github.com/user-attachments/assets/06a63973-ba77-4669-91e3-6166c6d17695">

**Actual behavior**
<img width="501" alt="Снимок экрана 2024-09-30 в 15 17 05" src="https://github.com/user-attachments/assets/6d81b558-df66-4302-9000-f5e2dfd5830d">

**Environment details:**
 - https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
 - Indigo branch 2175-acs-style-rendering
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AliaksandrDziarkach** [comment]
Looks like this is ketcher issue - preview and saved file show different picture.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/e2fcd14a-2daa-4822-a3d6-b8159c1e660f)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
