### ISSUE TITLE
Reactions change the ordering on canvas after layout or save/load to/from RDF actions

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2452]
**Steps to Reproduce**
1. Add 2 reactions with Multi-Tailed Arrow and single arrow with shifted positions:
![image](https://github.com/user-attachments/assets/e561e4e8-fb75-423b-980a-39aed9fa4a07)
2. Click on Layout

**Actual behavior**
- The first reaction becomes the second:
![image](https://github.com/user-attachments/assets/cd1000fc-1ec0-48e5-a6e5-f8e9411b2b27)

**Expected behavior**
- The first reaction should be the first as it was before layout action

**Environment details**
- Detected on CI-CD environment with 2309-update-layout build
- Ketcher [Version 2.25.0-rc.2] Build at 2024-09-30; 06:32:00
- Version 1.25.0-dev.2.6-g0e1cfa10-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 129.0.6668.71 (Official Build) (64-bit)

**Notes**
- Pay attention, that it should be tested for saving to RDF as well and should work as expected;
- Issue is detected during exploratory testing of Import/Export for Multi-Tailed Arrow in cascade reactions - https://github.com/epam/Indigo/issues/2236

**Comment by yauhen-karmyzau** [comment]
Priority was changed to Medium as this case is not critical for initial requirements: more then one reaction on canvas.

**Comment by ivanmaslow** [comment]
Pre-tested on aws_ci environment with Ketcher master and Indigo 2407-branch-ordering branches:
- Ketcher [Version 2.26.0-rc.1] Build at 2024-10-24; 12:25:38;
- Indigo Version 1.25.0-rc.3.18-gcdee98d4-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 130.0.6723.70 (Official Build) (64-bit)

Fixed for case in the defect:
![image](https://github.com/user-attachments/assets/a74c8e7b-9eb3-49ff-8680-8dcf18160c0f)
![image](https://github.com/user-attachments/assets/3170b169-8419-4e90-96b1-a66e47df4d1b)

But in case of a bigger quantity of reactions, it can be reproduced on layout or save/load to/from RDF - ordering is changed for reactions:
![image](https://github.com/user-attachments/assets/866b1754-bdf5-4c64-897e-80a2345d456d)
![image](https://github.com/user-attachments/assets/0690522f-3d6a-4dc7-a4c5-f95a90b2b54f)
[ketcher-2452.zip](https://github.com/user-attachments/files/17509445/ketcher-2452.zip)
