### ISSUE TITLE
Preview: the reaction is not in the center of the picture after saved in png (svg)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2457]
**Steps to Reproduce**
1. Change Reaction component margin size in the Settings to 80 px
2. Bond length in the Settings is 20 px
3. add schema or create manually
[Margin between catalyst and arrow doesn't change.ket.zip](https://github.com/user-attachments/files/16849231/Margin.between.catalyst.and.arrow.doesn.t.change.ket.zip)

<img width="1138" alt="Снимок экрана 2024-09-03 в 14 49 47" src="https://github.com/user-attachments/assets/3cea0b82-6eb7-4b12-8051-618ec880e57c">

4. click on layout
5. save to png

**Actual behavior**
the reaction should be in the center of the picture

**Expected behavior**
the reaction is in the left corner of the picture
![ketcher (14)](https://github.com/user-attachments/assets/d4cd7b32-50ca-4122-a051-92e6fb1ccf1f)

**Environment details:**
- https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
- Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
- Indigo branch 2175-acs-style-rendering
- Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/63c61bc1-9cc6-4a7f-a4c8-38800f372c1d)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
