### ISSUE TITLE
Load/save hydrogen bonds from/to HELM, KET and MOL

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/Indigo#2460]
**Background**

Hydrogen bonds for macromolecules are a type of ambiguous connection (do not require attachment points). They can only be established between monomers (not between monomers and small molecules or between two small molecules).
Most formats do not support this type of bonds (for macromolecules), but HELM does, and KET should.

In the HELM specifications hydrogen bonds are referred to as "hydrogen pairings".
> From HELM Standards Specification: Version 2.01, page 17:
> The hydrogen pairings are defined as a special form of connection. It is not a bond between two atoms, but rather a set of hydrogen bonds between two monomers. Therefore, the representation uses the word ‘pair’ instead of the attachment point symbol ‘R#’.
Example: RNA1,CHEM1,21:pair‐1:pair

**Requirements**

1. User should be able to import/export macromonomer structures who contain hydrogen bonds from/to HELM.
2. Indigo should be able to convert KET files who contain macromolecules hydrogen bonds to/from HELM. (issue introducing H-bonds on the Ketcher side: [#5403](https://github.com/epam/ketcher/issues/5403))
3. Indigo should be able to convert KET files who contain macromolecules hydrogen bonds to/from MDL Molfile V3000.

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10
