### ISSUE TITLE
Preview: the thickness of the plus is incorrect when saving to png(svg)

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2461]
**Steps to Reproduce**
1. add to the Canvas 2 Benzene rings with plus between them
<img width="462" alt="Screenshot 2024-10-01 at 17 14 00" src="https://github.com/user-attachments/assets/cabdbaee-30cb-4a78-8ef4-09fa5821d890">

2. save to PNG (svg)

**Expected behavior**
the thickness of the plus should be the same as the thickness of bonds

**Actual behavior**
The thickness of the plus is not the same as bond
<img width="506" alt="Screenshot 2024-10-01 at 17 14 29" src="https://github.com/user-attachments/assets/cb1de716-e811-4592-8533-d15e144b9f31">

**Environment details:**
 - https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher branch 5362-sending-acs-parameters-when-requesting-render-to-png-and-svg
 - Indigo branch 2175-acs-style-rendering
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/f2fc9502-3032-4adc-9331-c579b311c024)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
