### ISSUE TITLE
IDT export is wrong for modified IDT monomers if phosphate attached at the end (IDT position indicator is wrong and Phos missed)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2471]
**Steps to Reproduce**
1. Toggle to Macro - Flex mode
2. Load from file: [IDT export is wrong for modified IDT monomers if phosphate attached at the end (IDT position indicator is wrong and Phos missed).zip](https://github.com/user-attachments/files/17230397/IDT.export.is.wrong.for.modified.IDT.monomers.if.phposphate.attached.at.the.end.IDT.position.indicator.is.wrong.and.Phos.missed.zip)
![image](https://github.com/user-attachments/assets/609247a5-a753-476f-bb6c-11ddba41f618)
3. Export canvas to IDT

**Actual behavior**
System provide the result: `/52MOErT//i2MOErT//i2MOErT/`
![image](https://github.com/user-attachments/assets/9121185b-14ca-4a7f-8666-8cd21f0a31a8)

**Expected behavior**
System provide the result: `/52MOErT//i2MOErT//i2MOErT//3Phos/`

**Versions**
- Ketcher Version 2.25.0-rc.5 Build at 2024-09-24; 18:17:25
- Indigo Toolkit Version 1.24.0-rc.4.0-gdf51dc428-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.71 (Official Build) (64-bit)
- Win10

Reference issues: https://github.com/epam/Indigo/issues/1899

**Comment by AliaksandrDziarkach** [comment]
Works as expected.
/i2MOErT/ already contains posphate.

**Comment by AlexeyGirin** [comment]
Verified.
Not a bug.
