### ISSUE TITLE
Support for three letter sequences

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/Indigo#2472]
All the requirements described in this task on Ketcher side: [#5556](https://github.com/epam/ketcher/issues/5556).

**Comment by AlexeyGirin** [comment]
Function is blocked by https://github.com/epam/Indigo/issues/2615
Moved to next release

**Comment by AlexeyGirin** [comment]
Fixed.
- Ketcher Version 2.28.0-rc.1 Build at 2024-12-03; 17:04:52
- Indigo Version 1.27.0-rc.1.0-g8d656a341-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.109 (Official Build) (64-bit)
- Win10
