### ISSUE TITLE
The arrow is displayed incorrect when import from rxn file

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2478]
**Steps to Reproduce**
1. Add to Canvas the reaction
[The arrow is displayed incorrect when import from rxn file.zip](https://github.com/user-attachments/files/17244585/The.arrow.is.displayed.incorrect.when.import.from.rxn.file.zip)
(from the auto test File-Management/Open-And-Save-Files/Rxn-Files/rxn-files.spec.ts:258)

**Actual behavior**
![Screenshot 2024-10-03 at 15 06 26](https://github.com/user-attachments/assets/c0a1701c-9d9d-4b07-9078-6ba3f7b90dab)

**Expected behavior**
![Screenshot 2024-10-03 at 15 06 36](https://github.com/user-attachments/assets/ef7dc7c2-0613-42dc-851d-0597e48e4178)

**Environment details:**
- Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- MacOs 15
- Version 129.0.6668.71 (Official Build) (arm64)

**Comment by AlexeyGirin** [comment]
Shift molecules to put default size arrow inside as per A.S. decision

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-11-11_16h41_22](https://github.com/user-attachments/assets/904dc188-5a13-423d-a1d9-9fc7fabde973)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.9]
**Indigo version** 
[Version 1.25.0-rc.5]
