### ISSUE TITLE
The arrow is displayed In the other direction after importing from rxn file

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2479]
**Steps to Reproduce**
1. Add to the Canvas
[The error is displayed to another side after importing from rxn file.zip](https://github.com/user-attachments/files/17244742/The.error.is.displayed.to.another.side.after.importing.from.rxn.file.zip)
(file is from auto test Reactions/Reaction-tools/Plus-and-Arrow-tools/plus-and-arrows-tools.spec.ts:634)

**Actual behavior**
the arrow is displayed In the other direction
![Screenshot 2024-10-03 at 15 18 58](https://github.com/user-attachments/assets/437e435c-1835-46fb-a349-e9bbdb7549e6)

**Expected behavior**
![Screenshot 2024-10-03 at 15 19 13](https://github.com/user-attachments/assets/5f6e14e3-71d7-432d-8c88-2b1851beb36f)

**Environment details:**
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- MacOs 15
- Version 129.0.6668.71 (Official Build) (arm64)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-11-11_16h43_13](https://github.com/user-attachments/assets/b2c44323-c7bf-4be0-bd49-5dcf2b51af4a)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.9]
**Indigo version** 
[Version 1.25.0-rc.5]
