### ISSUE TITLE
The stereobonds are displayed another after exporting from mol file

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2480]
**Steps to Reproduce**
1. add to the Canvas
[The stereobonds are displayed another after exporting from mol file.zip](https://github.com/user-attachments/files/17244914/The.stereobonds.are.displayed.another.after.exporting.from.mol.file.zip)
(the file is from auto test File-Management/Smile-Files/smile-files.spec.ts:183)

**Actual behavior**
![Screenshot 2024-10-03 at 15 32 17](https://github.com/user-attachments/assets/083b1b33-e97d-4c0f-a7b7-02d24d8fe0e5)

**Expected behavior**
![Screenshot 2024-10-03 at 15 32 30](https://github.com/user-attachments/assets/d2e26f92-b7f2-467d-a2d4-c6740ad16248)

**Environment details:**
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- MacOs 15
- Version 129.0.6668.71 (Official Build) (arm64)

**Comment by AnnaKosol** [comment]
The task which should be to solve this problem - https://github.com/epam/ketcher/issues/5635

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/c5245bcb-ecfb-42c6-add6-5c01b838783c)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
