### ISSUE TITLE
RXN file is incorrect when the reaction has two arrows and plus

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2483]
**Steps to Reproduce**
1. add to the Canvas
[RXN file is incorrect when the reaction has two arrows and plus.ket.zip](https://github.com/user-attachments/files/17245823/RXN.file.is.incorrect.when.the.reaction.has.two.arrows.and.plus.ket.zip)

2. Save to MDL RXN2000

**Actual behavior**
[RXN file is incorrect when the reaction has two arrows and plus actual.rxn.zip](https://github.com/user-attachments/files/17246000/RXN.file.is.incorrect.when.the.reaction.has.two.arrows.and.plus.actual.rxn.zip)
![Screenshot 2024-10-03 at 16 52 30](https://github.com/user-attachments/assets/bfd0834c-19dc-4262-ae9b-095c8dbacc39)

**Expected behavior**
[RXN file is incorrect when the reaction has two arrows and plus expected.rxn.zip](https://github.com/user-attachments/files/17246004/RXN.file.is.incorrect.when.the.reaction.has.two.arrows.and.plus.expected.rxn.zip)
![Screenshot 2024-10-03 at 16 52 52](https://github.com/user-attachments/assets/b49e8a4b-13b9-4bbf-bd5c-ffcc7e7ad14c)

**Environment details:**
- Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- MacOs 15
- Version 129.0.6668.71 (Official Build) (arm64)

**Comment by AlexeyGirin** [comment]
@AnnaKosol told that @AlexanderSavelyev told her that it is not a bug and works as expected

**Comment by AlexeyGirin** [comment]
Not a bug as per @AlexanderSavelyev 

    Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
    Indigo Toolkit Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
    Chrome Version 129.0.6668.90 (Official Build) (64-bit)
    Win10
