### ISSUE TITLE
The error is displayed in the 3DViewer after moving a molecule

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2484]
**Steps to Reproduce**
1. add to the Canvas
[3d viewer.ket.zip](https://github.com/user-attachments/files/17247330/3d.viewer.ket.zip)
![Screenshot 2024-10-03 at 18 37 25](https://github.com/user-attachments/assets/accf3b68-f895-4888-acda-a7d3db6f5491)

2. open 3DViewer
3. move molecule to the left a little bit
![Screenshot 2024-10-03 at 18 38 20](https://github.com/user-attachments/assets/6edec6db-3598-47a6-a790-b6807c0fc2ae)

4. click on Apply button

**Actual behavior**
The error is displayed
![Screenshot 2024-10-03 at 18 38 37](https://github.com/user-attachments/assets/fb8cfac0-a8d5-47de-a517-809405458e15)

**Expected behavior**
The modal window is closed without errors

**Environment details:**
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
- Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
- MacOs 15
- Version 129.0.6668.71 (Official Build) (arm64)

**Comment by Zhirnoff** [comment]
Bug fixed and approved by autotest
![2024-10-04_15h26_08](https://github.com/user-attachments/assets/546e2c91-1ca2-4348-86a3-fecc8dee82c9)

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/b8e90e10-2034-44bd-81b2-998320a7565d)
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10
