### ISSUE TITLE
Arrow changes direction after loading saved RXN single reaction if the elements were too close to single arrow on save

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2493]
**Steps to Reproduce**
1. Add a reaction with Multi-Tailed Arrow to Canvas, add chemical elements very close to the single arrow or add it from the KET file below:
[ketcher (1).zip](https://github.com/user-attachments/files/17247403/ketcher.1.zip)
![image](https://github.com/user-attachments/assets/87f4503a-deae-498c-8688-c974e44ad906)

2. Click on Save as..., select RXN V2000/V3000
3. Copy RXN from the preview and paste to Canvas

**Actual Result**
- Arrow changed the direction:
![image](https://github.com/user-attachments/assets/3fc79fe8-692a-40af-baf8-aa7dc7f9c117)

**Expected Result**
- 2:1 reaction with a single arrow and plus is displayed:
![image](https://github.com/user-attachments/assets/d6967d31-e2b1-4f8e-bc8a-19b78b21be7b)

**Environment details**
- Detected on CI-CD master env
- Ketcher [Version 2.25.0-rc.2] Build at 2024-10-03; 05:09:39
- Indigo Version 1.25.0-dev.3.4-g6469f588-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 129.0.6668.71 (Official Build) (64-bit)

**Notes**
- Issue is detected during exploratory testing of Update Save to RXN for cascade reactions feature, but it's not caused by Cascade Reaction changes - https://github.com/epam/Indigo/issues/2234

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-11-11_16h38_59](https://github.com/user-attachments/assets/b428f8ea-99a4-4fc7-aff6-39482e3b1b48)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.9]
**Indigo version** 
[Version 1.25.0-rc.5]
