### ISSUE TITLE
Open Angel Arrows changed to Multi-tail arrow after layout

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2496]
**Steps to Reproduce**
1. Add to the Canvas 
[Open Angel Arrows changed to Multi-tail arrow after layout.ket.zip](https://github.com/user-attachments/files/17258921/Open.Angel.Arrows.changed.to.Multi-tail.arrow.after.layout.ket.zip)
<img width="1220" alt="Screenshot 2024-10-04 at 15 21 20" src="https://github.com/user-attachments/assets/f27e7473-0ff7-463e-b35a-475038774d38">

2. click on layout

**Actual behavior**
Open Angel Arrows changed to Multi-tail arrow

<img width="523" alt="Screenshot 2024-10-04 at 15 24 09" src="https://github.com/user-attachments/assets/ba396921-ac62-4e4d-acbb-ed2878788aef">

**Expected behavior**
the reactions are arranged according to margin

**Environment details:**
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
 - MacOs 15
 - Chrome Version 129.0.6668.71 (Official Build) (arm64)

**Comment by ivanmaslow** [comment]
Tested on RC Remote env:
- Ketcher [Version 2.26.0-rc.1] Build at 2024-10-04; 18:51:40
- Indigo Version 1.25.0-rc.1.0-g704673fcb-x86_64-linux-gnu-11.2.1
- Desktop, Windows 11 Enterprise
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)

Issue isn't reproducible anymore - arrows aren't changed to Multi-Tailed Arrow after layout:
![image](https://github.com/user-attachments/assets/02fdad10-dd29-4587-9b0d-cfa7dabcef2f)
