### ISSUE TITLE
The reaction with reaction mapping tool is displayed incorrect with ACS Style settings

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2501]
**Steps to Reproduce**
1. add reaction to the Canvas
[The reaction with reaction mapping tool is displayed incorrect.ket.zip](https://github.com/user-attachments/files/17261912/The.reaction.with.reaction.mapping.tool.is.displayed.incorrect.ket.zip)
<img width="867" alt="Screenshot 2024-10-04 at 19 22 09" src="https://github.com/user-attachments/assets/3b7f05d5-2d2c-4434-bdfe-b414a4fa4b81">

2. click on ACS Style button in the Settings
3. click on Apply button
4. click on Layout

**Actual behavior**
<img width="562" alt="Screenshot 2024-10-04 at 19 26 34" src="https://github.com/user-attachments/assets/ae93aa12-afb4-4089-920d-66282466d6e3">

**Expected behavior**
the schema is displayed regarding settings and margins
<img width="683" alt="Screenshot 2024-10-04 at 19 27 25" src="https://github.com/user-attachments/assets/56945753-98c0-4b00-9622-3a0cc037e638">

**Environment details:**
https://ci.test.lifescience.opensource.epam.com/5362-sending-acs-parameters-when-requesting-render-to-png-and-svg/feature/2175-acs-style-rendering/20240930-091010/micro/KetcherDemoSA/index.html
 - Ketcher Version 2.25.0-rc.2 Build at 2024-09-30; 09:14:32
 - Indigo Version 1.25.0-dev.2.7-g6118db71-wasm32-wasm-clang-12.0.0
 - MacOs 15

**Comment by AlexeyGirin** [comment]
Same reason as for https://github.com/epam/Indigo/issues/2458

**Comment by Zhirnoff** [comment]
Tested. Bug not fixed.


https://github.com/user-attachments/assets/58caea16-bc56-4ae9-aff9-a511bdd58366


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.5]
**Indigo version** 
[Version 1.25.0-rc.3]

**Comment by Zhirnoff** [comment]
Should be tested after fix on Ketcher side in 2.26.0-rc.6 https://github.com/epam/ketcher/issues/5650

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/4e085318-0ca6-45dc-a3ac-ae8d5596104e)
- Ketcher Version 2.26.0-rc.6 Build at 2024-10-25; 09:57:12
- Indigo Toolkit Version 1.25.0-rc.4.0-g8862ccb7e-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.59 (Official Build) (64-bit)
- Win10
