### ISSUE TITLE
The length of the arrow becomes 2 bonds after layout but should be 1

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2519]
**Steps to Reproduce**
1. add the reaction to the Canvas
<img width="1013" alt="Screenshot 2024-10-07 at 16 04 20" src="https://github.com/user-attachments/assets/323ecce5-ccd8-444f-a523-46f24ac16008">

[!rxn-v2000-reaction-2x2.rxn.zip](https://github.com/user-attachments/files/17279767/rxn-v2000-reaction-2x2.rxn.zip)

2. click on layout

**Actual behavior**
The length of the arrow becomes 2 bonds
<img width="1026" alt="Screenshot 2024-10-07 at 16 07 43" src="https://github.com/user-attachments/assets/e13890ba-0d3a-4017-9c0c-9c771f9abfab">

**Expected behavior**
The length of the arrow becomes 1 bonds
<img width="1104" alt="Screenshot 2024-10-07 at 16 08 34" src="https://github.com/user-attachments/assets/9b42aa3a-9e32-4c93-8e9f-8fe97d1782bc">

**Environment details:**
- Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- MacOs
- Chrome 129.0.6668.71 (Official Build) (arm64)

Issue found while testing https://github.com/epam/Indigo/issues/2176

**Comment by AlexeyGirin** [comment]
Reproduced at 
- Ketcher Version 2.26.0-rc.5 Build at 2024-10-21; 15:27:55
- Indigo Toolkit Version 1.25.0-rc.3.0-g795119115-wasm32-wasm-clang-19.0.0
- Chrome Version Version 130.0.6723.59 (Official Build) (64-bit)
- Win10

**Comment by AlexeyGirin** [comment]
Not fixed.
Arrow size should be equal to bond size as per [requirement](https://github.com/epam/ketcher/issues/5152):

> **Bond length** - length of one bond and the **length of the default arrows** (related issue: https://github.com/epam/ketcher/issues/5153);

![image](https://github.com/user-attachments/assets/6e89e7ae-ea1a-4ca4-8102-10ca57ca9a36)

- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10

**Comment by Zhirnoff** [comment]
https://github.com/user-attachments/assets/6a14e370-dd03-4300-b265-1d513a485c8a

**Comment by even1024** [comment]
Not merged into 1.26.0.

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-12-26_10h54_27](https://github.com/user-attachments/assets/b6b2becd-fb84-4e89-83ff-9b19b26b5fca)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.4]
**Indigo version** 
[Version 1.27.0-rc.2]
