### ISSUE TITLE
The length of arrow should be 1 bond after importing reaction from rxn file

### ISSUE THREAD

**Issue by AnnaKosol** [epam/Indigo#2520]
**Steps to Reproduce**
1. add to the Canvas the reaction
[!rxn-v2000-reaction-2x2.rxn.zip](https://github.com/user-attachments/files/17279919/rxn-v2000-reaction-2x2.rxn.zip)

**Actual behavior**
the length of arrow is less than 1 bond
<img width="1016" alt="Screenshot 2024-10-07 at 16 14 56" src="https://github.com/user-attachments/assets/eae553fc-1b9e-4b50-923b-17d013f085fe">

**Expected behavior**
the length of arrow is 1 bond (default size)
<img width="1020" alt="Screenshot 2024-10-07 at 16 20 35" src="https://github.com/user-attachments/assets/235327e4-3354-4f75-8ac5-4bad8e384164">

**Environment details:**
 - Ketcher Version 2.26.0-rc.1 Build at 2024-10-04; 18:45:04
- Indigo Version 1.25.0-rc.1.0-g704673fcb-wasm32-wasm-clang-19.0.0
- MacOs
- Chrome 129.0.6668.71 (Official Build) (arm64)

issue found while testing https://github.com/epam/Indigo/issues/2176

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-11-07_17h09_18](https://github.com/user-attachments/assets/eea52073-bab4-4272-b7f8-4e74acf5df54)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.27.0-rc.1]
**Indigo version** 
[Version 1.26.0-rc.1]
