### ISSUE TITLE
Duplicated $RDFILE $DATM records are displayed on save preview for RDF V2000/V3000 formats on Remote environment

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2543]
**Steps to Reproduce**
1. Open Remote Ketcher env
2. Add an arrow to Canvas
3. Click on Save as...
4. Select RDF V2000 or V3000

**Actual behavior**
- Duplicated $RDFILE $DATM records are on preview or in saved RDF file:
![image](https://github.com/user-attachments/assets/3b951f3b-4ab4-4d5a-87f5-2894f3fcc06d)

**Expected behavior**
- No duplicated  $RDFILE $DATM are on preview or in saved RDF file

**Environment details:**
- Tested on RC Remote env
- Ketcher [Version 2.26.0-rc.1] Build at 2024-10-04; 18:51:40
- Indigo Version 1.25.0-rc.1.0-g704673fcb-x86_64-linux-gnu-11.2.1
- Desktop, Windows 11 Enterprise
- Chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Note:**
- Issue isn't reproducible on SA env
- Issue is detected during exploratory testing of Save to RDF feature - https://github.com/epam/Indigo/issues/2237

**Comment by yauhen-karmyzau** [comment]
Fixed in [Indigo-1.25.0-rc.2](https://github.com/epam/Indigo/milestone/93)

**Comment by ivanmaslow** [comment]
Tested on Remote env:
- Ketcher [Version 2.26.0-rc.3] Build at 2024-10-16; 14:42:10
- Indigo Version 1.25.0-rc.2.0-g867ae250b-x86_64-linux-gnu-11.2.1
- Desktop, Windows 11 Enterprise
- Chrome Version 130.0.6723.59 (Official Build) (64-bit)

No duplicated records during saving to RDF V2000/V3000, but V3000 doesn't work on Remote env:
![image](https://github.com/user-attachments/assets/85a05fc7-3a93-4749-a659-9a52515794aa)
![image](https://github.com/user-attachments/assets/f6fb78f0-9d2b-4ac4-b351-99b0b24e756b)

**Comment by ivanmaslow** [comment]
Can't be tested because of related issue - https://github.com/epam/ketcher/issues/5814

**Comment by ivanmaslow** [comment]
The fix is successfully verified on uat remote env:
- Ketcher [Version 2.26.0-rc.8] Build at 2024-11-07; 12:00:43
- Indigo Version 1.25.0-rc.2.0-g867ae250b-x86_64-linux-gnu-11.2.1
- Desktop, Windows 11 Enterprise
- Chrome Version 130.0.6723.116 (Official Build) (64-bit)

There are no duplicated $RDFILE $DATM records on save for RDF V2000/V3000 formats:
![image](https://github.com/user-attachments/assets/25b3cafa-52b6-4239-9c96-eaf7306b6d0a)
![image](https://github.com/user-attachments/assets/9318874d-2684-410d-8b40-575d91bfd53d)
