### ISSUE TITLE
The 'H+' special node is not recognized as hydrogen with the Plus charge

### ISSUE THREAD

**Issue by Aniuta907** [epam/Indigo#255]
**Steps to reproduce:**

1. Create Mol file that contains H+ Special Node (or use mol.mol from [mol_example.zip](https://github.com/epam/Indigo/files/5664950/mol_example.zip))
2. Execute following endpoints: 
/v2/indigo/check
/v2/indigo/calculate

**Expected result:**
I do not get errors by calling /v2/indigo/check.

I get all necessary information about created structure by calling /v2/indigo/calculate.
For example, I get following information for D Special Node (mol1.mol from [mol_example.zip](https://github.com/epam/Indigo/files/5664950/mol_example.zip)):
{
  "gross": "H D", 
  "mass-composition": "H 100.00", 
  "molecular-weight": "3.0220418", 
  "monoisotopic-mass": "3.0219268", 
  "most-abundant-mass": "3.0219268"
}
 
**Actual result:**
Response for /v2/indigo/check contains warnings:
{
  "pseudoatoms": "Structure contains 1 pseudoatom", 
  "radicals": "Structure contains pseudoatoms, so radicals could not be checked"
}

Response for /v2/indigo/calculate contains information with errors:
{
  "gross": "", 
  "mass-composition": "error: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites", 
  "molecular-weight": "error: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites", 
  "monoisotopic-mass": "error: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites", 
  "most-abundant-mass": "error: Cannot calculate mass for structure with pseudoatoms, template atoms or RSites"
}

**Comment by Zhirnoff** [comment]
Replaced with more correct issue https://github.com/epam/Indigo/issues/1146
