### ISSUE TITLE
Unable to save canvas to CDX - system throws an error: Convert error! array: invalid index 2 (size=2)

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2558]
NOTE: This is the regress appeared after August 17th
As per @AliaksandrDziarkach - this is because one arrow misses molecule box

**Steps to Reproduce**
1. Go to Molecules mode
2. Load from file: [4 mol.ket.zip](https://github.com/user-attachments/files/16561201/4.mol.ket.zip)
![image](https://github.com/user-attachments/assets/b41f6fc1-0446-4385-9032-44d29f462ad2)
3. Export canvas to CDXML

**Actual behavior**
System throws exception: `Convert error! array: invalid index 2 (size=2)`
![image](https://github.com/user-attachments/assets/6717c217-bd13-407d-a0ee-ee869482b8cf)

**Expected behavior**
Export works correct

**Versions**
- Ketcher Version 2.26.0-rc.2 Build at 2024-10-14; 19:59:03
- Indigo Toolkit Version 1.25.0-rc.2.0-g867ae250b-wasm32-wasm-clang-19.0.0
- Chrome Version 129.0.6668.101 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/Indigo/issues/2217

**Comment by AlexeyGirin** [comment]
As per @AliaksandrDziarkach - this is because one arrow misses molecule box

**Comment by Zhirnoff** [comment]
Tested. Bug fixed. But after loading CDXML file structure lose valence https://github.com/epam/Indigo/issues/2582
![2024-10-26_13h07_07](https://github.com/user-attachments/assets/3d62ebb5-2812-490d-831d-32f1209e2c53)

![2024-10-26_13h09_24](https://github.com/user-attachments/assets/8f5c33fd-21a0-401e-9f05-9c5aae3270a9)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.6]
**Indigo version** 
[Version 1.25.0-rc.4]
