### ISSUE TITLE
Read Name and Reaction Conditions from RDF Metadata as a text

### ISSUE THREAD

**Issue by yauhen-karmyzau** [epam/Indigo#2559]
**Background**
In the current implementation, Indigo handles RDF files containing reactions (RXN) but lacks the capability to utilize metadata associated with these reactions. Metadata fields are crucial for detailed documentation and readability of chemical reactions. We want to use **$DTYPE Name** and **$DTYPE Reaction Conditions** Metadata fields to enhance documentation capabilities and allow users to leverage text for better clarity and communication, there is a need to introduce support for reading text description thru the metadata fields.

**Solution**

1. Metadata Reading and Parsing:

    **Objective**: Enable Indigo to accurately read and parse content from **Name** and **Reaction Conditions** metadata fields.
    **Details**:
    1. There are pairs of metadata in key-value format ($DTYPE-$DATUM) which can be located in RDF file after each reaction.
    ```
    ...
    11 12  1  0
    11  4  4  0
    M  END
    $DTYPE Name
    $DATUM Reaction name is here
    $DTYPE Reference
    $DATUM Not available
    $DTYPE Reaction Conditions
    $DATUM Reaction Conditions text
    ...
    ```

    2. We should read **Name** as text in **bold** and **Reaction Conditions** as text in _italic_
    3. If $DATUM contains "**Not available**" or empty, than we should ignore this field.

2. Prepare text block:
**Truncated text will be lost!**

    **Objective:** Prepare text block to display near reaction's arrow and truncate large text to layout reactions in readable format.
    **Details:**
    1. **Name** as text in **bold** and **Reaction Conditions** as text in _italic_ should be added to one KET text object.
    2. If Name and Reaction Conditions are exist, than empty line should be added after the name of reaction.
    3. Text must fit a rectangle using the following conditions:
    - not more that **30 symbols** in a line of text for width;
    - text block height must be equal 1/2 multi-tailed arrow's spine height exclude reaction-component-margin-size, however, not less, than 9 lines of text, including empty line between Name and Reaction Conditions.
   
    ---
   **Initial requirements of 2.3 are here.** However, we can't calculate exact text dimensions and will use other solution.
    maximum 6.5 default sizes of the bond for **width** exclude left and right **reaction-component-margin-size** and maximum 4.5 default sizes of the bond for **height** exclude bottom **reaction-component-margin-size**.
    **Max width**: 6.5 - 2*reaction-component-margin-size (6.5 - current arrow length, the same constant must be use!)
    **Max hight**: 4.5 - reaction-component-margin-size
    **render-font-size** parameter is already available in Indigo.
    ___
    ![Image](https://github.com/user-attachments/assets/7b598916-a863-4a3a-b72e-76f90529341e)

    4. If text line is too long to fit maximum width, than it must be broken into several lines to fit maximum width. In this case, line break must before a word which is not fitting maximum width.
    5. If a word is too wide to fit maximum width, than the line break should be added before the symbol which is not fitting maximum width.
    6. Text exceeding these box limits will be truncated with an ellipsis ("..."): 2 last symbols of the last word which is not fitting maximum width should be replaced by ellipsis.

    ![Image](https://github.com/user-attachments/assets/e2d29338-e4db-4c0d-b6e8-507106e1a2b3)
    ![Image](https://github.com/user-attachments/assets/9ce23994-a369-4f9f-af3d-9d94aa74e9c6)

    ![Image](https://github.com/user-attachments/assets/9c880b6d-678f-4cd3-a3db-d8dd3696b231)
    ![Image](https://github.com/user-attachments/assets/19e16648-8976-42c6-8c8e-445c3b10c92b)

3. Dynamic Positioning and Alignment:

    1. Text block sticked to reaction's arrow with a margin, **centered horizontally above a single arrow** or **aligned to the left for multi-tailed arrows**.
    ![Image](https://github.com/user-attachments/assets/d39b12b2-7361-41dd-bb94-7852bbfdc2fa)

---
**Automatic Layout Adjustments is out of scope! Keep it for history!**

4. Automatic Layout Adjustments:

    **Objective:** Dynamically adjust the layout of reaction diagrams based on the presence and size of text annotations.
    **Details:**
    1. The vertical spacing and positioning of reactions should be modified to accommodate blocks of text, ensuring a visually balanced and uncluttered diagram.
     Without text:
    ![Image](https://github.com/user-attachments/assets/59588f46-f87f-417a-ab9e-8e17014f45e4)
    With text:
    ![Image](https://github.com/user-attachments/assets/37b44b61-1b95-4eff-b896-ef8c8d9db401)

    2. Multi-tailed arrow's spine hight should be adjusted to fit Text Above Reaction Arrows and all the reactants. Head arrow should be centred, as it is.
    If current hight/2 size of the spine is less, than text box - spine's hight must be adjusted.
    3. If multi-tailed arrow's spine was increased, than tails and tree nodes should be adjusted proportionally.  
    ![image](https://github.com/user-attachments/assets/3c1b2069-a76b-4491-8d3a-379ef2316386)

**Comment by Zhirnoff** [comment]
Tested.

![2024-12-04_17h01_12](https://github.com/user-attachments/assets/2bb233c0-8192-45a0-9b36-6b0f68e06d9d)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
