### ISSUE TITLE
The 'R' special node is not recognized as Pseudoatom

### ISSUE THREAD

**Issue by Aniuta907** [epam/Indigo#256]
**Steps to reproduce:**

1. Create Mol file that contains R Special Node (or use [mol_example.zip](https://github.com/epam/Indigo/files/5665104/mol_example.zip))
2. Execute following endpoint: /v2/indigo/check

**Expected result:**
The 'R' special node should be recognized as Pseudoatom by calling /v2/indigo/check.

**Actual result:**
Response for /v2/indigo/check contains warning about RGroup:
{
  "rgroups": "Structure contains RGroup components"
}

**Comment by Zhirnoff** [comment]
Bug is fixed in 2.10.0
