### ISSUE TITLE
Support for Collapsed monomers

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/Indigo#2574]
**Background**
Related ticket on Ketcher side: [#5402](https://github.com/epam/ketcher/issues/5402)
This ticket should support export to non-KET formats.

**Requirements**
1. Collapsed monomers should be able to be exported to/imported from Molfiles (monomers who make up the collapsed monomer, as well as the shape that the user chose to represent the collapsed monomers, coordinates of the shape).
2. Collapsed monomers should be able to be exported to/imported from HELM (no information about the shape that the user chose to represent the collapsed monomers).
2. For every other non-KET, non-Mol, and non-HELM format, the collapsed monomers should be "Expanded" and exported thusly.

**Comment by AlexeyGirin** [comment]
Unable to test w/out ketcher side
