### ISSUE TITLE
Saving atom to monomer connections to Mol and HELM

### ISSUE THREAD

**Issue by ljubica-milovic** [epam/Indigo#2575]
- Atom to monomer connections should be able to be saved to Molfile and HELM.

An example: [Molfile](https://github.com/user-attachments/files/17505872/Molfile.txt)
An example HELM string: CHEM1{*C1CCCC1 |$_R1;;;;;;$|}|RNA1{R(A)P.R(C)P.R(G)P.R(T)}$RNA1,CHEM1,1:R1-1:R1$$$V2.0

**Comment by AlexeyGirin** [comment]
Verified.
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10
