### ISSUE TITLE
Not correct length of Multi-Tailed and Single arrows for reactions with atoms after loading from RDF or Layout actions

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2583]
**Steps to Reproduce**
1. Add to canvas reaction with atoms or load from file:
[ket-cascade-reaction-2-1-1-atoms.zip](https://github.com/user-attachments/files/17522043/ket-cascade-reaction-2-1-1-atoms.zip)
![image](https://github.com/user-attachments/assets/47ffaf04-26c7-4103-be21-088f264fac09)
2. Click on layout or make save/load to/from RDF actions

**Actual behavior**
- The length of the tails is bigger than 0.5, the length of the head arrow is bigger than 6.5, size of arrow is bigger than 7:
![image](https://github.com/user-attachments/assets/cca4a0db-f981-4ff4-b33b-d6821f02ced6)

**Expected behavior**
- Total length of Multi-Tailed Arrow is 7
    - Length of tail is 0.5
    - Length of head arrow is 6.5
- Total length of the single arrow is 7, this Multi-Tailed arrow can be used as a reference for arrow with correct total length:
[multi-tailed-arrow-default-indigo.zip](https://github.com/user-attachments/files/17522103/multi-tailed-arrow-default-indigo.zip)
![image](https://github.com/user-attachments/assets/5ddb5132-7948-4838-a821-e07066707159)

**Environment details:**
Reproduced on RC SA env:
- Ketcher [Version 2.26.0-rc.6] Build at 2024-10-25; 09:57:12;
- Indigo Version 1.25.0-rc.4.0-g8862ccb7e-wasm32-wasm-clang-19.0.0
- Desktop, Windows 11 Enterprise
- Chrome, Version 130.0.6723.70 (Official Build) (64-bit)

**Additional context**
- **4 tests are added to xls and should be automated**
- The defect is detected during retesting of https://github.com/epam/Indigo/issues/2555, but initially it's related to https://github.com/epam/Indigo/issues/2309

**Comment by ivanmaslow** [comment]
Need to check when Remote env will be available to define it is Indigo or Ketcher issue.

**Comment by ivanmaslow** [comment]
Looks like it could be fixed by https://github.com/epam/Indigo/issues/2610, but length of spine becomes bigger

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-12-05_13h04_31](https://github.com/user-attachments/assets/f1d75f98-0b4d-487a-8d22-bf6e51006c55)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
