### ISSUE TITLE
Bingo Elastic Java: support reactions

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#260]
We need to support same features as for molecules:
1. Substructure search
2. Similarity search
3. Exact search

**Comment by AlexanderSavelyev** [comment]
@khyurri  could you please provide a status for this task?

**Comment by khyurri** [comment]
Completed and merged into master: https://github.com/epam/Indigo/pull/274

**Comment by MysterionRise** [comment]
Let's close the issue then @khyurri @AlexanderSavelyev @mkviatkovskii
