### ISSUE TITLE
Unknown 'a' CIP stereochemistry cause error in CDXML parser

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2603]
**Description:** 
When copying a structure from ChemDraw (version 23.1.2) and pasting it into Ketcher, a reaction arrow is pasted instead of the intended structure. This issue is specific to certain example structures and was not reproducible in older versions of ChemDraw. Similar-sized molecules do not exhibit this behavior, indicating that it may be specific to certain structural characteristics.

**Steps to Reproduce:**

1. Open ChemDraw (version 23.1.2) and load structure [files.zip](https://github.com/user-attachments/files/17598227/files.zip)
2. Copy the structure using Ctrl + C.
3. Open Ketcher and paste the copied structure.

**Note:** If we paste the structure, for example, into Word, it pastes correctly.

**Actual behavior**
Instead of the structure, a reaction arrow is pasted into Ketcher, sometimes nothing is pasted at all. The issue seems to occur only with specific example structures provided by the user.
![2024-11-01_12h33_06](https://github.com/user-attachments/assets/26b23ac5-2b3d-4407-999b-4f66a4c0a14c)

**Expected behavior**
The structure from ChemDraw should paste correctly into Ketcher without any alterations.
**This is how the structure should look in Ketcher:**
![2024-11-01_16h50_55](https://github.com/user-attachments/assets/0fd81c7d-8def-4e3e-9b9c-3b710774957c)

**This is how the structure looks in ChemDraw:**
![2024-11-01_12h33_18](https://github.com/user-attachments/assets/c4c7b81a-8925-449f-85c1-52d21edbf8ae)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.6]
**Indigo version** 
[Version 1.25.0-rc.4]

#188509377

**Comment by AliaksandrDziarkach** [comment]
Error caused by unknown 'a' CIP stereochemistry option.
In cdxml it saved as 'AS="a"'.
Need to fix parser to avoid errors on unknown CIP stereo options.
Also latest Chemdraw shoud be checked to find what this option means.

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/4ada5b63-092d-4465-9075-c8c12c9149f0)

- Ketcher Version 2.26.0-rc.9 Build at 2024-11-11; 12:01:35
- Indigo Toolkit Version 1.25.0-rc.5.0-g45d28b8ca-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10
