### ISSUE TITLE
Preview: When Reaction Conditions text field is empty, clicking on placeholder text on canvas results in a blank line, with no visible text

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2608]
**Steps to Reproduce**
1. Copy and Paste on canvas
```
$RDFILE 1
$DATM    11/05/24 13:20
$RFMT
$RXN

 -INDIGO- 1105241320

  2  1
$MOL

  -INDIGO-11052413202D

  6  6  0  0  0  0  0  0  0  0999 V2000
   10.2348   -7.2251    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.9652   -7.2246    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.1016   -6.7250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.9652   -8.2255    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.2348   -8.2300    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.1038   -8.7250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  2  0  0  0  0
  1  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  4  1  0  0  0  0
  4  2  2  0  0  0  0
  2  3  1  0  0  0  0
M  END
$MOL

  -INDIGO-11052413202D

  6  6  0  0  0  0  0  0  0  0999 V2000
   10.1098   -9.5751    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.8402   -9.5746    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.9766   -9.0750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   11.8402  -10.5755    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.1098  -10.5800    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   10.9788  -11.0750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  2  0  0  0  0
  1  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  4  1  0  0  0  0
  4  2  2  0  0  0  0
  2  3  1  0  0  0  0
M  END
$MOL

  -INDIGO-11052413202D

  6  6  0  0  0  0  0  0  0  0999 V2000
   14.0348   -8.5251    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.7652   -8.5246    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9016   -8.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.7652   -9.5255    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.0348   -9.5300    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   14.9038  -10.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  3  1  2  0  0  0  0
  1  5  1  0  0  0  0
  5  6  2  0  0  0  0
  6  4  1  0  0  0  0
  4  2  2  0  0  0  0
  2  3  1  0  0  0  0
M  END
$DTYPE Name
$DATUM Asderwydfgewsghdjedghdfertsdfg
$DTYPE Reference
$DATUM Not available
$DTYPE Reaction Conditions
$DATUM  
```

**Actual behavior**
When 'Reaction Conditions text' field is empty, clicking on placeholder text on canvas results in a blank line, with no visible text

**Expected behavior**
If the 'Reaction Conditions text' field is empty, either no placeholder should appear on the canvas

**Screenshot**

![2024-11-05_14h24_21](https://github.com/user-attachments/assets/cb9da71f-11ed-44f7-b427-3937173e8d36)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.26.0-rc.7]
**Indigo version** 
[Version 1.27.0-dev.1]

Bug foun while pre-testing: https://github.com/epam/Indigo/issues/2559

**Comment by ivanmaslow** [comment]
The fix is verified on on CI-CD SA environment with Ketcher-Master, Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 09:14:36
- Indigo Version 1.27.0-dev.1.38-g6c821972-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.70 (Official Build) (64-bit)

Issue is fixed:
![image](https://github.com/user-attachments/assets/e6a12c2e-2963-4547-bd3d-2d36dcb4fa8f)

**Comment by Zhirnoff** [comment]
Tested.
![2024-12-04_17h21_40](https://github.com/user-attachments/assets/4b5de3e3-9b1e-4096-855b-48531fbddefc)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
