### ISSUE TITLE
Saving to MOL 3000 cause template data loss that causes wrong export to HELM

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2622]
**Steps to Reproduce**
1. Go to Macro - Flex mode
2. Load from file: [Export to HELM works wrong if canvas loaded from MOL 3000.zip](https://github.com/user-attachments/files/17676148/Export.to.HELM.works.wrong.if.canvas.loaded.from.MOL.3000.zip)
![image](https://github.com/user-attachments/assets/1296f5ab-ffc0-4db9-8e59-7a66551ad4e9)
3. Save canvas to HELM

**Actual behavior**
Export result contains inline SMILES: `PEPTIDE1{[N([*:1])[C@H](C([*:2])=O)C |$;_R1;;;_R2;;$|]}|PEPTIDE2{[C([*:2])([C@H](CS[*:3])N[*:1])=O |$;_R2;;;;_R3;;_R1;$|]}$PEPTIDE1,PEPTIDE2,1:pair-1:pair$$$V2.0`
![image](https://github.com/user-attachments/assets/2b854105-26dd-4cb4-aae3-c6e7fb054fcf)

**Expected behavior**
Export result contains peptides aliases (from library): `PEPTIDE1{A}|PEPTIDE2{C}$PEPTIDE1,PEPTIDE2,1:pair-1:pair$$$V2.0`
![image](https://github.com/user-attachments/assets/cde78e6b-d523-433a-ad43-4a4fa77f46ff)

**Versions**
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/Indigo/issues/2460

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2025-01-02_13h16_19](https://github.com/user-attachments/assets/77530064-11f7-45cd-8a5f-2e93c5407d8a)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 131.0.6778.205 (Official Build) (64-bit)

**Ketcher version** 
[Version 3.0.0-rc.1]
**Indigo version** 
[Version 1.28.0-rc.1]
