### ISSUE TITLE
Elliptic arrow rendered wrong while expotring to PNG in remote mode

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2624]
This is follow up on https://github.com/epam/Indigo/issues/2513

**Steps to Reproduce**
0. Open REMOTE VERSION
1. add the reaction to the Canvas
<img width="441" alt="Screenshot 2024-10-07 at 13 07 28" src="https://github.com/user-attachments/assets/d73ee469-95d8-455d-9d3d-0207d3a8815f">

[Elliptical arrows can be saved to the png.ket.zip](https://github.com/user-attachments/files/17277443/Elliptical.arrows.can.be.saved.to.the.png.ket.zip)

2. save to png

**Actual behavior**
Elliptical error looks wrong
![374527354-0ec130fb-c598-4d31-b9d0-495e8ae3a10b](https://github.com/user-attachments/assets/262589f3-5562-4a8a-a353-ecf870c95dbf)

**Expected behavior**
Elliptical error should look same as on the canvas

**Environment details:**
- Ketcher Version 2.27.0-rc.1 Build at 2024-11-05; 14:55:18
- Indigo Toolkit Version 1.26.0-rc.1.0-g904d2d992-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10

Issues found while testing https://github.com/epam/Indigo/issues/2175

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-12-26_15h33_14](https://github.com/user-attachments/assets/f6734819-863f-42b6-8734-b868a04a72a7)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.4]
**Indigo version** 
[Version 1.27.0-rc.2]
