### ISSUE TITLE
Preview: Reaction's name and conditions change places between parts of cascade reaction with Multi-Tailed and Single arrows after save/load to/from RDF or Layout actions

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2643]
**Steps to Reproduce**
1. Add cascade reaction with Multi-Tailed/Single arrows and with Reaction's name and conditions to Canvas from ket:
[text-issue-1.zip](https://github.com/user-attachments/files/17827657/text-issue-1.zip)
![image](https://github.com/user-attachments/assets/263694ec-d733-4f0f-8d7f-10a95b1ef0c5)
2. Make save/load to/from RDF or Layout actions

**Actual Result**
- Name and conditions of the first reaction and second are switched:
![image](https://github.com/user-attachments/assets/d9bc0323-af60-4d46-9e45-11084fb25068)

**Expected Result**
- Reaction's name and conditions aren't switched
![image](https://github.com/user-attachments/assets/263694ec-d733-4f0f-8d7f-10a95b1ef0c5)

**Environment details**
- Tested on CI-CD SA environment with Ketcher-Master, Indigo-2404-ket-to-rdf branches;
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 02:19:06
- Indigo Version 1.27.0-dev.1.37-gdee66d90-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.70 (Official Build) (64-bit)

**Notes**
- **Please, also check fix for more complex case:**
[!Synthia_path_5_tails.zip](https://github.com/user-attachments/files/17827829/Synthia_path_5_tails.zip)
- Issue is detected during exploratory testing of save text for reactions - https://github.com/epam/Indigo/issues/2404

**Comment by ivanmaslow** [comment]
The fix is verified on on CI-CD SA environment with Ketcher-Master, Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 09:14:36
- Indigo Version 1.27.0-dev.1.38-g6c821972-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.70 (Official Build) (64-bit)

Reaction's name and conditions aren't switched between cascade reaction's part after save and layout actions:
![image](https://github.com/user-attachments/assets/ad64697f-d62d-4a7c-994c-ac33221134e4)

**Comment by ivanmaslow** [comment]
Retested on aws_ci SA env with Ketcher-master and Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 19:58:39;
- Indigo Version 1.27.0-dev.1.43-gec603913-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)

It works correctly with most of cases, but there is an issue with this file:
[!Synthia_path_8_tails.zip](https://github.com/user-attachments/files/17843880/Synthia_path_8_tails.zip)
![image](https://github.com/user-attachments/assets/900aa764-c7c4-4fd2-815a-1e25a660b498)
After layout actions it looks different:
![image](https://github.com/user-attachments/assets/d5340c90-1630-4d77-958a-fefcc2659862)
Also, there is another issue after save/load to/from RDF:
![image](https://github.com/user-attachments/assets/396c16f5-8e51-4db8-9042-fabcbdad2b98)
Also, ABS sign is on top:
![image](https://github.com/user-attachments/assets/ddb91f38-4086-4e96-affa-a515ec4672b5)
It works different on RC SA:
![image](https://github.com/user-attachments/assets/1cd65f95-a470-411f-9389-e98d3625ac97)

**Comment by ivanmaslow** [comment]
Retested on aws_ci SA env with Ketcher-master and Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-22; 06:47:10
- Indigo Version 1.27.0-dev.1.49-gbbd67f22-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)

The issue is fixed including the case for [!Synthia_path_8_tails.zip](https://github.com/user-attachments/files/17843880/Synthia_path_8_tails.zip):
![image](https://github.com/user-attachments/assets/4ea214cd-9f9d-4c2c-b530-a875fe1fa2e7)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-12-05_16h56_03](https://github.com/user-attachments/assets/c1f5820e-3a0c-4342-a9b2-30c0f221dcc5)
![2024-12-05_16h56_28](https://github.com/user-attachments/assets/7cf0e6a6-cf75-42ac-867e-d206657431c5)
![2024-12-05_17h01_01](https://github.com/user-attachments/assets/d9d00b82-ea90-4f00-8ff2-7614b256d219)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
