### ISSUE TITLE
Preview: Unexpected additional new lines are added to text object of reaction's name and conditions in case of several rows of text after save/load to/from RDF or Layout actions

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2645]
**Steps to Reproduce**
1. Add reaction with Multi-Tailed arrow and reaction's name and conditions (31 symbols) to Canvas from RDF:
[text-issue-3.zip](https://github.com/user-attachments/files/17832998/text-issue-3.zip)
![image](https://github.com/user-attachments/assets/30ad2547-c171-4466-9de0-d77842dd832e)
2. Check the text in text editor:
![image](https://github.com/user-attachments/assets/d0fae4c1-cee3-40d0-8ad7-6b305b855ae2)
4. Save/load to/from RDF or make a Layout action

**Actual Result**
- Multi-Tailed Arrow size is increased, additional new lines are added to text object:
![image](https://github.com/user-attachments/assets/0abf1e01-78dc-4cda-90bf-2317c08dd79d)
![image](https://github.com/user-attachments/assets/2f0cc8aa-1b89-42c7-a18b-d016c63d4198)
- If user does Save/load to/from RDF or Layout action one more time more lines will be added:
![image](https://github.com/user-attachments/assets/3b1edc45-2495-44f0-9982-3f433ef68efc)
![image](https://github.com/user-attachments/assets/415beb6a-e656-46b6-a441-02fe73c34dfe)

**Expected Result**
- Reactions with Multi-Tailed arrow and reaction's name and conditions aren't changed after save/load to/from RDF or Layout actions

**Environment details**
- Tested on CI-CD SA environment with Ketcher-Master, Indigo-2404-ket-to-rdf branches;
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 09:14:36
- Indigo Version 1.27.0-dev.1.38-g6c821972-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.70 (Official Build) (64-bit)

**Notes**
- **Pay attention - check the fix for cases below**:
    - Load the reaction after that make save/load to RDF or layout action - new lines are added as in defect:
[text-issue-5.zip](https://github.com/user-attachments/files/17842724/text-issue-5.zip)
![image](https://github.com/user-attachments/assets/ed2c01b4-d465-4f9b-845d-1f3bf33c7580)
![image](https://github.com/user-attachments/assets/beb53b54-5504-471c-adad-96ab2ea3a7c6)
    - "of" should be in the first line as it supports 30 symbols:
[text-issue-4.zip](https://github.com/user-attachments/files/17832957/text-issue-4.zip)
![image](https://github.com/user-attachments/assets/ecae41f6-bdd7-4de5-9caf-29257b78db71)
- Issue is detected during exploratory testing of save text for reactions - https://github.com/epam/Indigo/issues/2404

**Comment by ivanmaslow** [comment]
The fix is successfully verified on aws_ci SA env with Ketcher-master and Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 19:58:39;
- Indigo Version 1.27.0-dev.1.43-gec603913-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)

New lines aren't added in both cases after save/load to/from RDF or layout actions:
![image](https://github.com/user-attachments/assets/3da5c33b-4bd0-426c-8d81-ab4be52d6d97)
![image](https://github.com/user-attachments/assets/3c897eea-98b0-41a1-9e72-8aed25716461)

New defect is created for the case with not correct wrapping: 
- https://github.com/epam/Indigo/issues/2646

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-12-06_10h47_26](https://github.com/user-attachments/assets/329f8cca-4373-4a95-9049-21348247b915)
![2024-12-06_10h47_42](https://github.com/user-attachments/assets/f48a0154-be40-4e8c-b547-f57f2e093d70)
![2024-12-06_10h48_00](https://github.com/user-attachments/assets/c422790b-c3be-4360-b336-f55c8d1c2a93)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
