### ISSUE TITLE
Preview: Reaction's name or conditions text wraps incorrectly: the line should only break after a complete word, ensuring no more than 30 characters per line

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2646]
**Steps to Reproduce**
1. Load from RDF the reaction with name and conditions (e.g.: 12345 678901234567890123456789 0)
[text-issue-6.zip](https://github.com/user-attachments/files/17843002/text-issue-6.zip)

**Actual Result**
- Reaction's name and conditions text wraps not after the 30th character:
![image](https://github.com/user-attachments/assets/b38078ea-f9f8-4a49-bdda-085f87cba2f1)
![image](https://github.com/user-attachments/assets/3ecc5dd6-c43c-40df-9ecd-5796a8789b58)

**Expected Result**
- Reaction's name and conditions text wraps after the 30th character:
![image](https://github.com/user-attachments/assets/021286c1-22fc-427f-af12-fe0d54d78fca)

**Environment details**
- Tested on aws_ci SA env with Ketcher-master and Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-20; 19:58:39;
- Indigo Version 1.27.0-dev.1.43-gec603913-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)

**Notes**
- The real case was with the reaction below "of" should bein the first line:
[text-issue-4.zip](https://github.com/user-attachments/files/17843320/text-issue-4.zip)
![image](https://github.com/user-attachments/assets/30755604-b663-4582-90ba-de04a76f6e95)
- **Also please fix the case when we have a punctuation mark at the 30 character - now it's removed on load (it works correctly for letters):**
[text-issue-7.zip](https://github.com/user-attachments/files/17843490/text-issue-7.zip)
![image](https://github.com/user-attachments/assets/8069fb39-df6d-4255-b720-c3f4347ec0cd)
![image](https://github.com/user-attachments/assets/c59f9bc3-a7d8-43ac-b53b-0dee165a8e4c)
- **TBD** - in case when we have word with 30 symbols, it's wrapped with the space to the next line:
[rdf-single-reaction-2x1-auto-wrap-space-after-30-symbols.zip](https://github.com/user-attachments/files/17849177/rdf-single-reaction-2x1-auto-wrap-space-after-30-symbols.zip)
![image](https://github.com/user-attachments/assets/4d92254f-580c-4b57-a320-b4fa9b22d43d)

- Issue is detected during exploratory retesting of https://github.com/epam/Indigo/issues/2645, but initially it's related to save text for reactions - https://github.com/epam/Indigo/issues/2404

**Comment by ivanmaslow** [comment]
Successfully retested on aws_ci SA env with Ketcher-master and Indigo-2404-ket-to-rdf branches:
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-22; 06:47:10
- Indigo Version 1.27.0-dev.1.49-gbbd67f22-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)

The cases above are covered:
- [text-issue-6.zip](https://github.com/user-attachments/files/17843002/text-issue-6.zip):
![image](https://github.com/user-attachments/assets/64c74d82-a671-4c69-984a-08e33f325da2)
- [text-issue-4.zip](https://github.com/user-attachments/files/17843320/text-issue-4.zip):
![image](https://github.com/user-attachments/assets/2edbb2c9-94b5-469c-8bc9-6dfc0a78e28d)
- [text-issue-7.zip](https://github.com/user-attachments/files/17843490/text-issue-7.zip):
![image](https://github.com/user-attachments/assets/2a208b69-2a4b-4fb8-81a9-26def35166bb)
- [rdf-single-reaction-2x1-auto-wrap-space-after-30-symbols.zip](https://github.com/user-attachments/files/17849177/rdf-single-reaction-2x1-auto-wrap-space-after-30-symbols.zip)
![image](https://github.com/user-attachments/assets/7ec95e3c-007e-4315-bb39-e247832abe97)

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.
![2024-12-05_16h49_06](https://github.com/user-attachments/assets/61fe71be-bee6-4ffe-8901-5707b3cdac8c)


**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
