### ISSUE TITLE
Reaction's name or conditions text wraps incorrectly in specific cases: the last line before truncating, removing of special symbols, empty line instead of "..."

### ISSUE THREAD

**Issue by ivanmaslow** [epam/Indigo#2647]
**Steps to Reproduce - the last line and special symbols issue**
1. Load from RDF the reaction with name, conditions and truncating:
[text-issue-8.zip](https://github.com/user-attachments/files/17871745/text-issue-8.zip)
![image](https://github.com/user-attachments/assets/da88ced8-d5c1-4394-b7d1-2004572351b4)

**Actual Result**
- The last line doesn't contain 27 symbols and "...", some special symbols are lost (":", ">"):
![image](https://github.com/user-attachments/assets/ae82f002-ec8d-4c27-bbed-3b33defdddb9)

**Expected Result**
- The last line contains 27 symbols and "...", special symbols aren't lost

**Steps to Reproduce - last line is empty**
1. Load from RDF the reaction with name and truncating:
[text-issue-9.zip](https://github.com/user-attachments/files/17871723/text-issue-9.zip)
![image](https://github.com/user-attachments/assets/4c1eff3b-359a-4b1b-a1f4-774b004d0d9f)

**Actual Result**
- The last line is empty, no information that some part of conditions were removed "...":
![image](https://github.com/user-attachments/assets/c9fd905a-47e2-499c-994e-d0359c857b96)

**Expected Result**
- The last line should contain information that conditions are lost

**Environment Details**
- Tested on aws_ci SA env with Ketcher-master and Indigo-2404-ket-to-rdf branches
- Ketcher [Version 2.28.0-dev.1] Build at 2024-11-22; 06:47:10
- Indigo Version 1.27.0-dev.1.49-gbbd67f22-wasm32-wasm-clang-12.0.0
- Desktop, Windows 11 Enterprise
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)

**Additional Context**
- Issue is detected during exploratory testing of https://github.com/epam/Indigo/issues/2559

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-12-06_11h12_06](https://github.com/user-attachments/assets/ecbde2c3-d0d1-4297-be4c-313affedf269)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
