### ISSUE TITLE
Arrow size become 2 bonds length after indigo changed default arrow size to 1

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2654]
**Steps to Reproduce**
1. Go to Macro - Flex mode
2. Load from file: [structure-with-s-groups-with-unsupported-s-group-type.zip](https://github.com/user-attachments/files/17919284/structure-with-s-groups-with-unsupported-s-group-type.zip)

**Actual behavior**
Arrow length in the reaction is 2 bonds length
![image](https://github.com/user-attachments/assets/05697665-204a-45bd-a927-cdef23bc0190)

**Expected behavior**
Arrow length in the reaction is 1 bonds length
![image](https://github.com/user-attachments/assets/5b031de3-6111-459d-8ef0-32584b9d0b9f)

As per [requirement](https://github.com/epam/ketcher/issues/5152):

> **Bond length** - length of one bond and the length of the default arrows (related issue: [#5153](https://github.com/epam/ketcher/issues/5153))

**Versions**
- Ketcher Version 2.28.0-dev.1 Build at 2024-11-26; 11:50:22
- Indigo Version 1.27.0-dev.2.0-g0c2a12eda-wasm32-wasm-clang-19.0.0
- Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Win10

Found while testing - https://github.com/epam/ketcher/pull/6009

**Comment by even1024** [comment]
Not merged into 1.26.0

**Comment by AlexeyGirin** [comment]
Verified in 1.26.0-rc.5
![image](https://github.com/user-attachments/assets/6ee86dc3-92f8-424c-b033-ec40c203b8af)

- Ketcher Version 2.27.0-rc.3 Build at 2024-12-25; 10:08:04
- Indigo Version 1.26.0-rc.5.0-g42ee8510b-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.205 (Official Build) (64-bit)
- Win10

**Comment by AlexeyGirin** [comment]
Verified in 1.26.0-rc.5
![image](https://github.com/user-attachments/assets/6ee86dc3-92f8-424c-b033-ec40c203b8af)

- Ketcher Version 2.27.0-rc.3 Build at 2024-12-25; 10:08:04
- Indigo Version 1.26.0-rc.5.0-g42ee8510b-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
