### ISSUE TITLE
Arrow size is wrong if reaction loaded from SMARTS

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2662]
**Steps to Reproduce**
1. Go to Micro
2. Load to canvas following reaction using paste from clipboard way: `[#6]1(-[#6])-[#6](-[#8])=[#6]-[#6](-[#16])=[#6](-[#7])-[#6]=1>>[#6]1(-Br)-[#6](-[#6])=[#6]-[#6](-I)=[#6](-[#8])-[#6]=1`

**Actual behavior**
Arrow size definitely longer than bond size 
![image](https://github.com/user-attachments/assets/248e7dbd-72fb-4848-bcee-26708ab7894b)

**Expected behavior**
Arrow size has bond size
![image](https://github.com/user-attachments/assets/35bb3ec8-fe3e-4e2a-8905-0baf5060a2b7)

As per [requirements](https://github.com/epam/ketcher/issues/5152):

> **Bond length** - length of one bond and the length of the default arrows (related issue: [#5153](https://github.com/epam/ketcher/issues/5153));

**Versions**
- Ketcher Version 2.28.0-dev.1 Build at 2024-11-28; 06:41:11
- Version 1.27.0-dev.3.0-g62217e49f-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5152, https://github.com/epam/Indigo/issues/2176

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-12-06_11h21_38](https://github.com/user-attachments/assets/da94a19d-015c-4b41-b97b-14b2cd71fb3b)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]
