### ISSUE TITLE
Vertical margin for catalyst is wrong 

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/Indigo#2664]
**Steps to Reproduce**
1. Go to Micro
2. Load to canvas following reaction using paste from clipboard way: `[#15]1-[#6]=[#6]-[#6]=[#6]-1>Br.Br>[#8]`

**Actual behavior**
Vertical distance between arrow and catalyst atoms to high
![image](https://github.com/user-attachments/assets/29ddf9fe-da01-418d-83a3-e68a037c57ae)

**Expected behavior**
Vertical distance between arrow and catalyst equal to hotizontal distance between catalyst and reaction molecule
![image](https://github.com/user-attachments/assets/a31fce34-638a-4854-b010-f7b6aa94d42b)

As per [requirements](https://github.com/epam/Indigo/issues/2176):

![image](https://github.com/user-attachments/assets/a0240e99-b040-4326-b695-44aa43b131d9)

**Versions**
- Ketcher Version 2.28.0-dev.1 Build at 2024-11-28; 06:41:11
- Version 1.27.0-dev.3.0-g62217e49f-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.86 (Official Build) (64-bit)
- Win10

Issue found while testing - https://github.com/epam/ketcher/issues/5152

**Comment by even1024** [comment]
Not merged into 1.26.0

**Comment by Zhirnoff** [comment]
Tested. Bug fixed.

![2024-12-26_10h52_28](https://github.com/user-attachments/assets/2b7e2009-2f56-427c-bc2c-7110a95bfc0c)

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.4]
**Indigo version** 
[Version 1.27.0-rc.2]
