### ISSUE TITLE
Molfile V3000 with SGROUP type DAT fails to load in Ketcher due to missing spaces in FIELDDISP

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#2681]
**Summary**
Ketcher fails to load .mol files containing SGROUPs of type DAT when the FIELDDISP field lacks proper spacing. The issue arises from Indigo's inability to parse improperly formatted FIELDDISP strings, leading to a failure to load the file.
Explanation: 
According to BIOVIA CTfile Formats reference specification FIELDDISP field stored value (Free-format string) should be 

> interpreted by V3000 as identical to V2000 appendix for Data Sgroup display (‘M SDD’) except for the index value.

that means that it should comply the following format:

> ### Data Sgroup Display Information [Sgroup]
> `M SDD sss xxxxx.xxxxyyyyy.yyyy eeefgh i jjjkkk ll m noo`
> | Mask | Description |
> | --- | --- |
> | sss: | Index of data Sgroup |
> | x,y: | Coordinates (2F10.4) |
> | eee: | (Reserved for future use) |
> | f: | Data display, A = attached, D = detached |
> | g: | Absolute, relative placement, A = absolute, R = relative |
> | h: | Display units, blank = no units displayed, U = display units |
> | i: | (Reserved for future use) |
> | jjj: | Number of characters to display (1...999 or ALL) |
> | kkk: | Number of lines to display (unused, always 1) |
> | ll: | (Reserved for future use) |
> | m: | Tag character for tagged detached display (if non-blank) |
> | n: | Data display DASP position (1...9). (MACCS-II only) |
> | oo: | (Reserved for future use) |
> 
> 
Biovia app in case of invalid FIELDDISP value simply reset it to its default one:
`M V30 FIELDDISP="  10.2166  -9.8608   DA   ALL 1    "`

**Steps to Reproduce**
1. Load file into micro mode [FromBioviaDoc.zip](https://github.com/user-attachments/files/18036930/FromBioviaDoc.zip)

**Actual behavior**
![2024-12-06_13h49_22](https://github.com/user-attachments/assets/7dfd194b-dacb-410a-92d4-51bc4c8c4096)
![2024-12-06_10h37_33](https://github.com/user-attachments/assets/05acbde6-d12a-49cb-9bda-bae115d1812c)

**Expected behavior**
If FIELDDISP string value length is less than 36 chars  we decide to trim all space block to one space each and try to interpret the rest of symbols as 
`M SDD sss xxxxx.xxxxyyyyy.yyyy fgh jjjkkk m n`
where:
| Mask | Description |
| --- | --- |
| sss: | Index of data Sgroup |
| x,y: | Coordinates (2F10.4) |
| f: | Data display, A = attached, D = detached |
| g: | Absolute, relative placement, A = absolute, R = relative |
| h: | Display units, blank = no units displayed, U = display units |
| jjj: | Number of characters to display (1...999 or ALL) |
| kkk: | Number of lines to display (unused, always 1) |
| m: | Tag character for tagged detached display (if non-blank) |
| n: | Data display DASP position (1...9). (MACCS-II only) |

**Desktop:**
 - OS: Windows 11
 - Browser Chrome
 - Version 128.0.6613.120 (Official Build) (64-bit)

**Ketcher version** 
[Version 2.28.0-rc.1]
**Indigo version** 
[Version 1.27.0-rc.1]

#188659797

**Comment by AlexeyGirin** [comment]
Verified.
![image](https://github.com/user-attachments/assets/99af82bd-840c-45c5-ac0b-1ef2c2752da8)
- Ketcher Version 2.27.0-rc.3 Build at 2024-12-25; 10:08:04
- Indigo Version 1.26.0-rc.5.0-g42ee8510b-wasm32-wasm-clang-19.0.0
- Chrome Version 131.0.6778.205 (Official Build) (64-bit)
- Win10
