### ISSUE TITLE
Update check() method to be consistent with indigo-service check() REST API call

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#269]
We have an REST API service written in Python called "indigo-service" (source file is here: https://github.com/epam/Indigo/blob/master/utils/indigo-service/service/v2/indigo_api.py). It has a number of REST API calls, some of them are thin wrappers over Indigo API, some of them contain some extended logic. We want to move all possible logic into C++ part to make it available not only in service.

Currently we have a `check()` method both in service and C++ API (entrypoint is `indigoCheck` in https://github.com/epam/Indigo/blob/master/api/src/indigo_misc.cpp). We need to unite their behavior to provide all required checks to C++ API.

Short example. Indigo API code:
```
from indigo import Indigo
i = Indigo()
qm = i.loadQueryMolecule('''
  Ketcher 12222012222D 1   1.00000     0.00000     0

  6  6  0     0  0            999 V2000
    6.2250   -5.4250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.0910   -5.9250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.0910   -6.9250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.2250   -7.4250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.3590   -6.9250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.3590   -5.9250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0     0  0
  2  3  2  0     0  0
  3  4  1  0     0  0
  4  5  2  0     0  0
  5  6  1  0     0  0
  6  1  2  0     0  0
M  RBC  1   4   2
M  END
''')
qm.check()
```
It returns empty JSON: `{}`. However, the service call for the same molecule returns
```
{
  "query": "Structure contains query features", 
  "stereo": "Structure has stereochemistry errors"
}
```

So we need to test all features that indigo-service checker affords and improve C++ checker to provide the same behavior.

Note: indigo-service checker could be used through Ketcher (https://lifescience.opensource.epam.com/ketcher/demo.html)

**Comment by Dmitrii-Chernov-epam-com** [comment]
**Steps to reproduce:**

1. Build python api:
	indigo-make-by-libs.py --type=python
	unzip Indigo/dist/indigo-python-1.4.1.5-win.zip to <dir>
2. Paste the issue sample into ISSUE.py file in the <dir>:
	..
	indigo
	lib
	ISSUE.py
3. Run ISSUE.py

**Actual result:** empty output
**Expected result:**
	{
		"query": "Structure contains query features", 
		"stereo": "Structure has stereochemistry errors"
	}
	


**Problem:**
The current python (and other platforms) api code:
    indigo/__init__.py
    def check(self, props=""):
        if props is None:
            props = ""
        self.dispatcher._setSessionId()
        return self.dispatcher._checkResultString(
            Indigo._lib.indigoCheck(self.id, props.encode(ENCODE_ENCODING))
        )
uses 
	/Indigo/api/src/indigo_misc.cpp
	CEXPORT const char* indigoCheck(int item, const char* props)
	
But the current Rest code performs additional checking in its
	/Indigo/utils/indigo-service/service/v2/indigo_api.py
	Line 727: def check():


**Solution:**
	1. The Rest check() code should be refactored into C++ code in the 	
		/Indigo/api/src/indigo_misc.cpp 
		CEXPORT const char* indigoCheck(int item, const char* props)
	2. indigoCheck(int item, const char* props) should have the same behavior as the Rest check() method
	3. Rest check() method should be replaced with the indigoCheck(int item, const char* props) API call.

**Comment by Dmitrii-Chernov-epam-com** [comment]
Pull request (DON'T MERGE! Not debugged yet! For review only)
https://github.com/epam/Indigo/pull/285

Please, look into ".....check2" features.

The class **StructureChecker2**
replaces StructureChecker and ReactionChecker classes.

The functions "check2" in C and Python replace the corresponding functions "check"

After debugging, "check" instances should be removed and "check2" instances should be renamed to "check"
