### ISSUE TITLE
All structures on the canvas are cleaned up if Clean Up function is applied to a part of one structure

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/Indigo#275]
**Affected Version:** Ketcher Standalone

**Steps to Reproduce:**

### Scenario1

1. Create two benzene structures.
2. Attach single bonds to the left structure.
3. Attach single and double bonds to the right structure.
4. Distort the structures.
5. Select a part of one structure using Lasso Selection.
6. Click 'Clean Up' button.

### Scenario#2

1. Create several structures.
2. Create R-Group labels in the different parts of the structures.
3. Distort the structures.
4. Select a part of one structure sing Lasso Selection.
5. Click 'Clean Up' button.

### Scenario#3

1. Create several structures with different atom symbols.
2. Set attachment points on different symbols.
3. Distort structures.
4. Select a part with attachment point of one structure.
5. Click 'Clean Up' button.

### Scenario#4
1. Create a chain structure.
2. Distort the created structure.
3. Select a part of the structure.
4. Click 'Clean Up' button.

### Scenario#5

1. Create 3-5 structures.
2. Distort the structures.
3. Select a part of one structure.
4. Click 'Clean Up' button.

**Expected Result:**
Only the selected part of the structure is leaned up.

**Scenario#1**
![2020-12-28_10h46_36](https://user-images.githubusercontent.com/75974843/103199922-0acc0280-48fd-11eb-9d16-d141ec71cf84.gif)

**Scenario#2**
![2020-12-28_10h50_07](https://user-images.githubusercontent.com/75974843/103199914-069fe500-48fd-11eb-9544-cfcb2a16911c.gif)

**Scenario#3**
![2020-12-28_11h02_18](https://user-images.githubusercontent.com/75974843/103199904-030c5e00-48fd-11eb-8da2-e2657ec45198.gif)

**Scenario#4**
![2020-12-28_11h28_52](https://user-images.githubusercontent.com/75974843/103201201-621fa200-4900-11eb-8029-825ba1f9285c.gif)

**Scenario#5**
![2020-12-28_11h55_10](https://user-images.githubusercontent.com/75974843/103206203-5e921800-490c-11eb-87b2-6a7e5c47b7b7.gif)

**Actual Result:**
All structures on the canvas are cleaned up when Clean Up function is applied to the part of one structure.

**Comment by AlexanderSavelyev** [comment]
Implement Indigo core 2 functions
CleanUp(BaseMolecule& )
CleanUp(BaseReaction& )
which can work with selected atoms
