### ISSUE TITLE
List atom of one structure is changed to Single atom after Clean Up is applied to another structure

### ISSUE THREAD

**Issue by ElenaKlepova** [epam/Indigo#278]
**Affected Version:** Ketcher _Standalone, Remote, release\2.1_

**Steps to reproduce:**
1. Create 2 structures.
2. Attach List atom to one structure.
3. Distort the created structures.
4. Select one structure without the list atom.
5. Click 'Clean Up' function.

**Actual Result:**
The unselected List atom is changed to Single atom after Clean Up function.
![103209074-38bc4180-4913-11eb-8235-ba1b8fe6cf7c](https://user-images.githubusercontent.com/75974843/103223120-9dd55e80-4936-11eb-81f0-b042cc466221.gif)

**Expected Result:**
The unselected List atom is not changed after Clean Up function.

**Comment by AllaZhbanova** [comment]
Fixed, tested on ketcher v2.4
