### ISSUE TITLE
Clang formatting problem with macros.

### ISSUE THREAD

**Issue by SunFellow** [epam/Indigo#282]
After `.clang-format` was added, the C++ files are forcibly formatted by Clang rules.
There is a lot of functions those format became damaged and badly readable, like:
```
CEXPORT int indigoIterateDataSGroups(int molecule){INDIGO_BEGIN{QS_DEF(Array<int>, sgs);
sgs.clear();
BaseMolecule& mol = self.getObject(molecule).getBaseMolecule();
mol.sgroups.findSGroups(SGroup::SG_TYPE, SGroup::SG_TYPE_DAT, sgs);
return self.addObject(new IndigoDataSGroupsIter(mol, sgs));
}
INDIGO_END(-1)
}
```
This looks like a bug of Clang formatting, that cannot be tuned with provided set of options.
The only workaround I've found is to remove the pair of braces, the first one - immediate after `INDIGO_BEGIN` and the last one - immediate before `INDIGO_END`. 
Where there is no opening brace after the macro, the formatting is OK, for example:
```
CEXPORT const char* indigoDbgProfiling(int whole_session)
{
    INDIGO_BEGIN
    {
        auto& tmp = self.getThreadTmpData();
        ArrayOutput out(tmp.string);
        profGetStatistics(out, whole_session != 0);

        tmp.string.push(0);
        return tmp.string.ptr();
    }
    INDIGO_END(0);
}
```

`INDIGO_BEGIN`  is intensively used in Indigo C++. There are 372 instances of `INDIGO_BEGIN` and ~205 instances of problematic `INDIGO_BEGIN{` .  So, it does not look realistic to get rid of the macros at the moment. 
However, we can remove the superfluous pair of braces between `INDIGO_BEGIN` and `INDIIGO_END`, since these macros anyway open and close a block inside `try { ... }`.

**Comment by AlexanderSavelyev** [comment]
Removing the { } looks too complicating in order to resolve the formatting issue
Are there any other possible ways to fix the issue. How do the 372-205 instances (not problematic) look like

FYI in the code above the sgs.clear(); is not required since it is already part of QS_DEF macros

**Comment by SunFellow** [comment]
@mkviatkovskii  has found better workaround: it's enough to add semicolon after `INDIGO_END(0)` macro and the formatting gets nice.
This is trivial find-and-replace operation.

**Comment by SunFellow** [comment]
> How do the 372-205 instances (not problematic) look like?

They look nice:
```
CEXPORT const char* indigoDbgProfiling(int whole_session)
{
    INDIGO_BEGIN
    {
        auto& tmp = self.getThreadTmpData();
        ArrayOutput out(tmp.string);
        profGetStatistics(out, whole_session != 0);

        tmp.string.push(0);
        return tmp.string.ptr();
    }
    INDIGO_END(0);
}
```
And yes, it's because of semicolon after `INDIGO_END()`.
