### ISSUE TITLE
Indigo.calculate  should respond values separated by semicolon

### ISSUE THREAD

**Issue by TomasLight** [epam/Indigo#295]
Caused by epam/ketcher#220

There is need to present formula values separately, and not summary of values.

Try calculate values for atoms:
Cl, Br, N

Expected result
```
{
   gross: "CIJ; H3N; BrH"
   mass-composition: "H 3 CI 97; H 18 N; H 1 Br 9"
   molecular-weight: "36.461; 17.031; 80.912"
   monoisotopic-mass: "35.977; 17.027; 79.926"
   most-abundant-mass: 132.929
}
```

Actual result
```
{
  gross: "Br Cl H5 N"
  mass-composition: "H 3.75 Br 59.45 Cl 26.38 N 10.42"
  molecular-weight: 134.403
  monoisotopic-mass: 132.929
  most-abundant-mass: 132.929
}
```

**Comment by SunFellow** [comment]
This requires significant change of Indigo API and coordinated changes in all wrappers. Currently, functions those calculate mass of **molecule** return single value (~summary mass of atoms). 
You request to return a map of values corresponding to atoms. Additionally, with a huge number of atoms per molecule, the size of the results transferring API layers will be multiplied N times.

**Comment by mkviatkovskii** [comment]
@TomasLight could you please show the exact molecule molfile that is passed to Indigo?

**Comment by TomasLight** [comment]
@mkviatkovskii 
```
"
  Ketcher  1222121 82D 1   1.00000     0.00000     0

  3  0  0     0  0            999 V2000
   18.6250   -6.9250    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   20.5500   -6.8250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   22.4750   -6.7500    0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
M  END
"
```

**Comment by SunFellow** [comment]
Found the target component: indigo-wasm.
