### ISSUE TITLE
'Calculated Values' for reaction doesn't work in Indigo JS version

### ISSUE THREAD

**Issue by KseniiaSemenishcheva** [epam/Indigo#319]
**Steps to Reproduce:**
1. call indigo.calculate(struct, indigoOptions) with following parameters

> struct: "$RXN↵↵↵↵  2  1  0↵$MOL↵↵  Ketcher  2 82115 42D 1   1.00000     0.00000     0↵↵  5  4  0     0  0            999 V2000↵    6.6250   -6.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    7.4910   -7.3250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    8.3572   -6.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    9.2232   -7.3250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   10.0892   -6.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵  1  2  1  0     0  0↵  2  3  1  0     0  0↵  3  4  1  0     0  0↵  4  5  1  0     0  0↵M  END↵$MOL↵↵  Ketcher  2 82115 42D 1   1.00000     0.00000     0↵↵  6  6  0     0  0            999 V2000↵   15.0751   -6.1250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   15.9411   -6.6250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   15.9411   -7.6250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   15.0751   -8.1251    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   14.2091   -7.6250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   14.2091   -6.6250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵  1  2  1  0     0  0↵  2  3  2  0     0  0↵  3  4  1  0     0  0↵  4  5  2  0     0  0↵  5  6  1  0     0  0↵  6  1  2  0     0  0↵M  END↵$MOL↵↵  Ketcher  2 82115 42D 1   1.00000     0.00000     0↵↵ 11 11  0     0  0            999 V2000↵   21.7251   -5.9000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   22.5911   -6.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   22.5911   -7.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   21.7251   -7.9001    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   20.8591   -7.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   20.8591   -6.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   23.5912   -6.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   24.0912   -5.5340    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   25.0912   -5.5340    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   25.5912   -4.6679    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   26.5912   -4.6679    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵  1  2  1  0     0  0↵  2  3  2  0     0  0↵  3  4  1  0     0  0↵  4  5  2  0     0  0↵  5  6  1  0     0  0↵  6  1  2  0     0  0↵  2  7  1  0     0  0↵  7  8  1  0     0  0↵  8  9  1  0     0  0↵  9 10  1  0     0  0↵ 10 11  1  0     0  0↵M  END↵"

**Expected Result:**
As for server API:

> {
  "gross": "[C5 H12] + [C6 H6] > [C11 H16]", 
  "mass-composition": "[C 83.24 H 16.76] + [C 92.26 H 7.74] > [C 89.12 H 10.88]", 
  "molecular-weight": "[72.1487818] + [78.1118417] > [148.2447433]", 
  "monoisotopic-mass": "[72.0939002] + [78.0469501] > [148.1252003]", 
  "most-abundant-mass": "[72.0939002] + [78.0469501] > [148.1252003]"
}

**Actual Result:**
Zero values, error message appears:
![StandaloneCalculatedValues](https://user-images.githubusercontent.com/75974465/107218476-b9954f80-6a20-11eb-9b25-6438595b00c1.jpg)

**Comment by KseniiaSemenishcheva** [comment]
Issue is related with: https://github.com/epam/ketcher/issues/294

**Comment by even1024** [comment]
The issue has been fixed in PR: fix319
