### ISSUE TITLE
Indigo Python wrapper syntax sugar proposal

### ISSUE THREAD

**Issue by khyurri** [epam/Indigo#322]
Hey, I want to make a proposal for new python syntax for managing indigo session automatically.

### Rationale

Class `Indigo` is the main primitive for synchronization states between indigo core (compiled C and C++ code) and python code. Users should manually manage creating and passing this class through the code. This can complicate the code and lead to errors.

Example: 

User has 2 different functions for creating molecules

```
...
def create_mol_1(session: Indigo) -> IndigoObject:
    return loadMolecule("[H]")
... 
def create_mol_2(session: Indigo) -> IndigoObject:
    return loadMolecule("[O]")
```

User somehow get's this molecules:
```
mol1 = create_mol_2(session)
...
mol2 = create_mol_2(session) 
```
Right now there is no guarantee, that `session` in functions argument is the same. Moreover, to compare this compounds, user should find this `session` again:

```
c_bits = session.commonBits(mol1.fingerprint('sim'), mol2.fingerprint('sim'))
```

If user loses the session, an error 

```
indigo.IndigoException: core: can not access object #1006: red-black tree: at(): key not found

```

will be occurred.

### Proposal

Additional `indigo_tools` module can provide user friendly and pythonic way to manage Indigo session.

#### Singleton

indigo will be same in any part of the users application. Not needed to pass it from one function to another.

```
from indigo_tools import indigo
... 
def create_mol_1() -> IndigoObject:
    return indigo().loadMolecule("[H]")
... 
def create_mol_2() -> IndigoObject:
    return indigo().loadMolecule("[O]")
```

Using `indigo_tools.indigo()` will help user to avoid `red-black tree: at(): key not found` exceptions for free.

```
from indigo_tools import indigo
...
c_bits = indigo().commonBits(mol1.fingerprint('sim'), mol2.fingerprint('sim'))
```

#### Thread safe

In any thread user will have own `indigo()` object. We should provide `copy` functionality to help users implement FanIn and FanOut patterns

Example:
```
def inside_thread():
    print(f'Inside thread {threading.current_thread().ident}: {indigo()}')
    indigo().loadMolecule("[H]").fingerprint('sim')


if __name__ == "__main__":
    print(f"Current session: {indigo()}")
    t1 = threading.Thread(target=inside_thread, daemon=True)
    t2 = threading.Thread(target=inside_thread, daemon=True)
    print('Every thread will have own indigo session')
    t1.start()
    t2.start()
    t1.join()
    t2.join()
```

Result:

```
Current session: <indigo.Indigo object at 0x7f8e0321b340>
Every thread will have own indigo session
Inside thread 123145547132928: <indigo.Indigo object at 0x7f8e032b5fa0>
Inside thread 123145563922432: <indigo.Indigo object at 0x7f8e032bf100>
```

#### Context managers

Users can change and restore `indigo()` state with context managers syntax:

```
with indigo_ctx():
    print(f'Context managers session: {indigo()}')
    indigo().setOption('render-background-color', '0 0 0')
print(f"Out of context managers session: {indigo()}")
```

Or pass options as argument:

```
with indigo_ctx(setOption={'render-background-color': '0 1 2'}):
    print(f'Context managers session: {indigo()}')
    indigo().setOption('render-background-color', '0 0 0')
print(f"Out of context managers session: {indigo()}")
```

#### Implementation problems/questions
1. We should think about fast session deep copy for context managers and FanIn/FanOut patterns
2. Not clear how to use `indigo()` with asyncio
3. Is it possible to implement similar functionality in other wrappers (Java, C#, JS, R)

### Backwards compatibility
1. Users can still manage Indigo manually, this feature provided by separate module. 
2. Only Python 3.7 and latest are supported

**Comment by MysterionRise** [comment]
Is Context manager example is expected final usage in most of the cases, where user do not need to spawn several threads?

**Comment by khyurri** [comment]
> Is Context manager example is expected final usage in most of the cases, where user do not need to spawn several threads?

I think the most common usage is just calling `indigo()` function that return correct `Indigo()` instance

Check the first example, Singleton
