### ISSUE TITLE
'Layout' function causes unintended bond changes

### ISSUE THREAD

**Issue by IanaStepanova** [epam/Indigo#331]
**Steps to reproduce:**
1. call indigo/layout(options, struct) with struct being as following (structure with bonds):

> "↵  Ketcher  2172114302D 1   1.00000     0.00000     0↵↵  9  8  0     0  0            999 V2000↵   -4.3250   -1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   -3.4590   -2.1000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   -2.5929   -1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   -1.7269   -2.1000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   -0.8609   -1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    0.0051   -2.1000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    0.8712   -1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    1.7372   -2.1000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵   -3.4590   -3.1000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵  1  2  1  0     0  0↵  2  3  1  0     0  0↵  3  4  1  0     0  0↵  4  5  1  0     0  0↵  5  6  1  0     0  0↵  6  7  1  0     0  0↵  7  8  1  0     0  0↵  2  9  1  1     0  0↵M  END↵"
![request](https://user-images.githubusercontent.com/53190213/108199059-842de780-712d-11eb-91da-65d2110a4f38.png)

**Expected result:**

1. struct stays the same, as the layout function is supposed to only change the location of the structure without making any changes to the structure

**Actual result:**

1. For cyclic structure: all stereobonds are changed to the single bonds
2. For line structure (chain): Single Down Bond is changed to the Single Up Bond, Single Up Bond is changed to the Single Down Bond
(please note the last line in the Bond Block in the provided example):

> "↵  -INDIGO-02172111302D↵↵  9  8  0  0  0  0  0  0  0  0999 V2000↵   -1.3856   -0.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    0.0000    0.0000    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0↵    1.3856   -0.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    2.7713    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    4.1569   -0.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    5.5426    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    6.9282   -0.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    8.3138    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵    0.0000    1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0↵  1  2  1  0  0  0  0↵  2  3  1  0  0  0  0↵  3  4  1  0  0  0  0↵  4  5  1  0  0  0  0↵  5  6  1  0  0  0  0↵  6  7  1  0  0  0  0↵  7  8  1  0  0  0  0↵  2  9  1  6  0  0  0↵M  END↵"
![response](https://user-images.githubusercontent.com/53190213/108199060-84c67e00-712d-11eb-80ec-19937ae64cd9.png)

**Comment by even1024** [comment]
Not a bug. Layout operates in 3d so it's up to layout algorithm to flip up-down and also to remove meaningless up or down bonds.

**Comment by AllaZhbanova** [comment]
Confirmed by @AlexanderSavelyev as not a bug
