### ISSUE TITLE
Error 5903896 during png generation

### ISSUE THREAD

**Issue by TomasLight** [epam/Indigo#336]
Caused [#343 issue in Ketcher](https://github.com/epam/ketcher/issues/343)

Try to generate png from molfile `All atom properties.mol`
[All atom properties.zip](https://github.com/epam/ketcher/files/6035606/All.atom.properties.zip)

**ER**: Generated base64

**AR**: error `Uncauth 5903896`

**Comment by even1024** [comment]
Fixed in PR: fix336
