### ISSUE TITLE
WASM: 'calculate' function does not work on simple part of structure that contains query features

### ISSUE THREAD

**Issue by AndreiMazol** [epam/Indigo#344]
**Step  to reproduce:**
1. Call 'calculate' method with the following arguments:
struct: 
"
  Ketcher  3 42118352D 1   1.00000     0.00000     0

  7  6  0     0  0            999 V2000
    3.8000   -4.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6660   -5.3750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.5321   -4.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.3981   -5.3750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.2641   -4.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.1301   -5.3750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.9962   -4.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0     0  0
  2  3  8  0     0  0
  3  4  1  0     0  0
  4  5  1  0     0  0
  5  6  1  0     0  0
  6  7  1  0     0  0
M  END
"

selected atoms: 
[5, 6]

**Expected result:**
 "gross" equals "C2 H5"

**Actual result:**
Error 'Cannot calculate properties for structures with query features' is thrown

**Comment by even1024** [comment]
Fixed in calculate_selection_rework PR
