### ISSUE TITLE
WASM: 'calculate' function does not work on part of reaction

### ISSUE THREAD

**Issue by AndreiMazol** [epam/Indigo#345]
**Step  to reproduce:**
1. Call 'calculate' method with the following arguments:
struct: 
"$RXN

  1  1  0
$MOL

  Ketcher  3 42118422D 1   1.00000     0.00000     0

  4  3  0     0  0            999 V2000
    3.0250   -5.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8910   -6.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.7571   -5.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.6231   -6.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0     0  0
  2  3  1  0     0  0
  3  4  1  0     0  0
M  END
$MOL

  Ketcher  3 42118422D 1   1.00000     0.00000     0

  5  4  0     0  0            999 V2000
   14.9750   -6.0500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.8410   -6.5500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.7071   -6.0500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.5731   -6.5500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.4391   -6.0500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0     0  0
  2  3  1  0     0  0
  3  4  1  0     0  0
  4  5  1  0     0  0
M  END
"

selected atoms: 
[0, 1, 2, 3]

**Expected result:**
 "gross" equals "C4 H10"

**Actual result:**
Error 'core: <reaction> is not a base molecule' is thrown

**Comment by even1024** [comment]
Fixed in calculate_selection_rework PR
