### ISSUE TITLE
Add support of SDF files more 4 GB length

### ISSUE THREAD

**Issue by IuriiPuzanov** [epam/Indigo#35]
Current version doesn't support SDF files with length more 4 GB.

**Comment by karnaukhovv** [comment]
I have a test which clearly shows problems with the Scanner class:

Max signed int: 2147483647
Read file of -1493696512 bytes length
Records total: 6291456
Reading the last record...
Done

Test data file is approx. 7 Gb large:
$ du -hs test.sdf
6,7G	test.sdf

SDFLoader reports correct number of records (6291456), however, Scanner reports some obviously broken file size (-1493696512).
I wasn't able to detect issues with SDFLoader itself yet.

**Comment by karnaukhovv** [comment]
With a proposed fix, file size calculation is now correct:

Max signed int: 2147483647
Read file of 7096238080 bytes length
Records total: 6291456
Reading the last record...
Done

I'm further testing the fix.

**Comment by karnaukhovv** [comment]
Changes are in the master branch. I'm closing the issue.
