### ISSUE TITLE
generateImageAsync: generic S-Groups are lost

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/Indigo#355]
**Steps to reproduce**:

1. Draw a structure
2. Add an S-Group with type - Generic
3. With this structure's mol call ketcher.generateImageAsync
4. Verify the result

**Expected result**: the generic S-Group is displayed in the image
**Actual result**: the generic S-Group is not displayed (the brackets are absent)

**Comment by even1024** [comment]
Fixed in 1.8.
