### ISSUE TITLE
generateImageAsync: R-Group fragment is lost

### ISSUE THREAD

**Issue by AleksandraTitova** [epam/Indigo#356]
**Steps to reproduce**:

1. Draw a structure
2. Click the structure with R-Group fragment tool, select a label, Ok
3. With this structure's mol call ketcher.generateImageAsync
4. Verify the result

**Expected result**: the R-Group is displayed in the image
**Actual result**: the image is empty

**Comment by even1024** [comment]
Fixed in 1.7.2
