### ISSUE TITLE
'Calculated values' - Data display is different in remote and standalone modes

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/Indigo#370]
Affected versions: Standalone

Steps to reproduce:

1. Launch Ketcher (Remote).
2. Execute 'v2/indigo/calculate' with the following parameters:
struct
[struct.zip](https://github.com/epam/Indigo/files/6189282/struct.zip)
selected, array 5
3. Select 'CH4' with 'Lasso selection'
4. Click 'Calculated Values'
5. Repeat steps 1-4 in Standalone mode

Expected result: Data is displayed the same way in two modes.

Actual result: Remote - All the calculated values ('Chemical Formula', 'Molecular Weight', 'Exact Mass', 'Elemental Analysis') are displayed without brackets.
Standalone - 'Molecular Weight', 'Exact Mass', 'Elemental Analysis' in 'Calculated values' are displayed with brackets.

**Comment by AndreiMazol** [comment]
Issue is still reproduced.
Remote:
![image](https://user-images.githubusercontent.com/72735611/112499030-229a1200-8d98-11eb-9e89-699b73311ba6.png)

Standalone:
![image](https://user-images.githubusercontent.com/72735611/112499075-2cbc1080-8d98-11eb-8a8c-268325909520.png)

**Comment by even1024** [comment]
> Issue is still reproduced.
> Remote:
> ![image](https://user-images.githubusercontent.com/72735611/112499030-229a1200-8d98-11eb-9e89-699b73311ba6.png)
> 
> Standalone:
> ![image](https://user-images.githubusercontent.com/72735611/112499075-2cbc1080-8d98-11eb-8a8c-268325909520.png)

With latest commit new output formatting implemented which differs from remote version, but approved by @AlexanderSavelyev
