### ISSUE TITLE
Substructure query count matches does not return a result

### ISSUE THREAD

**Issue by achher** [epam/Indigo#382]
For some substructure queries count matches does not return a result:

 aMolecule:= indigoLoadMoleculeFromFile('Problem_SSS.mol');
 indigoAromatize(aMolecule);
 aQuery:= indigoLoadQueryMoleculeFromFile('SSS.mol');
 indigoAromatize(aQuery);
 aMatcher:= indigoSubstructureMatcher(aMolecule, '');
 nCount:= indigoCountMatches(aMatcher, aQuery)

Call to indigoCountMatches does not return.
When setting indigoSetOptionInt('max-embeddings', 1) call returns with raising exception, that max embeddings has been reached. When setting 'max-embeddings' to a higher value than 1, then indigoCountMatches does not return.

Also iteratematches does not return a result in that situation.

Problem_SSS.mol:

![grafik](https://user-images.githubusercontent.com/70947872/112722813-dec81980-8f0b-11eb-9966-b7359c291475.png)

Query (SSS.mol):

![grafik](https://user-images.githubusercontent.com/70947872/112722841-fe5f4200-8f0b-11eb-973f-5019b227e7de.png)

Both molfiles are attached.
[Problem_SSS.zip](https://github.com/epam/Indigo/files/6215759/Problem_SSS.zip)
[SSS.zip](https://github.com/epam/Indigo/files/6215760/SSS.zip)

**Comment by khyurri** [comment]
Compounds in this example contains a too much edges, so it will take a lot of time for substructure calculation. Currently, substructure calculation is implemented using [Ullman’s Subgraph Isomorphism Algorithm](https://adriann.github.io/Ullman%20subgraph%20isomorphism.html). 

In the Bingo implementation and C++ implementation there is a TimeoutHandler for catching this situations and return no match by timeout.

**Comment by achher** [comment]
OK, indigo.setOption("timeout", "2000") is working. That helps a lot. Many thanks for looking into this issue.
Can you give me more information, which operations are cancelled by the timeout?

**Comment by mkviatkovskii** [comment]
Dear @achher,
Timeout handler set for basically all operations that may potentially consume a lot of time (substructure matching, automorphism search, molecule layout, atom-to-atom mapping, reaction product enumeration).

As for this particular case, I would also suggest using `indigoCountMatchesWithLimit`, like:
```c
indigoCountMatchesWithLimit(aMatcher, aQuery, 1)
```
If you just need to know if there exists a substructure matching for given query and target. Indigo quickly finds a valid matching, but after that starts suffering from a combinatorial explosion, trying to check all possible embeddings.

**Comment by achher** [comment]
Dear both,

indigoCountMatchesWithLimit(aMatcher, aQuery, 1) is working as expected. Together with the timeout option, I now have the right commands to avoid that problem. Many thaks for giving this very useful tips. Thank you so much.
