### ISSUE TITLE
switch all other bingo-elastic-reaction tests to `getTargetReaction(<filename>)` 

### ISSUE THREAD

**Issue by SunFellow** [epam/Indigo#401]
How about to switch all other tests to `getTargetReaction(<corr. file>)` ? 
None guarantees the order of files in directory is kept from run to run.

_Originally posted by @SunFellow in https://github.com/epam/Indigo/pull/394#discussion_r611759065_

**Comment by mkviatkovskii** [comment]
@MysterionRise should we do anything else here, or it could be closed?

**Comment by MysterionRise** [comment]
@mkviatkovskii I don't think so. Python API doesn't have similar problems
