### ISSUE TITLE
Error message when trying to calculate values of the structures with the hydrogen and dative bonds

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/Indigo#413]
Steps to reproduce:

1. Execute /v2/indigo/calculate with the following parameters:
struct
[hydrogen_test.zip](https://github.com/epam/Indigo/files/6540366/hydrogen_test.zip)

Expected result: The correct response with "gross", "mass-composition", "molecular-weight", "monoisotopic-mass", "most-abundant-mass" is received.

Actual result: "error": "IndigoException: molfile loader: unknown bond type: 10" message appears in response and in alert.

The issue is reproduced with the structures with the dative bonds. "error": "IndigoException: molfile loader: unknown bond type: 9" response is received.

**Comment by vitalgerko** [comment]
Bug still reproduces in Standalone mode (Ketcher).

**Comment by AllaZhbanova** [comment]
The issue is fixed
Tested ketcher v. 2.3.3-272
