### ISSUE TITLE
Generation of images works incorrectly

### ISSUE THREAD

**Issue by AndreiMazol** [epam/Indigo#415]
**Steps to reproduce:**
1. Call /render endpoint with the following options (use any struct):
`"options":{"smart-layout":true,"ignore-stereochemistry-errors":true,"mass-skip-error-on-pseudoatoms":false,"gross-formula-add-rsites":true,"render-output-format":"png"}}`
2. Call /render endpoint with the following options (use any struct):
`"options":{"smart-layout":true,"ignore-stereochemistry-errors":true,"mass-skip-error-on-pseudoatoms":false,"gross-formula-add-rsites":true,"render-output-format":"svg"}}`

**Expected results:**
1. Step 1 should return png encoded as base64
2. Step 2 should return svg encoded as base64

**Actual results:**
1. Step 1 returns svg
2. Step 2 return raw svg (without encoding it)

_**NOTES**_
Expected results are based on results of the same method of Standalone mode. I guess API should be aligned.

**Comment by vitalgerko** [comment]
From the side of the API, now everything works correctly, a picture in PNG format is downloaded through Postman. Image download in PNG format does not occur through Ketcher

**Comment by AllaZhbanova** [comment]
The issue is still reproducible
In remote mode create any structure, Click Save As, select Image tab, Select PNG and click "Save As Image"
*Result* Nothing happened
*Expected result* Window is closed, Image is saved in PNG


![2021-12-21_15h34_48](https://user-images.githubusercontent.com/93334478/146931376-805844fa-eaac-4c5b-b5d4-0f98fdd356fc.png)

**Comment by even1024** [comment]
I clearly see that ketcher requests 'image/svg+xml' when png is chosen. 'image/png;base64' must be requested instead.

**Comment by even1024** [comment]
switched to options:render-output-format

**Comment by AllaZhbanova** [comment]
Fixed, tested 2.4
