### ISSUE TITLE
SVG Viewbox sizes are different in remote and standalone modes

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/Indigo#421]
Steps to reproduce:

1. Execute /v2/indigo/render with the following parameters:
struct 
[svg_test.zip](https://github.com/epam/Indigo/files/6599329/svg_test.zip)
options: { "smart-layout": true, "ignore-stereochemistry-errors": true, "mass-skip-error-on-pseudoatoms": false, "gross-formula-add-rsites": true, "render-output-format": "svg"}

_Expected result:_ SVG viewBox sizes are similar in both modes.
_Actual result:_ 
Remote - viewBox="0 0 200 200"
Standalone - viewBox="0 0 1019 1083"

**Comment by Svetlana-Asinovskaia** [comment]
Actual result in Ketcher:
Remote:
![image](https://user-images.githubusercontent.com/80695128/120822499-2350e080-c55f-11eb-85db-2eaa84a984a5.png)

Standalone:
![image](https://user-images.githubusercontent.com/80695128/120822564-35328380-c55f-11eb-9ce4-d7b2c01cfee3.png)

**Comment by even1024** [comment]
For standalone version the following options should be added: render-image-width, render-image-height.
