### ISSUE TITLE
api: integration tests: layout: inaccurate coordinates in multiple tests

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#432]
Reproduces on branch `indigo-1.5`. Tests affected:
* `layout/clean2d`
* `layout/macrocycles`
* `layout/reaction_layout_and_clean2d`
* `layout/selective_layout`
* `layout/template_layout`
 
Steps to reproduce (using `layout/clean2d` as example):
1. Run `indigo-integration-tests` with `-p layout/clean2d` key.
2. See the `api/tests/integration/out/layout/clean2d.py.diff` file. It should be full of following errors:
```
-   Item #1: Result: Success
+   Item #1: Result: Error: atom #0 (C) contains delta 0.11376903831348348 > 0.01
+    atom #1 (C) contains delta 0.10912619115409372 > 0.01
+    atom #2 (C) contains delta 0.106856986352142 > 0.01
+    atom #3 (C) contains delta 0.11159233051296942 > 0.01
+    atom #4 (C) contains delta 0.1078245664270285 > 0.01
+    atom #5 (C) contains delta 0.10316153462721772 > 0.01
+    atom #6 (C) contains delta 0.09949944182284626 > 0.01
```
It means like after clean2d procedure coordinates of some atoms are too far from expected. It is required to manually check the output structure, compare it with expected one and find out what causes the issue.

Python code of the test could be found at `api/tests/integration/tests/layout/clean2d.py`.

**Comment by even1024** [comment]
Tests fixed in Indigo 1.5.0.
