### ISSUE TITLE
Removing empty lines was blocked in the previous pull request, so this needs to be done within this task

### ISSUE THREAD

**Issue by yuriiq** [epam/Indigo#445]
For "replace-in-place" pull requests and touching huge number of files, like this, please **avoid removing empty lines**. Replace only what is to be replaced.
Diffs are mistaken when some lines are removed and this makes harder resolving future conflicts.

_Originally posted by @SunFellow in https://github.com/epam/Indigo/pull/423#discussion_r650203302_

**Comment by SunFellow** [comment]
We've left the removed lines in the original pull request. It was not worth to track separately.
This issue is not actual any longer.
