### ISSUE TITLE
.NET Indigo nuget error

### ISSUE THREAD

**Issue by RTommasi** [epam/Indigo#450]
Hi,
Thanks for your efforts to make these tools available.  I am working on a .NET application (VB) that will need to perform some SDF file manipulations and think that Indigo is the way to go.  I am using VS2019 under windows 10 and have installed the 1.4.3 nuget extension into my application.

When i try to implement an instance of the indigo object, i get the following error:
"Unable to load DLL 'indigo': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

I noticed that in the bin folder, while the Indigo.Net.dll is in the proper (debug) folder, it appears the app is looking for Indigo.dll. (Note error above).

I have separately downloaded the common tools which includes this and placed the Indigo.dll in the same debug folder.  In this instance, i get a different error when i try to create an instance of the Indigo object:

Managed Debugging Assistant 'PInvokeStackImbalance' 
  Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Indigo.Net!com.epam.indigo.IndigoLib::indigoSetSessionId' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

Not quite sure what i am missing here to get the nuget extension to work properly.

Thanks for any suggestions!
Ruben

**Comment by even1024** [comment]
Hello. I tried to reproduce the issue and took the following steps:
1) Installed fresh VS2019+.NET Professional Edition under Win10.
2) Created .NET/VB console application
3) Under Package Manager console:

PM> Install-Package Indigo.Net -Version 1.4.3

Both C# and VB apps worked flawlessly:

C#:

using System;
using com.epam.indigo;

namespace indigo_test
{
    class Program
    {
        static void Main(string[] args)
        {
            var indigo = new Indigo();
            var mol = indigo.loadMolecule("O=C(C)Oc1ccccc1C(=O)O");
            Console.WriteLine(mol.molfile());
        }
    }
}

VB:

Imports System
Imports com.epam.indigo

Module Program
    Sub Main(args As String())
        Dim indigo As New Indigo
        Dim mol As IndigoObject = indigo.loadMolecule("O=C(C)Oc1ccccc1C(=O)O")
        Console.WriteLine(mol.molfile)
    End Sub
End Module

**Comment by RTommasi** [comment]
Hi Even1024,

I can confirm that the example you provided above works for a console app.
When I try to take the same approach to use this in a windows form app (.NET framework 4.72), I get the same error that the dll cannot be loaded...
I see the same error when I build a C# app and try to run the code above with a button click.  the error comes up at: 
   _var indigo = new Indigo();_

here's an image of the error msg.

![image](https://user-images.githubusercontent.com/87488008/128076992-33af98a0-8609-4685-b7be-f76d408c6c7f.png)

I had previously tried to use this to build a class and had the same issues there.  does this only work with console app?

Thanks for your help with this!

**Comment by f1nzer** [comment]
@RTommasi hi!
Could you please try the following steps?
1) If you are using AnyCPU platform, then try to switch to the x64 platform (you might need to create this under Configuration Manager)
2) Copy all files manually from `packages\Indigo.Net.1.4.3\runtimes\win-x64` to `bin/x64/Debug`
3) Run the app

**Comment by RTommasi** [comment]
@f1nzer ,
Many thanks!  That worked!  only diff was that despite changing the platform to x64, there is no bin/x64/Debug, just bin/Debug.  placing a copy of the files there worked!
thanks for the help!
