### ISSUE TITLE
Error message while trying to open InChi AuxInfo file in Standalone mode 

### ISSUE THREAD

**Issue by nseufulina** [epam/Indigo#454]
**Steps to Reproduce**

1. Execute in standalone mode /v2/indigo/layout with the following parameters:
    struct: 
[struct.zip](https://github.com/epam/Indigo/files/6991521/struct.zip)
options: {smart-layout: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false,…}
output_format: "chemical/x-mdl-molfile"

**Expected behavior**
The same structure as in in struct.zip

**Actual behavior**
Error: Convert error!
Given string could not be loaded as (query or plaint) molecule or reaction, 
see the error messages: 'scanner: appendLine(): end of stream',
'scanner: appendLine(): end of stream', 
'RXN loader: bad header InChI=1S/C4H10/c1-3-4-2/h3-4H2,1-2H3',
'RXN loader: bad header InChI=1S/C4H10/c1-3-4-2/h3-4H2,1-2H3'

**Comment by AllaZhbanova** [comment]
Fixed, tested Ketcher v.2.4
