### ISSUE TITLE
Different results from "v2/indigo/calculate" and "calculate" method in wasm

### ISSUE THREAD

**Issue by MagomedGasanov** [epam/Indigo#465]
**Steps to reproduce:**

1. Execute /v2/indigo/calculate with the following parameters:
properties: ["molecular-weight", "most-abundant-mass", "monoisotopic-mass", "gross", "mass-composition"]
selected: [0, 1, 2, 3, 4, 5, 6]
struct: [reaction_2.zip](https://github.com/epam/Indigo/files/6885754/reaction_2.zip)

2. Execute the same using the "Calculate" method in wasm

Expected behavior: result should be the same

Actual behavior: result is different

Screenshots:

/v2/indigo/calculate:
![image](https://user-images.githubusercontent.com/57804693/127164965-36b10608-67b3-4ef3-94ca-f7ab6d0af09c.png)

wasm:
![image](https://user-images.githubusercontent.com/57804693/127163113-8468ec4e-9e9b-4197-ae8d-26d8aa98c210.png)

**Comment by AllaZhbanova** [comment]
related issue https://github.com/epam/Indigo/issues/564

**Comment by AllaZhbanova** [comment]
fixed, tested 2.4
