### ISSUE TITLE
Any plans to support PostgreSQL 13?

### ISSUE THREAD

**Issue by SPKorhonen** [epam/Indigo#466]
I would like to use Bingo in conjunction with exiting Django application but for other reasons I would like to consolidate the PostgreSQL to version 13. Are there any plans to add support for the new version?

From a quick look there are only few changes in the API which are incompatible. I would be willing to help on this (pull request etc.) if that helps.

**Comment by even1024** [comment]
You are welcome.

**Comment by mkviatkovskii** [comment]
PostgreSQ
