### ISSUE TITLE
The reaction components saved in CML are partly lost during opening in Standalone mode

### ISSUE THREAD

**Issue by aleksandrgordeev1** [epam/Indigo#473]
**Steps to Reproduce**
1. Execute convert method in standalone mode with the following CML file [test-reaction.zip](https://github.com/epam/Indigo/files/6991893/test-reaction.zip)
2. Execute /convert endpoint in remote mode with the following CML file [test-reaction.zip](https://github.com/epam/Indigo/files/6991893/test-reaction.zip), same as in step1

**Expected behavior**
Both  step 1 and step 2 responses has rxn file

**Actual behavior**
1 returns mol file (part of the reaction is lost)
2 returns rxn file

**Comment by AllaZhbanova** [comment]
Fixed, tested Ketcher 2.4
