### ISSUE TITLE
"No matching distribution found" When Installing epam.indigo in Docker Image

### ISSUE THREAD

**Issue by zachary-chiodini** [epam/Indigo#496]
Hi,

When running a "pip install -r requirements.txt" command in a Dockerfile during a build, I consistently get the error "No matching distribution found for epam.indigo." I have tried the latest version of epam.indigo, earlier versions and no version specified. All give this error during the package installation step of the build.

I am building the image using a GitHub actions workflow onto the GitHub Package Registry. [Here is a link to the repository](https://github.com/zachary-chiodini/RESTful-APIs).

What dependencies am I missing? The documentation simply says to run "pip install epam.indigo" to install the lastest version, but that is not working inside of this Docker build.

**Comment by khyurri** [comment]
Hi,

As I see your requirements.txt contains `epam.indigo==1.4.0`. This version is absent in PyPI, so could you please change this line to `epam.indigo==1.5.0` and try again? Should work. 

Regards, 
Ruslan

**Comment by zachary-chiodini** [comment]
> Hi,
> 
> As I see your requirements.txt contains `epam.indigo==1.4.0`. This version is absent in PyPI, so could you please change this line to `epam.indigo==1.5.0` and try again? Should work.
> 
> Regards, Ruslan

I receive the same error "Could not find a version that satisfies the requirement epam.indigo==1.5.0 "

**Comment by khyurri** [comment]
I've just checked your workflow, indigo downloaded successfully: 
https://github.com/zachary-chiodini/RESTful-APIs/runs/3743423260?check_suite_focus=true#step:8:1393

Error with something else in Dockerfile: https://github.com/zachary-chiodini/RESTful-APIs/runs/3743423260?check_suite_focus=true#step:8:2337

Regards,
Ruslan

**Comment by zachary-chiodini** [comment]
> I've just checked your workflow, indigo downloaded successfully: https://github.com/zachary-chiodini/RESTful-APIs/runs/3743423260?check_suite_focus=true#step:8:1393
> 
> Error with something else in Dockerfile: https://github.com/zachary-chiodini/RESTful-APIs/runs/3743423260?check_suite_focus=true#step:8:2337
> 
> Regards, Ruslan

The specific error I am referring to is found here:
https://github.com/zachary-chiodini/RESTful-APIs/runs/3743423260?check_suite_focus=true#step:8:2319

If I remove epam.indigo from the requirements.txt file, the workflow completes successfully.

**Comment by zachary-chiodini** [comment]
The problem is most likely with epam.indigo, because it gives me the error ["Could not find a version that satisfies the requirement epam.indigo==1.5.0,"](https://github.com/zachary-chiodini/RESTful-APIs/runs/3743423260?check_suite_focus=true#step:8:2319) and completes successfully when I remove epam.indigo from the requirements.

**Comment by AlexanderSavelyev** [comment]
aarch64  was added to the recent indigo versions. Closing the ticket
