### ISSUE TITLE
Fix aromatize/dearomatize functions

### ISSUE THREAD

**Issue by dkuzminov** [epam/Indigo#5]
Currently there are problems with aromatization/dearomatization of molecules with unusual number of hydrogens.

Lets take a molecule: N1C(S)=C2C([NH]=CN2)=NC=1N. Please see that the atom 5 (zero-based numbering) has one single, one double bond and one additional hydrogen. Thus the connectivity of nitrogen is 4.

The first question is if this molecule is valid (it was taken from the file with tautomers, but the question is open).
Next, there will be a problem if we perform sequential dearomatize(aromatize(molecule)): we will not get the initial molecule, but the one with several unresolved aromatic bonds. So, one of these procedures doesn't work well (if we assume that the molecule is valid).
If we compare the results of aromatization of this molecule given by Indigo and Marvin, we can see the difference.
Indigo: [n]1c(N)[n]c2[nH]c[nH]c2c1S (all cycles aromatized)
Marvin: Nc1nc(S)c2NC=[NH]c2n1 (only one cycle is aromatized)

**Comment by AlexanderSavelyev** [comment]
Marvin 15.3.2.0 also aromatizes two cycles
