### ISSUE TITLE
Aromatize / Dearomatize action with Fuctional Groups work incorrectly

### ISSUE THREAD

**Issue by vitalgerko** [epam/Indigo#506]
**Steps to reproduce:**

**Aromatize:**
Execute v2/indigo/aromatize
struct
[struct.zip](https://github.com/epam/Indigo/files/7415916/struct.zip)

{
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
}

**Dearomatize:**
Execute v2/indigo/dearomatize
struct
[struct.zip](https://github.com/epam/Indigo/files/7415917/struct.zip)

{
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
}

**Expected result:**
The structure isn't changed. 
Indigo should not change objects that it does not know.

**Actual result:**
Indigo changes objects.

A possible suggestion for implementation: add the flag "don't change this structure" to the format and use it with a TRUE for FGs when aromatize/dearomatize is applied for ones in Ketcher.

**Comment by AlexanderSavelyev** [comment]
add flag 'aromatize-skip-super-atoms'

**Comment by even1024** [comment]
aromatize-skip-super-atoms added

**Comment by AllaZhbanova** [comment]
The issue is still reproducible, after  aromatize applying FG is changed. Tested on
 Ketcher version2.3.3
build at 2021-12-14T07:10:36
Indigo Toolkit version1.6.0.6-gb2d73faeb-x86_64-linux-gnu-10.2.1

**Comment by even1024** [comment]
Please use aromatize-skip-super-atoms=true on ketcher's side.

**Comment by AllaZhbanova** [comment]
related https://github.com/epam/ketcher/issues/1108

**Comment by even1024** [comment]
aromatize-skip-super-atoms renamed to -> aromatize-skip-superatoms
