### ISSUE TITLE
Basic ElasticSearch example not working

### ISSUE THREAD

**Issue by ThomasLabstep** [epam/Indigo#510]
Hello,

I was hoping you could help figure out running a very basic example of the indigo elastic library that is not working. 

TEST
```
class TestClient:
    def setup_method(self):
        loadFixtures()

    def test_push_search(self):
        print("push")
        data = 'C1CCCCC1'
        extraParams = {}
        push(data, extraParams)

        data = 'C1CCCCC1'
        extraParams = {}
        push(data, extraParams)

        data = 'C1CCNCC1'
        extraParams = {}
        push(data, extraParams)

        data = 'N'
        extraParams = {}
        push(data, extraParams)

        print("search")
        result = search('N')
        print(len(list(result)))
        print(list(result))
```

SRC
```
def push(data):
  indigo = Indigo()
  compound = indigo.loadMolecule(data)
  indigo_record = IndigoRecordMolecule(indigo_object=compound)

  elasticRepository = elastic_repository_molecule()
  elasticRepository.index_record(record=indigo_record)

def search(data):
  indigo = Indigo()
  compound = indigo.loadMolecule(data)
  indigo_record = IndigoRecordMolecule(indigo_object=compound)

  elasticRepository = elastic_repository_molecule()
  return elasticRepository.filter(exact=indigo_record)
```

Query
> {'size': 10, 'query': {'script_score': {'query': {'bool': {'must': [{'term': {'sub_fingerprint': {'value': 893}}}, {'term': {'sub_fingerprint': {'value': 1457}}}, {'term': {'sub_fingerprint': {'value': 2864}}}, {'term': {'sub_fingerprint': {'value': 3297}}}, {'term': {'sub_fingerprint': {'value': 3636}}}, {'term': {'sub_fingerprint': {'value': 3649}}}]}}, 'script': {'source': '_score / doc['sub_fingerprint_len'].value'}}}, 'min_score': 1}

Output
> {'took': 1, 'timed_out': False, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}, 'hits': {'total': {'value': 0, 'relation': 'eq'}, 'max_score': None, 'hits': []}}

If I run the query manually on my index, I see 2 items.

So I suspect the script is causing the issue.

I'm using ES 7.15.1. Your readme suggests 7.9.x

I'm trying to downgrade but brew recipe is not available to do so so I need to improvise...

Any other idea what might go wrong?

Doc: https://github.com/epam/Indigo/blob/master/bingo/bingo-elastic/python/README.md

Thank you.

**Comment by MysterionRise** [comment]
Thanks for bringing that up Thomas. We need to update readme obviously. I
would also test this use case by the end of the week

**Comment by ThomasLabstep** [comment]
Could confirm it's still broken with ES 7.9.3.

**Comment by MysterionRise** [comment]
@ThomasLabstep sorry for delay in checking this. Basically, everything is working just fine. The problem here is, that Elasticsearch doesn't have strict notion of commits. So, what you need to do - is either have to wait or trigger commit and refresh somehow. FYI - https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-flush.html#flush-api-desc 

Basically, in your scenario - time.sleep(1) will do the trick to make it work for any version of Elastic
I've also updated readme to show that generally we work with newer versions as well. Let me know if you have more questions.

**Comment by ThomasLabstep** [comment]
Can confirm it's working well now.

Thank you so much for your help!

Cheers.
