### ISSUE TITLE
Does the API support batch queries?

### ISSUE THREAD

**Issue by xrfinbupt** [epam/Indigo#519]
Such as the following interface： @indigo_api.route('/render', methods=['POST'])
thx

**Comment by MysterionRise** [comment]
@khyurri could we add support for this one as well?

**Comment by khyurri** [comment]
Hi, @xrfinbupt 

Thank you for your request. Currently `indigo-service` is not supporting batching. We're trying to keep JSONApi as simple as possible. HTTP overhead should not be an issue in this API, so you can easily make requests concurrently. 

Batching may be added in future as plugin or extension for all endpoints, we're thinking about it
