### ISSUE TITLE
generateImageAsBase64 method doesn't work correctly in standalone mode

### ISSUE THREAD

**Issue by ViktoriiaFedotkina** [epam/Indigo#523]
Steps to reproduce:

1. call /v2/indigo/render in standalone mode with (options, struct) :
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
render-output-format: "svg" OR "png"
smart-layout: true

Expected result:
Correct PNG or SVG image encoded in base64 should be returned

Actual result:
An incorrect image is returned

[struct.zip](https://github.com/epam/Indigo/files/7528542/struct.zip)

**Comment by AllaZhbanova** [comment]
Fixed, tested Standalone ketcher v,2.4
