### ISSUE TITLE
Convert error! IndigoException: core: <query molecule> is not a molecule on saving structure in InChi 

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/Indigo#526]
**Steps to reproduce:**

1. call indigo/convert
options: {smart-layout: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false,…}
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
output_format: "chemical/x-inchi-aux"
struct:

[struct.zip](https://github.com/epam/Indigo/files/7563072/struct.zip)
**Expected Result:**
User is able to save structure in InChi format 
**Actual Result:**
{"error":"IndigoException: core: <query molecule> is not a molecule"}

**Comment by even1024** [comment]
Not reproduced
