### ISSUE TITLE
Error when user tries to use Automap

### ISSUE THREAD

**Issue by r1z3rISGOD** [epam/Indigo#529]
**Steps to reproduce:**

call indigo/automap
mode: "discard"
options: {
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
}
output_format: "chemical/x-indigo-ket"
struct: [struct.txt](https://github.com/epam/Indigo/files/7562122/struct.txt)

**Expected Result:**
Structs in reaction automaped

**Actual Result:**
Error in fetch by CORS policy and 502 code without response

**Comment by r1z3rISGOD** [comment]
Now the behavior has changed. If we reproduce the bug, we get the following result:
`IndigoException: molecule auto loader: Unsupported node for molecule`
To check the functionality, you can also use the structure: 
[reaction_4.txt](https://github.com/epam/Indigo/files/7625113/reaction_4.txt)

**Comment by AllaZhbanova** [comment]
fixed, tested 2.4
