### ISSUE TITLE
Error when user tries to use Check method for structure with text

### ISSUE THREAD

**Issue by ElenaOdnoshivkina** [epam/Indigo#530]
**Steps to reproduce:**

1) Execute /v2/indigo/check

"options": {
  "smart-layout": true,
  "ignore-stereochemistry-errors": true,
  "mass-skip-error-on-pseudoatoms": false,
  "gross-formula-add-rsites": true,
  "gross-formula-add-isotopes": true
    }, 
struct: [struct.txt](https://github.com/epam/Indigo/files/7568831/struct.txt),
"types": [
  "radicals",
  "pseudoatoms",
  "stereo",
  "query",
  "overlapping_atoms",
  "overlapping_bonds",
  "rgroups",
  "chiral",
  "3d"
]
      
**Expected Result:**
Response is object with errors or empty object

**Actual Result:**
Respons is HTML document
![image](https://user-images.githubusercontent.com/89905163/142591612-896701eb-71b5-454e-baa6-5fb9fd5084e7.png)

**Comment by AllaZhbanova** [comment]
Fixed, tested on 
Ketcher
version2.3.3
build at 2021-12-14T07:10:36
Indigo Toolkit
version1.6.0.6-gb2d73faeb-x86_64-linux-gnu-10.2.1
