### ISSUE TITLE
Error when user tries to use Layout

### ISSUE THREAD

**Issue by ElenaOdnoshivkina** [epam/Indigo#533]
**Steps to reproduce:**

1. Execute /v2/indigo/layout

options: {
        "smart-layout": true,
        "ignore-stereochemistry-errors": true, 
        "mass-skip-error-on-pseudoatoms": false,
        "gross-formula-add-isotopes": true,
        "gross-formula-add-rsites": true
},
output_format: "chemical/x-indigo-ket",
struct: [struct.txt](https://github.com/epam/Indigo/files/7581843/struct.txt)

**Expected Result:**
Response is structure that changed its position

**Actual Result:**
Respons is object contains error: "IndigoException: element: can not calculate valence on C, charge 0, connectivity 6"

**Comment by AllaZhbanova** [comment]
The structure is broken after /v2/indigo/layout execution for the structure

before
![2021-12-14_18h31_51](https://user-images.githubusercontent.com/93334478/146029050-d91169d3-9daa-4a33-b7c0-6ba88b288874.png)

after 
![2021-12-14_18h31_21](https://user-images.githubusercontent.com/93334478/146029067-2935aa30-92c5-4bfb-8894-3b4d793f2f1e.png)

**Comment by even1024** [comment]
The structure doesn't seem to be broken. This is how layout algorithm works.

**Comment by AllaZhbanova** [comment]
Retested on Ketcher v.2.3 , the behavior is the same
