### ISSUE TITLE
Query atom properties disappear from the structure after converting in Extended SMILES-format

### ISSUE THREAD

**Issue by ElenaOdnoshivkina** [epam/Indigo#537]
**Steps to reproduce:**

1. Execute /v2/indigo/convert
  output_format: "chemical/x-chemaxon-cxsmiles",
  struct: [struct.txt](https://github.com/epam/Indigo/files/7588620/struct.txt)
 
**Expected Result:**
Response is structure that contains information about query atom properties in format:
```
rb:atomIndex1:value,atomIndex2:value
s:atomIndex1:value,atomIndex2:value
u:atomIndex1,atomIndex2,atomIndex3
```
sourse: https://docs.chemaxon.com/display/docs/chemaxon-extended-smiles-and-smarts-cxsmiles-and-cxsmarts.md

**Actual Result:**
Response is structure that doesn't contain information about query atom properties

**Comment by AllaZhbanova** [comment]
Reproducible
Convert error is shown on  Extended SMILES file opening
[ketcher.zip](https://github.com/epam/Indigo/files/7755244/ketcher.zip)
![2021-12-21_15h22_00](https://user-images.githubusercontent.com/93334478/146929666-a0f2faf3-d98f-4075-acae-27ba285db811.png)

**Comment by even1024** [comment]
Looks like ketcher's issue

**Comment by AllaZhbanova** [comment]
Reproducible v. 2.3

**Comment by even1024** [comment]
Extended SMILES doesn't support ring bounds count, unsaturated and substitution count.
rb, u and s are query features so they belong to extended SMARTS.
