### ISSUE TITLE
Error when user tries to use Check

### ISSUE THREAD

**Issue by ElenaOdnoshivkina** [epam/Indigo#538]
**Steps to reproduce:**

1. Execute /v2/indigo/check
options: {
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
struct: [srtruct.txt](https://github.com/epam/Indigo/files/7594607/srtruct.txt),
types: [
  "radicals",
  "pseudoatoms",
  "stereo",
  "query",
  "overlapping_atoms",
  "overlapping_bonds",
  "rgroups",
  "chiral",
  "3d"
]

**Expected Result:**
Respons is empty object without errors

**Actual Result:**
Respons is object contains error: "IndigoException: element: can not calculate valence on C, charge 0, connectivity 6"

**Comment by AllaZhbanova** [comment]
Fixed, tested v.2.4
