### ISSUE TITLE
bingo.CheckMolecule : return null PostgreSQL

### ISSUE THREAD

**Issue by sitanshubhunia** [epam/Indigo#541]
In my project am facing problem in bingo.CheckMolecule method. 

Bingo Version
"1.9.1.r0-g353401f win64"

Query:
select bingo.CheckMolecule(bingo.FileToText('D:/checker.smiles'));

query file contains
ClC1=CC=CC=C1OC1=CC(CC2CCC3=C(CC4=NN=NN4)C4=CC=CC=[C]4=[N+]=C23)=CC=C1

[checker.smiles.txt](https://github.com/epam/Indigo/files/7600996/checker.smiles.txt)

Please remove .txt for run

I have check in this structure have issue

![Error](https://user-images.githubusercontent.com/840684/143398429-ba3f2537-6715-48db-9c12-b6c48de40e54.png)

But wen i run it on postgresql return null
![checkmolecule](https://user-images.githubusercontent.com/840684/143398498-63b617e9-f5e2-4ac0-b112-c763823747a6.png)

**Comment by AlexanderSavelyev** [comment]
bingo ignores valence errors while check molecules, will fix it in a next version

**Comment by AlexanderSavelyev** [comment]
as for strain error, bingo does not have that type of verification.

**Comment by sitanshubhunia** [comment]
@AlexanderSavelyev any idea of next version release date. It's just for my information only.

**Comment by AlexanderSavelyev** [comment]
@sitanshubhunia as open-source product Bingo is developed using developer free time. It is hard to estimate release dates. In next release we are going to add PG 13 support. We want to release this year, but it can happen earlier next year

**Comment by AlexanderSavelyev** [comment]
Hi @sitanshubhunia, we investigated the checkMolecule function and found that the reason for the null message is inside the smiles string. The carbon is inside brackets. 
ClC1=CC=CC=C1OC1=CC(CC2CCC3=C(CC4=NN=NN4)C4=CC=CC=**[C]**4=[N+]=C23)=CC=C1

Daylight SMILES format says that: "Elements in the "organic subset" B, C, N, O, P, S, F, Cl, Br, and I may be written without brackets if the number of attached hydrogens conforms to the lowest normal valence consistent with explicit bonds." In this case Indigo gives number of implicit hydrogens = 0 and valence = 5. One can check the error for the same molecule if load from the same SMILES but without Carbon brackets

```
select bingo.checkMolecule('ClC1=CC=CC=C1OC1=CC(CC2CCC3=C(CC4=NN=NN4)C4=CC=CC=C4=[N+]=C23)=CC=C1')

element: bad valence on C having 5 drawn bonds, charge 0, and 0 radical electrons
```

Or the same molecule loaded from molfile.

**Comment by sitanshubhunia** [comment]
@AlexanderSavelyev thanks for sharing the reason.
