### ISSUE TITLE
loadMolecule segfault for certain inputs

### ISSUE THREAD

**Issue by flc** [epam/Indigo#545]
Hi,

The segmentation fault can be reproduced with the following code:

```
import indigo
ind = indigo.Indigo()
ind.loadMolecule("7-oxabicyclo[2.2.1]heptane")
```

```
$ PYTHONFAULTHANDLER=1 python indigotest.py
Fatal Python error: Segmentation fault

Current thread 0x00007f0976db6740 (most recent call first):
  File "/home/f/.virtualenvs/indtest/lib/python3.8/site-packages/indigo/__init__.py", line 3490 in loadMolecule
  File "indigotest.py", line 3 in <module>
Segmentation fault
```

Even these statements cause a sefault:
```
ind.loadMolecule("oxabicyclo")
ind.loadMolecule("cyclo")
```

So it seems `cyclo` is the root of the problem.
I understand that name to structure conversion is not really supported by Indigo but segfault shouldn't happen for any input.

Python version: 
3.8.12
Indigo version: 
1.5.0-g1aef03cac-x86_64-linux-gnu-9.3.1

**Comment by rkrishnasanka** [comment]
Is there a PR for associated with this, it seems to be blocking some of the work for us too

**Comment by even1024** [comment]
This issue should be fixed in the latest Indigo release.
