### ISSUE TITLE
Convert method for InChi and InChi Aux formats doesn't accept empty structure

### ISSUE THREAD

**Issue by ViktoriiaFedotkina** [epam/Indigo#548]
Steps to reproduce:
1. Request /v2/indigo/convert with the following options:

options: {smart-layout: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false,…}
output_format: "chemical/x-inchi-aux"

or

options: {smart-layout: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false,…}
output_format: "chemical/x-inchi"

and struct 
[struct.txt](https://github.com/epam/Indigo/files/7659979/struct.txt)

Expected result:
Receive correct struct  (InChI=1S// string for InChi)

Actual result:
Receiving 400 and error: IndigoException: inchi-wrapper: Indigo-InChI: InChI generation failed: Empty structure. Code: 2.

**Comment by AllaZhbanova** [comment]
Fixed, tested 2.4
