### ISSUE TITLE
Implement Chemical Name to Structure conversion

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/Indigo#55]
Name to structure function for IUPAC names
function might have the following API
Molecule nameToStructure(const char\* str)

**Comment by karnaukhovv** [comment]
The feature is implemented and integrated into Indigo baseline.

The final API is:
int indigoNameToStructure(const char* name, const char* params)

Currently, the following grammar elements are supported:
- alkanes (-enes, -ynes) and its derivatives
- locants expansion
- cyclic alkanes (-enes, -ynes) and its derivatives
- skeletal 'a' substitution
- basic elements (up to number 100)
- a dictionary of trivial names (~150 names)
- relaxed vs. strict IUPAC grammar (penta-1,3-diene vs. 1,3-pentadiene)

I'm closing the issue. Further improvements will be tracked by separate different tickets.
