### ISSUE TITLE
IndigoException: stereocenters: stereocenter (0) pyramid must have at least 3 atoms error on any Indigo function for structures with stereo centers

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/Indigo#554]
Execute v2/indigo/aromatize
or v2/indigo/clean
or any other Indigo function
struct:
[struct (2).txt](https://github.com/epam/Indigo/files/7712150/struct.2.txt)

Expected Result:
function is executed without error
Actual Result:
Response contains error:  IndigoException: stereocenters: stereocenter (0) pyramid must have at least 3 atoms

**Comment by AllaZhbanova** [comment]
**Steps to Reproduce**

Create any structure
Change some bonds to stereo bonds
Select some atoms with Selection tool.
Click the ‘Stereochemistry’ button.
Check the ‘Create new AND Group’ radiobutton.
Click the ‘OK’ button.
Save to V3000 molfile
Open the file
**Expected behavior**
The structure contains Stereo Flag label and Stereo Center Label as before saving
**Actual behavior**
Stereo Flag label and Stereo Center Label are not set
[struct.2.txt](https://github.com/epam/Indigo/files/7788376/struct.2.txt)

**Comment by AndreiMazol** [comment]
The issue is still reproduced. Tested on indigo-ketcher v1.6.2-0

**Comment by even1024** [comment]
Exception is not reproduced. As for V3000 - wrong stereochemistry is not getting saved into V3000.
