### ISSUE TITLE
Installation issue Windows64bit -PostgreSQL 12

### ISSUE THREAD

**Issue by sitanshubhunia** [epam/Indigo#556]
I am getting a message after installation Bingo 1.9.1 on PostgreSQL 12.
Is anything is wrong ?
![bingiInstallation](https://user-images.githubusercontent.com/840684/146122370-61a81bbb-32e3-4c61-b1d8-f96242ecb867.jpg)

**Comment by AlexanderSavelyev** [comment]
there is nothing wrong with this messages. Installation is done successfully, otherwise one will see transaction abort
