### ISSUE TITLE
Implement graph neural network for predicting molecular activity

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#568]
We need to implement mol2vec procedure to use it in molecular properties prediction. Overview of required steps:
1. Watch https://www.youtube.com/watch?v=npisouDQhLg seminar and learn about molecular fingerprints and other ways to represent molecule as ML input.
2. Get familiar with [Indigo API](https://pypi.org/project/epam.indigo/) ([documentation](https://lifescience.opensource.epam.com/indigo/api/)) and build a simple model using Indigo fingerprints and Scikit regression models (random forest, support vectors) and estimate it's `r^2` value.
3. Take a look at DGL-LifeSci code and learn how it constructs a feature vector from molecules.
4. Reimplement (and probably improve) approach from step 3 using Indigo, use DGL as a backend (or maybe look at other implementations of GNN, like Tensorflow?)
5. Build prediction model using step 4 and compare it with models from step 2.

Dataset:
* [ci8b00768_si_001.zip (1.97 MB)](https://pubs.acs.org/doi/suppl/10.1021/acs.jcim.8b00768/suppl_file/ci8b00768_si_001.zip) (use Adrenergic_dataset.csv, use "Structure" column to get input molecules; "logP" and "AdrA1A_PCHEMBL_VALUE" as target value to predict.

DGL-LifeScience implementation based on RDKit:
* https://github.com/awslabs/dgl-lifesci/tree/master/examples/property_prediction/MTL

Useful JetBrains seminars:
* https://www.youtube.com/watch?v=30ZyLaPscN0
* https://www.youtube.com/watch?v=JaZkTH_dQcE
* https://www.youtube.com/watch?v=FihxvHY4ceI
* https://www.youtube.com/watch?v=-SoGbpWFKV8

Knowledge Base: https://github.com/epam/Indigo/wiki/Indigo-ML-knowledge-base

**Comment by MysterionRise** [comment]
Looks like cool thing to do!

**Comment by suppnova** [comment]
Pushed notebook with scikit RandomForestRegressor into api/python/notebooks/adrenergic_activity

**Comment by suppnova** [comment]
Pushed notebook with scikit RandomForestRegressor into api/python/notebooks/adrenergic_activity
Results (mean r2_score):
logP 0.71
AdrA1A_PCHEMBL_VALUE 0,54

**Comment by suppnova** [comment]
Duplicate results of DGL-LifeSci models (api/python/notebooks/adrenergic_activity/dgl-lifesci-results)

![image](https://user-images.githubusercontent.com/65091469/147552928-f15d5ae9-d445-4bde-9d00-5d900bd08664.png)

**Comment by mkviatkovskii** [comment]
@suppnova, this table is for `AdrA1A_PCHEMBL_VALUE`, right?

**Comment by suppnova** [comment]
@mkviatkovskii, Yes.
The result for logP is also there (GCN)
![image](https://user-images.githubusercontent.com/65091469/147563115-541c93bb-dbd4-47e7-9a72-2cdb5cce6e09.png)

**Comment by suppnova** [comment]
The results have been updated so that comparison with the random forest is correct (dataset cleaned: NaNs from the AdrA1A_PCHEMBL_VALUE column droped). AdrA1A_PCHEMBL_VALUE column was chosen as the most populated with valid values.
![image](https://user-images.githubusercontent.com/65091469/147638116-32879ab3-b1f7-437f-a23c-a39aec276b47.png)
The AttentiveFP model showed the best results with cleaned dataset.

**Comment by mkviatkovskii** [comment]
Closed as further tasks had been created.
