### ISSUE TITLE
Clean Up action removes reaction arrow and plus from structure

### ISSUE THREAD

**Issue by ViktoriiaFedotkina** [epam/Indigo#571]
Steps to reproduce:
1. make post request to /v2/indigo/clean with
options: {aromatize-skip-super-atoms: true, gross-formula-add-isotopes: true, gross-formula-add-rsites: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false, smart-layout: true}
output_format: "chemical/x-indigo-ket"
and struct 
[struct 2.txt.zip](https://github.com/epam/Indigo/files/7751075/struct.2.txt.zip)

Actual result:
Ketcher receives structure without reaction arrow and plus

Expected result:
Reaction arrow and plus are not removed from struct

**Comment by AllaZhbanova** [comment]
The issue is fixed, tested 2.4
