### ISSUE TITLE
S stereo label instead R  in response on Calculate CIP action

### ISSUE THREAD

**Issue by AllaZhbanova** [epam/Indigo#586]
***Steps***
**Case1:** 
1. Call v2/indigo/calculate_cip
options: {smart-layout: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false,…}
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
output_format: "chemical/x-indigo-ket"
struct [ketcher (12) (1).zip](https://github.com/epam/Indigo/files/7784314/ketcher.12.1.zip)

***Result***  S stereo label  in response:
```
{"format":"chemical/x-indigo-ket","struct":"{\"root\":{\"nodes\":[{\"$ref\":\"mol0\"}]},\"mol0\":{\"type\":\"molecule\",\"atoms\":[{\"label\":\"C\",\"location\":[1.299992322921753,4.999970436096191,0.0]},{\"label\":\"C\",\"location\":[2.165987253189087,5.499967575073242,0.0]},{\"label\":\"C\",\"location\":[3.0320820808410646,4.999970436096191,0.0],\"stereoLabel\":\"abs\"},{\"label\":\"C\",\"location\":[3.8980770111083986,5.499967575073242,0.0]},{\"label\":\"C\",\"location\":[4.764071941375732,4.999970436096191,0.0]},{\"label\":\"C\",\"location\":[5.630066871643066,5.499967575073242,0.0]},{\"label\":\"C\",\"location\":[6.496161937713623,4.999970436096191,0.0]},{\"label\":\"C\",\"location\":[3.0320820808410646,3.999976396560669,0.0]}],\"bonds\":[{\"type\":1,\"atoms\":[0,1]},{\"type\":1,\"atoms\":[1,2]},{\"type\":1,\"atoms\":[2,3]},{\"type\":1,\"atoms\":[3,4]},{\"type\":1,\"atoms\":[4,5]},{\"type\":1,\"atoms\":[5,6]},{\"type\":1,\"atoms\":[2,7],\"stereo\":1}],\"sgroups\":[{\"type\":\"DAT\",\"atoms\":[2],\"fieldName\":\"INDIGO_CIP_DESC\",\"fieldData\":\"(S)\",\"x\":0.0,\"y\":0.0,\"placement\":true}]}}"}
```
***Expected result*** R stereo label  in response

**Case2:** On Calculate CIP action for the structure  
[structures_with_stereo_bonds_2 (1).zip](https://github.com/epam/Indigo/files/7784336/structures_with_stereo_bonds_2.1.zip)

 **Result**: superfluous R,S are shown
***Expected result*** R,S are not shown

**Comment by even1024** [comment]
Looks like ket generation issue on kecher side. "stereo" attribute must be one of the following:

BOND_UP : stereo = 1
cis/trans ignore: stereo = 3
BOND_EITHER: stereo = 4
BOND_DOWN: stereo = 6

for the first case stereo=1, but stereo=6 is expected.

**Comment by SunFellow** [comment]
Just formatted the description to make MD-renderer not to distort JSON content.
