### ISSUE TITLE
bingo-postgres: error when executing ImportSDF

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#604]
Could be reproduced on fresh master (commit g47a793661) at least on PostgreSQL 14 and macOS:
```sql
create table test(id serial, molfile varchar);
select bingo.ImportSDF('test', 'molfile', '', '/tmp/indigo/data/molecules/basic/sugars.sdf');
```
Output:
```
[2022-01-10 17:54:46] [XX000] ERROR: errstart was not called
```
The problem is gone if we change `molfile` column type to `text`. Still it is very unclear error message that gives zero useful information about the source of the problem.

**Comment by mkviatkovskii** [comment]
@AlexanderSavelyev it seems like there is something serious with error handling, at least on Postgres 14. I see hundreds of such errors in Bingo tests.

**Comment by AATDev21** [comment]
@AlexanderSavelyev , it occurs in the following Bingo tests: test_exact, test_pseudoatoms, test_resonance, test_rexact, test_substructure.

**Comment by AlexanderSavelyev** [comment]
can't reproduce on Linux x64, postgres12
it returns the following message
SQL Error [XX000]: ERROR: error: bingo-postgres: can not import a structure: unsupported column 'a' type; supported values: 'text', 'bytea', 'integer'

But it was reproduced for postgres 14. So it seems there is something wrong with exception handling

**Comment by mkviatkovskii** [comment]
Guess it should also fail on Postgres 13.
