### ISSUE TITLE
Investigate typical atom and bond features that could be used in mol2graph

### ISSUE THREAD

**Issue by mkviatkovskii** [epam/Indigo#612]
Take a look at:
1. DGL-LifeScience
2. https://github.com/xzenglab/KGNN
3. Various articles on GNN and molecular properties prediction (and maybe other topics as well).

Prepare a list of functions to featurize atoms and bonds, that we need to implement further.

**Comment by featherko** [comment]
1) Getting set of descriptors using genetic algorithm
https://sci-hub.hkvisa.net/10.1016/s0169-7439(02)00068-0

2) Descriptors package
https://singroup.github.io/dscribe/0.3.x/tutorials/basics.html
