### ISSUE TITLE
RXN-files creation data issue in Bingo tests

### ISSUE THREAD

**Issue by AATDev21** [epam/Indigo#615]
Different creation data of RXN-files leads to tests failure, making files for result and expected incompatible even in case of the same reactions. An example if test_aam is shown below:

```
result = '$RXN\n\n -INDIGO- 0121222202\n\n  1  1\n$MOL\ncooh\n  -INDIGO-01212222022D\n\n  9  9  0  0  0  0  0  0  0  0999 V2000...4  1  0  0  0  0\n  4  5  2  0  0  0  0\n  5  6  1  0  0  0  0\n  6  1  2  0  0  0  0\n  2  7  1  0  0  0  0\nM  END\n'
expected = '$RXN\n\n -INDIGO- 0515131756\n\n  1  1\n$MOL\ncooh\n  -INDIGO-05151317562D\n\n  9  9  0  0  0  0  0  0  0  0999 V2000...4  1  0  0  0  0\n  4  5  2  0  0  0  0\n  5  6  1  0  0  0  0\n  6  1  2  0  0  0  0\n  2  7  1  0  0  0  0\nM  END\n'
```

Would be better to set creation data some default value to make it less specific.

**Comment by AlexanderSavelyev** [comment]
the following options will be added to bingo_config
ct_format_save_date (true, false)
ct_format_mode (v2000, v3000, auto)

it will affect molfile and rxnfile
