### ISSUE TITLE
Hydrogens calculation error

### ISSUE THREAD

**Issue by AATDev21** [epam/Indigo#616]
Some tests in test_mass and test_gross from the Bingo tests set failed with a similar error. 

In the case of test_mass comparing result and expected values differ by 1 or 3 g/mol:
```
1) result = 6.044083595275879
    expected = 5.0

2) result = 62.152183294296265
     expected = 61.1

3) result = 13409.060661315918
     expected = 13406.0

4) result = 13419.923394560814
     expected = 13416.9
```
In the case of test_gross result and expected gross formula differ by 1 or 3 hydrogen atoms:
```
5) result = 'H4'
     expected = 'H3'

6) result = 'C4 O9 Na5 S Cl4 H12'
     expected = 'C4 O9 Na5 S Cl4 H11'

7) result = 'He Li Be B C N O F Ne ... No Lr Rf H71'
     expected = 'He Li Be B C N O F Ne ... No Lr Rf H68'
```

**Comment by AlexanderSavelyev** [comment]
result = 'H4'
expected = 'H3'

![image](https://user-images.githubusercontent.com/7427808/154863067-5fd9ddcd-8633-47ff-a8b1-04fc4077d3f6.png)

Number of implicit hydrogens = 1. So the correct formula is HD HD or H4

**Comment by AlexanderSavelyev** [comment]
result = 'C4 O9 Na5 S Cl4 H12'
expected = 'C4 O9 Na5 S Cl4 H11'

![image](https://user-images.githubusercontent.com/7427808/154863907-e571fcb3-76ab-410c-9cd9-dc42cca6e664.png)


Number of implicit and explicit hydrogens = 11

It seems the calculation of gross formula and mass was corrected due to implicit hydrogens

**Comment by AlexanderSavelyev** [comment]
@AATDev21 please provide molfiles, it is tricky to find the molecules by expected result and then count by id.

**Comment by AATDev21** [comment]
@AlexanderSavelyev, thank you! I've checked all molecules and everything was calculated correctly.
The difference with expected results is caused by changes in calculation behavior - single H is considered as molecule H2 now. Same for D and T.
