### ISSUE TITLE
SMILES/SMARTS parser doesn't match daylight specification 

### ISSUE THREAD

**Issue by even1024** [epam/Indigo#618]
Current Indigo implementation doesn't support some SMILES/SMARTS features like recursive patterns.
It requires to be fixed and full SMILES/SMARTS compliance tests should be implemented.

https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html

**Comment by AlexanderSavelyev** [comment]
closing as duplicate of epic:smarts
