### ISSUE TITLE
search substructure in complicated molecule failed

### ISSUE THREAD

**Issue by pumaatlarge** [epam/Indigo#62]
I am making a web app which using Indigo for substructure matching. It works well for small molecules. But when complicated macromolecule such as cyclosporinA(MW =1200 around)  presented , there is an innerexception happenend, it said " "molfile loader: direction of bond #74 makes no sense".  Is there a limit for indigo on macromolecule?

**Comment by IuriiPuzanov** [comment]
There are no such limit. It looks like there is some issue with stereo information in the structure. So there are two options: to change wrong stereo information or to use corresponding Indigo option for ignoring possible stereo errors in the input structures - "ignore-stereochemistry-errors".

**Comment by pumaatlarge** [comment]
You are right, there is a stereo center has wrong drawing. The search function works after ignoring the error. Thanks a lot!
