### ISSUE TITLE
Cannot build on Mac

### ISSUE THREAD

**Issue by jstaker7** [epam/Indigo#64]
Using either:
build_scripts\indigo-release-libs.py --preset=mac10.8
build_scripts\indigo-release-libs.py --preset=mac-universal

Causes the following error:

-- The C compiler identification is AppleClang 5.0.0.5000276
-- The CXX compiler identification is AppleClang 5.0.0.5000276
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- System-specific folder name: Mac
-- Subsystem-specific folder name: 10.7
-- Set CMAKE_BUILD_TYPE to Release
-- CMAKE_BUILD_TYPE=Release
-- Deployment target: 10.7
-- SDK: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk
-- CMAKE_OSX_ARCHITECTURES x86_64
-- CMAKE_C_FLAGS  -arch x86_64
-- CMAKE_CXX_FLAGS  -arch x86_64
-- Common output dir: /Users/staker/Downloads/Indigo-master/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_10.7_NO_STATIC_TRUE_UNIVERSAL_BUILD_TRUE/dist/Mac/10.7
-- ***\* Indigo ****
-- Using local ZLib library
-- Found Git: /usr/bin/git (found version "1.8.3.4 (Apple Git-47)")
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at /Users/staker/Downloads/Indigo-master/api/indigo-version.cmake:6 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  /Users/staker/Downloads/Indigo-master/api/CMakeLists.txt:5 (include)

CMake Error at /Users/staker/Downloads/Indigo-master/api/indigo-version.cmake:7 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  /Users/staker/Downloads/Indigo-master/api/CMakeLists.txt:5 (include)

-- Indigo full version:
-- Indigo version is
-- ***\* Indigo-inchi ****
-- ***\* Indigo-renderer ****
-- Using local LibPNG library
-- Using local Pixman library
-- Using local Cairo library
-- Framework ApplicationServices found at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/ApplicationServices.framework
-- ***\* Bingo ****
-- Configuring incomplete, errors occurred!
See also "/Users/staker/Downloads/Indigo-master/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_10.7_NO_STATIC_TRUE_UNIVERSAL_BUILD_TRUE/CMakeFiles/CMakeOutput.log".
make: **\* No rule to make target `package'.  Stop.
make: *** No rule to make target`install'.  Stop.
UpdateCTestConfiguration  from :/Users/staker/Downloads/Indigo-master/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_10.7_NO_STATIC_TRUE_UNIVERSAL_BUILD_TRUE/DartConfiguration.tcl
Parse Config file:/Users/staker/Downloads/Indigo-master/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_10.7_NO_STATIC_TRUE_UNIVERSAL_BUILD_TRUE/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/staker/Downloads/Indigo-master/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_10.7_NO_STATIC_TRUE_UNIVERSAL_BUILD_TRUE/DartConfiguration.tcl
Parse Config file:/Users/staker/Downloads/Indigo-master/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_10.7_NO_STATIC_TRUE_UNIVERSAL_BUILD_TRUE/DartConfiguration.tcl
Test project /Users/staker/Downloads/Indigo-master/build/indigo_Unix_Makefiles_ReleaseSUBSYSTEM_NAME_10.7_NO_STATIC_TRUE_UNIVERSAL_BUILD_TRUE
Constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
No tests were found!!!

**Comment by AlexanderSavelyev** [comment]
@jstaker7 could you specify your cmake version?

**Comment by jstaker7** [comment]
Tested using cmake v3.4.0 and also v3.6.1 with seemingly the same errors.

**Comment by alexeykuptsov** [comment]
I've reproduced the issue at Mac 10.11. It seems that indigo-release-libs.py somehow depends on Git repository. See row `fatal: Not a git repository (or any of the parent directories): .git`

When I cloned the Indigo repository, the script is executed well. When the source code is downloaded as a zip archive, I get exactly the same log.

**Comment by jstaker7** [comment]
I can confirm. I compiled successfully when I cloned the repo instead of downloading zip.

**Comment by MysterionRise** [comment]
Not relevant anymore, dependencies on another git repo deleted. @jstaker7  please follow the readme in order to build. Thanks!
