### ISSUE TITLE
SVGs for molecules with extend symbols have non-unique symbol IDs

### ISSUE THREAD

**Issue by ElenaOdnoshivkina** [epam/Indigo#656]
**Steps to Reproduce:**

1. Send a request to create an SVG for a molecule with the "HAR" query atom:
options: {
    "smart-layout": true,
    "ignore-stereochemistry-errors": true,
    "mass-skip-error-on-pseudoatoms": false,
    "gross-formula-add-rsites": true,
    "aromatize-skip-superatoms": true,
    "render-output-format": "svg"
}
struct:
[struct1.txt](https://github.com/epam/Indigo/files/8066532/struct1.txt)

2.  View the source of the SVG:
![1](https://user-images.githubusercontent.com/89905163/154010714-3e21576a-087c-4923-8b7f-dcfc63a0b99a.svg)

Notice that the three symbols defined at the top which correspond to the H A and R symbols have the IDs: glyph0-1 (H), glyph0-2 (A), and glyph0-3 (R).

3. Send a request to create an SVG for a molecule with the "HAR" and "A" query atoms:
options: {
    "smart-layout": true,
    "ignore-stereochemistry-errors": true,
    "mass-skip-error-on-pseudoatoms": false,
    "gross-formula-add-rsites": true,
    "aromatize-skip-superatoms": true,
    "render-output-format": "svg"
}
struct:
[struct2.txt](https://github.com/epam/Indigo/files/8066546/struct2.txt)

4.  View the source of the SVG:
![2](https://user-images.githubusercontent.com/89905163/154010932-1745ebba-764c-4837-95f0-5a5f26f0a9ba.svg)

Notice that again, we have three IDs for the 3 different atoms of H A and R, with IDs: glyph0-1 (A), glyph0-2(H), and glyph0-3 (R).

5. Create a simple page to display both of these SVGs inline: 
![image](https://user-images.githubusercontent.com/89905163/154009091-0504a2ed-3f12-4a4b-963a-6207db248bff.png)

The second SVG has incorrectly displayed the symbols of it's query features; swapping the H + A symbols.

**Actual behaviour:**
SVGs for molecules with extended atoms have non-unique symbol IDs.

**Expected behaviour:**
There would be unique IDs for each SVG's symbol definitions for uniquely displaying the symbols, independent from one another.

**Comment by even1024** [comment]
Not indigo issue. Generated SVGs are correct and those ids shouldn't be unique. Demand of having ids globally unique is not consistent. Responsibility for handling of the issue is completely on behalf of page renderer side.
