### ISSUE TITLE
Incorrect number of hydrogen atoms passed to InChI for tetravalent sulfur

### ISSUE THREAD

**Issue by dan2097** [epam/Indigo#67]
In the case below the hydrogen on the sulfur appears to not be being passed to the InChI algorithm. 

Indigo indigo = new Indigo();
IndigoInchi indigoInchi = new IndigoInchi(indigo);
IndigoObject mol = indigo.loadMolecule("C(N(N1CCC(C(=O)C2C=CC(F)=CC=2)CC1)C=SC)#N");
System.out.println(indigoInchi.getInchi(mol));

Produces:
InChI=1S/C15H17FN3OS/c1-21-11-19(10-17)18-8-6-13(7-9-18)15(20)12-2-4-14(16)5-3-12/h2-5,11,13H,6-9H2,1H3

but it should produce:
InChI=1S/C15H18FN3OS/c1-21-11-19(10-17)18-8-6-13(7-9-18)15(20)12-2-4-14(16)5-3-12/h2-5,11,13,21H,6-9H2,1H3

(if mol.unfoldHydrogens() is called before calling getInchi then the correct InChI is returned!)

**Comment by IuriiPuzanov** [comment]
It seems that there is no issue. InChi just returns another tautomer form of this compound with preference of 2-valence sulfur. And using unfoldHydrogens() you converts implicit hydrogen to explicit form, so it resolves the issue.

**Comment by dan2097** [comment]
Just to be clear the two InChIs are NOT tautomers, the latter contains an additional hydrogen (C15H18FN3OS vs C15H17FN3OS). Incidentally for common tautomers StdInChI is tautomer invariant.
It is true that unfoldHydrogens does workaround the issue, but it shouldn't be required as whether hydrogens are implicit or explicit doesn't actually change the number of hydrogens.

**Comment by IuriiPuzanov** [comment]
One another variant for correct InChi conversion is to add hydrogen into S atom description to point tetravalent character of sulfur:  "C(N(N1CCC(C(=O)C2C=CC(F)=CC=2)CC1)C=[SH]C)#N". Is it acceptable?

**Comment by dan2097** [comment]
I can confirm that the input of  "C(N(N1CCC(C(=O)C2C=CC(F)=CC=2)CC1)C=[SH]C)#N" does indeed give the correct InChI.... however the fact that these two different SMILES give different results doesn't really make sense.
In what way does Indigo's internal representation of "C(N(N1CCC(C(=O)C2C=CC(F)=CC=2)CC1)C=SC)#N" and "C(N(N1CCC(C(=O)C2C=CC(F)=CC=2)CC1)C=[SH]C)#N" actually differ? I've checked a few properties e.g. mol.getAtom(18).valence(), mol.getAtom(18).countImplicitHydrogens() and they were identical for both SMILES at the sulfur (valence =4, implicit hydrogens=1).  I expect the issue is that when [SH] is present in the SMILES the hydrogen count is being explicitly provided to the InChI algorithm, while when S is present the hydrogen handling is being left to the InChI algorithm. The InChI algorithm has a concept of implicit hydrogen, which will often agree with Indigo's representation, however it will NOT add an implicit hydrogen to a trivalent sulfur (InChI technical manual, Appendix 1. InChI Standard Valences) i.e. it's better to in all cases explicitly pass the implicit hydrogen count information to the InChI algorithm rather than hope it calculates the same number of implicit hydrogen.

**Comment by IuriiPuzanov** [comment]
I've added special case handling for tetravalent sulfur to avoid such issues. Thank you very much for this finding!

**Comment by dan2097** [comment]
Thanks for the fix. Look at the code above your fix, I think there may be a more general fix though. The default value of hcount in the code is -1 (line 421), which gives the InChI algorithm control of the implicit hcount, and hence probably should be avoided at all costs as the Indigo toolkit should know more about the actual implicit hydrogen count than the InChI toolkit.
As getImplicitH_NoThrow looks safe to call regardless of whether Indigo knows actually knows the implicit hcount, can the code be simplified by replacing lines 422-439 with just lines 424-433?
[the issue for the sulfur case looks to be that the implicit hydrogen count was determinable. but isImplicitHSet returned false, but just calling getImplicitH_NoThrow(v, -1) seems to tell you whether or not the implicit hydrogen count was determinable as -1 will be returned anyway if it is not]

I'm not sure when getImplicitH_NoThrow(v, -1)  fails (and gives -1), hence I'm not sure whether a failure value of 0 would or wouldn't be more appropriate.
