### ISSUE TITLE
Undesirable rendering behavior

### ISSUE THREAD

**Issue by jstaker7** [epam/Indigo#68]
My molecules are always rendered in the bottom left corner, and are often cut off. I have compensated for this in the past by rendering with sufficient margin, then using external tools to crop, pad, and center. But this has been cumbersome and slow. Ideally I'd like no margin at all and in the very least, to not have the rendering cut off. Any suggestions on how to fix this, apart from adding lots of margin and/or offset?

Rendered with margin = 1 and no offset. You can see that it gets cut off, and adds lots of unnecessary whitespace:

<img width="657" alt="img_example" src="https://cloud.githubusercontent.com/assets/1364252/19000210/35b6cff2-86f6-11e6-9d7c-8eb8bbfe8e94.png">

**Comment by jstaker7** [comment]
Also tried removing all rendering options and also tested both rendering to buffer or rendering to file. In all cases I'm experiencing the same behavior and can't seem to narrow down any particular option that causes the issue.

**Comment by adekker2** [comment]
Same issue here, I've tried the simplest rendering for buffer or file and still get the same behaviour.

using Indigo 1.2.3.r0

- Adriano
ChEBI Team.

**Comment by jstaker7** [comment]
Update: I noticed that the error happens in OSX but images appear fine in Linux. Also noticed that rendering styles differ in subtle ways between the two systems, although not really a big deal, nor all that unexpected.

**Comment by AlexanderSavelyev** [comment]
We also tried to reproduce the issue on linux, but without a success. @jstaker7 could you please provide a code example for this error?

**Comment by jstaker7** [comment]
I was mistaken. It looks like my rendering is coming out fine in Linux. Have you been able to reproduce the error in OS X? I can provide a code example, if needed.

**Comment by adekker2** [comment]
I confirm the error occurs on Mac.

**Comment by urlix** [comment]
I tried to reproduce it on Windows and Linux and there everything work fine. Could you please provide your code to be sure that we are on the same page.

**Comment by jstaker7** [comment]
This code reproduces the error in OS X 10.11 and MacOS Sierra. You may need to adjust the package imports at the top of the script.
[indigo_error_repro.py.zip](https://github.com/epam/Indigo/files/593276/indigo_error_repro.py.zip)

**Comment by karnaukhovv** [comment]
This issue should be fixed by recent changes in Indigo Renderer, updated cairo and Pixman sources. I checked the attached testcase on Linux, Windows, and macOS, and all output was correctly rendered and positioned. I can also see many improvements in rendering on macOS with our tests.

I'm closing the issue. Please feel free to re-open it or open a new one if you still experience rendering degradation on any platform, or should you encounter any new problems.
