### ISSUE TITLE
could not access file "$libdir/libbingo-postgres": No such file or directory

### ISSUE THREAD

**Issue by niuzhenjiang** [epam/Indigo#692]
ubuntu 18.04
postgresql 12.6
i want to install bingo，and I followed the installation manual
<img width="940" alt="image" src="https://user-images.githubusercontent.com/42111602/158054287-440b749b-8575-4199-8074-30217384360e.png">
an error will occur
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/42111602/158054319-295cba19-c7a4-4c62-b825-ffd25ef15a80.png">
and i know this is because I didn't generate the libbingo-postgres.so file,But when I execute 
```
./bingo-pg-install.sh -libdir
```
 it should appear in the lib folder under the current folder and the file does not appear
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/42111602/158054424-4fe42584-adbe-4af9-8c91-64e677cc1a08.png">
Did I miss something? grateful

**Comment by AlexanderSavelyev** [comment]
Hi @niuzhenjiang 

 if you specify the  -pglibdir the libbingo-postgres.so should be copied into the PostgreSQL default library folder (e.g. /usr/local/pgsql/lib). 
-libdir should be used with a parameter (e.g. -libdir /home/test/lib/)
If you want to use the lib/ directory in the example above, you should not use any parameters while running the sh script

Thanks
Aleksandr

**Comment by niuzhenjiang** [comment]
> 嗨@牛振江
> 
> 如果您指定-pglibdir，则应该将libbingo-postgres.so 复制到PostgreSQL 默认库文件夹（例如/usr/local/pgsql/lib）中。 -libdir 应与参数一起使用（例如 -libdir /home/test/lib/） 如果要使用上例中的 lib/ 目录，则在运行 sh 脚本时不应使用任何参数
> 
> 谢谢 亚历山大

thanks,What I want to ask is how to generate bingo-post.so file from the source code, because the document is not very clear, I compiled according to the description of the document, but the bingo-post.so file was not generated, so I want to ask how to generate bingo-post.so file, thanks a lot

**Comment by AlexanderSavelyev** [comment]
Hi @niuzhenjiang , one can find build source code scripts in the github CI scripts
https://github.com/epam/Indigo/blob/1700dafec86c7fdfe429346043cba1ba1f32c67b/.github/workflows/indigo-ci.yaml#L915
