### ISSUE TITLE
Bingo error when creating index

### ISSUE THREAD

**Issue by rccc** [epam/Indigo#693]
Hello,

I tried : create index smiles_1_idx on molecule_1 using bingo_idx (smiles bingo.molecule);

after    ~ 600000 lines cas processed i got this error : 

ERROR:  error: bingo: Error while executing build index procedure error: bingo: molecule build engine: error while processing records with ctid='(268420,19)'::tid: non-unique dearomatization: Dearomatization is not unique. Cannot restore hydrogens. ERROR ON id=360

I delete the corresponding line but now error appears each time i try to create the index, event after a vacuum, the error is still the same, no molecule are processed !

bingo 1.9.1.r1-g302eead linux64
psql (PostgreSQL) 12.10 (Debian 12.10-1.pgdg110+1)

Thanks in advance
Eric

**Comment by AlexanderSavelyev** [comment]
Hello
Could you try to change the 'ALLOW_NON_UNIQUE_DEAROMATIZATION' in bingo_config?
Thanks
Aleksandr

**Comment by rccc** [comment]
Dear Aleksandr,

Many thanks for response !

I wil try this.

I am currently check correcteness of structures to isolate those which have errors so that i will be able to create index on only correct structures.

I will then check this config.

Have a nice day.

Eric
