### ISSUE TITLE
JSON cannot be properly deserialized if input cointains R-Groups

### ISSUE THREAD

**Issue by akolyakov42** [epam/Indigo#699]
**Steps to reproduce**
Call v2/indigo/clean in remote mode with (options, struct):
```
options: {
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
output_format: "chemical/x-indigo-ket",
struct: {<attached>}
```
[undeserialized_json.ket.zip](https://github.com/epam/Indigo/files/8396969/undeserialized_json.ket.zip)

**Expected result**
JSON successfully deserialized, Ketcher canvas is Cleaned Up

**Actual result**
JSON cannot be deserialized, Ketcher produces error message.

**Attached Issue**
epam/ketcher#1391

**Comment by even1024** [comment]
Fixed in 1.6.4
