### ISSUE TITLE
Bingo failed tests

### ISSUE THREAD

**Issue by AATDev21** [epam/Indigo#703]
Four Bingo tests - smarts, rsmarts, rexact, rsub - contain several failed results. It's necessary to confirm if these results are really failed.
All tests can be found in a branch bingo_failed_tests_#703. Also I have a .key-file with query reactions and expected and actually derived from the tests reactions for comparison.

**Comment by AlexanderSavelyev** [comment]
1 comment for the running scripts

Follow the instructions on bingo/test/README.md
Running only postgres
The following errors

python3 -m pytest --db postgres
ImportError while loading conftest '/home/tarquin/repo/indigo/bingo/tests/conftest.py'.
conftest.py:2: in <module>
    from bingo_elastic.elastic import IndexName
E   ModuleNotFoundError: No module named 'bingo_elastic'
tarquin@EPRUPETW0B58:~/repo/indigo/bingo/tests$ python3 -m pytest --db postgres
ImportError while loading conftest '/home/tarquin/repo/indigo/bingo/tests/conftest.py'.
conftest.py:14: in <module>
    from .dbc.BingoElastic import BingoElastic
dbc/BingoElastic.py:1: in <module>
    from bingo_elastic.elastic import ElasticRepository
E   ModuleNotFoundError: No module named 'bingo_elastic'

need to disable the bingo_elastic part if run only postgres
