### ISSUE TITLE
Text object in not displayed after opening file saved in PNG/SVG

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/Indigo#706]
**Steps to Reproduce**
1. Import the structure with text as Image (SVG Documents/PNG Image formats)
Call v2/indigo/render

options:
{
"gross-formula-add-rsites": true,
"ignore-stereochemistry-errors": true,
"mass-skip-error-on-pseudoatoms": false,
"render-output-format": "png",
"smart-layout": true,
}

[Struct.txt](https://github.com/epam/Indigo/files/8487756/Struct.txt)

2. Export the Image with text

**Expected behavior**
A structure with text object is saved in SVG/PNG. It is displayed after opening the file. 

**Actual behavior**
The Image is exported without text

OS: [Microsoft Windows]
Browsers: Google Chrome: Version 100.0.4896.75/FireFox: Version 99.0 (64-bit)
Ketcher v2.3.2-8-ge3f270d8

**Comment by ZhannaNovikova** [comment]
Related issue in the Ketcher: https://github.com/epam/ketcher/issues/1404

**Comment by even1024** [comment]
Fixed in 1.7.2

**Comment by AndreiMazol** [comment]
Reopened. Text objects are ignored if structure has reaction arrows

**Comment by even1024** [comment]
fixed in 1.7.3
