### ISSUE TITLE
v2/indigo/render endpoint throws exception after selecting the file formats 

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/Indigo#710]
**Steps to Reproduce**
1.  Save the structure with more than one arrow
Call the v2/indigo/convert

options:

{
"aromatize-skip-superatoms": true,
"gross-formula-add-isotopes": true,
"gross-formula-add-rsites": true,
"ignore-stereochemistry-errors": true,
"mass-skip-error-on-pseudoatoms": false,
"molfile-saving-mode": "3000",
"smart-layout": true,
}

**Expected behavior**

Structure with one or multiple arrow can be convert to the server file format
Respons HTTP 200 OK

**Actual behavior**

400 HTTP code is gotten with the following description:
{
"error": "'struct data not recognized as molecule, query, reaction or reaction query'"
}
[issues710.zip](https://github.com/epam/Indigo/files/8514233/issues710.zip)

Reproducible after selected the formats:
MDL Molfile V2000; MDL Molfile V3000; Extended SMILES; Daylight SMARTS; InChI; InChI AuxInfo; CML

Version 1.6.3.0-g3f1d38c03-wasm32-wasm-clang-13.0.0

**Comment by even1024** [comment]
Not reproduced in 1.7.1
