### ISSUE TITLE
R-Group definition changes when server functions are applied

### ISSUE THREAD

**Issue by Svetlana-Asinovskaia** [epam/Indigo#711]
**Steps to Reproduce**
1. Execute v2/indigo/layout with the following options:
{smart-layout: true, ignore-stereochemistry-errors: true, mass-skip-error-on-pseudoatoms: false,…}
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true

[struct.zip](https://github.com/epam/Indigo/files/8516008/struct.zip)

**Expected behavior**
rg28 is present in the response.

**Actual behavior**
Response contains rg1.

**Indigo/Bingo version**  
Indigo Version 1.6.1.10-gd1a8a571b-x86_64-linux-gnu-10.2.1

**Additional context**
Reproduced with Clean Up, Aromatize, Dearomatize, Save, Structure Check functions.

**Comment by even1024** [comment]
Fixed in 1.7.1
