### ISSUE TITLE
api: python: implement salt stripping method

### ISSUE THREAD

**Issue by AATDev21** [epam/Indigo#713]
**Description**
We need to extend standardization procedure by adding a method, which removes all inorganic fragments from multifragment molecules. The example is shown on the picture below:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/78915761/164222891-f9a2c8a7-0743-428f-80a5-53be30bba06a.png">

**ToDo**
Implement a method for `IndigoObject` that accepts a molecule and optional flag `inplace`, which specifies a mode for the molecule modification.

**Comment by SunFellow** [comment]
@AATDev21 , @mkviatkovskii ,
Question: Do we need to add the same method to other languages libs: .NET and Java?

**Comment by mkviatkovskii** [comment]
> @AATDev21 , @mkviatkovskii ,
> 
> Question: Do we need to add the same method to other languages libs: .NET and Java?
> 

We definitely would like to have it, but someone should reimplement it in C++ first.
