### ISSUE TITLE
All descriptors are empty

### ISSUE THREAD

**Issue by digitalroll** [epam/Indigo#714]
**Steps to Reproduce**
Request to `/indigo/descriptors`

```
{
  "data": {
    "type": "descriptor",
    "attributes": {
      "compound": {
        "structure": "CCC",
        "format": "auto"
      },
      "descriptors": [
        "countAtoms"
      ]
    }
  }
}
```

**Expected behavior**
"countAtoms": "3"

**Actual behavior**
"countAtoms": ""

**Indigo/Bingo version**  
1.6.3, 1.6.4, 1.6.5
But a few days ago someone published a working version (id:b1b72d61c2bd) at the request of Tikhova Alina. But now this version is no longer available.

**Comment by digitalroll** [comment]
Full id b1b72d61c2bd85978c143f35b26ad846ea81757a39e5e9e39eb8e31e39a3e247

**Comment by khyurri** [comment]
@digitalroll , you may use the latest docker image: `epmlsop/indigo-service:enhanced-1.7.4` 

This bug is not reproduced in latest published release and in master branch
