### ISSUE TITLE
Cannot deserialize input JSON if input contains Not List atoms

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/Indigo#730]
Case 1
**Steps to Reproduce**
1. Call the v2/indigo/clean

options: {
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
output_format: "chemical/x-indigo-ket"
struct:
[structure with Not List atom.zip](https://github.com/epam/Indigo/files/8686271/structure.with.Not.List.atom.zip)

**Expected behavior**
JSON successfully deserialized, Ketcher canvas is Cleaned Up

**Actual behavior**
The following error message is displayed: "Error: Cannot deserialize input JSON." 

Case 2
**Steps to Reproduce**
1. Call the v2/indigo/layout

options: {
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
output_format:"chemical/x-indigo-ket"
struct:
[structure with Not List atom.zip](https://github.com/epam/Indigo/files/8686271/structure.with.Not.List.atom.zip)

**Expected behavior**
JSON successfully deserialized, the Layout is applied to Ketcher canvas

**Actual behavior**
The following error message is displayed: "Error: Cannot deserialize input JSON." 

Version 1.6.1.10-gd1a8a571b-x86_64-linux-gnu-10.2.1

**Comment by even1024** [comment]
Not reproduced
