### ISSUE TITLE
Appearance of reactions (plus and arrow) is changing after applying the layout Server function

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/Indigo#732]
Case 1
Steps to Reproduce:
1. Execute the /v2/indigo/layout with the following parameters:
struct:
[structure with reaction arrow.zip](https://github.com/epam/Indigo/files/8713697/structure.with.reaction.arrow.zip)

options: {
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
output_format: "chemical/x-indigo-ket"

Case 2
Steps to Reproduce:
1.  Execute the /v2/indigo/layout with the following parameters:
struct:
[structure with reaction of the plus and arrow.zip](https://github.com/epam/Indigo/files/8713705/structure.with.reaction.of.the.plus.and.arrow.zip)
options: {
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
output_format: "chemical/x-indigo-ket"

Expected behavior:
Response is received with correct reaction structure, e.g: 
[Response from Remote mode.zip](https://github.com/epam/Indigo/files/8713960/Response.from.Remote.mode.zip)

Actual behavior:
Appearance of reactions (plus and arrow) has been changed after applying the layout Server function  

**Note**: the issue is reproducible in the Standalone mode only

Ketcher v2.4.2-331-ga26690b0
Version 1.7.0-alpha.0-gd57edc00d-wasm32-wasm-clang-13.0.0

**Comment by even1024** [comment]
Fixed in 1.7.1
