### ISSUE TITLE
The IndigoException: molecule: casting to molecule is invalid after applying the Calculate CIP function

### ISSUE THREAD

**Issue by ZhannaNovikova** [epam/Indigo#736]
Case 1
**Steps to Reproduce**
1. Execute the v2/indigo/calculate_cip with the following parameters:
struct:
[Structure with the List atom.zip](https://github.com/epam/Indigo/files/8738478/Structure.with.the.List.atom.zip)

options: 
{
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
output_format: "chemical/x-indigo-ket"

Case 2
**Steps to Reproduce**
1. Execute the v2/indigo/calculate_cip with the following parameters:
struct:
[Structure with the Not List atom.zip](https://github.com/epam/Indigo/files/8738528/Structure.with.the.Not.List.atom.zip)

options: 
{
aromatize-skip-superatoms: true
gross-formula-add-isotopes: true
gross-formula-add-rsites: true
ignore-stereochemistry-errors: true
mass-skip-error-on-pseudoatoms: false
smart-layout: true
},
output_format: "chemical/x-indigo-ket"

**Expected behavior**
The Calculate CIP function is performed successfully
Respons HTTP 200 OK

**Actual behavior**
400 HTTP code is gotten with the following description:
{
"error":"IndigoException: molecule: casting to molecule is invalid"
}

Note: works as expected when the structure contains the single atom

Version 1.7.0.0-g260b32105-x86_64-linux-gnu-11.2.1

**Comment by even1024** [comment]
Fixed in 1.7.1
