### ISSUE TITLE
'Not list' information is lost when structure is saved as 'Daylight SMARTS'

### ISSUE THREAD

**Issue by AndreiMazol** [epam/Indigo#764]
**Steps to Reproduce**
1. create any structure (MOL)  with 'Not List' element (the list should contain 2or more elements)
2. convert created structure to SMARTS
3. convert SMARTS to mol

**Expected behavior**
structure1 (step1) equals to structture2 (step3)

**Actual behavior**
'Not LIst' information is lost.

**Attachments**
If applicable, add attachment files to reproduce the issue.

**Indigo/Bingo version**  
Version 1.7.2.0-gfd50d72ab-wasm32-wasm-clang-13.0.0

**Comment by even1024** [comment]
Fixed in 1.7.4
