### ISSUE TITLE
Versions 1.5 and later conflict with xgboost

### ISSUE THREAD

**Issue by balabin** [epam/Indigo#770]
**Steps to Reproduce**
1. Install Indigo version 1.5 or later using pip3 from the repository or a downloaded wheel.
2. In a Python environment, import and initialize Indigo:
          from indigo import *
          indigo = Indigo()
3. Instantiate and run xgboost XGBClassifier on any dataset:
          import numpy as np
          from sklearn.model_selection import train_test_split
          from xgboost import XGBClassifier
          n = 1000
          X = np.random.rand(n, 1)
          y = np.random.rand(n)
          X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
          xgb = XGBClassifier()
          y_pred = xgb.fit(X_train, y_train).predict(X_test)
4. Uninstall this version of Indigo and install version 1.2 - 1.4.
5. Repeat steps 2 and 3.

**Expected behavior**
XGB trains on the training dataset and then produces predictions for the test dataset.

**Actual behavior**
For Indigo versions 1.2 - 1.4, XGBClassifier performs as expected. For Indigo versions 1.5 - 1.7, it crashes and produces incorrect error messages about the type of its parameters (this was tested with multiple different types of training/test data and input parameters).

**Attachments**
If applicable, add attachment files to reproduce the issue.

**Indigo/Bingo version**  
Tested versions 1.2.3 - 1.7.0

**Additional context**
Tested using Python versions 3.6, 3.9, 3.10 in a text console and a Jupyter notebook (jupyter v. 1.0.0 installed using pip3). The problem also occurs if indigo is imported without using the wild card:
          import indigo
          indigo = indigo.Indigo()

**Comment by balabin** [comment]
P.S.: This was tested on several systems running Ubuntu and Debian, with same outcome.

**Comment by mkviatkovskii** [comment]
Dear @balabin,
Thanks for you bug report! Could you please specify, how were the Indigo and especially XGBoost installed? I've just created a fresh install using
```bash
python3 -m pip install epam.indigo xgboost scikit-learn
```
And ran the script:
```python
import indigo
indigo = indigo.Indigo()
m = indigo.loadMolecule("c1ccccc1")
m.dearomatize()
print(m.smiles())

import numpy as np
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
n = 1000
X = np.random.rand(n, 1)
y = np.random.rand(n)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
xgb = XGBClassifier()
y_pred = xgb.fit(X_train, y_train).predict(X_test)
print(y_pred)
```

Everything worked fine on Ubuntu 20.04 with Python 3.8 and CentOS7 with Python 3.7.

Have you installed Indigo and XGBoost using pip, or maybe used some other way?

**Comment by mkviatkovskii** [comment]
Dear @balabin,
Changing classification to binary and starting the script in Jupyter allowed me to catch the problem, I see the following error:
```
XGBoostError: Invalid Parameter format for gpu_id expect int but value='-1'
```
Is that the error you get?

**Comment by balabin** [comment]
Hi Mikhail,

There are two unrelated issues here:

 1. Binary classification. In the original submission, I typed the code
    in from memory and missed converting the labels to 0/1. Without
    that, the code will rightly complain about invalid (non-integer)
    labels. With the labels converted to 0/1, that issue is closed, no
    matter if the code is run in a console or a Jupyter notebook.
 2. XGBoost errors that *only* arise when the code is run in a Jupyter
    notebook *and* Indigo v. 1.5 or above has been imported and
    instantiated. This needs a bit of explanation:
    - The error message you see does not make sense, since the code does
    not set a gpu_id value
    - The error message I see is as follows:
               Invalid Parameter format for num_feature expect int
    (non-negative) but value=''
    This message does not make sense either, since the code does not set
    a num_feature value. I tried setting it, but that only resulted in
    similar error messages regarding other XGBClassifier parameters.
    Most importantly, neither gpu_id, nor num_feature values must be set
    by a user; they have default values that are sufficient for running
    XGBClassifier. The meaninglessness of the error messages suggests
    that the issue is not with the XGBClassifier parameters but with
    something else. I wonder whether something might have changed in the
    Indigo namespace in version 1.5.0?

It does not look like the example notebook I attached to my previous 
email made it through. I am attaching it to the next message.

Thanks for your time and help, and please let me know what other 
information could be useful for you.

Best regards,
Ilya Balabin, Ph.D.

**Comment by balabin** [comment]
[](url
[Test_Indigo.ipynb.txt](https://github.com/epam/Indigo/files/9033397/Test_Indigo.ipynb.txt)
)

**Comment by mkviatkovskii** [comment]
Dear @balabin,
Sorry for delay, it took more time than I expected. I believe I fixed the issue. Could you please check if problem is gone on your side using whl file from this archive? [indigo-python](https://github.com/epam/Indigo/suites/7461756524/artifacts/305600587)

**Comment by balabin** [comment]
Hi @mkviatkovskii ,

An install from epam.indigo-1.7.4-py2.py3-none-manylinux1_x86_64.whl on a Debian stable box runs without a hitch. Tested it with the notebook above as well as several other notebooks I actually work with, and everything looks fine so far. Thank you so much for your time and efforts; I really appreciate the diligence. 

Best regards,
Ilya
