### ISSUE TITLE
v2/indigo/render is failed with 500 status code 

### ISSUE THREAD

**Issue by evgeniiFrolov1** [epam/Indigo#841]
**Steps to Reproduce**
```
curl --request POST \
  --url https://lifescience.opensource.epam.com/v2/indigo/render \
  --header 'accept: image/png' \
  --header 'content-type: application/json' \
  --data '{"struct":"c1ccccc1N","output_format":"image/png"}'

```

**Expected behavior**

API call returns image

**Actual behavior**

v2/indigo/render is failed with 500 status code and returns 
```json
{"error":"'HTTP_ACCEPT'"}
```

**Indigo/Bingo version**  
`1.7.4.0-g86f1ef175-x86_64-linux-gnu-11.2.1`

**Additional context**
- the same for SVG
- the issue is reproduced only on lifescience.opensource.epam.com env

**Comment by AlexanderSavelyev** [comment]
the issue was resolved by changing cloud front parameter to no cache
