### ISSUE TITLE
Add parameter for dearomatize on load

### ISSUE THREAD

**Issue by evgeniiFrolov1** [epam/Indigo#868]
**Is your feature request related to a problem? Please describe.**
In the ketcher we would like to add the property `dearomatize`. The main goal of this feature is to add a parameter to `layout` and to `convert` API to dearomatize struct on load automatically

**Describe the solution you'd like**
To add a parameter to `layout` and to `convert` API to dearomatize struct on load automatically

**Comment by AlexanderSavelyev** [comment]
make indigo option "dearomatize-on-load"

**Comment by even1024** [comment]
fixed in 1.8.0.rc.2
