### ISSUE TITLE
(RXN files) structure is missing when "Paste from clipboard" or "Open from file" if reaction consists of two or more reaction arrows and structures.

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#870]
**Steps to Reproduce**
1. Open Ketcher v2.5.2
2. Add a reaction with multiple (more than one reaction arrow) as shown in the image
3. Save file in MDL Rxnfile V2000 and MDL Rxnfile V3000
4. Paste files from clipboard or open saved files from saved directory.

**Expected behavior**
Structure is correctly opens from saved files. Keep only first reaction arrow and keep all structures (all intermediate structures should be products and the arrow is replaced by a plus)

**Actual behavior**
In MDL Rxnfile V2000 the arrow disappears, and when opening MDL Rxnfile V3000 the arrow and structure disappear

**Attachments**
![2022-10-07_14h54_14](https://user-images.githubusercontent.com/62464241/194911769-195438fa-36fe-46bb-95d2-cf00784415e5.png)

**Indigo/Bingo version**  
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.7.4.0-g86f1ef175-x86_64-linux-gnu-11.2.1

**Additional context**
Ketcher issue: https://github.com/epam/ketcher/issues/1837

**Comment by AlexanderSavelyev** [comment]
rxn supports only one arrow, but structure should no disappear

**Comment by even1024** [comment]
fixed in 1.8.1
