### ISSUE TITLE
Add indigo option to save daylight smiles

### ISSUE THREAD

**Issue by AlexanderSavelyev** [epam/Indigo#876]
**Is your feature request related to a problem? Please describe.**
There is no way to save in daylight smiles

**Describe the solution you'd like**
Add option in indigo "smiles-saving-format"
two possible values
* chemaxon(default)
* daylight

Update indigo-service and indigo-wasm to use this option while convert

**Comment by johnmay** [comment]
It seems Curly SMILES are now written by default? 
Is it possible to update https://lifescience.opensource.epam.com/indigo/options/index.html. I had to dig into the code to find the option
