### ISSUE TITLE
Postgresql > bingo.CheckMolecule : getting error 

### ISSUE THREAD

**Issue by sitanshubhunia** [epam/Indigo#907]
**Steps to Reproduce**
1.Environment
Database: "PostgreSQL 12.7, compiled by Visual C++ build 1914, 64-bit"
Bingo version: "1.9.1.r0-g353401f win64"
2
select bingo.CheckMolecule('
  Marvin  11282214462D          

 77 88  0  0  0  0            999 V2000
    3.8170   -3.0821    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1026   -2.6696    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1026   -1.8446    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8170   -1.4321    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.5315   -1.8446    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.5315   -2.6696    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8109   -0.4996    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    2.9861   -0.5093    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5821   -1.2285    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7571   -1.2382    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3363   -0.5287    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7403    0.1906    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5652    0.2003    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7796    6.2239    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4964    5.8157    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.5015    4.9907    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7896    4.5739    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0726    4.9821    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0676    5.8071    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.7960    3.6443    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9680    1.5254    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5606    2.2426    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7356    2.2485    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3180    1.5371    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7254    0.8197    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5504    0.8138    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5262    1.5431    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    0.5128    0.7180    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2302    0.3106    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2361   -0.5143    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5246   -0.9319    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1928   -0.5246    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1987    0.3004    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5011    2.3679    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2164    2.7753    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2222    3.6002    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4893    4.0178    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2067    3.6105    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2126    2.7855    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.1307   -0.9162    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.4133   -0.5089    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.4074    0.3161    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.1189    0.7337    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.8364    0.3263    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.8422   -0.4986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.0968    1.5592    0.0000 P   0  0  0  0  0  0  0  0  0  0  0  0
    7.1071    2.3836    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.3898    2.7910    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.3839    3.6159    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.0954    4.0335    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.8128    3.6262    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.8187    2.8012    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.9380    1.5646    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.3454    2.2819    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.1704    2.2878    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.5880    1.5763    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    9.1806    0.8590    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    8.3556    0.8531    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8059    1.5526    0.0000 Pd  0  0  0  0  0  0  0  0  0  0  0  0
    4.6359   -0.4959    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0517   -1.2086    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.8767   -1.2049    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.2860   -0.4886    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.8703    0.2241    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0453    0.2204    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.6209    3.6443    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.9710    3.6443    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0334    2.9298    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.8584    2.9298    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.2709    3.6443    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.8584    4.3588    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.0334    4.3588    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5585    4.3588    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7335    4.3588    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3210    3.6443    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7335    2.9298    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5585    2.9298    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  1  6  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  2  0  0  0  0
  4  5  1  0  0  0  0
  4  7  1  0  0  0  0
  5  6  2  0  0  0  0
  7  8  1  0  0  0  0
  7 59  8  0  0  0  0
  7 60  1  0  0  0  0
  8  9  2  0  0  0  0
  8 13  1  0  0  0  0
  9 10  1  0  0  0  0
 10 11  2  0  0  0  0
 11 12  1  0  0  0  0
 12 13  2  0  0  0  0
 14 15  2  0  0  0  0
 14 19  1  0  0  0  0
 15 16  1  0  0  0  0
 16 17  2  0  0  0  0
 17 18  1  0  0  0  0
 17 20  1  0  0  0  0
 18 19  2  0  0  0  0
 20 66  1  0  0  0  0
 20 67  1  0  0  0  0
 20 59  8  0  0  0  0
 21 22  2  0  0  0  0
 21 26  1  0  0  0  0
 22 23  1  0  0  0  0
 23 24  2  0  0  0  0
 24 25  1  0  0  0  0
 24 27  1  0  0  0  0
 25 26  2  0  0  0  0
 27 28  1  0  0  0  0
 27 34  1  0  0  0  0
 27 59  8  0  0  0  0
 28 29  2  0  0  0  0
 28 33  1  0  0  0  0
 29 30  1  0  0  0  0
 30 31  2  0  0  0  0
 31 32  1  0  0  0  0
 32 33  2  0  0  0  0
 34 35  2  0  0  0  0
 34 39  1  0  0  0  0
 35 36  1  0  0  0  0
 36 37  2  0  0  0  0
 37 38  1  0  0  0  0
 38 39  2  0  0  0  0
 40 41  2  0  0  0  0
 40 45  1  0  0  0  0
 41 42  1  0  0  0  0
 42 43  2  0  0  0  0
 43 44  1  0  0  0  0
 43 46  1  0  0  0  0
 44 45  2  0  0  0  0
 46 47  1  0  0  0  0
 46 53  1  0  0  0  0
 46 59  8  0  0  0  0
 47 48  2  0  0  0  0
 47 52  1  0  0  0  0
 48 49  1  0  0  0  0
 49 50  2  0  0  0  0
 50 51  1  0  0  0  0
 51 52  2  0  0  0  0
 53 54  2  0  0  0  0
 53 58  1  0  0  0  0
 54 55  1  0  0  0  0
 55 56  2  0  0  0  0
 56 57  1  0  0  0  0
 57 58  2  0  0  0  0
 60 61  1  0  0  0  0
 60 65  2  0  0  0  0
 61 62  2  0  0  0  0
 62 63  1  0  0  0  0
 63 64  2  0  0  0  0
 64 65  1  0  0  0  0
 66 68  1  0  0  0  0
 66 72  2  0  0  0  0
 67 73  1  0  0  0  0
 67 77  2  0  0  0  0
 68 69  2  0  0  0  0
 69 70  1  0  0  0  0
 70 71  2  0  0  0  0
 71 72  1  0  0  0  0
 73 74  2  0  0  0  0
 74 75  1  0  0  0  0
 75 76  2  0  0  0  0
 76 77  1  0  0  0  0
M  END
')
FYI
[error_script.txt](https://github.com/epam/Indigo/files/10102275/error_script.txt)

 

**Expected behavior**
 select bingo.CheckMolecule('....') or select bingo.SMILES('..') should return value

**Actual behavior**
select bingo.CheckMolecule('....') 
 returns  **molfile loader: 'any' bonds are allowed only for queries**

 select bingo.SMILES('..')  
returns  **null**

**Attachments**
![image](https://user-images.githubusercontent.com/840684/204242817-de708844-4938-409d-86db-bbcccff016de.png)

![image](https://user-images.githubusercontent.com/840684/204242969-f0269580-2a6e-4d4f-91b2-2b136c4d4bf0.png)

**Comment by AATDev21** [comment]
Hi @sitanshubhunia, 
Sorry for the late response.

In molfile you provided Pd-P bond type is labeled as "any bond" ([bond types in Molfile V2000](https://en.wikipedia.org/wiki/Chemical_table_file#Bond_block_specification)), which is obviously not correct. Moreover, "any" bond type is allowed only for a query molecule, how it was mentioned in the error message from you attachment: bingo.checkmolecule() function returns a string with the problem description if molecule has any, and NULL otherwise ([Bingo User Manual](https://lifescience.opensource.epam.com/bingo/user-manual-postgres.html)).

Using of coordination bond type for Pd-P instead helps to escape such errors. This bond type is supported in Molfile V3000:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/78915761/221165235-61cb9fc7-1edd-41d8-a93e-4171f7b2660d.png">

I modified your queries by adding V3000 molfiles [V3000_queries.txt](https://github.com/epam/Indigo/files/10823348/V3000_queries.txt) and got the following results:
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/78915761/221158055-90a64dc5-015e-4e2c-8094-728dc0f16b83.png">
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/78915761/221157838-6b617a73-8be3-4af5-ab40-5364a8d6955f.png">

**Comment by sitanshubhunia** [comment]
@AATDev21 Thanks for your explanation. 🙏
