### ISSUE TITLE
MDL Molfile v3000 encoding: Automatic selection of MDL Molfile v3000 encoding doesn't work if the number of atoms (or bonds) exceeds 999

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#910]
**Steps to Reproduce**
1. Open Ketcher
2. Create structure where the number of atoms (or bonds) exceeds 999 (File for testing:
[atoms (or bonds) exceeds 999.zip](https://github.com/epam/Indigo/files/11078830/atoms.or.bonds.exceeds.999.zip)
3. Open browser console
4. Get a molfile from a structure by calling ''ketcher.getMolfile()''
5. Check saved file format

**Expected behavior**
Structure is saved according to automated selected format MDL Molfile v3000

**Actual behavior**
Structure is saved according to automated selected format MDL Molfile v2000

**Attachments**
![2022-11-28_15h12_36](https://user-images.githubusercontent.com/62464241/204274980-93ec4e3c-059b-4cf9-af41-eab3059357f6.png)

**Indigo/Bingo version**  
Version 1.8.1.0-ge56b8acfc-x86_64-linux-gnu-11.2.1

Related Ketcher issue: https://github.com/epam/ketcher/issues/1871

**Comment by Wadym** [comment]
MolfileSaver::_saveMolecule contains check on exceeding 999 molecules.
https://github.com/epam/Indigo/blob/bfa47485967b9a8569aa44ede7520968a76b241f/core/indigo-core/molecule/src/molfile_saver.cpp#L132

**Comment by Zhirnoff** [comment]
Renew attached file.
On Indigo 1.10.0.0 get a molfile from a structure by calling ''ketcher.getMolfile()'' returns mol v3000

**Comment by Wadym** [comment]
Structure is saved according to automated selected format MDL Molfile v3000 that corresponds to expected result.
![image](https://user-images.githubusercontent.com/19520607/228220389-b10ee5f8-ae8f-4f1a-bd27-369cb67ae7ad.png)
