### ISSUE TITLE
Generic atom types do not work

### ISSUE THREAD

**Issue by jstaker7** [epam/Indigo#92]
For example, I can open this structure just fine in Ketcher:

[R1]C1=CC=CC=C1C1N=C2C=CN(CC3=CC=CC=N3)C=C2N=1

But when loading with the api I get this error:
SMILES loader: 'R' specifier is allowed only for query molecules

And setting this option did not help:
indigo.setOption("ignore-noncritical-query-features", True)

**Comment by IuriiPuzanov** [comment]
Hello,
   Thank you very much for using Indigo.
As about your issue I have some notes:
1. Use please latest Indigo version (master branch), it includes support of Biovia Draw R-site notation.
2. R is not a generic type atom, as I've mentioned above this is special notation of R-site which is not included in Daylight's SMILES format.
3. Generic type atoms (like A, AH, Q, QH, X, XH, M, MH) are allowed only in queries and these are query features which can't be ignored.
4. Option indigo.setOption("ignore-noncritical-query-features", True) has effect only for loading molecules from MOLFILE format with query features like H count, topology, stereo care, ring bond count, unsaturated, 3D and Marvin's SMARTS notations inside MOLFILE.

Best Regards!
Yuriy
