### ISSUE TITLE
Reagents: When opening Daylight SMILES and Extended SMILES files with reagent the original structure is distorted

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#932]
**Steps to Reproduce**
1. Launch Ketcher
2. Create structure with arrow and reagent molecule above arrow
3. Save file as Daylight SMILES
4. Open saved file
5. Save file as Extended SMILES
6. Open saved file
Note: Same behavior with reagent below arrow
**Expected behavior**
When opening Daylight SMILES and Extended SMILES files with reagent the original structure is NOT distorted

**Actual behavior**
When opening Daylight SMILES and Extended SMILES files with reagent the original structure is distorted

**Attachments**
![2022-12-14_19h20_48](https://user-images.githubusercontent.com/62464241/207834405-f29e1671-d84e-4894-a3a7-3aa6806ca5d8.png)
![2022-12-14_19h21_58](https://user-images.githubusercontent.com/62464241/207834417-2e9253c4-89ef-477a-a8dc-05dba35d09a9.png)

**Indigo/Bingo version**  
Version 1.8.3.0-gded13d6dc-x86_64-linux-gnu-11.2.1

**Additional context**
Ketcher requirements issue: https://github.com/epam/ketcher/issues/1703
Related Ketcher issue: https://github.com/epam/ketcher/issues/1930

**Comment by lorken24** [comment]
<img width="1512" alt="Screenshot 2023-02-13 at 13 18 13" src="https://user-images.githubusercontent.com/65543532/218456427-646cbc0b-6cf9-4ea7-b4f0-a806eddd7ad6.png">
Issue reproduction about SMILES formats with reagents.

[Reaction with Cl ext sml.cxsmi.zip](https://github.com/epam/Indigo/files/10722127/Reaction.with.Cl.ext.sml.cxsmi.zip)
[Reaction with Cl day sml.smi.zip](https://github.com/epam/Indigo/files/10722128/Reaction.with.Cl.day.sml.smi.zip)
[Reaction with Cl (1).rxn.zip](https://github.com/epam/Indigo/files/10722129/Reaction.with.Cl.1.rxn.zip)
