### ISSUE TITLE
ketcher generate  *.ket format .How to save in indigo?

### ISSUE THREAD

**Issue by Aiden-max** [epam/Indigo#935]
![img_v2_1d3a2890-1e28-4417-b198-c096822f7ceg](https://user-images.githubusercontent.com/59681542/208001903-9f2e1128-6e2f-4abb-aea2-225a740c79c0.jpg)

**Comment by even1024** [comment]
Could you clarify your question? How to save .ket programmatically? Which programming language binding you use?

**Comment by mkviatkovskii** [comment]
Hello @Aiden-max,
it's
```python
molecule = indigo.loadMolecule("C")
print(molecule.json())
```

**Comment by mkviatkovskii** [comment]
I'm closing the issue, please feel free to reopen it if you have any more questions.
