### ISSUE TITLE
CDX import: Greek letters, Celsius and Fahrenheit signs are replaced with question marks

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#944]
**Steps to Reproduce**
1. Launch Ketcher
2. Open [File](https://github.com/epam/Indigo/files/10277466/greekCelsiusFaren.zip)
3. Look at structure

**Expected behavior**
The structure looks the same as it was drawn
![2022-12-21_15h02_40](https://user-images.githubusercontent.com/62464241/208901453-f342e10c-0f52-4b30-99b1-4f1a567855b3.png)

**Actual behavior**
Reaction arrow disappear when opening a file and Greek letters, Celsius and Fahrenheit signs are replaced with question marks

**Attachments**

![2022-12-21_15h04_14](https://user-images.githubusercontent.com/62464241/208901865-63b865ab-2aab-4680-a068-ff4cb3a70158.png)

**Indigo/Bingo version**  
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.9.0-rc.1.0-g9dd0dfc98-x86_64-linux-gnu-11.2.1

**Comment by even1024** [comment]
Not reproduced

**Comment by even1024** [comment]
The attached file has invalid text encoding and the text appears in the same form in ChemDraw and Marvin. Arrow doesn't disappear in 1.9.0rc4.

**Comment by vanoprenko** [comment]
@Zhirnoff , please take a look
