### ISSUE TITLE
CDXML import: 'superscript' and 'subscript' appears below the letter

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#962]
**Steps to Reproduce**
1. Launch Ketcher
2. Write 'X' letter, add '2' number with superscript or subscript
3. Save as CDXML or copy from Clipboard
4. Open/Paste from Clipboard saved file
5. Look to text

**Expected behavior**
When you open a saved file with 'superscript' and 'subscript' it is displayed correctly as saved

**Actual behavior**
'superscript' and 'subscript' are not displayed correctly

**Attachments**

https://user-images.githubusercontent.com/62464241/210390732-96152c34-2fef-4e60-bea3-925f1557b2d7.mp4

**Indigo/Bingo version**  
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.9.0-rc.2.0-g40c4e3793-x86_64-linux-gnu-11.2.1

**Comment by vanoprenko** [comment]
This is CDXML import problem. Appears if there is more than one style in single line of text.

**Comment by even1024** [comment]
Fixed in rc3

**Comment by Zhirnoff** [comment]
Bug is reproduced in Indigo 
Version 1.10.0-rc.2

https://user-images.githubusercontent.com/62464241/218065203-3d119df5-e404-4730-adf9-09aab54fd347.mp4
