### ISSUE TITLE
SMILES: Detection text above/below arrow as reagent doesn't work

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#970]
**Preconditions**

1. Ketcher is launched.
2. Structures added to canvas [ketcher (36).zip](https://github.com/epam/Indigo/files/10359066/ketcher.36.zip)
3. Added arrow (any reagent arrow type) on canvas
4. Added text on canvas above/below an arrow (in the area bounded by perpendiculars passing through the end of the arrow)

**Steps to Reproduce**

1. Click on saving icon or uses a shortcut Ctr+C
2. Choose "Daylight SMILES' format from the 'File format' dropdown
3. Check "Preview" tab
4. Choose "Extended SMILES' format from the 'File format' dropdown
5. Check "Preview" tab

**Expected behavior**
System detect text as reagent and write reagent in "Daylight SMILES' and "Extended SMILES' format  in "Preview" tab
(e.g. *CC(=O)C1=CC=CC=C1>CI>CC(C)(O)CC1=C1* where specifying reactant, agent and product molecule(s) separated by the "greater-than" symbol ('>').

**Actual behavior**
Detection text above/below arrow as reagent doesn't work. The preview does not display the presence of reagents and the reagent disappears when opening a saved file

**Attachments**
![2023-01-06_12h24_52](https://user-images.githubusercontent.com/62464241/210971503-f99e5700-5831-44ce-b3a1-172a1066f8bc.png)

**Indigo/Bingo version**  
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.9.0-rc.2.0-g40c4e3793-x86_64-linux-gnu-11.2.1

**Additional context**

**Comment by even1024** [comment]
It works as expected. SMILES doesn't support text agents.
