### ISSUE TITLE
RXN v2000,v3000: Detection text above/below arrow as reagent doesn't work

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#971]
**Preconditions**

1. Ketcher is launched.
2. Structures added to canvas [ketcher (36).zip](https://github.com/epam/Indigo/files/10359066/ketcher.36.zip)
3. Added arrow (any reagent arrow type) on canvas
4. Added text on canvas above/below an arrow (in the area bounded by perpendiculars passing through the end of the arrow)

**Steps to Reproduce**

1. Click on saving icon or uses a shortcut Ctr+C
2. Choose 'MDL rxnfile V2000' format from the 'File format' dropdown
3. Check "Preview" tab
4. Choose 'MDL rxnfile V3000' format from the 'File format' dropdown
5. Check "Preview" tab

**Expected behavior**
System detect text as reagent and write reagent in 'MDL rxnfile V2000' format in "Preview" tab
![2023-01-06_12h39_18](https://user-images.githubusercontent.com/62464241/210974560-85c0165f-d070-4f68-9991-6c5b9f6ca51e.png)
System detect text as reagent and write reagent in 'MDL rxnfile V3000' format in "Preview" tab
![2023-01-06_12h40_19](https://user-images.githubusercontent.com/62464241/210974620-51294ccd-9987-41c0-82f0-087392ebdab1.png)

**Actual behavior**
Detection text above/below arrow as reagent doesn't work. The preview does not display the presence of reagents and the reagent disappears when opening a saved file

**Attachments**
![2023-01-06_12h43_30](https://user-images.githubusercontent.com/62464241/210974792-5c78738c-f6d3-4398-a45e-21ec2464c805.png)

**Indigo/Bingo version**  
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.9.0-rc.2.0-g40c4e3793-x86_64-linux-gnu-11.2.1

**Additional context**

**Comment by even1024** [comment]
It works as expected. Text agents are not supported in RXN.
