### ISSUE TITLE
SVG/PNG: Molecule reagent located below arrow is displayed in preview above arrow

### ISSUE THREAD

**Issue by Zhirnoff** [epam/Indigo#974]
**Preconditions**

1. Ketcher is launched.
2. Structures added to canvas [ketcher (36).zip](https://github.com/epam/Indigo/files/10359066/ketcher.36.zip)
3. Added arrow (any reagent arrow type) on canvas
4. Added molecule on canvas below an arrow (in the area bounded by perpendiculars passing through the end of the arrow)

**Steps to Reproduce**

1. Click on saving icon or uses a shortcut Ctr+C
2. Choose 'SVG' format from the 'File format' dropdown
3. Look at preview and saved file
4. Choose 'PNG' format from the 'File format' dropdown
5. Look at preview and saved file

**Expected behavior**
The reagent located below arrow is displayed in preview below the arrow

**Actual behavior**
The reagent located below the arrow is displayed in the preview above the arrow
Note: Also reproduced for CDXML

**Attachments**
![2023-01-06_13h28_33](https://user-images.githubusercontent.com/62464241/210990023-7275fa2e-24b0-471e-aa15-b76991109187.png)
![2023-01-06_13h29_19](https://user-images.githubusercontent.com/62464241/210990049-729c1ac5-5c25-41d5-87a0-72343a392fc0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125 (Official Build) (64-bit)

**Indigo version** 
[Indigo Toolkit](http://lifescience.opensource.epam.com/indigo/)
Version 1.9.0-rc.2.0-g40c4e3793-x86_64-linux-gnu-11.2.1

**Additional context**

**Comment by even1024** [comment]
Can't reproduce it in 1.10.0rc2.

**Comment by Zhirnoff** [comment]
The bug is still reproduce in the Ketcher Version 2.8.0-rc.2
Build at 2023-01-31; 09:01:03, Indigo Toolkit
Version 1.10.0-rc.2
![2023-02-01_01h47_12](https://user-images.githubusercontent.com/62464241/215901717-ae50b720-860a-46fd-902c-9ad7d49697d8.png)
![2023-02-01_01h47_24](https://user-images.githubusercontent.com/62464241/215901721-b8998370-034b-4e36-a735-350f621493a8.png)

**Comment by even1024** [comment]
The attached file is incorrect, The bug is not reproducible with it.

![image](https://user-images.githubusercontent.com/7814977/215994895-e01230d3-ba18-4a97-970c-f3d507f73f58.png)
